//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:44 CEST

package bindings

/*
BG_TOKEN is generated from Windows.Win32 metadata.
*/
type BG_TOKEN uint32

const (
	/*
		BG_TOKEN_LOCAL_FILE from Windows.Win32 metadata.
	*/
	BG_TOKEN_LOCAL_FILE BG_TOKEN = 0x1

	/*
		BG_TOKEN_NETWORK from Windows.Win32 metadata.
	*/
	BG_TOKEN_NETWORK BG_TOKEN = 0x2
)

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	BG_NOTIFY_JOB_TRANSFERRED                      uint32
	BG_NOTIFY_JOB_ERROR                            uint32
	BG_NOTIFY_DISABLE                              uint32
	BG_NOTIFY_JOB_MODIFICATION                     uint32
	BG_NOTIFY_FILE_TRANSFERRED                     uint32
	BG_NOTIFY_FILE_RANGES_TRANSFERRED              uint32
	BG_JOB_ENUM_ALL_USERS                          uint32
	BG_COPY_FILE_OWNER                             uint32
	BG_COPY_FILE_GROUP                             uint32
	BG_COPY_FILE_DACL                              uint32
	BG_COPY_FILE_SACL                              uint32
	BG_COPY_FILE_ALL                               uint32
	BG_SSL_ENABLE_CRL_CHECK                        uint32
	BG_SSL_IGNORE_CERT_CN_INVALID                  uint32
	BG_SSL_IGNORE_CERT_DATE_INVALID                uint32
	BG_SSL_IGNORE_UNKNOWN_CA                       uint32
	BG_SSL_IGNORE_CERT_WRONG_USAGE                 uint32
	BG_HTTP_REDIRECT_POLICY_MASK                   uint32
	BG_HTTP_REDIRECT_POLICY_ALLOW_SILENT           uint32
	BG_HTTP_REDIRECT_POLICY_ALLOW_REPORT           uint32
	BG_HTTP_REDIRECT_POLICY_DISALLOW               uint32
	BG_HTTP_REDIRECT_POLICY_ALLOW_HTTPS_TO_HTTP    uint32
	BG_ENABLE_PEERCACHING_CLIENT                   uint32
	BG_ENABLE_PEERCACHING_SERVER                   uint32
	BG_DISABLE_BRANCH_CACHE                        uint32
	BG_JOB_ENABLE_PEERCACHING_CLIENT               uint32
	BG_JOB_ENABLE_PEERCACHING_SERVER               uint32
	BG_JOB_DISABLE_BRANCH_CACHE                    uint32
	BITS_COST_STATE_UNRESTRICTED                   uint32
	BITS_COST_STATE_CAPPED_USAGE_UNKNOWN           uint32
	BITS_COST_STATE_BELOW_CAP                      uint32
	BITS_COST_STATE_NEAR_CAP                       uint32
	BITS_COST_STATE_OVERCAP_CHARGED                uint32
	BITS_COST_STATE_OVERCAP_THROTTLED              uint32
	BITS_COST_STATE_USAGE_BASED                    uint32
	BITS_COST_STATE_ROAMING                        uint32
	BITS_COST_OPTION_IGNORE_CONGESTION             uint32
	BITS_COST_STATE_RESERVED                       uint32
	QM_NOTIFY_FILE_DONE                            uint32
	QM_NOTIFY_JOB_DONE                             uint32
	QM_NOTIFY_GROUP_DONE                           uint32
	QM_NOTIFY_DISABLE_NOTIFY                       uint32
	QM_NOTIFY_USE_PROGRESSEX                       uint32
	QM_STATUS_FILE_COMPLETE                        uint32
	QM_STATUS_FILE_INCOMPLETE                      uint32
	QM_STATUS_JOB_COMPLETE                         uint32
	QM_STATUS_JOB_INCOMPLETE                       uint32
	QM_STATUS_JOB_ERROR                            uint32
	QM_STATUS_JOB_FOREGROUND                       uint32
	QM_STATUS_GROUP_COMPLETE                       uint32
	QM_STATUS_GROUP_INCOMPLETE                     uint32
	QM_STATUS_GROUP_SUSPENDED                      uint32
	QM_STATUS_GROUP_ERROR                          uint32
	QM_STATUS_GROUP_FOREGROUND                     uint32
	QM_PROTOCOL_HTTP                               uint32
	QM_PROTOCOL_FTP                                uint32
	QM_PROTOCOL_SMB                                uint32
	QM_PROTOCOL_CUSTOM                             uint32
	QM_PROGRESS_PERCENT_DONE                       uint32
	QM_PROGRESS_TIME_DONE                          uint32
	QM_PROGRESS_SIZE_DONE                          uint32
	QM_E_INVALID_STATE                             uint32
	QM_E_SERVICE_UNAVAILABLE                       uint32
	QM_E_DOWNLOADER_UNAVAILABLE                    uint32
	QM_E_ITEM_NOT_FOUND                            uint32
	BG_E_NOT_FOUND                                 int32
	BG_E_INVALID_STATE                             int32
	BG_E_EMPTY                                     int32
	BG_E_FILE_NOT_AVAILABLE                        int32
	BG_E_PROTOCOL_NOT_AVAILABLE                    int32
	BG_S_ERROR_CONTEXT_NONE                        int32
	BG_E_ERROR_CONTEXT_UNKNOWN                     int32
	BG_E_ERROR_CONTEXT_GENERAL_QUEUE_MANAGER       int32
	BG_E_ERROR_CONTEXT_LOCAL_FILE                  int32
	BG_E_ERROR_CONTEXT_REMOTE_FILE                 int32
	BG_E_ERROR_CONTEXT_GENERAL_TRANSPORT           int32
	BG_E_ERROR_CONTEXT_QUEUE_MANAGER_NOTIFICATION  int32
	BG_E_DESTINATION_LOCKED                        int32
	BG_E_VOLUME_CHANGED                            int32
	BG_E_ERROR_INFORMATION_UNAVAILABLE             int32
	BG_E_NETWORK_DISCONNECTED                      int32
	BG_E_MISSING_FILE_SIZE                         int32
	BG_E_INSUFFICIENT_HTTP_SUPPORT                 int32
	BG_E_INSUFFICIENT_RANGE_SUPPORT                int32
	BG_E_REMOTE_NOT_SUPPORTED                      int32
	BG_E_NEW_OWNER_DIFF_MAPPING                    int32
	BG_E_NEW_OWNER_NO_FILE_ACCESS                  int32
	BG_S_PARTIAL_COMPLETE                          int32
	BG_E_PROXY_LIST_TOO_LARGE                      int32
	BG_E_PROXY_BYPASS_LIST_TOO_LARGE               int32
	BG_S_UNABLE_TO_DELETE_FILES                    int32
	BG_E_INVALID_SERVER_RESPONSE                   int32
	BG_E_TOO_MANY_FILES                            int32
	BG_E_LOCAL_FILE_CHANGED                        int32
	BG_E_ERROR_CONTEXT_REMOTE_APPLICATION          int32
	BG_E_SESSION_NOT_FOUND                         int32
	BG_E_TOO_LARGE                                 int32
	BG_E_STRING_TOO_LONG                           int32
	BG_E_CLIENT_SERVER_PROTOCOL_MISMATCH           int32
	BG_E_SERVER_EXECUTE_ENABLE                     int32
	BG_E_NO_PROGRESS                               int32
	BG_E_USERNAME_TOO_LARGE                        int32
	BG_E_PASSWORD_TOO_LARGE                        int32
	BG_E_INVALID_AUTH_TARGET                       int32
	BG_E_INVALID_AUTH_SCHEME                       int32
	BG_E_FILE_NOT_FOUND                            int32
	BG_S_PROXY_CHANGED                             int32
	BG_E_INVALID_RANGE                             int32
	BG_E_OVERLAPPING_RANGES                        int32
	BG_E_CONNECT_FAILURE                           int32
	BG_E_CONNECTION_CLOSED                         int32
	BG_E_BLOCKED_BY_POLICY                         int32
	BG_E_INVALID_PROXY_INFO                        int32
	BG_E_INVALID_CREDENTIALS                       int32
	BG_E_INVALID_HASH_ALGORITHM                    int32
	BG_E_RECORD_DELETED                            int32
	BG_E_COMMIT_IN_PROGRESS                        int32
	BG_E_DISCOVERY_IN_PROGRESS                     int32
	BG_E_UPNP_ERROR                                int32
	BG_E_TEST_OPTION_BLOCKED_DOWNLOAD              int32
	BG_E_PEERCACHING_DISABLED                      int32
	BG_E_BUSYCACHERECORD                           int32
	BG_E_TOO_MANY_JOBS_PER_USER                    int32
	BG_E_TOO_MANY_JOBS_PER_MACHINE                 int32
	BG_E_TOO_MANY_FILES_IN_JOB                     int32
	BG_E_TOO_MANY_RANGES_IN_FILE                   int32
	BG_E_VALIDATION_FAILED                         int32
	BG_E_MAXDOWNLOAD_TIMEOUT                       int32
	BG_S_OVERRIDDEN_BY_POLICY                      int32
	BG_E_TOKEN_REQUIRED                            int32
	BG_E_UNKNOWN_PROPERTY_ID                       int32
	BG_E_READ_ONLY_PROPERTY                        int32
	BG_E_BLOCKED_BY_COST_TRANSFER_POLICY           int32
	BG_E_PROPERTY_SUPPORTED_FOR_DOWNLOAD_JOBS_ONLY int32
	BG_E_READ_ONLY_PROPERTY_AFTER_ADDFILE          int32
	BG_E_READ_ONLY_PROPERTY_AFTER_RESUME           int32
	BG_E_MAX_DOWNLOAD_SIZE_INVALID_VALUE           int32
	BG_E_MAX_DOWNLOAD_SIZE_LIMIT_REACHED           int32
	BG_E_STANDBY_MODE                              int32
	BG_E_USE_STORED_CREDENTIALS_NOT_SUPPORTED      int32
	BG_E_BLOCKED_BY_BATTERY_POLICY                 int32
	BG_E_BLOCKED_BY_BATTERY_SAVER                  int32
	BG_E_WATCHDOG_TIMEOUT                          int32
	BG_E_APP_PACKAGE_NOT_FOUND                     int32
	BG_E_APP_PACKAGE_SCENARIO_NOT_SUPPORTED        int32
	BG_E_DATABASE_CORRUPT                          int32
	BG_E_RANDOM_ACCESS_NOT_SUPPORTED               int32
	BG_E_BLOCKED_BY_BACKGROUND_ACCESS_POLICY       int32
	BG_E_BLOCKED_BY_GAME_MODE                      int32
	BG_E_BLOCKED_BY_SYSTEM_POLICY                  int32
	BG_E_NOT_SUPPORTED_WITH_CUSTOM_HTTP_METHOD     int32
	BG_E_UNSUPPORTED_JOB_CONFIGURATION             int32
	BG_E_REMOTE_FILE_CHANGED                       int32
	BG_E_SERVER_CERT_VALIDATION_INTERFACE_REQUIRED int32
	BG_E_READ_ONLY_WHEN_JOB_ACTIVE                 int32
	BG_E_ERROR_CONTEXT_SERVER_CERTIFICATE_CALLBACK int32
	BG_E_HTTP_ERROR_100                            int32
	BG_E_HTTP_ERROR_101                            int32
	BG_E_HTTP_ERROR_200                            int32
	BG_E_HTTP_ERROR_201                            int32
	BG_E_HTTP_ERROR_202                            int32
	BG_E_HTTP_ERROR_203                            int32
	BG_E_HTTP_ERROR_204                            int32
	BG_E_HTTP_ERROR_205                            int32
	BG_E_HTTP_ERROR_206                            int32
	BG_E_HTTP_ERROR_300                            int32
	BG_E_HTTP_ERROR_301                            int32
	BG_E_HTTP_ERROR_302                            int32
	BG_E_HTTP_ERROR_303                            int32
	BG_E_HTTP_ERROR_304                            int32
	BG_E_HTTP_ERROR_305                            int32
	BG_E_HTTP_ERROR_307                            int32
	BG_E_HTTP_ERROR_400                            int32
	BG_E_HTTP_ERROR_401                            int32
	BG_E_HTTP_ERROR_402                            int32
	BG_E_HTTP_ERROR_403                            int32
	BG_E_HTTP_ERROR_404                            int32
	BG_E_HTTP_ERROR_405                            int32
	BG_E_HTTP_ERROR_406                            int32
	BG_E_HTTP_ERROR_407                            int32
	BG_E_HTTP_ERROR_408                            int32
	BG_E_HTTP_ERROR_409                            int32
	BG_E_HTTP_ERROR_410                            int32
	BG_E_HTTP_ERROR_411                            int32
	BG_E_HTTP_ERROR_412                            int32
	BG_E_HTTP_ERROR_413                            int32
	BG_E_HTTP_ERROR_414                            int32
	BG_E_HTTP_ERROR_415                            int32
	BG_E_HTTP_ERROR_416                            int32
	BG_E_HTTP_ERROR_417                            int32
	BG_E_HTTP_ERROR_449                            int32
	BG_E_HTTP_ERROR_500                            int32
	BG_E_HTTP_ERROR_501                            int32
	BG_E_HTTP_ERROR_502                            int32
	BG_E_HTTP_ERROR_503                            int32
	BG_E_HTTP_ERROR_504                            int32
	BG_E_HTTP_ERROR_505                            int32
	BITS_MC_JOB_CANCELLED                          int32
	BITS_MC_FILE_DELETION_FAILED                   int32
	BITS_MC_FILE_DELETION_FAILED_MORE              int32
	BITS_MC_JOB_PROPERTY_CHANGE                    int32
	BITS_MC_JOB_TAKE_OWNERSHIP                     int32
	BITS_MC_JOB_SCAVENGED                          int32
	BITS_MC_JOB_NOTIFICATION_FAILURE               int32
	BITS_MC_STATE_FILE_CORRUPT                     int32
	BITS_MC_FAILED_TO_START                        int32
	BITS_MC_FATAL_IGD_ERROR                        int32
	BITS_MC_PEERCACHING_PORT                       int32
	BITS_MC_WSD_PORT                               int32
}

/*
BG_FILE_PROGRESS is generated from Windows.Win32 metadata.
*/
type BG_FILE_PROGRESS struct {
	BytesTotal       uint64
	BytesTransferred uint64
	Completed        BOOL
}

/*
IBackgroundCopyFile is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyFile uintptr

/*
IEnumBackgroundCopyFiles is generated from Windows.Win32 metadata.
*/
type IEnumBackgroundCopyFiles uintptr

/*
BG_ERROR_CONTEXT is generated from Windows.Win32 metadata.
*/
type BG_ERROR_CONTEXT int32

const (
	/*
		BG_ERROR_CONTEXT_NONE from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_NONE BG_ERROR_CONTEXT = 0x0

	/*
		BG_ERROR_CONTEXT_UNKNOWN from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_UNKNOWN BG_ERROR_CONTEXT = 0x1

	/*
		BG_ERROR_CONTEXT_GENERAL_QUEUE_MANAGER from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_GENERAL_QUEUE_MANAGER BG_ERROR_CONTEXT = 0x2

	/*
		BG_ERROR_CONTEXT_QUEUE_MANAGER_NOTIFICATION from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_QUEUE_MANAGER_NOTIFICATION BG_ERROR_CONTEXT = 0x3

	/*
		BG_ERROR_CONTEXT_LOCAL_FILE from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_LOCAL_FILE BG_ERROR_CONTEXT = 0x4

	/*
		BG_ERROR_CONTEXT_REMOTE_FILE from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_REMOTE_FILE BG_ERROR_CONTEXT = 0x5

	/*
		BG_ERROR_CONTEXT_GENERAL_TRANSPORT from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_GENERAL_TRANSPORT BG_ERROR_CONTEXT = 0x6

	/*
		BG_ERROR_CONTEXT_REMOTE_APPLICATION from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_REMOTE_APPLICATION BG_ERROR_CONTEXT = 0x7

	/*
		BG_ERROR_CONTEXT_SERVER_CERTIFICATE_CALLBACK from Windows.Win32 metadata.
	*/
	BG_ERROR_CONTEXT_SERVER_CERTIFICATE_CALLBACK BG_ERROR_CONTEXT = 0x8
)

/*
IBackgroundCopyError is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyError uintptr

/*
BG_FILE_INFO is generated from Windows.Win32 metadata.
*/
type BG_FILE_INFO struct {
	RemoteName *PWSTRElement
	LocalName  *PWSTRElement
}

/*
BG_JOB_PROGRESS is generated from Windows.Win32 metadata.
*/
type BG_JOB_PROGRESS struct {
	BytesTotal       uint64
	BytesTransferred uint64
	FilesTotal       uint32
	FilesTransferred uint32
}

/*
BG_JOB_TIMES is generated from Windows.Win32 metadata.
*/
type BG_JOB_TIMES struct {
	CreationTime           FILETIME
	ModificationTime       FILETIME
	TransferCompletionTime FILETIME
}

/*
BG_JOB_PRIORITY is generated from Windows.Win32 metadata.
*/
type BG_JOB_PRIORITY int32

const (
	/*
		BG_JOB_PRIORITY_FOREGROUND from Windows.Win32 metadata.
	*/
	BG_JOB_PRIORITY_FOREGROUND BG_JOB_PRIORITY = 0x0

	/*
		BG_JOB_PRIORITY_HIGH from Windows.Win32 metadata.
	*/
	BG_JOB_PRIORITY_HIGH BG_JOB_PRIORITY = 0x1

	/*
		BG_JOB_PRIORITY_NORMAL from Windows.Win32 metadata.
	*/
	BG_JOB_PRIORITY_NORMAL BG_JOB_PRIORITY = 0x2

	/*
		BG_JOB_PRIORITY_LOW from Windows.Win32 metadata.
	*/
	BG_JOB_PRIORITY_LOW BG_JOB_PRIORITY = 0x3
)

/*
BG_JOB_STATE is generated from Windows.Win32 metadata.
*/
type BG_JOB_STATE int32

const (
	/*
		BG_JOB_STATE_QUEUED from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_QUEUED BG_JOB_STATE = 0x0

	/*
		BG_JOB_STATE_CONNECTING from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_CONNECTING BG_JOB_STATE = 0x1

	/*
		BG_JOB_STATE_TRANSFERRING from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_TRANSFERRING BG_JOB_STATE = 0x2

	/*
		BG_JOB_STATE_SUSPENDED from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_SUSPENDED BG_JOB_STATE = 0x3

	/*
		BG_JOB_STATE_ERROR from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_ERROR BG_JOB_STATE = 0x4

	/*
		BG_JOB_STATE_TRANSIENT_ERROR from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_TRANSIENT_ERROR BG_JOB_STATE = 0x5

	/*
		BG_JOB_STATE_TRANSFERRED from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_TRANSFERRED BG_JOB_STATE = 0x6

	/*
		BG_JOB_STATE_ACKNOWLEDGED from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_ACKNOWLEDGED BG_JOB_STATE = 0x7

	/*
		BG_JOB_STATE_CANCELLED from Windows.Win32 metadata.
	*/
	BG_JOB_STATE_CANCELLED BG_JOB_STATE = 0x8
)

/*
BG_JOB_TYPE is generated from Windows.Win32 metadata.
*/
type BG_JOB_TYPE int32

const (
	/*
		BG_JOB_TYPE_DOWNLOAD from Windows.Win32 metadata.
	*/
	BG_JOB_TYPE_DOWNLOAD BG_JOB_TYPE = 0x0

	/*
		BG_JOB_TYPE_UPLOAD from Windows.Win32 metadata.
	*/
	BG_JOB_TYPE_UPLOAD BG_JOB_TYPE = 0x1

	/*
		BG_JOB_TYPE_UPLOAD_REPLY from Windows.Win32 metadata.
	*/
	BG_JOB_TYPE_UPLOAD_REPLY BG_JOB_TYPE = 0x2
)

/*
BG_JOB_PROXY_USAGE is generated from Windows.Win32 metadata.
*/
type BG_JOB_PROXY_USAGE int32

const (
	/*
		BG_JOB_PROXY_USAGE_PRECONFIG from Windows.Win32 metadata.
	*/
	BG_JOB_PROXY_USAGE_PRECONFIG BG_JOB_PROXY_USAGE = 0x0

	/*
		BG_JOB_PROXY_USAGE_NO_PROXY from Windows.Win32 metadata.
	*/
	BG_JOB_PROXY_USAGE_NO_PROXY BG_JOB_PROXY_USAGE = 0x1

	/*
		BG_JOB_PROXY_USAGE_OVERRIDE from Windows.Win32 metadata.
	*/
	BG_JOB_PROXY_USAGE_OVERRIDE BG_JOB_PROXY_USAGE = 0x2

	/*
		BG_JOB_PROXY_USAGE_AUTODETECT from Windows.Win32 metadata.
	*/
	BG_JOB_PROXY_USAGE_AUTODETECT BG_JOB_PROXY_USAGE = 0x3
)

/*
IBackgroundCopyJob is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJob uintptr

/*
IEnumBackgroundCopyJobs is generated from Windows.Win32 metadata.
*/
type IEnumBackgroundCopyJobs uintptr

/*
IBackgroundCopyCallback is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyCallback uintptr

/*
AsyncIBackgroundCopyCallback is generated from Windows.Win32 metadata.
*/
type AsyncIBackgroundCopyCallback uintptr

/*
IBackgroundCopyManager is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyManager uintptr

/*
BackgroundCopyManager is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager struct {
}

/*
BG_JOB_REPLY_PROGRESS is generated from Windows.Win32 metadata.
*/
type BG_JOB_REPLY_PROGRESS struct {
	BytesTotal       uint64
	BytesTransferred uint64
}

/*
BG_AUTH_TARGET is generated from Windows.Win32 metadata.
*/
type BG_AUTH_TARGET int32

const (
	/*
		BG_AUTH_TARGET_SERVER from Windows.Win32 metadata.
	*/
	BG_AUTH_TARGET_SERVER BG_AUTH_TARGET = 0x1

	/*
		BG_AUTH_TARGET_PROXY from Windows.Win32 metadata.
	*/
	BG_AUTH_TARGET_PROXY BG_AUTH_TARGET = 0x2
)

/*
BG_AUTH_SCHEME is generated from Windows.Win32 metadata.
*/
type BG_AUTH_SCHEME int32

const (
	/*
		BG_AUTH_SCHEME_BASIC from Windows.Win32 metadata.
	*/
	BG_AUTH_SCHEME_BASIC BG_AUTH_SCHEME = 0x1

	/*
		BG_AUTH_SCHEME_DIGEST from Windows.Win32 metadata.
	*/
	BG_AUTH_SCHEME_DIGEST BG_AUTH_SCHEME = 0x2

	/*
		BG_AUTH_SCHEME_NTLM from Windows.Win32 metadata.
	*/
	BG_AUTH_SCHEME_NTLM BG_AUTH_SCHEME = 0x3

	/*
		BG_AUTH_SCHEME_NEGOTIATE from Windows.Win32 metadata.
	*/
	BG_AUTH_SCHEME_NEGOTIATE BG_AUTH_SCHEME = 0x4

	/*
		BG_AUTH_SCHEME_PASSPORT from Windows.Win32 metadata.
	*/
	BG_AUTH_SCHEME_PASSPORT BG_AUTH_SCHEME = 0x5
)

/*
BG_BASIC_CREDENTIALS is generated from Windows.Win32 metadata.
*/
type BG_BASIC_CREDENTIALS struct {
	UserName *PWSTRElement
	Password *PWSTRElement
}

/*
BG_AUTH_CREDENTIALS_UNION is generated from Windows.Win32 metadata.
*/
type BG_AUTH_CREDENTIALS_UNION struct {
	Basic BG_BASIC_CREDENTIALS
}

/*
BG_AUTH_CREDENTIALS is generated from Windows.Win32 metadata.
*/
type BG_AUTH_CREDENTIALS struct {
	Target      BG_AUTH_TARGET
	Scheme      BG_AUTH_SCHEME
	Credentials BG_AUTH_CREDENTIALS_UNION
}

/*
IBackgroundCopyJob2 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJob2 uintptr

/*
BackgroundCopyManager1_5 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager1_5 struct {
}

/*
BG_FILE_RANGE is generated from Windows.Win32 metadata.
*/
type BG_FILE_RANGE struct {
	InitialOffset uint64
	Length        uint64
}

/*
IBackgroundCopyJob3 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJob3 uintptr

/*
IBackgroundCopyFile2 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyFile2 uintptr

/*
BackgroundCopyManager2_0 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager2_0 struct {
}

/*
BG_CERT_STORE_LOCATION is generated from Windows.Win32 metadata.
*/
type BG_CERT_STORE_LOCATION int32

const (
	/*
		BG_CERT_STORE_LOCATION_CURRENT_USER from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_CURRENT_USER BG_CERT_STORE_LOCATION = 0x0

	/*
		BG_CERT_STORE_LOCATION_LOCAL_MACHINE from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_LOCAL_MACHINE BG_CERT_STORE_LOCATION = 0x1

	/*
		BG_CERT_STORE_LOCATION_CURRENT_SERVICE from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_CURRENT_SERVICE BG_CERT_STORE_LOCATION = 0x2

	/*
		BG_CERT_STORE_LOCATION_SERVICES from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_SERVICES BG_CERT_STORE_LOCATION = 0x3

	/*
		BG_CERT_STORE_LOCATION_USERS from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_USERS BG_CERT_STORE_LOCATION = 0x4

	/*
		BG_CERT_STORE_LOCATION_CURRENT_USER_GROUP_POLICY from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_CURRENT_USER_GROUP_POLICY BG_CERT_STORE_LOCATION = 0x5

	/*
		BG_CERT_STORE_LOCATION_LOCAL_MACHINE_GROUP_POLICY from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_LOCAL_MACHINE_GROUP_POLICY BG_CERT_STORE_LOCATION = 0x6

	/*
		BG_CERT_STORE_LOCATION_LOCAL_MACHINE_ENTERPRISE from Windows.Win32 metadata.
	*/
	BG_CERT_STORE_LOCATION_LOCAL_MACHINE_ENTERPRISE BG_CERT_STORE_LOCATION = 0x7
)

/*
IBackgroundCopyJobHttpOptions is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJobHttpOptions uintptr

/*
BackgroundCopyManager2_5 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager2_5 struct {
}

/*
IBitsPeerCacheRecord is generated from Windows.Win32 metadata.
*/
type IBitsPeerCacheRecord uintptr

/*
IEnumBitsPeerCacheRecords is generated from Windows.Win32 metadata.
*/
type IEnumBitsPeerCacheRecords uintptr

/*
IBitsPeer is generated from Windows.Win32 metadata.
*/
type IBitsPeer uintptr

/*
IEnumBitsPeers is generated from Windows.Win32 metadata.
*/
type IEnumBitsPeers uintptr

/*
IBitsPeerCacheAdministration is generated from Windows.Win32 metadata.
*/
type IBitsPeerCacheAdministration uintptr

/*
IBackgroundCopyJob4 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJob4 uintptr

/*
IBackgroundCopyFile3 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyFile3 uintptr

/*
IBackgroundCopyCallback2 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyCallback2 uintptr

/*
BackgroundCopyManager3_0 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager3_0 struct {
}

/*
IBitsTokenOptions is generated from Windows.Win32 metadata.
*/
type IBitsTokenOptions uintptr

/*
IBackgroundCopyFile4 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyFile4 uintptr

/*
BackgroundCopyManager4_0 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager4_0 struct {
}

/*
BITS_JOB_TRANSFER_POLICY is generated from Windows.Win32 metadata.
*/
type BITS_JOB_TRANSFER_POLICY int32

const (
	/*
		BITS_JOB_TRANSFER_POLICY_ALWAYS from Windows.Win32 metadata.
	*/
	BITS_JOB_TRANSFER_POLICY_ALWAYS BITS_JOB_TRANSFER_POLICY = -2147483393

	/*
		BITS_JOB_TRANSFER_POLICY_NOT_ROAMING from Windows.Win32 metadata.
	*/
	BITS_JOB_TRANSFER_POLICY_NOT_ROAMING BITS_JOB_TRANSFER_POLICY = -2147483521

	/*
		BITS_JOB_TRANSFER_POLICY_NO_SURCHARGE from Windows.Win32 metadata.
	*/
	BITS_JOB_TRANSFER_POLICY_NO_SURCHARGE BITS_JOB_TRANSFER_POLICY = -2147483537

	/*
		BITS_JOB_TRANSFER_POLICY_STANDARD from Windows.Win32 metadata.
	*/
	BITS_JOB_TRANSFER_POLICY_STANDARD BITS_JOB_TRANSFER_POLICY = -2147483545

	/*
		BITS_JOB_TRANSFER_POLICY_UNRESTRICTED from Windows.Win32 metadata.
	*/
	BITS_JOB_TRANSFER_POLICY_UNRESTRICTED BITS_JOB_TRANSFER_POLICY = -2147483615
)

/*
BITS_JOB_PROPERTY_ID is generated from Windows.Win32 metadata.
*/
type BITS_JOB_PROPERTY_ID int32

const (
	/*
		BITS_JOB_PROPERTY_ID_COST_FLAGS from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_ID_COST_FLAGS BITS_JOB_PROPERTY_ID = 0x1

	/*
		BITS_JOB_PROPERTY_NOTIFICATION_CLSID from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_NOTIFICATION_CLSID BITS_JOB_PROPERTY_ID = 0x2

	/*
		BITS_JOB_PROPERTY_DYNAMIC_CONTENT from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_DYNAMIC_CONTENT BITS_JOB_PROPERTY_ID = 0x3

	/*
		BITS_JOB_PROPERTY_HIGH_PERFORMANCE from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_HIGH_PERFORMANCE BITS_JOB_PROPERTY_ID = 0x4

	/*
		BITS_JOB_PROPERTY_MAX_DOWNLOAD_SIZE from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_MAX_DOWNLOAD_SIZE BITS_JOB_PROPERTY_ID = 0x5

	/*
		BITS_JOB_PROPERTY_USE_STORED_CREDENTIALS from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_USE_STORED_CREDENTIALS BITS_JOB_PROPERTY_ID = 0x7

	/*
		BITS_JOB_PROPERTY_MINIMUM_NOTIFICATION_INTERVAL_MS from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_MINIMUM_NOTIFICATION_INTERVAL_MS BITS_JOB_PROPERTY_ID = 0x9

	/*
		BITS_JOB_PROPERTY_ON_DEMAND_MODE from Windows.Win32 metadata.
	*/
	BITS_JOB_PROPERTY_ON_DEMAND_MODE BITS_JOB_PROPERTY_ID = 0xa
)

/*
BITS_JOB_PROPERTY_VALUE is generated from Windows.Win32 metadata.
*/
type BITS_JOB_PROPERTY_VALUE struct {
	Dword uint32
}

/*
BITS_FILE_PROPERTY_ID is generated from Windows.Win32 metadata.
*/
type BITS_FILE_PROPERTY_ID int32

const (
	/*
		BITS_FILE_PROPERTY_ID_HTTP_RESPONSE_HEADERS from Windows.Win32 metadata.
	*/
	BITS_FILE_PROPERTY_ID_HTTP_RESPONSE_HEADERS BITS_FILE_PROPERTY_ID = 0x1
)

/*
BITS_FILE_PROPERTY_VALUE is generated from Windows.Win32 metadata.
*/
type BITS_FILE_PROPERTY_VALUE struct {
	String *PWSTRElement
}

/*
IBackgroundCopyJob5 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJob5 uintptr

/*
IBackgroundCopyFile5 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyFile5 uintptr

/*
BackgroundCopyManager5_0 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager5_0 struct {
}

/*
IBackgroundCopyCallback3 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyCallback3 uintptr

/*
IBackgroundCopyFile6 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyFile6 uintptr

/*
BackgroundCopyManager10_1 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager10_1 struct {
}

/*
IBackgroundCopyJobHttpOptions2 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJobHttpOptions2 uintptr

/*
BackgroundCopyManager10_2 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager10_2 struct {
}

/*
IBackgroundCopyServerCertificateValidationCallback is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyServerCertificateValidationCallback uintptr

/*
IBackgroundCopyJobHttpOptions3 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJobHttpOptions3 uintptr

/*
BackgroundCopyManager10_3 is generated from Windows.Win32 metadata.
*/
type BackgroundCopyManager10_3 struct {
}

/*
IBITSExtensionSetup is generated from Windows.Win32 metadata.
*/
type IBITSExtensionSetup uintptr

/*
IBITSExtensionSetupFactory is generated from Windows.Win32 metadata.
*/
type IBITSExtensionSetupFactory uintptr

/*
BITSExtensionSetupFactory is generated from Windows.Win32 metadata.
*/
type BITSExtensionSetupFactory struct {
}

/*
FILESETINFO is generated from Windows.Win32 metadata.
*/
type FILESETINFO struct {
	BstrRemoteFile *BSTRElement
	BstrLocalFile  *BSTRElement
	DwSizeHint     uint32
}

/*
IBackgroundCopyJob1 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyJob1 uintptr

/*
IEnumBackgroundCopyJobs1 is generated from Windows.Win32 metadata.
*/
type IEnumBackgroundCopyJobs1 uintptr

/*
GROUPPROP is generated from Windows.Win32 metadata.
*/
type GROUPPROP int32

const (
	/*
		GROUPPROP_PRIORITY from Windows.Win32 metadata.
	*/
	GROUPPROP_PRIORITY GROUPPROP = 0x0

	/*
		GROUPPROP_REMOTEUSERID from Windows.Win32 metadata.
	*/
	GROUPPROP_REMOTEUSERID GROUPPROP = 0x1

	/*
		GROUPPROP_REMOTEUSERPWD from Windows.Win32 metadata.
	*/
	GROUPPROP_REMOTEUSERPWD GROUPPROP = 0x2

	/*
		GROUPPROP_LOCALUSERID from Windows.Win32 metadata.
	*/
	GROUPPROP_LOCALUSERID GROUPPROP = 0x3

	/*
		GROUPPROP_LOCALUSERPWD from Windows.Win32 metadata.
	*/
	GROUPPROP_LOCALUSERPWD GROUPPROP = 0x4

	/*
		GROUPPROP_PROTOCOLFLAGS from Windows.Win32 metadata.
	*/
	GROUPPROP_PROTOCOLFLAGS GROUPPROP = 0x5

	/*
		GROUPPROP_NOTIFYFLAGS from Windows.Win32 metadata.
	*/
	GROUPPROP_NOTIFYFLAGS GROUPPROP = 0x6

	/*
		GROUPPROP_NOTIFYCLSID from Windows.Win32 metadata.
	*/
	GROUPPROP_NOTIFYCLSID GROUPPROP = 0x7

	/*
		GROUPPROP_PROGRESSSIZE from Windows.Win32 metadata.
	*/
	GROUPPROP_PROGRESSSIZE GROUPPROP = 0x8

	/*
		GROUPPROP_PROGRESSPERCENT from Windows.Win32 metadata.
	*/
	GROUPPROP_PROGRESSPERCENT GROUPPROP = 0x9

	/*
		GROUPPROP_PROGRESSTIME from Windows.Win32 metadata.
	*/
	GROUPPROP_PROGRESSTIME GROUPPROP = 0xa

	/*
		GROUPPROP_DISPLAYNAME from Windows.Win32 metadata.
	*/
	GROUPPROP_DISPLAYNAME GROUPPROP = 0xb

	/*
		GROUPPROP_DESCRIPTION from Windows.Win32 metadata.
	*/
	GROUPPROP_DESCRIPTION GROUPPROP = 0xc
)

/*
IBackgroundCopyGroup is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyGroup uintptr

/*
IEnumBackgroundCopyGroups is generated from Windows.Win32 metadata.
*/
type IEnumBackgroundCopyGroups uintptr

/*
IBackgroundCopyCallback1 is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyCallback1 uintptr

/*
IBackgroundCopyQMgr is generated from Windows.Win32 metadata.
*/
type IBackgroundCopyQMgr uintptr

/*
BackgroundCopyQMgr is generated from Windows.Win32 metadata.
*/
type BackgroundCopyQMgr struct {
}
