//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_CreateSecurityPage maps to CreateSecurityPage in aclui.dll.
*/
type PFN_CreateSecurityPage func(psi *ISecurityInformation) HPROPSHEETPAGE

/*
PFN_EditSecurity maps to EditSecurity in aclui.dll.
*/
type PFN_EditSecurity func(hwndOwner HWND, psi *ISecurityInformation) BOOL

/*
PFN_EditSecurityAdvanced maps to EditSecurityAdvanced in aclui.dll.
*/
type PFN_EditSecurityAdvanced func(hwndOwner HWND, psi *ISecurityInformation, uSIPage SI_PAGE_TYPE) HRESULT
