//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:45 CEST

package bindings

/*
PFN_MFPCreateMediaPlayer maps to MFPCreateMediaPlayer in mfplay.dll.
*/
type PFN_MFPCreateMediaPlayer func(pwszURL *PWSTRElement, fStartPlayback BOOL, creationOptions MFP_CREATION_OPTIONS, pCallback *IMFPMediaPlayerCallback, hWnd HWND, ppMediaPlayer **IMFPMediaPlayer) HRESULT
