//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_BCryptOpenAlgorithmProvider maps to BCryptOpenAlgorithmProvider in bcrypt.dll.
*/
type PFN_BCryptOpenAlgorithmProvider func(phAlgorithm *BCRYPT_ALG_HANDLE, pszAlgId *PWSTRElement, pszImplementation *PWSTRElement, dwFlags BCRYPT_OPEN_ALGORITHM_PROVIDER_FLAGS) NTSTATUS

/*
PFN_BCryptEnumAlgorithms maps to BCryptEnumAlgorithms in bcrypt.dll.
*/
type PFN_BCryptEnumAlgorithms func(dwAlgOperations BCRYPT_OPERATION, pAlgCount *uint32, ppAlgList **BCRYPT_ALGORITHM_IDENTIFIER, dwFlags uint32) NTSTATUS

/*
PFN_BCryptEnumProviders maps to BCryptEnumProviders in bcrypt.dll.
*/
type PFN_BCryptEnumProviders func(pszAlgId *PWSTRElement, pImplCount *uint32, ppImplList **BCRYPT_PROVIDER_NAME, dwFlags uint32) NTSTATUS

/*
PFN_BCryptGetProperty maps to BCryptGetProperty in bcrypt.dll.
*/
type PFN_BCryptGetProperty func(hObject BCRYPT_HANDLE, pszProperty *PWSTRElement, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptSetProperty maps to BCryptSetProperty in bcrypt.dll.
*/
type PFN_BCryptSetProperty func(hObject BCRYPT_HANDLE, pszProperty *PWSTRElement, pbInput *uint8, cbInput uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptCloseAlgorithmProvider maps to BCryptCloseAlgorithmProvider in bcrypt.dll.
*/
type PFN_BCryptCloseAlgorithmProvider func(hAlgorithm BCRYPT_ALG_HANDLE, dwFlags uint32) NTSTATUS

/*
PFN_BCryptFreeBuffer maps to BCryptFreeBuffer in bcrypt.dll.
*/
type PFN_BCryptFreeBuffer func(pvBuffer uintptr)

/*
PFN_BCryptGenerateSymmetricKey maps to BCryptGenerateSymmetricKey in bcrypt.dll.
*/
type PFN_BCryptGenerateSymmetricKey func(hAlgorithm BCRYPT_ALG_HANDLE, phKey *BCRYPT_KEY_HANDLE, pbKeyObject *uint8, cbKeyObject uint32, pbSecret *uint8, cbSecret uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptGenerateKeyPair maps to BCryptGenerateKeyPair in bcrypt.dll.
*/
type PFN_BCryptGenerateKeyPair func(hAlgorithm BCRYPT_ALG_HANDLE, phKey *BCRYPT_KEY_HANDLE, dwLength uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptEncrypt maps to BCryptEncrypt in bcrypt.dll.
*/
type PFN_BCryptEncrypt func(hKey BCRYPT_KEY_HANDLE, pbInput *uint8, cbInput uint32, pPaddingInfo uintptr, pbIV *uint8, cbIV uint32, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags BCRYPT_FLAGS) NTSTATUS

/*
PFN_BCryptDecrypt maps to BCryptDecrypt in bcrypt.dll.
*/
type PFN_BCryptDecrypt func(hKey BCRYPT_KEY_HANDLE, pbInput *uint8, cbInput uint32, pPaddingInfo uintptr, pbIV *uint8, cbIV uint32, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags BCRYPT_FLAGS) NTSTATUS

/*
PFN_BCryptExportKey maps to BCryptExportKey in bcrypt.dll.
*/
type PFN_BCryptExportKey func(hKey BCRYPT_KEY_HANDLE, hExportKey BCRYPT_KEY_HANDLE, pszBlobType *PWSTRElement, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptImportKey maps to BCryptImportKey in bcrypt.dll.
*/
type PFN_BCryptImportKey func(hAlgorithm BCRYPT_ALG_HANDLE, hImportKey BCRYPT_KEY_HANDLE, pszBlobType *PWSTRElement, phKey *BCRYPT_KEY_HANDLE, pbKeyObject *uint8, cbKeyObject uint32, pbInput *uint8, cbInput uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptImportKeyPair maps to BCryptImportKeyPair in bcrypt.dll.
*/
type PFN_BCryptImportKeyPair func(hAlgorithm BCRYPT_ALG_HANDLE, hImportKey BCRYPT_KEY_HANDLE, pszBlobType *PWSTRElement, phKey *BCRYPT_KEY_HANDLE, pbInput *uint8, cbInput uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptDuplicateKey maps to BCryptDuplicateKey in bcrypt.dll.
*/
type PFN_BCryptDuplicateKey func(hKey BCRYPT_KEY_HANDLE, phNewKey *BCRYPT_KEY_HANDLE, pbKeyObject *uint8, cbKeyObject uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptFinalizeKeyPair maps to BCryptFinalizeKeyPair in bcrypt.dll.
*/
type PFN_BCryptFinalizeKeyPair func(hKey BCRYPT_KEY_HANDLE, dwFlags uint32) NTSTATUS

/*
PFN_BCryptDestroyKey maps to BCryptDestroyKey in bcrypt.dll.
*/
type PFN_BCryptDestroyKey func(hKey BCRYPT_KEY_HANDLE) NTSTATUS

/*
PFN_BCryptDestroySecret maps to BCryptDestroySecret in bcrypt.dll.
*/
type PFN_BCryptDestroySecret func(hSecret BCRYPT_SECRET_HANDLE) NTSTATUS

/*
PFN_BCryptSignHash maps to BCryptSignHash in bcrypt.dll.
*/
type PFN_BCryptSignHash func(hKey BCRYPT_KEY_HANDLE, pPaddingInfo uintptr, pbInput *uint8, cbInput uint32, pbOutput *uint8, cbOutput uint32, pcbResult *uint32, dwFlags BCRYPT_FLAGS) NTSTATUS

/*
PFN_BCryptVerifySignature maps to BCryptVerifySignature in bcrypt.dll.
*/
type PFN_BCryptVerifySignature func(hKey BCRYPT_KEY_HANDLE, pPaddingInfo uintptr, pbHash *uint8, cbHash uint32, pbSignature *uint8, cbSignature uint32, dwFlags BCRYPT_FLAGS) NTSTATUS

/*
PFN_BCryptSecretAgreement maps to BCryptSecretAgreement in bcrypt.dll.
*/
type PFN_BCryptSecretAgreement func(hPrivKey BCRYPT_KEY_HANDLE, hPubKey BCRYPT_KEY_HANDLE, phAgreedSecret *BCRYPT_SECRET_HANDLE, dwFlags uint32) NTSTATUS

/*
PFN_BCryptDeriveKey maps to BCryptDeriveKey in bcrypt.dll.
*/
type PFN_BCryptDeriveKey func(hSharedSecret BCRYPT_SECRET_HANDLE, pwszKDF *PWSTRElement, pParameterList *BCryptBufferDesc, pbDerivedKey *uint8, cbDerivedKey uint32, pcbResult *uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptKeyDerivation maps to BCryptKeyDerivation in bcrypt.dll.
*/
type PFN_BCryptKeyDerivation func(hKey BCRYPT_KEY_HANDLE, pParameterList *BCryptBufferDesc, pbDerivedKey *uint8, cbDerivedKey uint32, pcbResult *uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptCreateHash maps to BCryptCreateHash in bcrypt.dll.
*/
type PFN_BCryptCreateHash func(hAlgorithm BCRYPT_ALG_HANDLE, phHash *BCRYPT_HASH_HANDLE, pbHashObject *uint8, cbHashObject uint32, pbSecret *uint8, cbSecret uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptHashData maps to BCryptHashData in bcrypt.dll.
*/
type PFN_BCryptHashData func(hHash BCRYPT_HASH_HANDLE, pbInput *uint8, cbInput uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptFinishHash maps to BCryptFinishHash in bcrypt.dll.
*/
type PFN_BCryptFinishHash func(hHash BCRYPT_HASH_HANDLE, pbOutput *uint8, cbOutput uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptCreateMultiHash maps to BCryptCreateMultiHash in bcrypt.dll.
*/
type PFN_BCryptCreateMultiHash func(hAlgorithm BCRYPT_ALG_HANDLE, phHash *BCRYPT_HASH_HANDLE, nHashes uint32, pbHashObject *uint8, cbHashObject uint32, pbSecret *uint8, cbSecret uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptProcessMultiOperations maps to BCryptProcessMultiOperations in bcrypt.dll.
*/
type PFN_BCryptProcessMultiOperations func(hObject BCRYPT_HANDLE, operationType BCRYPT_MULTI_OPERATION_TYPE, pOperations uintptr, cbOperations uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptDuplicateHash maps to BCryptDuplicateHash in bcrypt.dll.
*/
type PFN_BCryptDuplicateHash func(hHash BCRYPT_HASH_HANDLE, phNewHash *BCRYPT_HASH_HANDLE, pbHashObject *uint8, cbHashObject uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptDestroyHash maps to BCryptDestroyHash in bcrypt.dll.
*/
type PFN_BCryptDestroyHash func(hHash BCRYPT_HASH_HANDLE) NTSTATUS

/*
PFN_BCryptHash maps to BCryptHash in bcrypt.dll.
*/
type PFN_BCryptHash func(hAlgorithm BCRYPT_ALG_HANDLE, pbSecret *uint8, cbSecret uint32, pbInput *uint8, cbInput uint32, pbOutput *uint8, cbOutput uint32) NTSTATUS

/*
PFN_BCryptGenRandom maps to BCryptGenRandom in bcrypt.dll.
*/
type PFN_BCryptGenRandom func(hAlgorithm BCRYPT_ALG_HANDLE, pbBuffer *uint8, cbBuffer uint32, dwFlags BCRYPTGENRANDOM_FLAGS) NTSTATUS

/*
PFN_BCryptDeriveKeyCapi maps to BCryptDeriveKeyCapi in bcrypt.dll.
*/
type PFN_BCryptDeriveKeyCapi func(hHash BCRYPT_HASH_HANDLE, hTargetAlg BCRYPT_ALG_HANDLE, pbDerivedKey *uint8, cbDerivedKey uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptDeriveKeyPBKDF2 maps to BCryptDeriveKeyPBKDF2 in bcrypt.dll.
*/
type PFN_BCryptDeriveKeyPBKDF2 func(hPrf BCRYPT_ALG_HANDLE, pbPassword *uint8, cbPassword uint32, pbSalt *uint8, cbSalt uint32, cIterations uint64, pbDerivedKey *uint8, cbDerivedKey uint32, dwFlags uint32) NTSTATUS

/*
PFN_BCryptQueryProviderRegistration maps to BCryptQueryProviderRegistration in bcrypt.dll.
*/
type PFN_BCryptQueryProviderRegistration func(pszProvider *PWSTRElement, dwMode BCRYPT_QUERY_PROVIDER_MODE, dwInterface BCRYPT_INTERFACE, pcbBuffer *uint32, ppBuffer **CRYPT_PROVIDER_REG) NTSTATUS

/*
PFN_BCryptEnumRegisteredProviders maps to BCryptEnumRegisteredProviders in bcrypt.dll.
*/
type PFN_BCryptEnumRegisteredProviders func(pcbBuffer *uint32, ppBuffer **CRYPT_PROVIDERS) NTSTATUS

/*
PFN_BCryptCreateContext maps to BCryptCreateContext in bcrypt.dll.
*/
type PFN_BCryptCreateContext func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, pConfig *CRYPT_CONTEXT_CONFIG) NTSTATUS

/*
PFN_BCryptDeleteContext maps to BCryptDeleteContext in bcrypt.dll.
*/
type PFN_BCryptDeleteContext func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement) NTSTATUS

/*
PFN_BCryptEnumContexts maps to BCryptEnumContexts in bcrypt.dll.
*/
type PFN_BCryptEnumContexts func(dwTable BCRYPT_TABLE, pcbBuffer *uint32, ppBuffer **CRYPT_CONTEXTS) NTSTATUS

/*
PFN_BCryptConfigureContext maps to BCryptConfigureContext in bcrypt.dll.
*/
type PFN_BCryptConfigureContext func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, pConfig *CRYPT_CONTEXT_CONFIG) NTSTATUS

/*
PFN_BCryptQueryContextConfiguration maps to BCryptQueryContextConfiguration in bcrypt.dll.
*/
type PFN_BCryptQueryContextConfiguration func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, pcbBuffer *uint32, ppBuffer **CRYPT_CONTEXT_CONFIG) NTSTATUS

/*
PFN_BCryptAddContextFunction maps to BCryptAddContextFunction in bcrypt.dll.
*/
type PFN_BCryptAddContextFunction func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement, dwPosition uint32) NTSTATUS

/*
PFN_BCryptRemoveContextFunction maps to BCryptRemoveContextFunction in bcrypt.dll.
*/
type PFN_BCryptRemoveContextFunction func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement) NTSTATUS

/*
PFN_BCryptEnumContextFunctions maps to BCryptEnumContextFunctions in bcrypt.dll.
*/
type PFN_BCryptEnumContextFunctions func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pcbBuffer *uint32, ppBuffer **CRYPT_CONTEXT_FUNCTIONS) NTSTATUS

/*
PFN_BCryptConfigureContextFunction maps to BCryptConfigureContextFunction in bcrypt.dll.
*/
type PFN_BCryptConfigureContextFunction func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement, pConfig *CRYPT_CONTEXT_FUNCTION_CONFIG) NTSTATUS

/*
PFN_BCryptQueryContextFunctionConfiguration maps to BCryptQueryContextFunctionConfiguration in bcrypt.dll.
*/
type PFN_BCryptQueryContextFunctionConfiguration func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement, pcbBuffer *uint32, ppBuffer **CRYPT_CONTEXT_FUNCTION_CONFIG) NTSTATUS

/*
PFN_BCryptEnumContextFunctionProviders maps to BCryptEnumContextFunctionProviders in bcrypt.dll.
*/
type PFN_BCryptEnumContextFunctionProviders func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement, pcbBuffer *uint32, ppBuffer **CRYPT_CONTEXT_FUNCTION_PROVIDERS) NTSTATUS

/*
PFN_BCryptSetContextFunctionProperty maps to BCryptSetContextFunctionProperty in bcrypt.dll.
*/
type PFN_BCryptSetContextFunctionProperty func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement, pszProperty *PWSTRElement, cbValue uint32, pbValue *uint8) NTSTATUS

/*
PFN_BCryptQueryContextFunctionProperty maps to BCryptQueryContextFunctionProperty in bcrypt.dll.
*/
type PFN_BCryptQueryContextFunctionProperty func(dwTable BCRYPT_TABLE, pszContext *PWSTRElement, dwInterface BCRYPT_INTERFACE, pszFunction *PWSTRElement, pszProperty *PWSTRElement, pcbValue *uint32, ppbValue **uint8) NTSTATUS

/*
PFN_BCryptRegisterConfigChangeNotify maps to BCryptRegisterConfigChangeNotify in bcrypt.dll.
*/
type PFN_BCryptRegisterConfigChangeNotify func(phEvent *HANDLE) NTSTATUS

/*
PFN_BCryptUnregisterConfigChangeNotify maps to BCryptUnregisterConfigChangeNotify in bcrypt.dll.
*/
type PFN_BCryptUnregisterConfigChangeNotify func(hEvent HANDLE) NTSTATUS

/*
PFN_BCryptResolveProviders maps to BCryptResolveProviders in bcrypt.dll.
*/
type PFN_BCryptResolveProviders func(pszContext *PWSTRElement, dwInterface uint32, pszFunction *PWSTRElement, pszProvider *PWSTRElement, dwMode BCRYPT_QUERY_PROVIDER_MODE, dwFlags BCRYPT_RESOLVE_PROVIDERS_FLAGS, pcbBuffer *uint32, ppBuffer **CRYPT_PROVIDER_REFS) NTSTATUS

/*
PFN_BCryptGetFipsAlgorithmMode maps to BCryptGetFipsAlgorithmMode in bcrypt.dll.
*/
type PFN_BCryptGetFipsAlgorithmMode func(pfEnabled *uint8) NTSTATUS
