//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:44 CEST

package bindings

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	IDENTITY_KEYWORD_ASSOCIATED           uintptr
	IDENTITY_KEYWORD_LOCAL                uintptr
	IDENTITY_KEYWORD_HOMEGROUP            uintptr
	IDENTITY_KEYWORD_CONNECTED            uintptr
	OID_OAssociatedIdentityProviderObject Guid
	STR_OUT_OF_BOX_EXPERIENCE             uintptr
	STR_MODERN_SETTINGS_ADD_USER          uintptr
	STR_OUT_OF_BOX_UPGRADE_EXPERIENCE     uintptr
	STR_COMPLETE_ACCOUNT                  uintptr
	STR_NTH_USER_FIRST_AUTH               uintptr
	STR_USER_NAME                         uintptr
	STR_PROPERTY_STORE                    uintptr
}

/*
IDENTITY_TYPE is generated from Windows.Win32 metadata.
*/
type IDENTITY_TYPE int32

const (
	/*
		IDENTITIES_ALL from Windows.Win32 metadata.
	*/
	IDENTITIES_ALL IDENTITY_TYPE = 0x0

	/*
		IDENTITIES_ME_ONLY from Windows.Win32 metadata.
	*/
	IDENTITIES_ME_ONLY IDENTITY_TYPE = 0x1
)

/*
IdentityUpdateEvent is generated from Windows.Win32 metadata.
*/
type IdentityUpdateEvent int32

const (
	/*
		IDENTITY_ASSOCIATED from Windows.Win32 metadata.
	*/
	IDENTITY_ASSOCIATED IdentityUpdateEvent = 0x1

	/*
		IDENTITY_DISASSOCIATED from Windows.Win32 metadata.
	*/
	IDENTITY_DISASSOCIATED IdentityUpdateEvent = 0x2

	/*
		IDENTITY_CREATED from Windows.Win32 metadata.
	*/
	IDENTITY_CREATED IdentityUpdateEvent = 0x4

	/*
		IDENTITY_IMPORTED from Windows.Win32 metadata.
	*/
	IDENTITY_IMPORTED IdentityUpdateEvent = 0x8

	/*
		IDENTITY_DELETED from Windows.Win32 metadata.
	*/
	IDENTITY_DELETED IdentityUpdateEvent = 0x10

	/*
		IDENTITY_PROPCHANGED from Windows.Win32 metadata.
	*/
	IDENTITY_PROPCHANGED IdentityUpdateEvent = 0x20

	/*
		IDENTITY_CONNECTED from Windows.Win32 metadata.
	*/
	IDENTITY_CONNECTED IdentityUpdateEvent = 0x40

	/*
		IDENTITY_DISCONNECTED from Windows.Win32 metadata.
	*/
	IDENTITY_DISCONNECTED IdentityUpdateEvent = 0x80
)

/*
IIdentityAdvise is generated from Windows.Win32 metadata.
*/
type IIdentityAdvise uintptr

/*
AsyncIIdentityAdvise is generated from Windows.Win32 metadata.
*/
type AsyncIIdentityAdvise uintptr

/*
IIdentityProvider is generated from Windows.Win32 metadata.
*/
type IIdentityProvider uintptr

/*
AsyncIIdentityProvider is generated from Windows.Win32 metadata.
*/
type AsyncIIdentityProvider uintptr

/*
IAssociatedIdentityProvider is generated from Windows.Win32 metadata.
*/
type IAssociatedIdentityProvider uintptr

/*
AsyncIAssociatedIdentityProvider is generated from Windows.Win32 metadata.
*/
type AsyncIAssociatedIdentityProvider uintptr

/*
IDENTITY_URL is generated from Windows.Win32 metadata.
*/
type IDENTITY_URL int32

const (
	/*
		IDENTITY_URL_CREATE_ACCOUNT_WIZARD from Windows.Win32 metadata.
	*/
	IDENTITY_URL_CREATE_ACCOUNT_WIZARD IDENTITY_URL = 0x0

	/*
		IDENTITY_URL_SIGN_IN_WIZARD from Windows.Win32 metadata.
	*/
	IDENTITY_URL_SIGN_IN_WIZARD IDENTITY_URL = 0x1

	/*
		IDENTITY_URL_CHANGE_PASSWORD_WIZARD from Windows.Win32 metadata.
	*/
	IDENTITY_URL_CHANGE_PASSWORD_WIZARD IDENTITY_URL = 0x2

	/*
		IDENTITY_URL_IFEXISTS_WIZARD from Windows.Win32 metadata.
	*/
	IDENTITY_URL_IFEXISTS_WIZARD IDENTITY_URL = 0x3

	/*
		IDENTITY_URL_ACCOUNT_SETTINGS from Windows.Win32 metadata.
	*/
	IDENTITY_URL_ACCOUNT_SETTINGS IDENTITY_URL = 0x4

	/*
		IDENTITY_URL_RESTORE_WIZARD from Windows.Win32 metadata.
	*/
	IDENTITY_URL_RESTORE_WIZARD IDENTITY_URL = 0x5

	/*
		IDENTITY_URL_CONNECT_WIZARD from Windows.Win32 metadata.
	*/
	IDENTITY_URL_CONNECT_WIZARD IDENTITY_URL = 0x6
)

/*
ACCOUNT_STATE is generated from Windows.Win32 metadata.
*/
type ACCOUNT_STATE int32

const (
	/*
		NOT_CONNECTED from Windows.Win32 metadata.
	*/
	NOT_CONNECTED ACCOUNT_STATE = 0x0

	/*
		CONNECTING from Windows.Win32 metadata.
	*/
	CONNECTING ACCOUNT_STATE = 0x1

	/*
		CONNECT_COMPLETED from Windows.Win32 metadata.
	*/
	CONNECT_COMPLETED ACCOUNT_STATE = 0x2
)

/*
IConnectedIdentityProvider is generated from Windows.Win32 metadata.
*/
type IConnectedIdentityProvider uintptr

/*
AsyncIConnectedIdentityProvider is generated from Windows.Win32 metadata.
*/
type AsyncIConnectedIdentityProvider uintptr

/*
IIdentityAuthentication is generated from Windows.Win32 metadata.
*/
type IIdentityAuthentication uintptr

/*
AsyncIIdentityAuthentication is generated from Windows.Win32 metadata.
*/
type AsyncIIdentityAuthentication uintptr

/*
IIdentityStore is generated from Windows.Win32 metadata.
*/
type IIdentityStore uintptr

/*
AsyncIIdentityStore is generated from Windows.Win32 metadata.
*/
type AsyncIIdentityStore uintptr

/*
IIdentityStoreEx is generated from Windows.Win32 metadata.
*/
type IIdentityStoreEx uintptr

/*
AsyncIIdentityStoreEx is generated from Windows.Win32 metadata.
*/
type AsyncIIdentityStoreEx uintptr

/*
CoClassIdentityStore is generated from Windows.Win32 metadata.
*/
type CoClassIdentityStore struct {
}

/*
CIdentityProfileHandler is generated from Windows.Win32 metadata.
*/
type CIdentityProfileHandler struct {
}
