//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:45 CEST

package bindings

/*
PFN_RunSetupCommandA maps to RunSetupCommandA in advpack.dll.
*/
type PFN_RunSetupCommandA func(hWnd HWND, szCmdName *PSTRElement, szInfSection *PSTRElement, szDir *PSTRElement, lpszTitle *PSTRElement, phEXE *HANDLE, dwFlags uint32, pvReserved uintptr) HRESULT

/*
PFN_RunSetupCommandW maps to RunSetupCommandW in advpack.dll.
*/
type PFN_RunSetupCommandW func(hWnd HWND, szCmdName *PWSTRElement, szInfSection *PWSTRElement, szDir *PWSTRElement, lpszTitle *PWSTRElement, phEXE *HANDLE, dwFlags uint32, pvReserved uintptr) HRESULT

/*
PFN_NeedRebootInit maps to NeedRebootInit in advpack.dll.
*/
type PFN_NeedRebootInit func() uint32

/*
PFN_NeedReboot maps to NeedReboot in advpack.dll.
*/
type PFN_NeedReboot func(dwRebootCheck uint32) BOOL

/*
PFN_RebootCheckOnInstallA maps to RebootCheckOnInstallA in advpack.dll.
*/
type PFN_RebootCheckOnInstallA func(hwnd HWND, pszINF *PSTRElement, pszSec *PSTRElement, dwReserved uint32) HRESULT

/*
PFN_RebootCheckOnInstallW maps to RebootCheckOnInstallW in advpack.dll.
*/
type PFN_RebootCheckOnInstallW func(hwnd HWND, pszINF *PWSTRElement, pszSec *PWSTRElement, dwReserved uint32) HRESULT

/*
PFN_TranslateInfStringA maps to TranslateInfStringA in advpack.dll.
*/
type PFN_TranslateInfStringA func(pszInfFilename *PSTRElement, pszInstallSection *PSTRElement, pszTranslateSection *PSTRElement, pszTranslateKey *PSTRElement, pszBuffer *PSTRElement, cchBuffer uint32, pdwRequiredSize *uint32, pvReserved uintptr) HRESULT

/*
PFN_TranslateInfStringW maps to TranslateInfStringW in advpack.dll.
*/
type PFN_TranslateInfStringW func(pszInfFilename *PWSTRElement, pszInstallSection *PWSTRElement, pszTranslateSection *PWSTRElement, pszTranslateKey *PWSTRElement, pszBuffer *PWSTRElement, cchBuffer uint32, pdwRequiredSize *uint32, pvReserved uintptr) HRESULT

/*
PFN_RegInstallA maps to RegInstallA in advpack.dll.
*/
type PFN_RegInstallA func(hmod HMODULE, pszSection *PSTRElement, pstTable *STRTABLEA) HRESULT

/*
PFN_RegInstallW maps to RegInstallW in advpack.dll.
*/
type PFN_RegInstallW func(hmod HMODULE, pszSection *PWSTRElement, pstTable *STRTABLEW) HRESULT

/*
PFN_LaunchINFSectionExW maps to LaunchINFSectionExW in advpack.dll.
*/
type PFN_LaunchINFSectionExW func(hwnd HWND, hInstance HINSTANCE, pszParms *PWSTRElement, nShow int32) HRESULT

/*
PFN_ExecuteCabA maps to ExecuteCabA in advpack.dll.
*/
type PFN_ExecuteCabA func(hwnd HWND, pCab *CABINFOA, pReserved uintptr) HRESULT

/*
PFN_ExecuteCabW maps to ExecuteCabW in advpack.dll.
*/
type PFN_ExecuteCabW func(hwnd HWND, pCab *CABINFOW, pReserved uintptr) HRESULT

/*
PFN_AdvInstallFileA maps to AdvInstallFileA in advpack.dll.
*/
type PFN_AdvInstallFileA func(hwnd HWND, lpszSourceDir *PSTRElement, lpszSourceFile *PSTRElement, lpszDestDir *PSTRElement, lpszDestFile *PSTRElement, dwFlags uint32, dwReserved uint32) HRESULT

/*
PFN_AdvInstallFileW maps to AdvInstallFileW in advpack.dll.
*/
type PFN_AdvInstallFileW func(hwnd HWND, lpszSourceDir *PWSTRElement, lpszSourceFile *PWSTRElement, lpszDestDir *PWSTRElement, lpszDestFile *PWSTRElement, dwFlags uint32, dwReserved uint32) HRESULT

/*
PFN_RegSaveRestoreA maps to RegSaveRestoreA in advpack.dll.
*/
type PFN_RegSaveRestoreA func(hWnd HWND, pszTitleString *PSTRElement, hkBckupKey HKEY, pcszRootKey *PSTRElement, pcszSubKey *PSTRElement, pcszValueName *PSTRElement, dwFlags uint32) HRESULT

/*
PFN_RegSaveRestoreW maps to RegSaveRestoreW in advpack.dll.
*/
type PFN_RegSaveRestoreW func(hWnd HWND, pszTitleString *PWSTRElement, hkBckupKey HKEY, pcszRootKey *PWSTRElement, pcszSubKey *PWSTRElement, pcszValueName *PWSTRElement, dwFlags uint32) HRESULT

/*
PFN_RegSaveRestoreOnINFA maps to RegSaveRestoreOnINFA in advpack.dll.
*/
type PFN_RegSaveRestoreOnINFA func(hWnd HWND, pszTitle *PSTRElement, pszINF *PSTRElement, pszSection *PSTRElement, hHKLMBackKey HKEY, hHKCUBackKey HKEY, dwFlags uint32) HRESULT

/*
PFN_RegSaveRestoreOnINFW maps to RegSaveRestoreOnINFW in advpack.dll.
*/
type PFN_RegSaveRestoreOnINFW func(hWnd HWND, pszTitle *PWSTRElement, pszINF *PWSTRElement, pszSection *PWSTRElement, hHKLMBackKey HKEY, hHKCUBackKey HKEY, dwFlags uint32) HRESULT

/*
PFN_RegRestoreAllA maps to RegRestoreAllA in advpack.dll.
*/
type PFN_RegRestoreAllA func(hWnd HWND, pszTitleString *PSTRElement, hkBckupKey HKEY) HRESULT

/*
PFN_RegRestoreAllW maps to RegRestoreAllW in advpack.dll.
*/
type PFN_RegRestoreAllW func(hWnd HWND, pszTitleString *PWSTRElement, hkBckupKey HKEY) HRESULT

/*
PFN_FileSaveRestoreW maps to FileSaveRestoreW in advpack.dll.
*/
type PFN_FileSaveRestoreW func(hDlg HWND, lpFileList *PWSTRElement, lpDir *PWSTRElement, lpBaseName *PWSTRElement, dwFlags uint32) HRESULT

/*
PFN_FileSaveRestoreOnINFA maps to FileSaveRestoreOnINFA in advpack.dll.
*/
type PFN_FileSaveRestoreOnINFA func(hWnd HWND, pszTitle *PSTRElement, pszINF *PSTRElement, pszSection *PSTRElement, pszBackupDir *PSTRElement, pszBaseBackupFile *PSTRElement, dwFlags uint32) HRESULT

/*
PFN_FileSaveRestoreOnINFW maps to FileSaveRestoreOnINFW in advpack.dll.
*/
type PFN_FileSaveRestoreOnINFW func(hWnd HWND, pszTitle *PWSTRElement, pszINF *PWSTRElement, pszSection *PWSTRElement, pszBackupDir *PWSTRElement, pszBaseBackupFile *PWSTRElement, dwFlags uint32) HRESULT

/*
PFN_AddDelBackupEntryA maps to AddDelBackupEntryA in advpack.dll.
*/
type PFN_AddDelBackupEntryA func(lpcszFileList *PSTRElement, lpcszBackupDir *PSTRElement, lpcszBaseName *PSTRElement, dwFlags uint32) HRESULT

/*
PFN_AddDelBackupEntryW maps to AddDelBackupEntryW in advpack.dll.
*/
type PFN_AddDelBackupEntryW func(lpcszFileList *PWSTRElement, lpcszBackupDir *PWSTRElement, lpcszBaseName *PWSTRElement, dwFlags uint32) HRESULT

/*
PFN_FileSaveMarkNotExistA maps to FileSaveMarkNotExistA in advpack.dll.
*/
type PFN_FileSaveMarkNotExistA func(lpFileList *PSTRElement, lpDir *PSTRElement, lpBaseName *PSTRElement) HRESULT

/*
PFN_FileSaveMarkNotExistW maps to FileSaveMarkNotExistW in advpack.dll.
*/
type PFN_FileSaveMarkNotExistW func(lpFileList *PWSTRElement, lpDir *PWSTRElement, lpBaseName *PWSTRElement) HRESULT

/*
PFN_GetVersionFromFileA maps to GetVersionFromFileA in advpack.dll.
*/
type PFN_GetVersionFromFileA func(lpszFilename *PSTRElement, pdwMSVer *uint32, pdwLSVer *uint32, bVersion BOOL) HRESULT

/*
PFN_GetVersionFromFileW maps to GetVersionFromFileW in advpack.dll.
*/
type PFN_GetVersionFromFileW func(lpszFilename *PWSTRElement, pdwMSVer *uint32, pdwLSVer *uint32, bVersion BOOL) HRESULT

/*
PFN_GetVersionFromFileExA maps to GetVersionFromFileExA in advpack.dll.
*/
type PFN_GetVersionFromFileExA func(lpszFilename *PSTRElement, pdwMSVer *uint32, pdwLSVer *uint32, bVersion BOOL) HRESULT

/*
PFN_GetVersionFromFileExW maps to GetVersionFromFileExW in advpack.dll.
*/
type PFN_GetVersionFromFileExW func(lpszFilename *PWSTRElement, pdwMSVer *uint32, pdwLSVer *uint32, bVersion BOOL) HRESULT

/*
PFN_IsNTAdmin maps to IsNTAdmin in advpack.dll.
*/
type PFN_IsNTAdmin func(dwReserved uint32, lpdwReserved *uint32) BOOL

/*
PFN_DelNodeA maps to DelNodeA in advpack.dll.
*/
type PFN_DelNodeA func(pszFileOrDirName *PSTRElement, dwFlags uint32) HRESULT

/*
PFN_DelNodeW maps to DelNodeW in advpack.dll.
*/
type PFN_DelNodeW func(pszFileOrDirName *PWSTRElement, dwFlags uint32) HRESULT

/*
PFN_DelNodeRunDLL32W maps to DelNodeRunDLL32W in advpack.dll.
*/
type PFN_DelNodeRunDLL32W func(hwnd HWND, hInstance HINSTANCE, pszParms *PWSTRElement, nShow int32) HRESULT

/*
PFN_OpenINFEngineA maps to OpenINFEngineA in advpack.dll.
*/
type PFN_OpenINFEngineA func(pszInfFilename *PSTRElement, pszInstallSection *PSTRElement, dwFlags uint32, phInf *uintptr, pvReserved uintptr) HRESULT

/*
PFN_OpenINFEngineW maps to OpenINFEngineW in advpack.dll.
*/
type PFN_OpenINFEngineW func(pszInfFilename *PWSTRElement, pszInstallSection *PWSTRElement, dwFlags uint32, phInf *uintptr, pvReserved uintptr) HRESULT

/*
PFN_TranslateInfStringExA maps to TranslateInfStringExA in advpack.dll.
*/
type PFN_TranslateInfStringExA func(hInf uintptr, pszInfFilename *PSTRElement, pszTranslateSection *PSTRElement, pszTranslateKey *PSTRElement, pszBuffer *PSTRElement, dwBufferSize uint32, pdwRequiredSize *uint32, pvReserved uintptr) HRESULT

/*
PFN_TranslateInfStringExW maps to TranslateInfStringExW in advpack.dll.
*/
type PFN_TranslateInfStringExW func(hInf uintptr, pszInfFilename *PWSTRElement, pszTranslateSection *PWSTRElement, pszTranslateKey *PWSTRElement, pszBuffer *PWSTRElement, dwBufferSize uint32, pdwRequiredSize *uint32, pvReserved uintptr) HRESULT

/*
PFN_CloseINFEngine maps to CloseINFEngine in advpack.dll.
*/
type PFN_CloseINFEngine func(hInf uintptr) HRESULT

/*
PFN_ExtractFilesA maps to ExtractFilesA in advpack.dll.
*/
type PFN_ExtractFilesA func(pszCabName *PSTRElement, pszExpandDir *PSTRElement, dwFlags uint32, pszFileList *PSTRElement, lpReserved uintptr, dwReserved uint32) HRESULT

/*
PFN_ExtractFilesW maps to ExtractFilesW in advpack.dll.
*/
type PFN_ExtractFilesW func(pszCabName *PWSTRElement, pszExpandDir *PWSTRElement, dwFlags uint32, pszFileList *PWSTRElement, lpReserved uintptr, dwReserved uint32) HRESULT

/*
PFN_LaunchINFSectionW maps to LaunchINFSectionW in advpack.dll.
*/
type PFN_LaunchINFSectionW func(hwndOwner HWND, hInstance HINSTANCE, pszParams *PWSTRElement, nShow int32) int32

/*
PFN_UserInstStubWrapperA maps to UserInstStubWrapperA in advpack.dll.
*/
type PFN_UserInstStubWrapperA func(hwnd HWND, hInstance HINSTANCE, pszParms *PSTRElement, nShow int32) HRESULT

/*
PFN_UserInstStubWrapperW maps to UserInstStubWrapperW in advpack.dll.
*/
type PFN_UserInstStubWrapperW func(hwnd HWND, hInstance HINSTANCE, pszParms *PWSTRElement, nShow int32) HRESULT

/*
PFN_UserUnInstStubWrapperA maps to UserUnInstStubWrapperA in advpack.dll.
*/
type PFN_UserUnInstStubWrapperA func(hwnd HWND, hInstance HINSTANCE, pszParms *PSTRElement, nShow int32) HRESULT

/*
PFN_UserUnInstStubWrapperW maps to UserUnInstStubWrapperW in advpack.dll.
*/
type PFN_UserUnInstStubWrapperW func(hwnd HWND, hInstance HINSTANCE, pszParms *PWSTRElement, nShow int32) HRESULT

/*
PFN_SetPerUserSecValuesA maps to SetPerUserSecValuesA in advpack.dll.
*/
type PFN_SetPerUserSecValuesA func(pPerUser *PERUSERSECTIONA) HRESULT

/*
PFN_SetPerUserSecValuesW maps to SetPerUserSecValuesW in advpack.dll.
*/
type PFN_SetPerUserSecValuesW func(pPerUser *PERUSERSECTIONW) HRESULT
