//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_AllocateUserPhysicalPages2 maps to AllocateUserPhysicalPages2 in api-ms-win-core-memory-l1-1-8.dll.
*/
type PFN_AllocateUserPhysicalPages2 func(ObjectHandle HANDLE, NumberOfPages *uintptr, PageArray *uintptr, ExtendedParameters *MEM_EXTENDED_PARAMETER, ExtendedParameterCount uint32) BOOL

/*
PFN_OpenDedicatedMemoryPartition maps to OpenDedicatedMemoryPartition in api-ms-win-core-memory-l1-1-8.dll.
*/
type PFN_OpenDedicatedMemoryPartition func(Partition HANDLE, DedicatedMemoryTypeId uint64, DesiredAccess uint32, InheritHandle BOOL) HANDLE

/*
PFN_QueryPartitionInformation maps to QueryPartitionInformation in api-ms-win-core-memory-l1-1-8.dll.
*/
type PFN_QueryPartitionInformation func(Partition HANDLE, PartitionInformationClass WIN32_MEMORY_PARTITION_INFORMATION_CLASS, PartitionInformation uintptr, PartitionInformationLength uint32) BOOL
