//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_NetworkIsolationSetupAppContainerBinaries maps to NetworkIsolationSetupAppContainerBinaries in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationSetupAppContainerBinaries func(applicationContainerSid PSID, packageFullName *PWSTRElement, packageFolder *PWSTRElement, displayName *PWSTRElement, bBinariesFullyComputed BOOL, binaries **PWSTRElement, binariesCount uint32) HRESULT

/*
PFN_NetworkIsolationRegisterForAppContainerChanges maps to NetworkIsolationRegisterForAppContainerChanges in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationRegisterForAppContainerChanges func(flags uint32, callback PAC_CHANGES_CALLBACK_FN, context uintptr, registrationObject *HANDLE) uint32

/*
PFN_NetworkIsolationUnregisterForAppContainerChanges maps to NetworkIsolationUnregisterForAppContainerChanges in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationUnregisterForAppContainerChanges func(registrationObject HANDLE) uint32

/*
PFN_NetworkIsolationFreeAppContainers maps to NetworkIsolationFreeAppContainers in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationFreeAppContainers func(pPublicAppCs *INET_FIREWALL_APP_CONTAINER) uint32

/*
PFN_NetworkIsolationEnumAppContainers maps to NetworkIsolationEnumAppContainers in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationEnumAppContainers func(Flags uint32, pdwNumPublicAppCs *uint32, ppPublicAppCs **INET_FIREWALL_APP_CONTAINER) uint32

/*
PFN_NetworkIsolationGetAppContainerConfig maps to NetworkIsolationGetAppContainerConfig in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationGetAppContainerConfig func(pdwNumPublicAppCs *uint32, appContainerSids **SID_AND_ATTRIBUTES) uint32

/*
PFN_NetworkIsolationSetAppContainerConfig maps to NetworkIsolationSetAppContainerConfig in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationSetAppContainerConfig func(dwNumPublicAppCs uint32, appContainerSids *SID_AND_ATTRIBUTES) uint32

/*
PFN_NetworkIsolationDiagnoseConnectFailureAndGetInfo maps to NetworkIsolationDiagnoseConnectFailureAndGetInfo in api-ms-win-net-isolation-l1-1-0.dll.
*/
type PFN_NetworkIsolationDiagnoseConnectFailureAndGetInfo func(wszServerName *PWSTRElement, netIsoError *NETISO_ERROR_TYPE) uint32
