//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:54 CEST

package bindings

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	WMT_VIDEOIMAGE_SAMPLE_INPUT_FRAME               uint32
	WMT_VIDEOIMAGE_SAMPLE_OUTPUT_FRAME              uint32
	WMT_VIDEOIMAGE_SAMPLE_USES_CURRENT_INPUT_FRAME  uint32
	WMT_VIDEOIMAGE_SAMPLE_USES_PREVIOUS_INPUT_FRAME uint32
	WMT_VIDEOIMAGE_SAMPLE_MOTION                    uint32
	WMT_VIDEOIMAGE_SAMPLE_ROTATION                  uint32
	WMT_VIDEOIMAGE_SAMPLE_BLENDING                  uint32
	WMT_VIDEOIMAGE_SAMPLE_ADV_BLENDING              uint32
	WMT_VIDEOIMAGE_INTEGER_DENOMINATOR              int32
	WMT_VIDEOIMAGE_MAGIC_NUMBER                     uint32
	WMT_VIDEOIMAGE_MAGIC_NUMBER_2                   uint32
	WMT_VIDEOIMAGE_TRANSITION_BOW_TIE               uint32
	WMT_VIDEOIMAGE_TRANSITION_CIRCLE                uint32
	WMT_VIDEOIMAGE_TRANSITION_CROSS_FADE            uint32
	WMT_VIDEOIMAGE_TRANSITION_DIAGONAL              uint32
	WMT_VIDEOIMAGE_TRANSITION_DIAMOND               uint32
	WMT_VIDEOIMAGE_TRANSITION_FADE_TO_COLOR         uint32
	WMT_VIDEOIMAGE_TRANSITION_FILLED_V              uint32
	WMT_VIDEOIMAGE_TRANSITION_FLIP                  uint32
	WMT_VIDEOIMAGE_TRANSITION_INSET                 uint32
	WMT_VIDEOIMAGE_TRANSITION_IRIS                  uint32
	WMT_VIDEOIMAGE_TRANSITION_PAGE_ROLL             uint32
	WMT_VIDEOIMAGE_TRANSITION_RECTANGLE             uint32
	WMT_VIDEOIMAGE_TRANSITION_REVEAL                uint32
	WMT_VIDEOIMAGE_TRANSITION_SLIDE                 uint32
	WMT_VIDEOIMAGE_TRANSITION_SPLIT                 uint32
	WMT_VIDEOIMAGE_TRANSITION_STAR                  uint32
	WMT_VIDEOIMAGE_TRANSITION_WHEEL                 uint32
	WM_SampleExtension_ContentType_Size             uint32
	WM_SampleExtension_PixelAspectRatio_Size        uint32
	WM_SampleExtension_Timecode_Size                uint32
	WM_SampleExtension_SampleDuration_Size          uint32
	WM_SampleExtension_ChromaLocation_Size          uint32
	WM_SampleExtension_ColorSpaceInfo_Size          uint32
	WM_CT_REPEAT_FIRST_FIELD                        uint32
	WM_CT_BOTTOM_FIELD_FIRST                        uint32
	WM_CT_TOP_FIELD_FIRST                           uint32
	WM_CT_INTERLACED                                uint32
	WM_CL_INTERLACED420                             uint32
	WM_CL_PROGRESSIVE420                            uint32
	WM_MAX_VIDEO_STREAMS                            uint32
	WM_MAX_STREAMS                                  uint32
	WMDRM_IMPORT_INIT_STRUCT_DEFINED                uint32
	DRM_OPL_TYPES                                   uint32
	G_dwWMSpecialAttributes                         uint32
	G_wszWMDuration                                 uintptr
	G_wszWMBitrate                                  uintptr
	G_wszWMSeekable                                 uintptr
	G_wszWMStridable                                uintptr
	G_wszWMBroadcast                                uintptr
	G_wszWMProtected                                uintptr
	G_wszWMTrusted                                  uintptr
	G_wszWMSignature_Name                           uintptr
	G_wszWMHasAudio                                 uintptr
	G_wszWMHasImage                                 uintptr
	G_wszWMHasScript                                uintptr
	G_wszWMHasVideo                                 uintptr
	G_wszWMCurrentBitrate                           uintptr
	G_wszWMOptimalBitrate                           uintptr
	G_wszWMHasAttachedImages                        uintptr
	G_wszWMSkipBackward                             uintptr
	G_wszWMSkipForward                              uintptr
	G_wszWMNumberOfFrames                           uintptr
	G_wszWMFileSize                                 uintptr
	G_wszWMHasArbitraryDataStream                   uintptr
	G_wszWMHasFileTransferStream                    uintptr
	G_wszWMContainerFormat                          uintptr
	G_dwWMContentAttributes                         uint32
	G_wszWMTitle                                    uintptr
	G_wszWMTitleSort                                uintptr
	G_wszWMAuthor                                   uintptr
	G_wszWMAuthorSort                               uintptr
	G_wszWMDescription                              uintptr
	G_wszWMRating                                   uintptr
	G_wszWMCopyright                                uintptr
	G_wszWMUse_DRM                                  uintptr
	G_wszWMDRM_Flags                                uintptr
	G_wszWMDRM_Level                                uintptr
	G_wszWMUse_Advanced_DRM                         uintptr
	G_wszWMDRM_KeySeed                              uintptr
	G_wszWMDRM_KeyID                                uintptr
	G_wszWMDRM_ContentID                            uintptr
	G_wszWMDRM_SourceID                             uintptr
	G_wszWMDRM_IndividualizedVersion                uintptr
	G_wszWMDRM_LicenseAcqURL                        uintptr
	G_wszWMDRM_V1LicenseAcqURL                      uintptr
	G_wszWMDRM_HeaderSignPrivKey                    uintptr
	G_wszWMDRM_LASignaturePrivKey                   uintptr
	G_wszWMDRM_LASignatureCert                      uintptr
	G_wszWMDRM_LASignatureLicSrvCert                uintptr
	G_wszWMDRM_LASignatureRootCert                  uintptr
	G_wszWMAlbumTitle                               uintptr
	G_wszWMAlbumTitleSort                           uintptr
	G_wszWMTrack                                    uintptr
	G_wszWMPromotionURL                             uintptr
	G_wszWMAlbumCoverURL                            uintptr
	G_wszWMGenre                                    uintptr
	G_wszWMYear                                     uintptr
	G_wszWMGenreID                                  uintptr
	G_wszWMMCDI                                     uintptr
	G_wszWMComposer                                 uintptr
	G_wszWMComposerSort                             uintptr
	G_wszWMLyrics                                   uintptr
	G_wszWMTrackNumber                              uintptr
	G_wszWMToolName                                 uintptr
	G_wszWMToolVersion                              uintptr
	G_wszWMIsVBR                                    uintptr
	G_wszWMAlbumArtist                              uintptr
	G_wszWMAlbumArtistSort                          uintptr
	G_wszWMBannerImageType                          uintptr
	G_wszWMBannerImageData                          uintptr
	G_wszWMBannerImageURL                           uintptr
	G_wszWMCopyrightURL                             uintptr
	G_wszWMAspectRatioX                             uintptr
	G_wszWMAspectRatioY                             uintptr
	G_wszASFLeakyBucketPairs                        uintptr
	G_dwWMNSCAttributes                             uint32
	G_wszWMNSCName                                  uintptr
	G_wszWMNSCAddress                               uintptr
	G_wszWMNSCPhone                                 uintptr
	G_wszWMNSCEmail                                 uintptr
	G_wszWMNSCDescription                           uintptr
	G_wszWMWriter                                   uintptr
	G_wszWMConductor                                uintptr
	G_wszWMProducer                                 uintptr
	G_wszWMDirector                                 uintptr
	G_wszWMContentGroupDescription                  uintptr
	G_wszWMSubTitle                                 uintptr
	G_wszWMPartOfSet                                uintptr
	G_wszWMProtectionType                           uintptr
	G_wszWMVideoHeight                              uintptr
	G_wszWMVideoWidth                               uintptr
	G_wszWMVideoFrameRate                           uintptr
	G_wszWMMediaClassPrimaryID                      uintptr
	G_wszWMMediaClassSecondaryID                    uintptr
	G_wszWMPeriod                                   uintptr
	G_wszWMCategory                                 uintptr
	G_wszWMPicture                                  uintptr
	G_wszWMLyrics_Synchronised                      uintptr
	G_wszWMOriginalLyricist                         uintptr
	G_wszWMOriginalArtist                           uintptr
	G_wszWMOriginalAlbumTitle                       uintptr
	G_wszWMOriginalReleaseYear                      uintptr
	G_wszWMOriginalFilename                         uintptr
	G_wszWMPublisher                                uintptr
	G_wszWMEncodedBy                                uintptr
	G_wszWMEncodingSettings                         uintptr
	G_wszWMEncodingTime                             uintptr
	G_wszWMAuthorURL                                uintptr
	G_wszWMUserWebURL                               uintptr
	G_wszWMAudioFileURL                             uintptr
	G_wszWMAudioSourceURL                           uintptr
	G_wszWMLanguage                                 uintptr
	G_wszWMParentalRating                           uintptr
	G_wszWMBeatsPerMinute                           uintptr
	G_wszWMInitialKey                               uintptr
	G_wszWMMood                                     uintptr
	G_wszWMText                                     uintptr
	G_wszWMDVDID                                    uintptr
	G_wszWMWMContentID                              uintptr
	G_wszWMWMCollectionID                           uintptr
	G_wszWMWMCollectionGroupID                      uintptr
	G_wszWMUniqueFileIdentifier                     uintptr
	G_wszWMModifiedBy                               uintptr
	G_wszWMRadioStationName                         uintptr
	G_wszWMRadioStationOwner                        uintptr
	G_wszWMPlaylistDelay                            uintptr
	G_wszWMCodec                                    uintptr
	G_wszWMDRM                                      uintptr
	G_wszWMISRC                                     uintptr
	G_wszWMProvider                                 uintptr
	G_wszWMProviderRating                           uintptr
	G_wszWMProviderStyle                            uintptr
	G_wszWMContentDistributor                       uintptr
	G_wszWMSubscriptionContentID                    uintptr
	G_wszWMWMADRCPeakReference                      uintptr
	G_wszWMWMADRCPeakTarget                         uintptr
	G_wszWMWMADRCAverageReference                   uintptr
	G_wszWMWMADRCAverageTarget                      uintptr
	G_wszWMStreamTypeInfo                           uintptr
	G_wszWMPeakBitrate                              uintptr
	G_wszWMASFPacketCount                           uintptr
	G_wszWMASFSecurityObjectsSize                   uintptr
	G_wszWMSharedUserRating                         uintptr
	G_wszWMSubTitleDescription                      uintptr
	G_wszWMMediaCredits                             uintptr
	G_wszWMParentalRatingReason                     uintptr
	G_wszWMOriginalReleaseTime                      uintptr
	G_wszWMMediaStationCallSign                     uintptr
	G_wszWMMediaStationName                         uintptr
	G_wszWMMediaNetworkAffiliation                  uintptr
	G_wszWMMediaOriginalChannel                     uintptr
	G_wszWMMediaOriginalBroadcastDateTime           uintptr
	G_wszWMMediaIsStereo                            uintptr
	G_wszWMVideoClosedCaptioning                    uintptr
	G_wszWMMediaIsRepeat                            uintptr
	G_wszWMMediaIsLive                              uintptr
	G_wszWMMediaIsTape                              uintptr
	G_wszWMMediaIsDelay                             uintptr
	G_wszWMMediaIsSubtitled                         uintptr
	G_wszWMMediaIsPremiere                          uintptr
	G_wszWMMediaIsFinale                            uintptr
	G_wszWMMediaIsSAP                               uintptr
	G_wszWMProviderCopyright                        uintptr
	G_wszWMISAN                                     uintptr
	G_wszWMADID                                     uintptr
	G_wszWMWMShadowFileSourceFileType               uintptr
	G_wszWMWMShadowFileSourceDRMType                uintptr
	G_wszWMWMCPDistributor                          uintptr
	G_wszWMWMCPDistributorID                        uintptr
	G_wszWMSeasonNumber                             uintptr
	G_wszWMEpisodeNumber                            uintptr
	G_wszEarlyDataDelivery                          uintptr
	G_wszJustInTimeDecode                           uintptr
	G_wszSingleOutputBuffer                         uintptr
	G_wszSoftwareScaling                            uintptr
	G_wszDeliverOnReceive                           uintptr
	G_wszScrambledAudio                             uintptr
	G_wszDedicatedDeliveryThread                    uintptr
	G_wszEnableDiscreteOutput                       uintptr
	G_wszSpeakerConfig                              uintptr
	G_wszDynamicRangeControl                        uintptr
	G_wszAllowInterlacedOutput                      uintptr
	G_wszVideoSampleDurations                       uintptr
	G_wszStreamLanguage                             uintptr
	G_wszEnableWMAProSPDIFOutput                    uintptr
	G_wszDeinterlaceMode                            uintptr
	G_wszInitialPatternForInverseTelecine           uintptr
	G_wszJPEGCompressionQuality                     uintptr
	G_wszWatermarkCLSID                             uintptr
	G_wszWatermarkConfig                            uintptr
	G_wszInterlacedCoding                           uintptr
	G_wszFixedFrameRate                             uintptr
	G_wszOriginalSourceFormatTag                    uintptr
	G_wszOriginalWaveFormat                         uintptr
	G_wszEDL                                        uintptr
	G_wszComplexity                                 uintptr
	G_wszDecoderComplexityRequested                 uintptr
	G_wszReloadIndexOnSeek                          uintptr
	G_wszStreamNumIndexObjects                      uintptr
	G_wszFailSeekOnError                            uintptr
	G_wszPermitSeeksBeyondEndOfStream               uintptr
	G_wszUsePacketAtSeekPoint                       uintptr
	G_wszSourceBufferTime                           uintptr
	G_wszSourceMaxBytesAtOnce                       uintptr
	G_wszVBREnabled                                 uintptr
	G_wszVBRQuality                                 uintptr
	G_wszVBRBitrateMax                              uintptr
	G_wszVBRBufferWindowMax                         uintptr
	G_wszVBRPeak                                    uintptr
	G_wszBufferAverage                              uintptr
	G_wszComplexityMax                              uintptr
	G_wszComplexityOffline                          uintptr
	G_wszComplexityLive                             uintptr
	G_wszIsVBRSupported                             uintptr
	G_wszNumPasses                                  uintptr
	G_wszMusicSpeechClassMode                       uintptr
	G_wszMusicClassMode                             uintptr
	G_wszSpeechClassMode                            uintptr
	G_wszMixedClassMode                             uintptr
	G_wszSpeechCaps                                 uintptr
	G_wszPeakValue                                  uintptr
	G_wszAverageLevel                               uintptr
	G_wszFold6To2Channels3                          uintptr
	G_wszFoldToChannelsTemplate                     uintptr
	G_wszDeviceConformanceTemplate                  uintptr
	G_wszEnableFrameInterpolation                   uintptr
	G_wszNeedsPreviousSample                        uintptr
	G_wszWMIsCompilation                            uintptr
	WMMEDIASUBTYPE_Base                             Guid
	WMMEDIATYPE_Video                               Guid
	WMMEDIASUBTYPE_RGB1                             Guid
	WMMEDIASUBTYPE_RGB4                             Guid
	WMMEDIASUBTYPE_RGB8                             Guid
	WMMEDIASUBTYPE_RGB565                           Guid
	WMMEDIASUBTYPE_RGB555                           Guid
	WMMEDIASUBTYPE_RGB24                            Guid
	WMMEDIASUBTYPE_RGB32                            Guid
	WMMEDIASUBTYPE_I420                             Guid
	WMMEDIASUBTYPE_IYUV                             Guid
	WMMEDIASUBTYPE_YV12                             Guid
	WMMEDIASUBTYPE_YUY2                             Guid
	WMMEDIASUBTYPE_P422                             Guid
	WMMEDIASUBTYPE_UYVY                             Guid
	WMMEDIASUBTYPE_YVYU                             Guid
	WMMEDIASUBTYPE_YVU9                             Guid
	WMMEDIASUBTYPE_VIDEOIMAGE                       Guid
	WMMEDIASUBTYPE_MP43                             Guid
	WMMEDIASUBTYPE_MP4S                             Guid
	WMMEDIASUBTYPE_M4S2                             Guid
	WMMEDIASUBTYPE_WMV1                             Guid
	WMMEDIASUBTYPE_WMV2                             Guid
	WMMEDIASUBTYPE_MSS1                             Guid
	WMMEDIASUBTYPE_MPEG2_VIDEO                      Guid
	WMMEDIATYPE_Audio                               Guid
	WMMEDIASUBTYPE_PCM                              Guid
	WMMEDIASUBTYPE_DRM                              Guid
	WMMEDIASUBTYPE_WMAudioV9                        Guid
	WMMEDIASUBTYPE_WMAudio_Lossless                 Guid
	WMMEDIASUBTYPE_MSS2                             Guid
	WMMEDIASUBTYPE_WMSP1                            Guid
	WMMEDIASUBTYPE_WMSP2                            Guid
	WMMEDIASUBTYPE_WMV3                             Guid
	WMMEDIASUBTYPE_WMVP                             Guid
	WMMEDIASUBTYPE_WVP2                             Guid
	WMMEDIASUBTYPE_WMVA                             Guid
	WMMEDIASUBTYPE_WVC1                             Guid
	WMMEDIASUBTYPE_WMAudioV8                        Guid
	WMMEDIASUBTYPE_WMAudioV7                        Guid
	WMMEDIASUBTYPE_WMAudioV2                        Guid
	WMMEDIASUBTYPE_ACELPnet                         Guid
	WMMEDIASUBTYPE_MP3                              Guid
	WMMEDIASUBTYPE_WebStream                        Guid
	WMMEDIATYPE_Script                              Guid
	WMMEDIATYPE_Image                               Guid
	WMMEDIATYPE_FileTransfer                        Guid
	WMMEDIATYPE_Text                                Guid
	WMFORMAT_VideoInfo                              Guid
	WMFORMAT_MPEG2Video                             Guid
	WMFORMAT_WaveFormatEx                           Guid
	WMFORMAT_Script                                 Guid
	WMFORMAT_WebStream                              Guid
	WMSCRIPTTYPE_TwoStrings                         Guid
	WM_SampleExtensionGUID_OutputCleanPoint         Guid
	WM_SampleExtensionGUID_Timecode                 Guid
	WM_SampleExtensionGUID_ChromaLocation           Guid
	WM_SampleExtensionGUID_ColorSpaceInfo           Guid
	WM_SampleExtensionGUID_UserDataInfo             Guid
	WM_SampleExtensionGUID_FileName                 Guid
	WM_SampleExtensionGUID_ContentType              Guid
	WM_SampleExtensionGUID_PixelAspectRatio         Guid
	WM_SampleExtensionGUID_SampleDuration           Guid
	WM_SampleExtensionGUID_SampleProtectionSalt     Guid
	CLSID_WMMUTEX_Language                          Guid
	CLSID_WMMUTEX_Bitrate                           Guid
	CLSID_WMMUTEX_Presentation                      Guid
	CLSID_WMMUTEX_Unknown                           Guid
	CLSID_WMBandwidthSharing_Exclusive              Guid
	CLSID_WMBandwidthSharing_Partial                Guid
	WMT_DMOCATEGORY_AUDIO_WATERMARK                 Guid
	WMT_DMOCATEGORY_VIDEO_WATERMARK                 Guid
	CLSID_ClientNetManager                          Guid
}

/*
_AM_ASFWRITERCONFIG_PARAM is generated from Windows.Win32 metadata.
*/
type _AM_ASFWRITERCONFIG_PARAM int32

const (
	/*
		AM_CONFIGASFWRITER_PARAM_AUTOINDEX from Windows.Win32 metadata.
	*/
	AM_CONFIGASFWRITER_PARAM_AUTOINDEX _AM_ASFWRITERCONFIG_PARAM = 0x1

	/*
		AM_CONFIGASFWRITER_PARAM_MULTIPASS from Windows.Win32 metadata.
	*/
	AM_CONFIGASFWRITER_PARAM_MULTIPASS _AM_ASFWRITERCONFIG_PARAM = 0x2

	/*
		AM_CONFIGASFWRITER_PARAM_DONTCOMPRESS from Windows.Win32 metadata.
	*/
	AM_CONFIGASFWRITER_PARAM_DONTCOMPRESS _AM_ASFWRITERCONFIG_PARAM = 0x3
)

/*
AM_WMT_EVENT_DATA is generated from Windows.Win32 metadata.
*/
type AM_WMT_EVENT_DATA struct {
	HrStatus HRESULT
	PData    uintptr
}

/*
INSSBuffer is generated from Windows.Win32 metadata.
*/
type INSSBuffer uintptr

/*
INSSBuffer2 is generated from Windows.Win32 metadata.
*/
type INSSBuffer2 uintptr

/*
INSSBuffer3 is generated from Windows.Win32 metadata.
*/
type INSSBuffer3 uintptr

/*
INSSBuffer4 is generated from Windows.Win32 metadata.
*/
type INSSBuffer4 uintptr

/*
IWMSBufferAllocator is generated from Windows.Win32 metadata.
*/
type IWMSBufferAllocator uintptr

/*
WEBSTREAM_SAMPLE_TYPE is generated from Windows.Win32 metadata.
*/
type WEBSTREAM_SAMPLE_TYPE int32

const (
	/*
		WEBSTREAM_SAMPLE_TYPE_FILE from Windows.Win32 metadata.
	*/
	WEBSTREAM_SAMPLE_TYPE_FILE WEBSTREAM_SAMPLE_TYPE = 0x1

	/*
		WEBSTREAM_SAMPLE_TYPE_RENDER from Windows.Win32 metadata.
	*/
	WEBSTREAM_SAMPLE_TYPE_RENDER WEBSTREAM_SAMPLE_TYPE = 0x2
)

/*
WM_SF_TYPE is generated from Windows.Win32 metadata.
*/
type WM_SF_TYPE int32

const (
	/*
		WM_SF_CLEANPOINT from Windows.Win32 metadata.
	*/
	WM_SF_CLEANPOINT WM_SF_TYPE = 0x1

	/*
		WM_SF_DISCONTINUITY from Windows.Win32 metadata.
	*/
	WM_SF_DISCONTINUITY WM_SF_TYPE = 0x2

	/*
		WM_SF_DATALOSS from Windows.Win32 metadata.
	*/
	WM_SF_DATALOSS WM_SF_TYPE = 0x4
)

/*
WM_SFEX_TYPE is generated from Windows.Win32 metadata.
*/
type WM_SFEX_TYPE int32

const (
	/*
		WM_SFEX_NOTASYNCPOINT from Windows.Win32 metadata.
	*/
	WM_SFEX_NOTASYNCPOINT WM_SFEX_TYPE = 0x2

	/*
		WM_SFEX_DATALOSS from Windows.Win32 metadata.
	*/
	WM_SFEX_DATALOSS WM_SFEX_TYPE = 0x4
)

/*
WMT_STATUS is generated from Windows.Win32 metadata.
*/
type WMT_STATUS int32

const (
	/*
		WMT_ERROR from Windows.Win32 metadata.
	*/
	WMT_ERROR WMT_STATUS = 0x0

	/*
		WMT_OPENED from Windows.Win32 metadata.
	*/
	WMT_OPENED WMT_STATUS = 0x1

	/*
		WMT_BUFFERING_START from Windows.Win32 metadata.
	*/
	WMT_BUFFERING_START WMT_STATUS = 0x2

	/*
		WMT_BUFFERING_STOP from Windows.Win32 metadata.
	*/
	WMT_BUFFERING_STOP WMT_STATUS = 0x3

	/*
		WMT_EOF from Windows.Win32 metadata.
	*/
	WMT_EOF WMT_STATUS = 0x4

	/*
		WMT_END_OF_FILE from Windows.Win32 metadata.
	*/
	WMT_END_OF_FILE WMT_STATUS = 0x4

	/*
		WMT_END_OF_SEGMENT from Windows.Win32 metadata.
	*/
	WMT_END_OF_SEGMENT WMT_STATUS = 0x5

	/*
		WMT_END_OF_STREAMING from Windows.Win32 metadata.
	*/
	WMT_END_OF_STREAMING WMT_STATUS = 0x6

	/*
		WMT_LOCATING from Windows.Win32 metadata.
	*/
	WMT_LOCATING WMT_STATUS = 0x7

	/*
		WMT_CONNECTING from Windows.Win32 metadata.
	*/
	WMT_CONNECTING WMT_STATUS = 0x8

	/*
		WMT_NO_RIGHTS from Windows.Win32 metadata.
	*/
	WMT_NO_RIGHTS WMT_STATUS = 0x9

	/*
		WMT_MISSING_CODEC from Windows.Win32 metadata.
	*/
	WMT_MISSING_CODEC WMT_STATUS = 0xa

	/*
		WMT_STARTED from Windows.Win32 metadata.
	*/
	WMT_STARTED WMT_STATUS = 0xb

	/*
		WMT_STOPPED from Windows.Win32 metadata.
	*/
	WMT_STOPPED WMT_STATUS = 0xc

	/*
		WMT_CLOSED from Windows.Win32 metadata.
	*/
	WMT_CLOSED WMT_STATUS = 0xd

	/*
		WMT_STRIDING from Windows.Win32 metadata.
	*/
	WMT_STRIDING WMT_STATUS = 0xe

	/*
		WMT_TIMER from Windows.Win32 metadata.
	*/
	WMT_TIMER WMT_STATUS = 0xf

	/*
		WMT_INDEX_PROGRESS from Windows.Win32 metadata.
	*/
	WMT_INDEX_PROGRESS WMT_STATUS = 0x10

	/*
		WMT_SAVEAS_START from Windows.Win32 metadata.
	*/
	WMT_SAVEAS_START WMT_STATUS = 0x11

	/*
		WMT_SAVEAS_STOP from Windows.Win32 metadata.
	*/
	WMT_SAVEAS_STOP WMT_STATUS = 0x12

	/*
		WMT_NEW_SOURCEFLAGS from Windows.Win32 metadata.
	*/
	WMT_NEW_SOURCEFLAGS WMT_STATUS = 0x13

	/*
		WMT_NEW_METADATA from Windows.Win32 metadata.
	*/
	WMT_NEW_METADATA WMT_STATUS = 0x14

	/*
		WMT_BACKUPRESTORE_BEGIN from Windows.Win32 metadata.
	*/
	WMT_BACKUPRESTORE_BEGIN WMT_STATUS = 0x15

	/*
		WMT_SOURCE_SWITCH from Windows.Win32 metadata.
	*/
	WMT_SOURCE_SWITCH WMT_STATUS = 0x16

	/*
		WMT_ACQUIRE_LICENSE from Windows.Win32 metadata.
	*/
	WMT_ACQUIRE_LICENSE WMT_STATUS = 0x17

	/*
		WMT_INDIVIDUALIZE from Windows.Win32 metadata.
	*/
	WMT_INDIVIDUALIZE WMT_STATUS = 0x18

	/*
		WMT_NEEDS_INDIVIDUALIZATION from Windows.Win32 metadata.
	*/
	WMT_NEEDS_INDIVIDUALIZATION WMT_STATUS = 0x19

	/*
		WMT_NO_RIGHTS_EX from Windows.Win32 metadata.
	*/
	WMT_NO_RIGHTS_EX WMT_STATUS = 0x1a

	/*
		WMT_BACKUPRESTORE_END from Windows.Win32 metadata.
	*/
	WMT_BACKUPRESTORE_END WMT_STATUS = 0x1b

	/*
		WMT_BACKUPRESTORE_CONNECTING from Windows.Win32 metadata.
	*/
	WMT_BACKUPRESTORE_CONNECTING WMT_STATUS = 0x1c

	/*
		WMT_BACKUPRESTORE_DISCONNECTING from Windows.Win32 metadata.
	*/
	WMT_BACKUPRESTORE_DISCONNECTING WMT_STATUS = 0x1d

	/*
		WMT_ERROR_WITHURL from Windows.Win32 metadata.
	*/
	WMT_ERROR_WITHURL WMT_STATUS = 0x1e

	/*
		WMT_RESTRICTED_LICENSE from Windows.Win32 metadata.
	*/
	WMT_RESTRICTED_LICENSE WMT_STATUS = 0x1f

	/*
		WMT_CLIENT_CONNECT from Windows.Win32 metadata.
	*/
	WMT_CLIENT_CONNECT WMT_STATUS = 0x20

	/*
		WMT_CLIENT_DISCONNECT from Windows.Win32 metadata.
	*/
	WMT_CLIENT_DISCONNECT WMT_STATUS = 0x21

	/*
		WMT_NATIVE_OUTPUT_PROPS_CHANGED from Windows.Win32 metadata.
	*/
	WMT_NATIVE_OUTPUT_PROPS_CHANGED WMT_STATUS = 0x22

	/*
		WMT_RECONNECT_START from Windows.Win32 metadata.
	*/
	WMT_RECONNECT_START WMT_STATUS = 0x23

	/*
		WMT_RECONNECT_END from Windows.Win32 metadata.
	*/
	WMT_RECONNECT_END WMT_STATUS = 0x24

	/*
		WMT_CLIENT_CONNECT_EX from Windows.Win32 metadata.
	*/
	WMT_CLIENT_CONNECT_EX WMT_STATUS = 0x25

	/*
		WMT_CLIENT_DISCONNECT_EX from Windows.Win32 metadata.
	*/
	WMT_CLIENT_DISCONNECT_EX WMT_STATUS = 0x26

	/*
		WMT_SET_FEC_SPAN from Windows.Win32 metadata.
	*/
	WMT_SET_FEC_SPAN WMT_STATUS = 0x27

	/*
		WMT_PREROLL_READY from Windows.Win32 metadata.
	*/
	WMT_PREROLL_READY WMT_STATUS = 0x28

	/*
		WMT_PREROLL_COMPLETE from Windows.Win32 metadata.
	*/
	WMT_PREROLL_COMPLETE WMT_STATUS = 0x29

	/*
		WMT_CLIENT_PROPERTIES from Windows.Win32 metadata.
	*/
	WMT_CLIENT_PROPERTIES WMT_STATUS = 0x2a

	/*
		WMT_LICENSEURL_SIGNATURE_STATE from Windows.Win32 metadata.
	*/
	WMT_LICENSEURL_SIGNATURE_STATE WMT_STATUS = 0x2b

	/*
		WMT_INIT_PLAYLIST_BURN from Windows.Win32 metadata.
	*/
	WMT_INIT_PLAYLIST_BURN WMT_STATUS = 0x2c

	/*
		WMT_TRANSCRYPTOR_INIT from Windows.Win32 metadata.
	*/
	WMT_TRANSCRYPTOR_INIT WMT_STATUS = 0x2d

	/*
		WMT_TRANSCRYPTOR_SEEKED from Windows.Win32 metadata.
	*/
	WMT_TRANSCRYPTOR_SEEKED WMT_STATUS = 0x2e

	/*
		WMT_TRANSCRYPTOR_READ from Windows.Win32 metadata.
	*/
	WMT_TRANSCRYPTOR_READ WMT_STATUS = 0x2f

	/*
		WMT_TRANSCRYPTOR_CLOSED from Windows.Win32 metadata.
	*/
	WMT_TRANSCRYPTOR_CLOSED WMT_STATUS = 0x30

	/*
		WMT_PROXIMITY_RESULT from Windows.Win32 metadata.
	*/
	WMT_PROXIMITY_RESULT WMT_STATUS = 0x31

	/*
		WMT_PROXIMITY_COMPLETED from Windows.Win32 metadata.
	*/
	WMT_PROXIMITY_COMPLETED WMT_STATUS = 0x32

	/*
		WMT_CONTENT_ENABLER from Windows.Win32 metadata.
	*/
	WMT_CONTENT_ENABLER WMT_STATUS = 0x33
)

/*
WMT_STREAM_SELECTION is generated from Windows.Win32 metadata.
*/
type WMT_STREAM_SELECTION int32

const (
	/*
		WMT_OFF from Windows.Win32 metadata.
	*/
	WMT_OFF WMT_STREAM_SELECTION = 0x0

	/*
		WMT_CLEANPOINT_ONLY from Windows.Win32 metadata.
	*/
	WMT_CLEANPOINT_ONLY WMT_STREAM_SELECTION = 0x1

	/*
		WMT_ON from Windows.Win32 metadata.
	*/
	WMT_ON WMT_STREAM_SELECTION = 0x2
)

/*
WMT_IMAGE_TYPE is generated from Windows.Win32 metadata.
*/
type WMT_IMAGE_TYPE int32

const (
	/*
		WMT_IT_NONE from Windows.Win32 metadata.
	*/
	WMT_IT_NONE WMT_IMAGE_TYPE = 0x0

	/*
		WMT_IT_BITMAP from Windows.Win32 metadata.
	*/
	WMT_IT_BITMAP WMT_IMAGE_TYPE = 0x1

	/*
		WMT_IT_JPEG from Windows.Win32 metadata.
	*/
	WMT_IT_JPEG WMT_IMAGE_TYPE = 0x2

	/*
		WMT_IT_GIF from Windows.Win32 metadata.
	*/
	WMT_IT_GIF WMT_IMAGE_TYPE = 0x3
)

/*
WMT_ATTR_DATATYPE is generated from Windows.Win32 metadata.
*/
type WMT_ATTR_DATATYPE int32

const (
	/*
		WMT_TYPE_DWORD from Windows.Win32 metadata.
	*/
	WMT_TYPE_DWORD WMT_ATTR_DATATYPE = 0x0

	/*
		WMT_TYPE_STRING from Windows.Win32 metadata.
	*/
	WMT_TYPE_STRING WMT_ATTR_DATATYPE = 0x1

	/*
		WMT_TYPE_BINARY from Windows.Win32 metadata.
	*/
	WMT_TYPE_BINARY WMT_ATTR_DATATYPE = 0x2

	/*
		WMT_TYPE_BOOL from Windows.Win32 metadata.
	*/
	WMT_TYPE_BOOL WMT_ATTR_DATATYPE = 0x3

	/*
		WMT_TYPE_QWORD from Windows.Win32 metadata.
	*/
	WMT_TYPE_QWORD WMT_ATTR_DATATYPE = 0x4

	/*
		WMT_TYPE_WORD from Windows.Win32 metadata.
	*/
	WMT_TYPE_WORD WMT_ATTR_DATATYPE = 0x5

	/*
		WMT_TYPE_GUID from Windows.Win32 metadata.
	*/
	WMT_TYPE_GUID WMT_ATTR_DATATYPE = 0x6
)

/*
WMT_ATTR_IMAGETYPE is generated from Windows.Win32 metadata.
*/
type WMT_ATTR_IMAGETYPE int32

const (
	/*
		WMT_IMAGETYPE_BITMAP from Windows.Win32 metadata.
	*/
	WMT_IMAGETYPE_BITMAP WMT_ATTR_IMAGETYPE = 0x1

	/*
		WMT_IMAGETYPE_JPEG from Windows.Win32 metadata.
	*/
	WMT_IMAGETYPE_JPEG WMT_ATTR_IMAGETYPE = 0x2

	/*
		WMT_IMAGETYPE_GIF from Windows.Win32 metadata.
	*/
	WMT_IMAGETYPE_GIF WMT_ATTR_IMAGETYPE = 0x3
)

/*
WMT_VERSION is generated from Windows.Win32 metadata.
*/
type WMT_VERSION int32

const (
	/*
		WMT_VER_4_0 from Windows.Win32 metadata.
	*/
	WMT_VER_4_0 WMT_VERSION = 0x40000

	/*
		WMT_VER_7_0 from Windows.Win32 metadata.
	*/
	WMT_VER_7_0 WMT_VERSION = 0x70000

	/*
		WMT_VER_8_0 from Windows.Win32 metadata.
	*/
	WMT_VER_8_0 WMT_VERSION = 0x80000

	/*
		WMT_VER_9_0 from Windows.Win32 metadata.
	*/
	WMT_VER_9_0 WMT_VERSION = 0x90000
)

/*
WMT_STORAGE_FORMAT is generated from Windows.Win32 metadata.
*/
type WMT_STORAGE_FORMAT int32

const (
	/*
		WMT_Storage_Format_MP3 from Windows.Win32 metadata.
	*/
	WMT_Storage_Format_MP3 WMT_STORAGE_FORMAT = 0x0

	/*
		WMT_Storage_Format_V1 from Windows.Win32 metadata.
	*/
	WMT_Storage_Format_V1 WMT_STORAGE_FORMAT = 0x1
)

/*
WMT_DRMLA_TRUST is generated from Windows.Win32 metadata.
*/
type WMT_DRMLA_TRUST int32

const (
	/*
		WMT_DRMLA_UNTRUSTED from Windows.Win32 metadata.
	*/
	WMT_DRMLA_UNTRUSTED WMT_DRMLA_TRUST = 0x0

	/*
		WMT_DRMLA_TRUSTED from Windows.Win32 metadata.
	*/
	WMT_DRMLA_TRUSTED WMT_DRMLA_TRUST = 0x1

	/*
		WMT_DRMLA_TAMPERED from Windows.Win32 metadata.
	*/
	WMT_DRMLA_TAMPERED WMT_DRMLA_TRUST = 0x2
)

/*
WMT_TRANSPORT_TYPE is generated from Windows.Win32 metadata.
*/
type WMT_TRANSPORT_TYPE int32

const (
	/*
		WMT_Transport_Type_Unreliable from Windows.Win32 metadata.
	*/
	WMT_Transport_Type_Unreliable WMT_TRANSPORT_TYPE = 0x0

	/*
		WMT_Transport_Type_Reliable from Windows.Win32 metadata.
	*/
	WMT_Transport_Type_Reliable WMT_TRANSPORT_TYPE = 0x1
)

/*
WMT_NET_PROTOCOL is generated from Windows.Win32 metadata.
*/
type WMT_NET_PROTOCOL int32

const (
	/*
		WMT_PROTOCOL_HTTP from Windows.Win32 metadata.
	*/
	WMT_PROTOCOL_HTTP WMT_NET_PROTOCOL = 0x0
)

/*
WMT_PLAY_MODE is generated from Windows.Win32 metadata.
*/
type WMT_PLAY_MODE int32

const (
	/*
		WMT_PLAY_MODE_AUTOSELECT from Windows.Win32 metadata.
	*/
	WMT_PLAY_MODE_AUTOSELECT WMT_PLAY_MODE = 0x0

	/*
		WMT_PLAY_MODE_LOCAL from Windows.Win32 metadata.
	*/
	WMT_PLAY_MODE_LOCAL WMT_PLAY_MODE = 0x1

	/*
		WMT_PLAY_MODE_DOWNLOAD from Windows.Win32 metadata.
	*/
	WMT_PLAY_MODE_DOWNLOAD WMT_PLAY_MODE = 0x2

	/*
		WMT_PLAY_MODE_STREAMING from Windows.Win32 metadata.
	*/
	WMT_PLAY_MODE_STREAMING WMT_PLAY_MODE = 0x3
)

/*
WMT_PROXY_SETTINGS is generated from Windows.Win32 metadata.
*/
type WMT_PROXY_SETTINGS int32

const (
	/*
		WMT_PROXY_SETTING_NONE from Windows.Win32 metadata.
	*/
	WMT_PROXY_SETTING_NONE WMT_PROXY_SETTINGS = 0x0

	/*
		WMT_PROXY_SETTING_MANUAL from Windows.Win32 metadata.
	*/
	WMT_PROXY_SETTING_MANUAL WMT_PROXY_SETTINGS = 0x1

	/*
		WMT_PROXY_SETTING_AUTO from Windows.Win32 metadata.
	*/
	WMT_PROXY_SETTING_AUTO WMT_PROXY_SETTINGS = 0x2

	/*
		WMT_PROXY_SETTING_BROWSER from Windows.Win32 metadata.
	*/
	WMT_PROXY_SETTING_BROWSER WMT_PROXY_SETTINGS = 0x3

	/*
		WMT_PROXY_SETTING_MAX from Windows.Win32 metadata.
	*/
	WMT_PROXY_SETTING_MAX WMT_PROXY_SETTINGS = 0x4
)

/*
WMT_CODEC_INFO_TYPE is generated from Windows.Win32 metadata.
*/
type WMT_CODEC_INFO_TYPE int32

const (
	/*
		WMT_CODECINFO_AUDIO from Windows.Win32 metadata.
	*/
	WMT_CODECINFO_AUDIO WMT_CODEC_INFO_TYPE = 0x0

	/*
		WMT_CODECINFO_VIDEO from Windows.Win32 metadata.
	*/
	WMT_CODECINFO_VIDEO WMT_CODEC_INFO_TYPE = 0x1

	/*
		WMT_CODECINFO_UNKNOWN from Windows.Win32 metadata.
	*/
	WMT_CODECINFO_UNKNOWN WMT_CODEC_INFO_TYPE = -1
)

/*
WM_DM_INTERLACED_TYPE is generated from Windows.Win32 metadata.
*/
type WM_DM_INTERLACED_TYPE int32

const (
	/*
		WM_DM_NOTINTERLACED from Windows.Win32 metadata.
	*/
	WM_DM_NOTINTERLACED WM_DM_INTERLACED_TYPE = 0x0

	/*
		WM_DM_DEINTERLACE_NORMAL from Windows.Win32 metadata.
	*/
	WM_DM_DEINTERLACE_NORMAL WM_DM_INTERLACED_TYPE = 0x1

	/*
		WM_DM_DEINTERLACE_HALFSIZE from Windows.Win32 metadata.
	*/
	WM_DM_DEINTERLACE_HALFSIZE WM_DM_INTERLACED_TYPE = 0x2

	/*
		WM_DM_DEINTERLACE_HALFSIZEDOUBLERATE from Windows.Win32 metadata.
	*/
	WM_DM_DEINTERLACE_HALFSIZEDOUBLERATE WM_DM_INTERLACED_TYPE = 0x3

	/*
		WM_DM_DEINTERLACE_INVERSETELECINE from Windows.Win32 metadata.
	*/
	WM_DM_DEINTERLACE_INVERSETELECINE WM_DM_INTERLACED_TYPE = 0x4

	/*
		WM_DM_DEINTERLACE_VERTICALHALFSIZEDOUBLERATE from Windows.Win32 metadata.
	*/
	WM_DM_DEINTERLACE_VERTICALHALFSIZEDOUBLERATE WM_DM_INTERLACED_TYPE = 0x5
)

/*
WM_DM_IT_FIRST_FRAME_COHERENCY is generated from Windows.Win32 metadata.
*/
type WM_DM_IT_FIRST_FRAME_COHERENCY int32

const (
	/*
		WM_DM_IT_DISABLE_COHERENT_MODE from Windows.Win32 metadata.
	*/
	WM_DM_IT_DISABLE_COHERENT_MODE WM_DM_IT_FIRST_FRAME_COHERENCY = 0x0

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_AA_TOP from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_AA_TOP WM_DM_IT_FIRST_FRAME_COHERENCY = 0x1

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BB_TOP from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BB_TOP WM_DM_IT_FIRST_FRAME_COHERENCY = 0x2

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BC_TOP from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BC_TOP WM_DM_IT_FIRST_FRAME_COHERENCY = 0x3

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_CD_TOP from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_CD_TOP WM_DM_IT_FIRST_FRAME_COHERENCY = 0x4

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_DD_TOP from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_DD_TOP WM_DM_IT_FIRST_FRAME_COHERENCY = 0x5

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_AA_BOTTOM from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_AA_BOTTOM WM_DM_IT_FIRST_FRAME_COHERENCY = 0x6

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BB_BOTTOM from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BB_BOTTOM WM_DM_IT_FIRST_FRAME_COHERENCY = 0x7

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BC_BOTTOM from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_BC_BOTTOM WM_DM_IT_FIRST_FRAME_COHERENCY = 0x8

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_CD_BOTTOM from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_CD_BOTTOM WM_DM_IT_FIRST_FRAME_COHERENCY = 0x9

	/*
		WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_DD_BOTTOM from Windows.Win32 metadata.
	*/
	WM_DM_IT_FIRST_FRAME_IN_CLIP_IS_DD_BOTTOM WM_DM_IT_FIRST_FRAME_COHERENCY = 0xa
)

/*
WMT_OFFSET_FORMAT is generated from Windows.Win32 metadata.
*/
type WMT_OFFSET_FORMAT int32

const (
	/*
		WMT_OFFSET_FORMAT_100NS from Windows.Win32 metadata.
	*/
	WMT_OFFSET_FORMAT_100NS WMT_OFFSET_FORMAT = 0x0

	/*
		WMT_OFFSET_FORMAT_FRAME_NUMBERS from Windows.Win32 metadata.
	*/
	WMT_OFFSET_FORMAT_FRAME_NUMBERS WMT_OFFSET_FORMAT = 0x1

	/*
		WMT_OFFSET_FORMAT_PLAYLIST_OFFSET from Windows.Win32 metadata.
	*/
	WMT_OFFSET_FORMAT_PLAYLIST_OFFSET WMT_OFFSET_FORMAT = 0x2

	/*
		WMT_OFFSET_FORMAT_TIMECODE from Windows.Win32 metadata.
	*/
	WMT_OFFSET_FORMAT_TIMECODE WMT_OFFSET_FORMAT = 0x3

	/*
		WMT_OFFSET_FORMAT_100NS_APPROXIMATE from Windows.Win32 metadata.
	*/
	WMT_OFFSET_FORMAT_100NS_APPROXIMATE WMT_OFFSET_FORMAT = 0x4
)

/*
WMT_INDEXER_TYPE is generated from Windows.Win32 metadata.
*/
type WMT_INDEXER_TYPE int32

const (
	/*
		WMT_IT_PRESENTATION_TIME from Windows.Win32 metadata.
	*/
	WMT_IT_PRESENTATION_TIME WMT_INDEXER_TYPE = 0x0

	/*
		WMT_IT_FRAME_NUMBERS from Windows.Win32 metadata.
	*/
	WMT_IT_FRAME_NUMBERS WMT_INDEXER_TYPE = 0x1

	/*
		WMT_IT_TIMECODE from Windows.Win32 metadata.
	*/
	WMT_IT_TIMECODE WMT_INDEXER_TYPE = 0x2
)

/*
WMT_INDEX_TYPE is generated from Windows.Win32 metadata.
*/
type WMT_INDEX_TYPE int32

const (
	/*
		WMT_IT_NEAREST_DATA_UNIT from Windows.Win32 metadata.
	*/
	WMT_IT_NEAREST_DATA_UNIT WMT_INDEX_TYPE = 0x1

	/*
		WMT_IT_NEAREST_OBJECT from Windows.Win32 metadata.
	*/
	WMT_IT_NEAREST_OBJECT WMT_INDEX_TYPE = 0x2

	/*
		WMT_IT_NEAREST_CLEAN_POINT from Windows.Win32 metadata.
	*/
	WMT_IT_NEAREST_CLEAN_POINT WMT_INDEX_TYPE = 0x3
)

/*
WMT_FILESINK_MODE is generated from Windows.Win32 metadata.
*/
type WMT_FILESINK_MODE int32

const (
	/*
		WMT_FM_SINGLE_BUFFERS from Windows.Win32 metadata.
	*/
	WMT_FM_SINGLE_BUFFERS WMT_FILESINK_MODE = 0x1

	/*
		WMT_FM_FILESINK_DATA_UNITS from Windows.Win32 metadata.
	*/
	WMT_FM_FILESINK_DATA_UNITS WMT_FILESINK_MODE = 0x2

	/*
		WMT_FM_FILESINK_UNBUFFERED from Windows.Win32 metadata.
	*/
	WMT_FM_FILESINK_UNBUFFERED WMT_FILESINK_MODE = 0x4
)

/*
WMT_MUSICSPEECH_CLASS_MODE is generated from Windows.Win32 metadata.
*/
type WMT_MUSICSPEECH_CLASS_MODE int32

const (
	/*
		WMT_MS_CLASS_MUSIC from Windows.Win32 metadata.
	*/
	WMT_MS_CLASS_MUSIC WMT_MUSICSPEECH_CLASS_MODE = 0x0

	/*
		WMT_MS_CLASS_SPEECH from Windows.Win32 metadata.
	*/
	WMT_MS_CLASS_SPEECH WMT_MUSICSPEECH_CLASS_MODE = 0x1

	/*
		WMT_MS_CLASS_MIXED from Windows.Win32 metadata.
	*/
	WMT_MS_CLASS_MIXED WMT_MUSICSPEECH_CLASS_MODE = 0x2
)

/*
WMT_WATERMARK_ENTRY_TYPE is generated from Windows.Win32 metadata.
*/
type WMT_WATERMARK_ENTRY_TYPE int32

const (
	/*
		WMT_WMETYPE_AUDIO from Windows.Win32 metadata.
	*/
	WMT_WMETYPE_AUDIO WMT_WATERMARK_ENTRY_TYPE = 0x1

	/*
		WMT_WMETYPE_VIDEO from Windows.Win32 metadata.
	*/
	WMT_WMETYPE_VIDEO WMT_WATERMARK_ENTRY_TYPE = 0x2
)

/*
WM_PLAYBACK_DRC_LEVEL is generated from Windows.Win32 metadata.
*/
type WM_PLAYBACK_DRC_LEVEL int32

const (
	/*
		WM_PLAYBACK_DRC_HIGH from Windows.Win32 metadata.
	*/
	WM_PLAYBACK_DRC_HIGH WM_PLAYBACK_DRC_LEVEL = 0x0

	/*
		WM_PLAYBACK_DRC_MEDIUM from Windows.Win32 metadata.
	*/
	WM_PLAYBACK_DRC_MEDIUM WM_PLAYBACK_DRC_LEVEL = 0x1

	/*
		WM_PLAYBACK_DRC_LOW from Windows.Win32 metadata.
	*/
	WM_PLAYBACK_DRC_LOW WM_PLAYBACK_DRC_LEVEL = 0x2
)

/*
WMT_TIMECODE_FRAMERATE is generated from Windows.Win32 metadata.
*/
type WMT_TIMECODE_FRAMERATE int32

const (
	/*
		WMT_TIMECODE_FRAMERATE_30 from Windows.Win32 metadata.
	*/
	WMT_TIMECODE_FRAMERATE_30 WMT_TIMECODE_FRAMERATE = 0x0

	/*
		WMT_TIMECODE_FRAMERATE_30DROP from Windows.Win32 metadata.
	*/
	WMT_TIMECODE_FRAMERATE_30DROP WMT_TIMECODE_FRAMERATE = 0x1

	/*
		WMT_TIMECODE_FRAMERATE_25 from Windows.Win32 metadata.
	*/
	WMT_TIMECODE_FRAMERATE_25 WMT_TIMECODE_FRAMERATE = 0x2

	/*
		WMT_TIMECODE_FRAMERATE_24 from Windows.Win32 metadata.
	*/
	WMT_TIMECODE_FRAMERATE_24 WMT_TIMECODE_FRAMERATE = 0x3
)

/*
WMT_CREDENTIAL_FLAGS is generated from Windows.Win32 metadata.
*/
type WMT_CREDENTIAL_FLAGS int32

const (
	/*
		WMT_CREDENTIAL_SAVE from Windows.Win32 metadata.
	*/
	WMT_CREDENTIAL_SAVE WMT_CREDENTIAL_FLAGS = 0x1

	/*
		WMT_CREDENTIAL_DONT_CACHE from Windows.Win32 metadata.
	*/
	WMT_CREDENTIAL_DONT_CACHE WMT_CREDENTIAL_FLAGS = 0x2

	/*
		WMT_CREDENTIAL_CLEAR_TEXT from Windows.Win32 metadata.
	*/
	WMT_CREDENTIAL_CLEAR_TEXT WMT_CREDENTIAL_FLAGS = 0x4

	/*
		WMT_CREDENTIAL_PROXY from Windows.Win32 metadata.
	*/
	WMT_CREDENTIAL_PROXY WMT_CREDENTIAL_FLAGS = 0x8

	/*
		WMT_CREDENTIAL_ENCRYPT from Windows.Win32 metadata.
	*/
	WMT_CREDENTIAL_ENCRYPT WMT_CREDENTIAL_FLAGS = 0x10
)

/*
WM_AETYPE is generated from Windows.Win32 metadata.
*/
type WM_AETYPE int32

const (
	/*
		WM_AETYPE_INCLUDE from Windows.Win32 metadata.
	*/
	WM_AETYPE_INCLUDE WM_AETYPE = 0x69

	/*
		WM_AETYPE_EXCLUDE from Windows.Win32 metadata.
	*/
	WM_AETYPE_EXCLUDE WM_AETYPE = 0x65
)

/*
WMT_RIGHTS is generated from Windows.Win32 metadata.
*/
type WMT_RIGHTS int32

const (
	/*
		WMT_RIGHT_PLAYBACK from Windows.Win32 metadata.
	*/
	WMT_RIGHT_PLAYBACK WMT_RIGHTS = 0x1

	/*
		WMT_RIGHT_COPY_TO_NON_SDMI_DEVICE from Windows.Win32 metadata.
	*/
	WMT_RIGHT_COPY_TO_NON_SDMI_DEVICE WMT_RIGHTS = 0x2

	/*
		WMT_RIGHT_COPY_TO_CD from Windows.Win32 metadata.
	*/
	WMT_RIGHT_COPY_TO_CD WMT_RIGHTS = 0x8

	/*
		WMT_RIGHT_COPY_TO_SDMI_DEVICE from Windows.Win32 metadata.
	*/
	WMT_RIGHT_COPY_TO_SDMI_DEVICE WMT_RIGHTS = 0x10

	/*
		WMT_RIGHT_ONE_TIME from Windows.Win32 metadata.
	*/
	WMT_RIGHT_ONE_TIME WMT_RIGHTS = 0x20

	/*
		WMT_RIGHT_SAVE_STREAM_PROTECTED from Windows.Win32 metadata.
	*/
	WMT_RIGHT_SAVE_STREAM_PROTECTED WMT_RIGHTS = 0x40

	/*
		WMT_RIGHT_COPY from Windows.Win32 metadata.
	*/
	WMT_RIGHT_COPY WMT_RIGHTS = 0x80

	/*
		WMT_RIGHT_COLLABORATIVE_PLAY from Windows.Win32 metadata.
	*/
	WMT_RIGHT_COLLABORATIVE_PLAY WMT_RIGHTS = 0x100

	/*
		WMT_RIGHT_SDMI_TRIGGER from Windows.Win32 metadata.
	*/
	WMT_RIGHT_SDMI_TRIGGER WMT_RIGHTS = 0x10000

	/*
		WMT_RIGHT_SDMI_NOMORECOPIES from Windows.Win32 metadata.
	*/
	WMT_RIGHT_SDMI_NOMORECOPIES WMT_RIGHTS = 0x20000
)

/*
WM_STREAM_PRIORITY_RECORD is generated from Windows.Win32 metadata.
*/
type WM_STREAM_PRIORITY_RECORD struct {
	WStreamNumber uint16
	FMandatory    BOOL
}

/*
WM_WRITER_STATISTICS is generated from Windows.Win32 metadata.
*/
type WM_WRITER_STATISTICS struct {
	QwSampleCount        uint64
	QwByteCount          uint64
	QwDroppedSampleCount uint64
	QwDroppedByteCount   uint64
	DwCurrentBitrate     uint32
	DwAverageBitrate     uint32
	DwExpectedBitrate    uint32
	DwCurrentSampleRate  uint32
	DwAverageSampleRate  uint32
	DwExpectedSampleRate uint32
}

/*
WM_WRITER_STATISTICS_EX is generated from Windows.Win32 metadata.
*/
type WM_WRITER_STATISTICS_EX struct {
	DwBitratePlusOverhead                uint32
	DwCurrentSampleDropRateInQueue       uint32
	DwCurrentSampleDropRateInCodec       uint32
	DwCurrentSampleDropRateInMultiplexer uint32
	DwTotalSampleDropsInQueue            uint32
	DwTotalSampleDropsInCodec            uint32
	DwTotalSampleDropsInMultiplexer      uint32
}

/*
WM_READER_STATISTICS is generated from Windows.Win32 metadata.
*/
type WM_READER_STATISTICS struct {
	CbSize            uint32
	DwBandwidth       uint32
	CPacketsReceived  uint32
	CPacketsRecovered uint32
	CPacketsLost      uint32
	WQuality          uint16
}

/*
WM_READER_CLIENTINFO is generated from Windows.Win32 metadata.
*/
type WM_READER_CLIENTINFO struct {
	CbSize              uint32
	WszLang             *PWSTRElement
	WszBrowserUserAgent *PWSTRElement
	WszBrowserWebPage   *PWSTRElement
	QwReserved          uint64
	PReserved           *LPARAM
	WszHostExe          *PWSTRElement
	QwHostVersion       uint64
	WszPlayerUserAgent  *PWSTRElement
}

/*
WM_CLIENT_PROPERTIES is generated from Windows.Win32 metadata.
*/
type WM_CLIENT_PROPERTIES struct {
	DwIPAddress uint32
	DwPort      uint32
}

/*
WM_CLIENT_PROPERTIES_EX is generated from Windows.Win32 metadata.
*/
type WM_CLIENT_PROPERTIES_EX struct {
	CbSize        uint32
	PwszIPAddress *PWSTRElement
	PwszPort      *PWSTRElement
	PwszDNSName   *PWSTRElement
}

/*
WM_PORT_NUMBER_RANGE is generated from Windows.Win32 metadata.
*/
type WM_PORT_NUMBER_RANGE struct {
	WPortBegin uint16
	WPortEnd   uint16
}

/*
WMT_BUFFER_SEGMENT is generated from Windows.Win32 metadata.
*/
type WMT_BUFFER_SEGMENT struct {
	PBuffer  *INSSBuffer
	CbOffset uint32
	CbLength uint32
}

/*
WMT_PAYLOAD_FRAGMENT is generated from Windows.Win32 metadata.
*/
type WMT_PAYLOAD_FRAGMENT struct {
	DwPayloadIndex uint32
	SegmentData    WMT_BUFFER_SEGMENT
}

/*
WMT_FILESINK_DATA_UNIT is generated from Windows.Win32 metadata.
*/
type WMT_FILESINK_DATA_UNIT struct {
	PacketHeaderBuffer    WMT_BUFFER_SEGMENT
	CPayloads             uint32
	PPayloadHeaderBuffers *WMT_BUFFER_SEGMENT
	CPayloadDataFragments uint32
	PPayloadDataFragments *WMT_PAYLOAD_FRAGMENT
}

/*
WMT_WEBSTREAM_FORMAT is generated from Windows.Win32 metadata.
*/
type WMT_WEBSTREAM_FORMAT struct {
	CbSize                  uint16
	CbSampleHeaderFixedData uint16
	WVersion                uint16
	WReserved               uint16
}

/*
WMT_WEBSTREAM_SAMPLE_HEADER is generated from Windows.Win32 metadata.
*/
type WMT_WEBSTREAM_SAMPLE_HEADER struct {
	CbLength    uint16
	WPart       uint16
	CTotalParts uint16
	WSampleType uint16
	WszURL      [1]uint16
}

/*
WM_ADDRESS_ACCESSENTRY is generated from Windows.Win32 metadata.
*/
type WM_ADDRESS_ACCESSENTRY struct {
	DwIPAddress uint32
	DwMask      uint32
}

/*
WM_PICTURE is generated from Windows.Win32 metadata.
*/
type WM_PICTURE struct {
	PwszMIMEType    *PWSTRElement
	BPictureType    uint8
	PwszDescription *PWSTRElement
	DwDataLen       uint32
	PbData          *uint8
}

/*
WM_SYNCHRONISED_LYRICS is generated from Windows.Win32 metadata.
*/
type WM_SYNCHRONISED_LYRICS struct {
	BTimeStampFormat      uint8
	BContentType          uint8
	PwszContentDescriptor *PWSTRElement
	DwLyricsLen           uint32
	PbLyrics              *uint8
}

/*
WM_USER_WEB_URL is generated from Windows.Win32 metadata.
*/
type WM_USER_WEB_URL struct {
	PwszDescription *PWSTRElement
	PwszURL         *PWSTRElement
}

/*
WM_USER_TEXT is generated from Windows.Win32 metadata.
*/
type WM_USER_TEXT struct {
	PwszDescription *PWSTRElement
	PwszText        *PWSTRElement
}

/*
WM_LEAKY_BUCKET_PAIR is generated from Windows.Win32 metadata.
*/
type WM_LEAKY_BUCKET_PAIR struct {
	DwBitrate      uint32
	MsBufferWindow uint32
}

/*
WM_STREAM_TYPE_INFO is generated from Windows.Win32 metadata.
*/
type WM_STREAM_TYPE_INFO struct {
	GuidMajorType Guid
	CbFormat      uint32
}

/*
WMT_WATERMARK_ENTRY is generated from Windows.Win32 metadata.
*/
type WMT_WATERMARK_ENTRY struct {
	WmetType        WMT_WATERMARK_ENTRY_TYPE
	Clsid           Guid
	CbDisplayName   uint32
	PwszDisplayName *PWSTRElement
}

/*
WMT_VIDEOIMAGE_SAMPLE is generated from Windows.Win32 metadata.
*/
type WMT_VIDEOIMAGE_SAMPLE struct {
	DwMagic            uint32
	CbStruct           uint32
	DwControlFlags     uint32
	DwInputFlagsCur    uint32
	LCurMotionXtoX     int32
	LCurMotionYtoX     int32
	LCurMotionXoffset  int32
	LCurMotionXtoY     int32
	LCurMotionYtoY     int32
	LCurMotionYoffset  int32
	LCurBlendCoef1     int32
	LCurBlendCoef2     int32
	DwInputFlagsPrev   uint32
	LPrevMotionXtoX    int32
	LPrevMotionYtoX    int32
	LPrevMotionXoffset int32
	LPrevMotionXtoY    int32
	LPrevMotionYtoY    int32
	LPrevMotionYoffset int32
	LPrevBlendCoef1    int32
	LPrevBlendCoef2    int32
}

/*
WMT_VIDEOIMAGE_SAMPLE2 is generated from Windows.Win32 metadata.
*/
type WMT_VIDEOIMAGE_SAMPLE2 struct {
	DwMagic           uint32
	DwStructSize      uint32
	DwControlFlags    uint32
	DwViewportWidth   uint32
	DwViewportHeight  uint32
	DwCurrImageWidth  uint32
	DwCurrImageHeight uint32
	FCurrRegionX0     float32
	FCurrRegionY0     float32
	FCurrRegionWidth  float32
	FCurrRegionHeight float32
	FCurrBlendCoef    float32
	DwPrevImageWidth  uint32
	DwPrevImageHeight uint32
	FPrevRegionX0     float32
	FPrevRegionY0     float32
	FPrevRegionWidth  float32
	FPrevRegionHeight float32
	FPrevBlendCoef    float32
	DwEffectType      uint32
	DwNumEffectParas  uint32
	FEffectPara0      float32
	FEffectPara1      float32
	FEffectPara2      float32
	FEffectPara3      float32
	FEffectPara4      float32
	BKeepPrevImage    BOOL
}

/*
WM_MEDIA_TYPE is generated from Windows.Win32 metadata.
*/
type WM_MEDIA_TYPE struct {
	Majortype            Guid
	Subtype              Guid
	BFixedSizeSamples    BOOL
	BTemporalCompression BOOL
	LSampleSize          uint32
	Formattype           Guid
	PUnk                 *IUnknown
	CbFormat             uint32
	PbFormat             *uint8
}

/*
WMVIDEOINFOHEADER is generated from Windows.Win32 metadata.
*/
type WMVIDEOINFOHEADER struct {
	RcSource        RECT
	RcTarget        RECT
	DwBitRate       uint32
	DwBitErrorRate  uint32
	AvgTimePerFrame int64
	BmiHeader       BITMAPINFOHEADER
}

/*
WMVIDEOINFOHEADER2 is generated from Windows.Win32 metadata.
*/
type WMVIDEOINFOHEADER2 struct {
	RcSource           RECT
	RcTarget           RECT
	DwBitRate          uint32
	DwBitErrorRate     uint32
	AvgTimePerFrame    int64
	DwInterlaceFlags   uint32
	DwCopyProtectFlags uint32
	DwPictAspectRatioX uint32
	DwPictAspectRatioY uint32
	DwReserved1        uint32
	DwReserved2        uint32
	BmiHeader          BITMAPINFOHEADER
}

/*
WMMPEG2VIDEOINFO is generated from Windows.Win32 metadata.
*/
type WMMPEG2VIDEOINFO struct {
	Hdr              WMVIDEOINFOHEADER2
	DwStartTimeCode  uint32
	CbSequenceHeader uint32
	DwProfile        uint32
	DwLevel          uint32
	DwFlags          uint32
	DwSequenceHeader [1]uint32
}

/*
WMSCRIPTFORMAT is generated from Windows.Win32 metadata.
*/
type WMSCRIPTFORMAT struct {
	ScriptType Guid
}

/*
WMT_COLORSPACEINFO_EXTENSION_DATA is generated from Windows.Win32 metadata.
*/
type WMT_COLORSPACEINFO_EXTENSION_DATA struct {
	UcColorPrimaries    uint8
	UcColorTransferChar uint8
	UcColorMatrixCoef   uint8
}

/*
WMT_TIMECODE_EXTENSION_DATA is generated from Windows.Win32 metadata.
*/
type WMT_TIMECODE_EXTENSION_DATA struct {
	WRange     uint16
	DwTimecode uint32
	DwUserbits uint32
	DwAmFlags  uint32
}

/*
DRM_VAL16 is generated from Windows.Win32 metadata.
*/
type DRM_VAL16 struct {
	Val [16]uint8
}

/*
IWMMediaProps is generated from Windows.Win32 metadata.
*/
type IWMMediaProps uintptr

/*
IWMVideoMediaProps is generated from Windows.Win32 metadata.
*/
type IWMVideoMediaProps uintptr

/*
IWMWriter is generated from Windows.Win32 metadata.
*/
type IWMWriter uintptr

/*
IWMDRMWriter is generated from Windows.Win32 metadata.
*/
type IWMDRMWriter uintptr

/*
WMDRM_IMPORT_INIT_STRUCT is generated from Windows.Win32 metadata.
*/
type WMDRM_IMPORT_INIT_STRUCT struct {
	DwVersion                    uint32
	CbEncryptedSessionKeyMessage uint32
	PbEncryptedSessionKeyMessage *uint8
	CbEncryptedKeyMessage        uint32
	PbEncryptedKeyMessage        *uint8
}

/*
IWMDRMWriter2 is generated from Windows.Win32 metadata.
*/
type IWMDRMWriter2 uintptr

/*
IWMDRMWriter3 is generated from Windows.Win32 metadata.
*/
type IWMDRMWriter3 uintptr

/*
IWMInputMediaProps is generated from Windows.Win32 metadata.
*/
type IWMInputMediaProps uintptr

/*
IWMPropertyVault is generated from Windows.Win32 metadata.
*/
type IWMPropertyVault uintptr

/*
IWMIStreamProps is generated from Windows.Win32 metadata.
*/
type IWMIStreamProps uintptr

/*
IWMReader is generated from Windows.Win32 metadata.
*/
type IWMReader uintptr

/*
IWMSyncReader is generated from Windows.Win32 metadata.
*/
type IWMSyncReader uintptr

/*
IWMSyncReader2 is generated from Windows.Win32 metadata.
*/
type IWMSyncReader2 uintptr

/*
IWMOutputMediaProps is generated from Windows.Win32 metadata.
*/
type IWMOutputMediaProps uintptr

/*
IWMStatusCallback is generated from Windows.Win32 metadata.
*/
type IWMStatusCallback uintptr

/*
IWMReaderCallback is generated from Windows.Win32 metadata.
*/
type IWMReaderCallback uintptr

/*
IWMCredentialCallback is generated from Windows.Win32 metadata.
*/
type IWMCredentialCallback uintptr

/*
IWMMetadataEditor is generated from Windows.Win32 metadata.
*/
type IWMMetadataEditor uintptr

/*
IWMMetadataEditor2 is generated from Windows.Win32 metadata.
*/
type IWMMetadataEditor2 uintptr

/*
IWMDRMEditor is generated from Windows.Win32 metadata.
*/
type IWMDRMEditor uintptr

/*
IWMHeaderInfo is generated from Windows.Win32 metadata.
*/
type IWMHeaderInfo uintptr

/*
IWMHeaderInfo2 is generated from Windows.Win32 metadata.
*/
type IWMHeaderInfo2 uintptr

/*
IWMHeaderInfo3 is generated from Windows.Win32 metadata.
*/
type IWMHeaderInfo3 uintptr

/*
IWMProfileManager is generated from Windows.Win32 metadata.
*/
type IWMProfileManager uintptr

/*
IWMProfileManager2 is generated from Windows.Win32 metadata.
*/
type IWMProfileManager2 uintptr

/*
IWMProfileManagerLanguage is generated from Windows.Win32 metadata.
*/
type IWMProfileManagerLanguage uintptr

/*
IWMProfile is generated from Windows.Win32 metadata.
*/
type IWMProfile uintptr

/*
IWMProfile2 is generated from Windows.Win32 metadata.
*/
type IWMProfile2 uintptr

/*
IWMProfile3 is generated from Windows.Win32 metadata.
*/
type IWMProfile3 uintptr

/*
IWMStreamConfig is generated from Windows.Win32 metadata.
*/
type IWMStreamConfig uintptr

/*
IWMStreamConfig2 is generated from Windows.Win32 metadata.
*/
type IWMStreamConfig2 uintptr

/*
IWMStreamConfig3 is generated from Windows.Win32 metadata.
*/
type IWMStreamConfig3 uintptr

/*
IWMPacketSize is generated from Windows.Win32 metadata.
*/
type IWMPacketSize uintptr

/*
IWMPacketSize2 is generated from Windows.Win32 metadata.
*/
type IWMPacketSize2 uintptr

/*
IWMStreamList is generated from Windows.Win32 metadata.
*/
type IWMStreamList uintptr

/*
IWMMutualExclusion is generated from Windows.Win32 metadata.
*/
type IWMMutualExclusion uintptr

/*
IWMMutualExclusion2 is generated from Windows.Win32 metadata.
*/
type IWMMutualExclusion2 uintptr

/*
IWMBandwidthSharing is generated from Windows.Win32 metadata.
*/
type IWMBandwidthSharing uintptr

/*
IWMStreamPrioritization is generated from Windows.Win32 metadata.
*/
type IWMStreamPrioritization uintptr

/*
IWMWriterAdvanced is generated from Windows.Win32 metadata.
*/
type IWMWriterAdvanced uintptr

/*
IWMWriterAdvanced2 is generated from Windows.Win32 metadata.
*/
type IWMWriterAdvanced2 uintptr

/*
IWMWriterAdvanced3 is generated from Windows.Win32 metadata.
*/
type IWMWriterAdvanced3 uintptr

/*
IWMWriterPreprocess is generated from Windows.Win32 metadata.
*/
type IWMWriterPreprocess uintptr

/*
IWMWriterPostViewCallback is generated from Windows.Win32 metadata.
*/
type IWMWriterPostViewCallback uintptr

/*
IWMWriterPostView is generated from Windows.Win32 metadata.
*/
type IWMWriterPostView uintptr

/*
IWMWriterSink is generated from Windows.Win32 metadata.
*/
type IWMWriterSink uintptr

/*
IWMRegisterCallback is generated from Windows.Win32 metadata.
*/
type IWMRegisterCallback uintptr

/*
IWMWriterFileSink is generated from Windows.Win32 metadata.
*/
type IWMWriterFileSink uintptr

/*
IWMWriterFileSink2 is generated from Windows.Win32 metadata.
*/
type IWMWriterFileSink2 uintptr

/*
IWMWriterFileSink3 is generated from Windows.Win32 metadata.
*/
type IWMWriterFileSink3 uintptr

/*
IWMWriterNetworkSink is generated from Windows.Win32 metadata.
*/
type IWMWriterNetworkSink uintptr

/*
IWMClientConnections is generated from Windows.Win32 metadata.
*/
type IWMClientConnections uintptr

/*
IWMClientConnections2 is generated from Windows.Win32 metadata.
*/
type IWMClientConnections2 uintptr

/*
IWMReaderAdvanced is generated from Windows.Win32 metadata.
*/
type IWMReaderAdvanced uintptr

/*
IWMReaderAdvanced2 is generated from Windows.Win32 metadata.
*/
type IWMReaderAdvanced2 uintptr

/*
IWMReaderAdvanced3 is generated from Windows.Win32 metadata.
*/
type IWMReaderAdvanced3 uintptr

/*
IWMReaderAdvanced4 is generated from Windows.Win32 metadata.
*/
type IWMReaderAdvanced4 uintptr

/*
IWMReaderAdvanced5 is generated from Windows.Win32 metadata.
*/
type IWMReaderAdvanced5 uintptr

/*
IWMReaderAdvanced6 is generated from Windows.Win32 metadata.
*/
type IWMReaderAdvanced6 uintptr

/*
IWMPlayerHook is generated from Windows.Win32 metadata.
*/
type IWMPlayerHook uintptr

/*
IWMReaderAllocatorEx is generated from Windows.Win32 metadata.
*/
type IWMReaderAllocatorEx uintptr

/*
IWMReaderTypeNegotiation is generated from Windows.Win32 metadata.
*/
type IWMReaderTypeNegotiation uintptr

/*
IWMReaderCallbackAdvanced is generated from Windows.Win32 metadata.
*/
type IWMReaderCallbackAdvanced uintptr

/*
IWMDRMReader is generated from Windows.Win32 metadata.
*/
type IWMDRMReader uintptr

/*
DRM_MINIMUM_OUTPUT_PROTECTION_LEVELS is generated from Windows.Win32 metadata.
*/
type DRM_MINIMUM_OUTPUT_PROTECTION_LEVELS struct {
	WCompressedDigitalVideo   uint16
	WUncompressedDigitalVideo uint16
	WAnalogVideo              uint16
	WCompressedDigitalAudio   uint16
	WUncompressedDigitalAudio uint16
}

/*
DRM_OPL_OUTPUT_IDS is generated from Windows.Win32 metadata.
*/
type DRM_OPL_OUTPUT_IDS struct {
	CIds  uint16
	RgIds *Guid
}

/*
DRM_OUTPUT_PROTECTION is generated from Windows.Win32 metadata.
*/
type DRM_OUTPUT_PROTECTION struct {
	GuidId      Guid
	BConfigData uint8
}

/*
DRM_VIDEO_OUTPUT_PROTECTION_IDS is generated from Windows.Win32 metadata.
*/
type DRM_VIDEO_OUTPUT_PROTECTION_IDS struct {
	CEntries uint16
	RgVop    *DRM_OUTPUT_PROTECTION
}

/*
DRM_PLAY_OPL is generated from Windows.Win32 metadata.
*/
type DRM_PLAY_OPL struct {
	MinOPL        DRM_MINIMUM_OUTPUT_PROTECTION_LEVELS
	OplIdReserved DRM_OPL_OUTPUT_IDS
	Vopi          DRM_VIDEO_OUTPUT_PROTECTION_IDS
}

/*
DRM_COPY_OPL is generated from Windows.Win32 metadata.
*/
type DRM_COPY_OPL struct {
	WMinimumCopyLevel uint16
	OplIdIncludes     DRM_OPL_OUTPUT_IDS
	OplIdExcludes     DRM_OPL_OUTPUT_IDS
}

/*
IWMDRMReader2 is generated from Windows.Win32 metadata.
*/
type IWMDRMReader2 uintptr

/*
IWMDRMReader3 is generated from Windows.Win32 metadata.
*/
type IWMDRMReader3 uintptr

/*
IWMReaderPlaylistBurn is generated from Windows.Win32 metadata.
*/
type IWMReaderPlaylistBurn uintptr

/*
IWMReaderNetworkConfig is generated from Windows.Win32 metadata.
*/
type IWMReaderNetworkConfig uintptr

/*
IWMReaderNetworkConfig2 is generated from Windows.Win32 metadata.
*/
type IWMReaderNetworkConfig2 uintptr

/*
IWMReaderStreamClock is generated from Windows.Win32 metadata.
*/
type IWMReaderStreamClock uintptr

/*
IWMIndexer is generated from Windows.Win32 metadata.
*/
type IWMIndexer uintptr

/*
IWMIndexer2 is generated from Windows.Win32 metadata.
*/
type IWMIndexer2 uintptr

/*
IWMLicenseBackup is generated from Windows.Win32 metadata.
*/
type IWMLicenseBackup uintptr

/*
IWMLicenseRestore is generated from Windows.Win32 metadata.
*/
type IWMLicenseRestore uintptr

/*
IWMBackupRestoreProps is generated from Windows.Win32 metadata.
*/
type IWMBackupRestoreProps uintptr

/*
IWMCodecInfo is generated from Windows.Win32 metadata.
*/
type IWMCodecInfo uintptr

/*
IWMCodecInfo2 is generated from Windows.Win32 metadata.
*/
type IWMCodecInfo2 uintptr

/*
IWMCodecInfo3 is generated from Windows.Win32 metadata.
*/
type IWMCodecInfo3 uintptr

/*
IWMLanguageList is generated from Windows.Win32 metadata.
*/
type IWMLanguageList uintptr

/*
IWMWriterPushSink is generated from Windows.Win32 metadata.
*/
type IWMWriterPushSink uintptr

/*
IWMDeviceRegistration is generated from Windows.Win32 metadata.
*/
type IWMDeviceRegistration uintptr

/*
IWMRegisteredDevice is generated from Windows.Win32 metadata.
*/
type IWMRegisteredDevice uintptr

/*
IWMProximityDetection is generated from Windows.Win32 metadata.
*/
type IWMProximityDetection uintptr

/*
IWMDRMMessageParser is generated from Windows.Win32 metadata.
*/
type IWMDRMMessageParser uintptr

/*
IWMDRMTranscryptor is generated from Windows.Win32 metadata.
*/
type IWMDRMTranscryptor uintptr

/*
IWMDRMTranscryptor2 is generated from Windows.Win32 metadata.
*/
type IWMDRMTranscryptor2 uintptr

/*
IWMDRMTranscryptionManager is generated from Windows.Win32 metadata.
*/
type IWMDRMTranscryptionManager uintptr

/*
IWMWatermarkInfo is generated from Windows.Win32 metadata.
*/
type IWMWatermarkInfo uintptr

/*
IWMReaderAccelerator is generated from Windows.Win32 metadata.
*/
type IWMReaderAccelerator uintptr

/*
IWMReaderTimecode is generated from Windows.Win32 metadata.
*/
type IWMReaderTimecode uintptr

/*
IWMAddressAccess is generated from Windows.Win32 metadata.
*/
type IWMAddressAccess uintptr

/*
IWMAddressAccess2 is generated from Windows.Win32 metadata.
*/
type IWMAddressAccess2 uintptr

/*
IWMImageInfo is generated from Windows.Win32 metadata.
*/
type IWMImageInfo uintptr

/*
IWMLicenseRevocationAgent is generated from Windows.Win32 metadata.
*/
type IWMLicenseRevocationAgent uintptr

/*
IWMAuthorizer is generated from Windows.Win32 metadata.
*/
type IWMAuthorizer uintptr

/*
IWMSecureChannel is generated from Windows.Win32 metadata.
*/
type IWMSecureChannel uintptr

/*
IWMGetSecureChannel is generated from Windows.Win32 metadata.
*/
type IWMGetSecureChannel uintptr

/*
INSNetSourceCreator is generated from Windows.Win32 metadata.
*/
type INSNetSourceCreator uintptr

/*
IWMPlayerTimestampHook is generated from Windows.Win32 metadata.
*/
type IWMPlayerTimestampHook uintptr

/*
NETSOURCE_URLCREDPOLICY_SETTINGS is generated from Windows.Win32 metadata.
*/
type NETSOURCE_URLCREDPOLICY_SETTINGS int32

const (
	/*
		NETSOURCE_URLCREDPOLICY_SETTING_SILENTLOGONOK from Windows.Win32 metadata.
	*/
	NETSOURCE_URLCREDPOLICY_SETTING_SILENTLOGONOK NETSOURCE_URLCREDPOLICY_SETTINGS = 0x0

	/*
		NETSOURCE_URLCREDPOLICY_SETTING_MUSTPROMPTUSER from Windows.Win32 metadata.
	*/
	NETSOURCE_URLCREDPOLICY_SETTING_MUSTPROMPTUSER NETSOURCE_URLCREDPOLICY_SETTINGS = 0x1

	/*
		NETSOURCE_URLCREDPOLICY_SETTING_ANONYMOUSONLY from Windows.Win32 metadata.
	*/
	NETSOURCE_URLCREDPOLICY_SETTING_ANONYMOUSONLY NETSOURCE_URLCREDPOLICY_SETTINGS = 0x2
)

/*
IWMSInternalAdminNetSource is generated from Windows.Win32 metadata.
*/
type IWMSInternalAdminNetSource uintptr

/*
IWMSInternalAdminNetSource2 is generated from Windows.Win32 metadata.
*/
type IWMSInternalAdminNetSource2 uintptr

/*
IWMSInternalAdminNetSource3 is generated from Windows.Win32 metadata.
*/
type IWMSInternalAdminNetSource3 uintptr
