//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_QueryVirtualMemoryInformation maps to QueryVirtualMemoryInformation in api-ms-win-core-memory-l1-1-4.dll.
*/
type PFN_QueryVirtualMemoryInformation func(Process HANDLE, VirtualAddress uintptr, MemoryInformationClass WIN32_MEMORY_INFORMATION_CLASS, MemoryInformation uintptr, MemoryInformationSize uintptr, ReturnSize *uintptr) BOOL
