//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:44 CEST

package bindings

/*
SECURITY_INFO_PAGE_FLAGS is generated from Windows.Win32 metadata.
*/
type SECURITY_INFO_PAGE_FLAGS uint32

const (
	/*
		SI_ADVANCED from Windows.Win32 metadata.
	*/
	SI_ADVANCED SECURITY_INFO_PAGE_FLAGS = 0x10

	/*
		SI_EDIT_AUDITS from Windows.Win32 metadata.
	*/
	SI_EDIT_AUDITS SECURITY_INFO_PAGE_FLAGS = 0x2

	/*
		SI_EDIT_PROPERTIES from Windows.Win32 metadata.
	*/
	SI_EDIT_PROPERTIES SECURITY_INFO_PAGE_FLAGS = 0x80
)

/*
SI_OBJECT_INFO_FLAGS is generated from Windows.Win32 metadata.
*/
type SI_OBJECT_INFO_FLAGS uint32

const (
	/*
		SI_AUDITS_ELEVATION_REQUIRED from Windows.Win32 metadata.
	*/
	SI_AUDITS_ELEVATION_REQUIRED SI_OBJECT_INFO_FLAGS = 0x2000000

	/*
		SI_DISABLE_DENY_ACE from Windows.Win32 metadata.
	*/
	SI_DISABLE_DENY_ACE SI_OBJECT_INFO_FLAGS = 0x80000000

	/*
		SI_EDIT_EFFECTIVE from Windows.Win32 metadata.
	*/
	SI_EDIT_EFFECTIVE SI_OBJECT_INFO_FLAGS = 0x20000

	/*
		SI_ENABLE_CENTRAL_POLICY from Windows.Win32 metadata.
	*/
	SI_ENABLE_CENTRAL_POLICY SI_OBJECT_INFO_FLAGS = 0x40000000

	/*
		SI_ENABLE_EDIT_ATTRIBUTE_CONDITION from Windows.Win32 metadata.
	*/
	SI_ENABLE_EDIT_ATTRIBUTE_CONDITION SI_OBJECT_INFO_FLAGS = 0x20000000

	/*
		SI_MAY_WRITE from Windows.Win32 metadata.
	*/
	SI_MAY_WRITE SI_OBJECT_INFO_FLAGS = 0x10000000

	/*
		SI_NO_ADDITIONAL_PERMISSION from Windows.Win32 metadata.
	*/
	SI_NO_ADDITIONAL_PERMISSION SI_OBJECT_INFO_FLAGS = 0x200000

	/*
		SI_OWNER_ELEVATION_REQUIRED from Windows.Win32 metadata.
	*/
	SI_OWNER_ELEVATION_REQUIRED SI_OBJECT_INFO_FLAGS = 0x4000000

	/*
		SI_PERMS_ELEVATION_REQUIRED from Windows.Win32 metadata.
	*/
	SI_PERMS_ELEVATION_REQUIRED SI_OBJECT_INFO_FLAGS = 0x1000000

	/*
		SI_RESET_DACL from Windows.Win32 metadata.
	*/
	SI_RESET_DACL SI_OBJECT_INFO_FLAGS = 0x40000

	/*
		SI_RESET_OWNER from Windows.Win32 metadata.
	*/
	SI_RESET_OWNER SI_OBJECT_INFO_FLAGS = 0x100000

	/*
		SI_RESET_SACL from Windows.Win32 metadata.
	*/
	SI_RESET_SACL SI_OBJECT_INFO_FLAGS = 0x80000

	/*
		SI_SCOPE_ELEVATION_REQUIRED from Windows.Win32 metadata.
	*/
	SI_SCOPE_ELEVATION_REQUIRED SI_OBJECT_INFO_FLAGS = 0x8000000

	/*
		SI_VIEW_ONLY from Windows.Win32 metadata.
	*/
	SI_VIEW_ONLY SI_OBJECT_INFO_FLAGS = 0x400000
)

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	SI_EDIT_PERMS                          int32
	SI_EDIT_OWNER                          int32
	SI_CONTAINER                           int32
	SI_READONLY                            int32
	SI_RESET                               int32
	SI_OWNER_READONLY                      int32
	SI_OWNER_RECURSE                       int32
	SI_NO_ACL_PROTECT                      int32
	SI_NO_TREE_APPLY                       int32
	SI_PAGE_TITLE                          int32
	SI_SERVER_IS_DC                        int32
	SI_RESET_DACL_TREE                     int32
	SI_RESET_SACL_TREE                     int32
	SI_OBJECT_GUID                         int32
	SI_ACCESS_SPECIFIC                     int32
	SI_ACCESS_GENERAL                      int32
	SI_ACCESS_CONTAINER                    int32
	SI_ACCESS_PROPERTY                     int32
	DOBJ_RES_CONT                          int32
	DOBJ_RES_ROOT                          int32
	DOBJ_VOL_NTACLS                        int32
	DOBJ_COND_NTACLS                       int32
	DOBJ_RIBBON_LAUNCH                     int32
	CFSTR_ACLUI_SID_INFO_LIST              uintptr
	SECURITY_OBJECT_ID_OBJECT_SD           uint32
	SECURITY_OBJECT_ID_SHARE               uint32
	SECURITY_OBJECT_ID_CENTRAL_POLICY      uint32
	SECURITY_OBJECT_ID_CENTRAL_ACCESS_RULE uint32
}

/*
SI_OBJECT_INFO is generated from Windows.Win32 metadata.
*/
type SI_OBJECT_INFO struct {
	DwFlags        SI_OBJECT_INFO_FLAGS
	HInstance      HINSTANCE
	PszServerName  *PWSTRElement
	PszObjectName  *PWSTRElement
	PszPageTitle   *PWSTRElement
	GuidObjectType Guid
}

/*
SI_ACCESS is generated from Windows.Win32 metadata.
*/
type SI_ACCESS struct {
	Pguid   *Guid
	Mask    uint32
	PszName *PWSTRElement
	DwFlags uint32
}

/*
SI_INHERIT_TYPE is generated from Windows.Win32 metadata.
*/
type SI_INHERIT_TYPE struct {
	Pguid   *Guid
	DwFlags ACE_FLAGS
	PszName *PWSTRElement
}

/*
SI_PAGE_TYPE is generated from Windows.Win32 metadata.
*/
type SI_PAGE_TYPE int32

const (
	/*
		SI_PAGE_PERM from Windows.Win32 metadata.
	*/
	SI_PAGE_PERM SI_PAGE_TYPE = 0x0

	/*
		SI_PAGE_ADVPERM from Windows.Win32 metadata.
	*/
	SI_PAGE_ADVPERM SI_PAGE_TYPE = 0x1

	/*
		SI_PAGE_AUDIT from Windows.Win32 metadata.
	*/
	SI_PAGE_AUDIT SI_PAGE_TYPE = 0x2

	/*
		SI_PAGE_OWNER from Windows.Win32 metadata.
	*/
	SI_PAGE_OWNER SI_PAGE_TYPE = 0x3

	/*
		SI_PAGE_EFFECTIVE from Windows.Win32 metadata.
	*/
	SI_PAGE_EFFECTIVE SI_PAGE_TYPE = 0x4

	/*
		SI_PAGE_TAKEOWNERSHIP from Windows.Win32 metadata.
	*/
	SI_PAGE_TAKEOWNERSHIP SI_PAGE_TYPE = 0x5

	/*
		SI_PAGE_SHARE from Windows.Win32 metadata.
	*/
	SI_PAGE_SHARE SI_PAGE_TYPE = 0x6
)

/*
SI_PAGE_ACTIVATED is generated from Windows.Win32 metadata.
*/
type SI_PAGE_ACTIVATED int32

const (
	/*
		SI_SHOW_DEFAULT from Windows.Win32 metadata.
	*/
	SI_SHOW_DEFAULT SI_PAGE_ACTIVATED = 0x0

	/*
		SI_SHOW_PERM_ACTIVATED from Windows.Win32 metadata.
	*/
	SI_SHOW_PERM_ACTIVATED SI_PAGE_ACTIVATED = 0x1

	/*
		SI_SHOW_AUDIT_ACTIVATED from Windows.Win32 metadata.
	*/
	SI_SHOW_AUDIT_ACTIVATED SI_PAGE_ACTIVATED = 0x2

	/*
		SI_SHOW_OWNER_ACTIVATED from Windows.Win32 metadata.
	*/
	SI_SHOW_OWNER_ACTIVATED SI_PAGE_ACTIVATED = 0x3

	/*
		SI_SHOW_EFFECTIVE_ACTIVATED from Windows.Win32 metadata.
	*/
	SI_SHOW_EFFECTIVE_ACTIVATED SI_PAGE_ACTIVATED = 0x4

	/*
		SI_SHOW_SHARE_ACTIVATED from Windows.Win32 metadata.
	*/
	SI_SHOW_SHARE_ACTIVATED SI_PAGE_ACTIVATED = 0x5

	/*
		SI_SHOW_CENTRAL_POLICY_ACTIVATED from Windows.Win32 metadata.
	*/
	SI_SHOW_CENTRAL_POLICY_ACTIVATED SI_PAGE_ACTIVATED = 0x6
)

/*
ISecurityInformation is generated from Windows.Win32 metadata.
*/
type ISecurityInformation uintptr

/*
ISecurityInformation2 is generated from Windows.Win32 metadata.
*/
type ISecurityInformation2 uintptr

/*
SID_INFO is generated from Windows.Win32 metadata.
*/
type SID_INFO struct {
	PSid          PSID
	PwzCommonName *PWSTRElement
	PwzClass      *PWSTRElement
	PwzUPN        *PWSTRElement
}

/*
SID_INFO_LIST is generated from Windows.Win32 metadata.
*/
type SID_INFO_LIST struct {
	CItems   uint32
	ASidInfo [1]SID_INFO
}

/*
IEffectivePermission is generated from Windows.Win32 metadata.
*/
type IEffectivePermission uintptr

/*
ISecurityObjectTypeInfo is generated from Windows.Win32 metadata.
*/
type ISecurityObjectTypeInfo uintptr

/*
ISecurityInformation3 is generated from Windows.Win32 metadata.
*/
type ISecurityInformation3 uintptr

/*
SECURITY_OBJECT is generated from Windows.Win32 metadata.
*/
type SECURITY_OBJECT struct {
	PwszName   *PWSTRElement
	PData      uintptr
	CbData     uint32
	PData2     uintptr
	CbData2    uint32
	Id         uint32
	FWellKnown BOOLEAN
}

/*
EFFPERM_RESULT_LIST is generated from Windows.Win32 metadata.
*/
type EFFPERM_RESULT_LIST struct {
	FEvaluated            BOOLEAN
	CObjectTypeListLength uint32
	PObjectTypeList       *OBJECT_TYPE_LIST
	PGrantedAccessList    *uint32
}

/*
ISecurityInformation4 is generated from Windows.Win32 metadata.
*/
type ISecurityInformation4 uintptr

/*
IEffectivePermission2 is generated from Windows.Win32 metadata.
*/
type IEffectivePermission2 uintptr
