//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_CreateRandomAccessStreamOnFile maps to CreateRandomAccessStreamOnFile in api-ms-win-shcore-stream-winrt-l1-1-0.dll.
*/
type PFN_CreateRandomAccessStreamOnFile func(filePath *PWSTRElement, accessMode uint32, riid *Guid, ppv *uintptr) HRESULT

/*
PFN_CreateRandomAccessStreamOverStream maps to CreateRandomAccessStreamOverStream in api-ms-win-shcore-stream-winrt-l1-1-0.dll.
*/
type PFN_CreateRandomAccessStreamOverStream func(stream *IStream, options BSOS_OPTIONS, riid *Guid, ppv *uintptr) HRESULT

/*
PFN_CreateStreamOverRandomAccessStream maps to CreateStreamOverRandomAccessStream in api-ms-win-shcore-stream-winrt-l1-1-0.dll.
*/
type PFN_CreateStreamOverRandomAccessStream func(randomAccessStream *IUnknown, riid *Guid, ppv *uintptr) HRESULT
