//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
IRadialControllerInterop is generated from Windows.Win32 metadata.
*/
type IRadialControllerInterop uintptr

/*
IRadialControllerConfigurationInterop is generated from Windows.Win32 metadata.
*/
type IRadialControllerConfigurationInterop uintptr

/*
IRadialControllerIndependentInputSourceInterop is generated from Windows.Win32 metadata.
*/
type IRadialControllerIndependentInputSourceInterop uintptr

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
}
