//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_HSTRING_UserSize maps to HSTRING_UserSize in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserSize func(param0 *uint32, param1 uint32, param2 *HSTRING) uint32

/*
PFN_HSTRING_UserMarshal maps to HSTRING_UserMarshal in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserMarshal func(param0 *uint32, param1 *uint8, param2 *HSTRING) *uint8

/*
PFN_HSTRING_UserUnmarshal maps to HSTRING_UserUnmarshal in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserUnmarshal func(param0 *uint32, param1 *uint8, param2 *HSTRING) *uint8

/*
PFN_HSTRING_UserFree maps to HSTRING_UserFree in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserFree func(param0 *uint32, param1 *HSTRING)

/*
PFN_HSTRING_UserSize64 maps to HSTRING_UserSize64 in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserSize64 func(param0 *uint32, param1 uint32, param2 *HSTRING) uint32

/*
PFN_HSTRING_UserMarshal64 maps to HSTRING_UserMarshal64 in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserMarshal64 func(param0 *uint32, param1 *uint8, param2 *HSTRING) *uint8

/*
PFN_HSTRING_UserUnmarshal64 maps to HSTRING_UserUnmarshal64 in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserUnmarshal64 func(param0 *uint32, param1 *uint8, param2 *HSTRING) *uint8

/*
PFN_HSTRING_UserFree64 maps to HSTRING_UserFree64 in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_HSTRING_UserFree64 func(param0 *uint32, param1 *HSTRING)

/*
PFN_WindowsCreateString maps to WindowsCreateString in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsCreateString func(sourceString *PWSTRElement, length uint32, string *HSTRING) HRESULT

/*
PFN_WindowsCreateStringReference maps to WindowsCreateStringReference in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsCreateStringReference func(sourceString *PWSTRElement, length uint32, hstringHeader *HSTRING_HEADER, string *HSTRING) HRESULT

/*
PFN_WindowsDeleteString maps to WindowsDeleteString in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsDeleteString func(string HSTRING) HRESULT

/*
PFN_WindowsDuplicateString maps to WindowsDuplicateString in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsDuplicateString func(string HSTRING, newString *HSTRING) HRESULT

/*
PFN_WindowsGetStringLen maps to WindowsGetStringLen in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsGetStringLen func(string HSTRING) uint32

/*
PFN_WindowsGetStringRawBuffer maps to WindowsGetStringRawBuffer in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsGetStringRawBuffer func(string HSTRING, length *uint32) *PWSTRElement

/*
PFN_WindowsIsStringEmpty maps to WindowsIsStringEmpty in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsIsStringEmpty func(string HSTRING) BOOL

/*
PFN_WindowsStringHasEmbeddedNull maps to WindowsStringHasEmbeddedNull in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsStringHasEmbeddedNull func(string HSTRING, hasEmbedNull *BOOL) HRESULT

/*
PFN_WindowsCompareStringOrdinal maps to WindowsCompareStringOrdinal in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsCompareStringOrdinal func(string1 HSTRING, string2 HSTRING, result *int32) HRESULT

/*
PFN_WindowsSubstring maps to WindowsSubstring in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsSubstring func(string HSTRING, startIndex uint32, newString *HSTRING) HRESULT

/*
PFN_WindowsSubstringWithSpecifiedLength maps to WindowsSubstringWithSpecifiedLength in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsSubstringWithSpecifiedLength func(string HSTRING, startIndex uint32, length uint32, newString *HSTRING) HRESULT

/*
PFN_WindowsConcatString maps to WindowsConcatString in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsConcatString func(string1 HSTRING, string2 HSTRING, newString *HSTRING) HRESULT

/*
PFN_WindowsReplaceString maps to WindowsReplaceString in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsReplaceString func(string HSTRING, stringReplaced HSTRING, stringReplaceWith HSTRING, newString *HSTRING) HRESULT

/*
PFN_WindowsTrimStringStart maps to WindowsTrimStringStart in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsTrimStringStart func(string HSTRING, trimString HSTRING, newString *HSTRING) HRESULT

/*
PFN_WindowsTrimStringEnd maps to WindowsTrimStringEnd in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsTrimStringEnd func(string HSTRING, trimString HSTRING, newString *HSTRING) HRESULT

/*
PFN_WindowsPreallocateStringBuffer maps to WindowsPreallocateStringBuffer in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsPreallocateStringBuffer func(length uint32, charBuffer **uint16, bufferHandle *HSTRING_BUFFER) HRESULT

/*
PFN_WindowsPromoteStringBuffer maps to WindowsPromoteStringBuffer in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsPromoteStringBuffer func(bufferHandle HSTRING_BUFFER, string *HSTRING) HRESULT

/*
PFN_WindowsDeleteStringBuffer maps to WindowsDeleteStringBuffer in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsDeleteStringBuffer func(bufferHandle HSTRING_BUFFER) HRESULT

/*
PFN_WindowsInspectString maps to WindowsInspectString in api-ms-win-core-winrt-string-l1-1-0.dll.
*/
type PFN_WindowsInspectString func(targetHString uintptr, machine uint16, callback PINSPECT_HSTRING_CALLBACK, context uintptr, length *uint32, targetStringAddress *uintptr) HRESULT
