//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_RegisterAppStateChangeNotification maps to RegisterAppStateChangeNotification in api-ms-win-core-psm-appnotify-l1-1-0.dll.
*/
type PFN_RegisterAppStateChangeNotification func(Routine PAPPSTATE_CHANGE_ROUTINE, Context uintptr, Registration *PAPPSTATE_REGISTRATION) uint32

/*
PFN_UnregisterAppStateChangeNotification maps to UnregisterAppStateChangeNotification in api-ms-win-core-psm-appnotify-l1-1-0.dll.
*/
type PFN_UnregisterAppStateChangeNotification func(Registration PAPPSTATE_REGISTRATION)
