//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:44 CEST

package bindings

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	PKEY_PhotoAcquire_RelativePathname      PROPERTYKEY
	PKEY_PhotoAcquire_FinalFilename         PROPERTYKEY
	PKEY_PhotoAcquire_GroupTag              PROPERTYKEY
	PKEY_PhotoAcquire_TransferResult        PROPERTYKEY
	PKEY_PhotoAcquire_OriginalFilename      PROPERTYKEY
	PKEY_PhotoAcquire_CameraSequenceNumber  PROPERTYKEY
	PKEY_PhotoAcquire_IntermediateFile      PROPERTYKEY
	PKEY_PhotoAcquire_SkipImport            PROPERTYKEY
	PKEY_PhotoAcquire_DuplicateDetectionID  PROPERTYKEY
	PROGRESS_INDETERMINATE                  int32
	PHOTOACQ_ERROR_RESTART_REQUIRED         HRESULT
	PHOTOACQ_RUN_DEFAULT                    uint32
	PHOTOACQ_NO_GALLERY_LAUNCH              uint32
	PHOTOACQ_DISABLE_AUTO_ROTATE            uint32
	PHOTOACQ_DISABLE_PLUGINS                uint32
	PHOTOACQ_DISABLE_GROUP_TAG_PROMPT       uint32
	PHOTOACQ_DISABLE_DB_INTEGRATION         uint32
	PHOTOACQ_DELETE_AFTER_ACQUIRE           uint32
	PHOTOACQ_DISABLE_DUPLICATE_DETECTION    uint32
	PHOTOACQ_ENABLE_THUMBNAIL_CACHING       uint32
	PHOTOACQ_DISABLE_METADATA_WRITE         uint32
	PHOTOACQ_DISABLE_THUMBNAIL_PROGRESS     uint32
	PHOTOACQ_DISABLE_SETTINGS_LINK          uint32
	PHOTOACQ_ABORT_ON_SETTINGS_UPDATE       uint32
	PHOTOACQ_IMPORT_VIDEO_AS_MULTIPLE_FILES uint32
	DSF_WPD_DEVICES                         uint32
	DSF_WIA_CAMERAS                         uint32
	DSF_WIA_SCANNERS                        uint32
	DSF_STI_DEVICES                         uint32
	DSF_TWAIN_DEVICES                       uint32
	DSF_FS_DEVICES                          uint32
	DSF_DV_DEVICES                          uint32
	DSF_ALL_DEVICES                         uint32
	DSF_CPL_MODE                            uint32
	DSF_SHOW_OFFLINE                        uint32
	PAPS_PRESAVE                            uint32
	PAPS_POSTSAVE                           uint32
	PAPS_CLEANUP                            uint32
}

/*
IPhotoAcquireItem is generated from Windows.Win32 metadata.
*/
type IPhotoAcquireItem uintptr

/*
USER_INPUT_STRING_TYPE is generated from Windows.Win32 metadata.
*/
type USER_INPUT_STRING_TYPE int32

const (
	/*
		USER_INPUT_DEFAULT from Windows.Win32 metadata.
	*/
	USER_INPUT_DEFAULT USER_INPUT_STRING_TYPE = 0x0

	/*
		USER_INPUT_PATH_ELEMENT from Windows.Win32 metadata.
	*/
	USER_INPUT_PATH_ELEMENT USER_INPUT_STRING_TYPE = 0x1
)

/*
IUserInputString is generated from Windows.Win32 metadata.
*/
type IUserInputString uintptr

/*
ERROR_ADVISE_MESSAGE_TYPE is generated from Windows.Win32 metadata.
*/
type ERROR_ADVISE_MESSAGE_TYPE int32

const (
	/*
		PHOTOACQUIRE_ERROR_SKIPRETRYCANCEL from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_ERROR_SKIPRETRYCANCEL ERROR_ADVISE_MESSAGE_TYPE = 0x0

	/*
		PHOTOACQUIRE_ERROR_RETRYCANCEL from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_ERROR_RETRYCANCEL ERROR_ADVISE_MESSAGE_TYPE = 0x1

	/*
		PHOTOACQUIRE_ERROR_YESNO from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_ERROR_YESNO ERROR_ADVISE_MESSAGE_TYPE = 0x2

	/*
		PHOTOACQUIRE_ERROR_OK from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_ERROR_OK ERROR_ADVISE_MESSAGE_TYPE = 0x3
)

/*
ERROR_ADVISE_RESULT is generated from Windows.Win32 metadata.
*/
type ERROR_ADVISE_RESULT int32

const (
	/*
		PHOTOACQUIRE_RESULT_YES from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_YES ERROR_ADVISE_RESULT = 0x0

	/*
		PHOTOACQUIRE_RESULT_NO from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_NO ERROR_ADVISE_RESULT = 0x1

	/*
		PHOTOACQUIRE_RESULT_OK from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_OK ERROR_ADVISE_RESULT = 0x2

	/*
		PHOTOACQUIRE_RESULT_SKIP from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_SKIP ERROR_ADVISE_RESULT = 0x3

	/*
		PHOTOACQUIRE_RESULT_SKIP_ALL from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_SKIP_ALL ERROR_ADVISE_RESULT = 0x4

	/*
		PHOTOACQUIRE_RESULT_RETRY from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_RETRY ERROR_ADVISE_RESULT = 0x5

	/*
		PHOTOACQUIRE_RESULT_ABORT from Windows.Win32 metadata.
	*/
	PHOTOACQUIRE_RESULT_ABORT ERROR_ADVISE_RESULT = 0x6
)

/*
IPhotoAcquireProgressCB is generated from Windows.Win32 metadata.
*/
type IPhotoAcquireProgressCB uintptr

/*
IPhotoProgressActionCB is generated from Windows.Win32 metadata.
*/
type IPhotoProgressActionCB uintptr

/*
PROGRESS_DIALOG_IMAGE_TYPE is generated from Windows.Win32 metadata.
*/
type PROGRESS_DIALOG_IMAGE_TYPE int32

const (
	/*
		PROGRESS_DIALOG_ICON_SMALL from Windows.Win32 metadata.
	*/
	PROGRESS_DIALOG_ICON_SMALL PROGRESS_DIALOG_IMAGE_TYPE = 0x0

	/*
		PROGRESS_DIALOG_ICON_LARGE from Windows.Win32 metadata.
	*/
	PROGRESS_DIALOG_ICON_LARGE PROGRESS_DIALOG_IMAGE_TYPE = 0x1

	/*
		PROGRESS_DIALOG_ICON_THUMBNAIL from Windows.Win32 metadata.
	*/
	PROGRESS_DIALOG_ICON_THUMBNAIL PROGRESS_DIALOG_IMAGE_TYPE = 0x2

	/*
		PROGRESS_DIALOG_BITMAP_THUMBNAIL from Windows.Win32 metadata.
	*/
	PROGRESS_DIALOG_BITMAP_THUMBNAIL PROGRESS_DIALOG_IMAGE_TYPE = 0x3
)

/*
PROGRESS_DIALOG_CHECKBOX_ID is generated from Windows.Win32 metadata.
*/
type PROGRESS_DIALOG_CHECKBOX_ID int32

const (
	/*
		PROGRESS_DIALOG_CHECKBOX_ID_DEFAULT from Windows.Win32 metadata.
	*/
	PROGRESS_DIALOG_CHECKBOX_ID_DEFAULT PROGRESS_DIALOG_CHECKBOX_ID = 0x0
)

/*
IPhotoProgressDialog is generated from Windows.Win32 metadata.
*/
type IPhotoProgressDialog uintptr

/*
IPhotoAcquireSource is generated from Windows.Win32 metadata.
*/
type IPhotoAcquireSource uintptr

/*
IPhotoAcquire is generated from Windows.Win32 metadata.
*/
type IPhotoAcquire uintptr

/*
IPhotoAcquireSettings is generated from Windows.Win32 metadata.
*/
type IPhotoAcquireSettings uintptr

/*
IPhotoAcquireOptionsDialog is generated from Windows.Win32 metadata.
*/
type IPhotoAcquireOptionsDialog uintptr

/*
DEVICE_SELECTION_DEVICE_TYPE is generated from Windows.Win32 metadata.
*/
type DEVICE_SELECTION_DEVICE_TYPE int32

const (
	/*
		DST_UNKNOWN_DEVICE from Windows.Win32 metadata.
	*/
	DST_UNKNOWN_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x0

	/*
		DST_WPD_DEVICE from Windows.Win32 metadata.
	*/
	DST_WPD_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x1

	/*
		DST_WIA_DEVICE from Windows.Win32 metadata.
	*/
	DST_WIA_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x2

	/*
		DST_STI_DEVICE from Windows.Win32 metadata.
	*/
	DST_STI_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x3

	/*
		DSF_TWAIN_DEVICE from Windows.Win32 metadata.
	*/
	DSF_TWAIN_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x4

	/*
		DST_FS_DEVICE from Windows.Win32 metadata.
	*/
	DST_FS_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x5

	/*
		DST_DV_DEVICE from Windows.Win32 metadata.
	*/
	DST_DV_DEVICE DEVICE_SELECTION_DEVICE_TYPE = 0x6
)

/*
IPhotoAcquireDeviceSelectionDialog is generated from Windows.Win32 metadata.
*/
type IPhotoAcquireDeviceSelectionDialog uintptr

/*
IPhotoAcquirePlugin is generated from Windows.Win32 metadata.
*/
type IPhotoAcquirePlugin uintptr

/*
PhotoAcquire is generated from Windows.Win32 metadata.
*/
type PhotoAcquire struct {
}

/*
PhotoAcquireAutoPlayDropTarget is generated from Windows.Win32 metadata.
*/
type PhotoAcquireAutoPlayDropTarget struct {
}

/*
PhotoAcquireAutoPlayHWEventHandler is generated from Windows.Win32 metadata.
*/
type PhotoAcquireAutoPlayHWEventHandler struct {
}

/*
PhotoAcquireOptionsDialog is generated from Windows.Win32 metadata.
*/
type PhotoAcquireOptionsDialog struct {
}

/*
PhotoProgressDialog is generated from Windows.Win32 metadata.
*/
type PhotoProgressDialog struct {
}

/*
PhotoAcquireDeviceSelectionDialog is generated from Windows.Win32 metadata.
*/
type PhotoAcquireDeviceSelectionDialog struct {
}
