//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_CoCreateActivity maps to CoCreateActivity in comsvcs.dll.
*/
type PFN_CoCreateActivity func(pIUnknown *IUnknown, riid *Guid, ppObj *uintptr) HRESULT

/*
PFN_CoEnterServiceDomain maps to CoEnterServiceDomain in comsvcs.dll.
*/
type PFN_CoEnterServiceDomain func(pConfigObject *IUnknown) HRESULT

/*
PFN_CoLeaveServiceDomain maps to CoLeaveServiceDomain in comsvcs.dll.
*/
type PFN_CoLeaveServiceDomain func(pUnkStatus *IUnknown)

/*
PFN_GetManagedExtensions maps to GetManagedExtensions in comsvcs.dll.
*/
type PFN_GetManagedExtensions func(dwExts *uint32) HRESULT

/*
PFN_SafeRef maps to SafeRef in comsvcs.dll.
*/
type PFN_SafeRef func(rid *Guid, pUnk *IUnknown) uintptr

/*
PFN_RecycleSurrogate maps to RecycleSurrogate in comsvcs.dll.
*/
type PFN_RecycleSurrogate func(lReasonCode int32) HRESULT

/*
PFN_MTSCreateActivity maps to MTSCreateActivity in comsvcs.dll.
*/
type PFN_MTSCreateActivity func(riid *Guid, ppobj *uintptr) HRESULT
