//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_SfcGetNextProtectedFile maps to SfcGetNextProtectedFile in sfc.dll.
*/
type PFN_SfcGetNextProtectedFile func(RpcHandle HANDLE, ProtFileData *PROTECTED_FILE_DATA) BOOL

/*
PFN_SfcIsFileProtected maps to SfcIsFileProtected in sfc.dll.
*/
type PFN_SfcIsFileProtected func(RpcHandle HANDLE, ProtFileName *PWSTRElement) BOOL

/*
PFN_SfcIsKeyProtected maps to SfcIsKeyProtected in sfc.dll.
*/
type PFN_SfcIsKeyProtected func(KeyHandle HKEY, SubKeyName *PWSTRElement, KeySam uint32) BOOL

/*
PFN_SfpVerifyFile maps to SfpVerifyFile in sfc.dll.
*/
type PFN_SfpVerifyFile func(pszFileName *PSTRElement, pszError *PSTRElement, dwErrSize uint32) BOOL

/*
PFN_SRSetRestorePointA maps to SRSetRestorePointA in sfc.dll.
*/
type PFN_SRSetRestorePointA func(pRestorePtSpec *RESTOREPOINTINFOA, pSMgrStatus *STATEMGRSTATUS) BOOL

/*
PFN_SRSetRestorePointW maps to SRSetRestorePointW in sfc.dll.
*/
type PFN_SRSetRestorePointW func(pRestorePtSpec *RESTOREPOINTINFOW, pSMgrStatus *STATEMGRSTATUS) BOOL
