//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:45 CEST

package bindings

/*
PFN_LsaRegisterLogonProcess maps to LsaRegisterLogonProcess in secur32.dll.
*/
type PFN_LsaRegisterLogonProcess func(LogonProcessName *LSA_STRING, LsaHandle *HANDLE, SecurityMode *uint32) NTSTATUS

/*
PFN_LsaLogonUser maps to LsaLogonUser in secur32.dll.
*/
type PFN_LsaLogonUser func(LsaHandle HANDLE, OriginName *LSA_STRING, LogonType SECURITY_LOGON_TYPE, AuthenticationPackage uint32, AuthenticationInformation uintptr, AuthenticationInformationLength uint32, LocalGroups *TOKEN_GROUPS, SourceContext *TOKEN_SOURCE, ProfileBuffer *uintptr, ProfileBufferLength *uint32, LogonId *LUID, Token *HANDLE, Quotas *QUOTA_LIMITS, SubStatus *int32) NTSTATUS

/*
PFN_LsaLookupAuthenticationPackage maps to LsaLookupAuthenticationPackage in secur32.dll.
*/
type PFN_LsaLookupAuthenticationPackage func(LsaHandle HANDLE, PackageName *LSA_STRING, AuthenticationPackage *uint32) NTSTATUS

/*
PFN_LsaFreeReturnBuffer maps to LsaFreeReturnBuffer in secur32.dll.
*/
type PFN_LsaFreeReturnBuffer func(Buffer uintptr) NTSTATUS

/*
PFN_LsaCallAuthenticationPackage maps to LsaCallAuthenticationPackage in secur32.dll.
*/
type PFN_LsaCallAuthenticationPackage func(LsaHandle HANDLE, AuthenticationPackage uint32, ProtocolSubmitBuffer uintptr, SubmitBufferLength uint32, ProtocolReturnBuffer *uintptr, ReturnBufferLength *uint32, ProtocolStatus *int32) NTSTATUS

/*
PFN_LsaDeregisterLogonProcess maps to LsaDeregisterLogonProcess in secur32.dll.
*/
type PFN_LsaDeregisterLogonProcess func(LsaHandle HANDLE) NTSTATUS

/*
PFN_LsaConnectUntrusted maps to LsaConnectUntrusted in secur32.dll.
*/
type PFN_LsaConnectUntrusted func(LsaHandle *HANDLE) NTSTATUS

/*
PFN_LsaEnumerateLogonSessions maps to LsaEnumerateLogonSessions in secur32.dll.
*/
type PFN_LsaEnumerateLogonSessions func(LogonSessionCount *uint32, LogonSessionList **LUID) NTSTATUS

/*
PFN_LsaGetLogonSessionData maps to LsaGetLogonSessionData in secur32.dll.
*/
type PFN_LsaGetLogonSessionData func(LogonId *LUID, ppLogonSessionData **SECURITY_LOGON_SESSION_DATA) NTSTATUS

/*
PFN_LsaRegisterPolicyChangeNotification maps to LsaRegisterPolicyChangeNotification in secur32.dll.
*/
type PFN_LsaRegisterPolicyChangeNotification func(InformationClass POLICY_NOTIFICATION_INFORMATION_CLASS, NotificationEventHandle HANDLE) NTSTATUS

/*
PFN_LsaUnregisterPolicyChangeNotification maps to LsaUnregisterPolicyChangeNotification in secur32.dll.
*/
type PFN_LsaUnregisterPolicyChangeNotification func(InformationClass POLICY_NOTIFICATION_INFORMATION_CLASS, NotificationEventHandle HANDLE) NTSTATUS

/*
PFN_AcquireCredentialsHandleW maps to AcquireCredentialsHandleW in secur32.dll.
*/
type PFN_AcquireCredentialsHandleW func(pszPrincipal *PWSTRElement, pszPackage *PWSTRElement, fCredentialUse SECPKG_CRED, pvLogonId uintptr, pAuthData uintptr, pGetKeyFn SEC_GET_KEY_FN, pvGetKeyArgument uintptr, phCredential *SecHandle, ptsExpiry *int64) HRESULT

/*
PFN_AcquireCredentialsHandleA maps to AcquireCredentialsHandleA in secur32.dll.
*/
type PFN_AcquireCredentialsHandleA func(pszPrincipal *PSTRElement, pszPackage *PSTRElement, fCredentialUse SECPKG_CRED, pvLogonId uintptr, pAuthData uintptr, pGetKeyFn SEC_GET_KEY_FN, pvGetKeyArgument uintptr, phCredential *SecHandle, ptsExpiry *int64) HRESULT

/*
PFN_FreeCredentialsHandle maps to FreeCredentialsHandle in secur32.dll.
*/
type PFN_FreeCredentialsHandle func(phCredential *SecHandle) HRESULT

/*
PFN_AddCredentialsW maps to AddCredentialsW in secur32.dll.
*/
type PFN_AddCredentialsW func(hCredentials *SecHandle, pszPrincipal *PWSTRElement, pszPackage *PWSTRElement, fCredentialUse uint32, pAuthData uintptr, pGetKeyFn SEC_GET_KEY_FN, pvGetKeyArgument uintptr, ptsExpiry *int64) HRESULT

/*
PFN_AddCredentialsA maps to AddCredentialsA in secur32.dll.
*/
type PFN_AddCredentialsA func(hCredentials *SecHandle, pszPrincipal *PSTRElement, pszPackage *PSTRElement, fCredentialUse uint32, pAuthData uintptr, pGetKeyFn SEC_GET_KEY_FN, pvGetKeyArgument uintptr, ptsExpiry *int64) HRESULT

/*
PFN_ChangeAccountPasswordW maps to ChangeAccountPasswordW in secur32.dll.
*/
type PFN_ChangeAccountPasswordW func(pszPackageName *uint16, pszDomainName *uint16, pszAccountName *uint16, pszOldPassword *uint16, pszNewPassword *uint16, bImpersonating BOOLEAN, dwReserved uint32, pOutput *SecBufferDesc) HRESULT

/*
PFN_ChangeAccountPasswordA maps to ChangeAccountPasswordA in secur32.dll.
*/
type PFN_ChangeAccountPasswordA func(pszPackageName *int8, pszDomainName *int8, pszAccountName *int8, pszOldPassword *int8, pszNewPassword *int8, bImpersonating BOOLEAN, dwReserved uint32, pOutput *SecBufferDesc) HRESULT

/*
PFN_InitializeSecurityContextW maps to InitializeSecurityContextW in secur32.dll.
*/
type PFN_InitializeSecurityContextW func(phCredential *SecHandle, phContext *SecHandle, pszTargetName *uint16, fContextReq ISC_REQ_FLAGS, Reserved1 uint32, TargetDataRep uint32, pInput *SecBufferDesc, Reserved2 uint32, phNewContext *SecHandle, pOutput *SecBufferDesc, pfContextAttr *uint32, ptsExpiry *int64) HRESULT

/*
PFN_InitializeSecurityContextA maps to InitializeSecurityContextA in secur32.dll.
*/
type PFN_InitializeSecurityContextA func(phCredential *SecHandle, phContext *SecHandle, pszTargetName *int8, fContextReq ISC_REQ_FLAGS, Reserved1 uint32, TargetDataRep uint32, pInput *SecBufferDesc, Reserved2 uint32, phNewContext *SecHandle, pOutput *SecBufferDesc, pfContextAttr *uint32, ptsExpiry *int64) HRESULT

/*
PFN_AcceptSecurityContext maps to AcceptSecurityContext in secur32.dll.
*/
type PFN_AcceptSecurityContext func(phCredential *SecHandle, phContext *SecHandle, pInput *SecBufferDesc, fContextReq ASC_REQ_FLAGS, TargetDataRep uint32, phNewContext *SecHandle, pOutput *SecBufferDesc, pfContextAttr *uint32, ptsExpiry *int64) HRESULT

/*
PFN_CompleteAuthToken maps to CompleteAuthToken in secur32.dll.
*/
type PFN_CompleteAuthToken func(phContext *SecHandle, pToken *SecBufferDesc) HRESULT

/*
PFN_ImpersonateSecurityContext maps to ImpersonateSecurityContext in secur32.dll.
*/
type PFN_ImpersonateSecurityContext func(phContext *SecHandle) HRESULT

/*
PFN_RevertSecurityContext maps to RevertSecurityContext in secur32.dll.
*/
type PFN_RevertSecurityContext func(phContext *SecHandle) HRESULT

/*
PFN_QuerySecurityContextToken maps to QuerySecurityContextToken in secur32.dll.
*/
type PFN_QuerySecurityContextToken func(phContext *SecHandle, Token *uintptr) HRESULT

/*
PFN_DeleteSecurityContext maps to DeleteSecurityContext in secur32.dll.
*/
type PFN_DeleteSecurityContext func(phContext *SecHandle) HRESULT

/*
PFN_ApplyControlToken maps to ApplyControlToken in secur32.dll.
*/
type PFN_ApplyControlToken func(phContext *SecHandle, pInput *SecBufferDesc) HRESULT

/*
PFN_QueryContextAttributesW maps to QueryContextAttributesW in secur32.dll.
*/
type PFN_QueryContextAttributesW func(phContext *SecHandle, ulAttribute SECPKG_ATTR, pBuffer uintptr) HRESULT

/*
PFN_QueryContextAttributesA maps to QueryContextAttributesA in secur32.dll.
*/
type PFN_QueryContextAttributesA func(phContext *SecHandle, ulAttribute SECPKG_ATTR, pBuffer uintptr) HRESULT

/*
PFN_SetContextAttributesW maps to SetContextAttributesW in secur32.dll.
*/
type PFN_SetContextAttributesW func(phContext *SecHandle, ulAttribute SECPKG_ATTR, pBuffer uintptr, cbBuffer uint32) HRESULT

/*
PFN_SetContextAttributesA maps to SetContextAttributesA in secur32.dll.
*/
type PFN_SetContextAttributesA func(phContext *SecHandle, ulAttribute SECPKG_ATTR, pBuffer uintptr, cbBuffer uint32) HRESULT

/*
PFN_QueryCredentialsAttributesW maps to QueryCredentialsAttributesW in secur32.dll.
*/
type PFN_QueryCredentialsAttributesW func(phCredential *SecHandle, ulAttribute uint32, pBuffer uintptr) HRESULT

/*
PFN_QueryCredentialsAttributesA maps to QueryCredentialsAttributesA in secur32.dll.
*/
type PFN_QueryCredentialsAttributesA func(phCredential *SecHandle, ulAttribute uint32, pBuffer uintptr) HRESULT

/*
PFN_SetCredentialsAttributesW maps to SetCredentialsAttributesW in secur32.dll.
*/
type PFN_SetCredentialsAttributesW func(phCredential *SecHandle, ulAttribute uint32, pBuffer uintptr, cbBuffer uint32) HRESULT

/*
PFN_SetCredentialsAttributesA maps to SetCredentialsAttributesA in secur32.dll.
*/
type PFN_SetCredentialsAttributesA func(phCredential *SecHandle, ulAttribute uint32, pBuffer uintptr, cbBuffer uint32) HRESULT

/*
PFN_FreeContextBuffer maps to FreeContextBuffer in secur32.dll.
*/
type PFN_FreeContextBuffer func(pvContextBuffer uintptr) HRESULT

/*
PFN_MakeSignature maps to MakeSignature in secur32.dll.
*/
type PFN_MakeSignature func(phContext *SecHandle, fQOP uint32, pMessage *SecBufferDesc, MessageSeqNo uint32) HRESULT

/*
PFN_VerifySignature maps to VerifySignature in secur32.dll.
*/
type PFN_VerifySignature func(phContext *SecHandle, pMessage *SecBufferDesc, MessageSeqNo uint32, pfQOP *uint32) HRESULT

/*
PFN_EncryptMessage maps to EncryptMessage in secur32.dll.
*/
type PFN_EncryptMessage func(phContext *SecHandle, fQOP uint32, pMessage *SecBufferDesc, MessageSeqNo uint32) HRESULT

/*
PFN_DecryptMessage maps to DecryptMessage in secur32.dll.
*/
type PFN_DecryptMessage func(phContext *SecHandle, pMessage *SecBufferDesc, MessageSeqNo uint32, pfQOP *uint32) HRESULT

/*
PFN_EnumerateSecurityPackagesW maps to EnumerateSecurityPackagesW in secur32.dll.
*/
type PFN_EnumerateSecurityPackagesW func(pcPackages *uint32, ppPackageInfo **SecPkgInfoW) HRESULT

/*
PFN_EnumerateSecurityPackagesA maps to EnumerateSecurityPackagesA in secur32.dll.
*/
type PFN_EnumerateSecurityPackagesA func(pcPackages *uint32, ppPackageInfo **SecPkgInfoA) HRESULT

/*
PFN_QuerySecurityPackageInfoW maps to QuerySecurityPackageInfoW in secur32.dll.
*/
type PFN_QuerySecurityPackageInfoW func(pszPackageName *PWSTRElement, ppPackageInfo **SecPkgInfoW) HRESULT

/*
PFN_QuerySecurityPackageInfoA maps to QuerySecurityPackageInfoA in secur32.dll.
*/
type PFN_QuerySecurityPackageInfoA func(pszPackageName *PSTRElement, ppPackageInfo **SecPkgInfoA) HRESULT

/*
PFN_ExportSecurityContext maps to ExportSecurityContext in secur32.dll.
*/
type PFN_ExportSecurityContext func(phContext *SecHandle, fFlags EXPORT_SECURITY_CONTEXT_FLAGS, pPackedContext *SecBuffer, pToken *uintptr) HRESULT

/*
PFN_ImportSecurityContextW maps to ImportSecurityContextW in secur32.dll.
*/
type PFN_ImportSecurityContextW func(pszPackage *PWSTRElement, pPackedContext *SecBuffer, Token uintptr, phContext *SecHandle) HRESULT

/*
PFN_ImportSecurityContextA maps to ImportSecurityContextA in secur32.dll.
*/
type PFN_ImportSecurityContextA func(pszPackage *PSTRElement, pPackedContext *SecBuffer, Token uintptr, phContext *SecHandle) HRESULT

/*
PFN_InitSecurityInterfaceA maps to InitSecurityInterfaceA in secur32.dll.
*/
type PFN_InitSecurityInterfaceA func() *SecurityFunctionTableA

/*
PFN_InitSecurityInterfaceW maps to InitSecurityInterfaceW in secur32.dll.
*/
type PFN_InitSecurityInterfaceW func() *SecurityFunctionTableW

/*
PFN_SaslEnumerateProfilesA maps to SaslEnumerateProfilesA in secur32.dll.
*/
type PFN_SaslEnumerateProfilesA func(ProfileList **PSTRElement, ProfileCount *uint32) HRESULT

/*
PFN_SaslEnumerateProfilesW maps to SaslEnumerateProfilesW in secur32.dll.
*/
type PFN_SaslEnumerateProfilesW func(ProfileList **PWSTRElement, ProfileCount *uint32) HRESULT

/*
PFN_SaslGetProfilePackageA maps to SaslGetProfilePackageA in secur32.dll.
*/
type PFN_SaslGetProfilePackageA func(ProfileName *PSTRElement, PackageInfo **SecPkgInfoA) HRESULT

/*
PFN_SaslGetProfilePackageW maps to SaslGetProfilePackageW in secur32.dll.
*/
type PFN_SaslGetProfilePackageW func(ProfileName *PWSTRElement, PackageInfo **SecPkgInfoW) HRESULT

/*
PFN_SaslIdentifyPackageA maps to SaslIdentifyPackageA in secur32.dll.
*/
type PFN_SaslIdentifyPackageA func(pInput *SecBufferDesc, PackageInfo **SecPkgInfoA) HRESULT

/*
PFN_SaslIdentifyPackageW maps to SaslIdentifyPackageW in secur32.dll.
*/
type PFN_SaslIdentifyPackageW func(pInput *SecBufferDesc, PackageInfo **SecPkgInfoW) HRESULT

/*
PFN_SaslInitializeSecurityContextW maps to SaslInitializeSecurityContextW in secur32.dll.
*/
type PFN_SaslInitializeSecurityContextW func(phCredential *SecHandle, phContext *SecHandle, pszTargetName *PWSTRElement, fContextReq ISC_REQ_FLAGS, Reserved1 uint32, TargetDataRep uint32, pInput *SecBufferDesc, Reserved2 uint32, phNewContext *SecHandle, pOutput *SecBufferDesc, pfContextAttr *uint32, ptsExpiry *int64) HRESULT

/*
PFN_SaslInitializeSecurityContextA maps to SaslInitializeSecurityContextA in secur32.dll.
*/
type PFN_SaslInitializeSecurityContextA func(phCredential *SecHandle, phContext *SecHandle, pszTargetName *PSTRElement, fContextReq ISC_REQ_FLAGS, Reserved1 uint32, TargetDataRep uint32, pInput *SecBufferDesc, Reserved2 uint32, phNewContext *SecHandle, pOutput *SecBufferDesc, pfContextAttr *uint32, ptsExpiry *int64) HRESULT

/*
PFN_SaslAcceptSecurityContext maps to SaslAcceptSecurityContext in secur32.dll.
*/
type PFN_SaslAcceptSecurityContext func(phCredential *SecHandle, phContext *SecHandle, pInput *SecBufferDesc, fContextReq ASC_REQ_FLAGS, TargetDataRep uint32, phNewContext *SecHandle, pOutput *SecBufferDesc, pfContextAttr *uint32, ptsExpiry *int64) HRESULT

/*
PFN_SaslSetContextOption maps to SaslSetContextOption in secur32.dll.
*/
type PFN_SaslSetContextOption func(ContextHandle *SecHandle, Option uint32, Value uintptr, Size uint32) HRESULT

/*
PFN_SaslGetContextOption maps to SaslGetContextOption in secur32.dll.
*/
type PFN_SaslGetContextOption func(ContextHandle *SecHandle, Option uint32, Value uintptr, Size uint32, Needed *uint32) HRESULT

/*
PFN_SspiPrepareForCredRead maps to SspiPrepareForCredRead in secur32.dll.
*/
type PFN_SspiPrepareForCredRead func(AuthIdentity uintptr, pszTargetName *PWSTRElement, pCredmanCredentialType *uint32, ppszCredmanTargetName **PWSTRElement) HRESULT

/*
PFN_SspiPrepareForCredWrite maps to SspiPrepareForCredWrite in secur32.dll.
*/
type PFN_SspiPrepareForCredWrite func(AuthIdentity uintptr, pszTargetName *PWSTRElement, pCredmanCredentialType *uint32, ppszCredmanTargetName **PWSTRElement, ppszCredmanUserName **PWSTRElement, ppCredentialBlob **uint8, pCredentialBlobSize *uint32) HRESULT

/*
PFN_SspiEncryptAuthIdentity maps to SspiEncryptAuthIdentity in secur32.dll.
*/
type PFN_SspiEncryptAuthIdentity func(AuthData uintptr) HRESULT

/*
PFN_SspiDecryptAuthIdentity maps to SspiDecryptAuthIdentity in secur32.dll.
*/
type PFN_SspiDecryptAuthIdentity func(EncryptedAuthData uintptr) HRESULT

/*
PFN_SspiIsAuthIdentityEncrypted maps to SspiIsAuthIdentityEncrypted in secur32.dll.
*/
type PFN_SspiIsAuthIdentityEncrypted func(EncryptedAuthData uintptr) BOOLEAN

/*
PFN_SspiEncodeAuthIdentityAsStrings maps to SspiEncodeAuthIdentityAsStrings in secur32.dll.
*/
type PFN_SspiEncodeAuthIdentityAsStrings func(pAuthIdentity uintptr, ppszUserName **PWSTRElement, ppszDomainName **PWSTRElement, ppszPackedCredentialsString **PWSTRElement) HRESULT

/*
PFN_SspiValidateAuthIdentity maps to SspiValidateAuthIdentity in secur32.dll.
*/
type PFN_SspiValidateAuthIdentity func(AuthData uintptr) HRESULT

/*
PFN_SspiCopyAuthIdentity maps to SspiCopyAuthIdentity in secur32.dll.
*/
type PFN_SspiCopyAuthIdentity func(AuthData uintptr, AuthDataCopy *uintptr) HRESULT

/*
PFN_SspiFreeAuthIdentity maps to SspiFreeAuthIdentity in secur32.dll.
*/
type PFN_SspiFreeAuthIdentity func(AuthData uintptr)

/*
PFN_SspiZeroAuthIdentity maps to SspiZeroAuthIdentity in secur32.dll.
*/
type PFN_SspiZeroAuthIdentity func(AuthData uintptr)

/*
PFN_SspiLocalFree maps to SspiLocalFree in secur32.dll.
*/
type PFN_SspiLocalFree func(DataBuffer uintptr)

/*
PFN_SspiEncodeStringsAsAuthIdentity maps to SspiEncodeStringsAsAuthIdentity in secur32.dll.
*/
type PFN_SspiEncodeStringsAsAuthIdentity func(pszUserName *PWSTRElement, pszDomainName *PWSTRElement, pszPackedCredentialsString *PWSTRElement, ppAuthIdentity *uintptr) HRESULT

/*
PFN_SspiCompareAuthIdentities maps to SspiCompareAuthIdentities in secur32.dll.
*/
type PFN_SspiCompareAuthIdentities func(AuthIdentity1 uintptr, AuthIdentity2 uintptr, SameSuppliedUser *BOOLEAN, SameSuppliedIdentity *BOOLEAN) HRESULT

/*
PFN_SspiMarshalAuthIdentity maps to SspiMarshalAuthIdentity in secur32.dll.
*/
type PFN_SspiMarshalAuthIdentity func(AuthIdentity uintptr, AuthIdentityLength *uint32, AuthIdentityByteArray **int8) HRESULT

/*
PFN_SspiUnmarshalAuthIdentity maps to SspiUnmarshalAuthIdentity in secur32.dll.
*/
type PFN_SspiUnmarshalAuthIdentity func(AuthIdentityLength uint32, AuthIdentityByteArray *PSTRElement, ppAuthIdentity *uintptr) HRESULT

/*
PFN_SspiGetTargetHostName maps to SspiGetTargetHostName in secur32.dll.
*/
type PFN_SspiGetTargetHostName func(pszTargetName *PWSTRElement, pszHostName **PWSTRElement) HRESULT

/*
PFN_SspiExcludePackage maps to SspiExcludePackage in secur32.dll.
*/
type PFN_SspiExcludePackage func(AuthIdentity uintptr, pszPackageName *PWSTRElement, ppNewAuthIdentity *uintptr) HRESULT

/*
PFN_AddSecurityPackageA maps to AddSecurityPackageA in secur32.dll.
*/
type PFN_AddSecurityPackageA func(pszPackageName *PSTRElement, pOptions *SECURITY_PACKAGE_OPTIONS) HRESULT

/*
PFN_AddSecurityPackageW maps to AddSecurityPackageW in secur32.dll.
*/
type PFN_AddSecurityPackageW func(pszPackageName *PWSTRElement, pOptions *SECURITY_PACKAGE_OPTIONS) HRESULT

/*
PFN_DeleteSecurityPackageA maps to DeleteSecurityPackageA in secur32.dll.
*/
type PFN_DeleteSecurityPackageA func(pszPackageName *PSTRElement) HRESULT

/*
PFN_DeleteSecurityPackageW maps to DeleteSecurityPackageW in secur32.dll.
*/
type PFN_DeleteSecurityPackageW func(pszPackageName *PWSTRElement) HRESULT

/*
PFN_CredMarshalTargetInfo maps to CredMarshalTargetInfo in secur32.dll.
*/
type PFN_CredMarshalTargetInfo func(InTargetInfo *CREDENTIAL_TARGET_INFORMATIONW, Buffer **uint16, BufferSize *uint32) NTSTATUS

/*
PFN_CredUnmarshalTargetInfo maps to CredUnmarshalTargetInfo in secur32.dll.
*/
type PFN_CredUnmarshalTargetInfo func(Buffer *uint16, BufferSize uint32, RetTargetInfo **CREDENTIAL_TARGET_INFORMATIONW, RetActualSize *uint32) NTSTATUS

/*
PFN_GetUserNameExA maps to GetUserNameExA in secur32.dll.
*/
type PFN_GetUserNameExA func(NameFormat EXTENDED_NAME_FORMAT, lpNameBuffer *PSTRElement, nSize *uint32) BOOLEAN

/*
PFN_GetUserNameExW maps to GetUserNameExW in secur32.dll.
*/
type PFN_GetUserNameExW func(NameFormat EXTENDED_NAME_FORMAT, lpNameBuffer *PWSTRElement, nSize *uint32) BOOLEAN

/*
PFN_GetComputerObjectNameA maps to GetComputerObjectNameA in secur32.dll.
*/
type PFN_GetComputerObjectNameA func(NameFormat EXTENDED_NAME_FORMAT, lpNameBuffer *PSTRElement, nSize *uint32) BOOLEAN

/*
PFN_GetComputerObjectNameW maps to GetComputerObjectNameW in secur32.dll.
*/
type PFN_GetComputerObjectNameW func(NameFormat EXTENDED_NAME_FORMAT, lpNameBuffer *PWSTRElement, nSize *uint32) BOOLEAN

/*
PFN_TranslateNameA maps to TranslateNameA in secur32.dll.
*/
type PFN_TranslateNameA func(lpAccountName *PSTRElement, AccountNameFormat EXTENDED_NAME_FORMAT, DesiredNameFormat EXTENDED_NAME_FORMAT, lpTranslatedName *PSTRElement, nSize *uint32) BOOLEAN

/*
PFN_TranslateNameW maps to TranslateNameW in secur32.dll.
*/
type PFN_TranslateNameW func(lpAccountName *PWSTRElement, AccountNameFormat EXTENDED_NAME_FORMAT, DesiredNameFormat EXTENDED_NAME_FORMAT, lpTranslatedName *PWSTRElement, nSize *uint32) BOOLEAN
