//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_HlinkCreateFromMoniker maps to HlinkCreateFromMoniker in hlink.dll.
*/
type PFN_HlinkCreateFromMoniker func(pimkTrgt *IMoniker, pwzLocation *PWSTRElement, pwzFriendlyName *PWSTRElement, pihlsite *IHlinkSite, dwSiteData uint32, piunkOuter *IUnknown, riid *Guid, ppvObj *uintptr) HRESULT

/*
PFN_HlinkCreateFromString maps to HlinkCreateFromString in hlink.dll.
*/
type PFN_HlinkCreateFromString func(pwzTarget *PWSTRElement, pwzLocation *PWSTRElement, pwzFriendlyName *PWSTRElement, pihlsite *IHlinkSite, dwSiteData uint32, piunkOuter *IUnknown, riid *Guid, ppvObj *uintptr) HRESULT

/*
PFN_HlinkCreateFromData maps to HlinkCreateFromData in hlink.dll.
*/
type PFN_HlinkCreateFromData func(piDataObj *IDataObject, pihlsite *IHlinkSite, dwSiteData uint32, piunkOuter *IUnknown, riid *Guid, ppvObj *uintptr) HRESULT

/*
PFN_HlinkQueryCreateFromData maps to HlinkQueryCreateFromData in hlink.dll.
*/
type PFN_HlinkQueryCreateFromData func(piDataObj *IDataObject) HRESULT

/*
PFN_HlinkClone maps to HlinkClone in hlink.dll.
*/
type PFN_HlinkClone func(pihl *IHlink, riid *Guid, pihlsiteForClone *IHlinkSite, dwSiteData uint32, ppvObj *uintptr) HRESULT

/*
PFN_HlinkCreateBrowseContext maps to HlinkCreateBrowseContext in hlink.dll.
*/
type PFN_HlinkCreateBrowseContext func(piunkOuter *IUnknown, riid *Guid, ppvObj *uintptr) HRESULT

/*
PFN_HlinkNavigateToStringReference maps to HlinkNavigateToStringReference in hlink.dll.
*/
type PFN_HlinkNavigateToStringReference func(pwzTarget *PWSTRElement, pwzLocation *PWSTRElement, pihlsite *IHlinkSite, dwSiteData uint32, pihlframe *IHlinkFrame, grfHLNF uint32, pibc *IBindCtx, pibsc *IBindStatusCallback, pihlbc *IHlinkBrowseContext) HRESULT

/*
PFN_HlinkNavigate maps to HlinkNavigate in hlink.dll.
*/
type PFN_HlinkNavigate func(pihl *IHlink, pihlframe *IHlinkFrame, grfHLNF uint32, pbc *IBindCtx, pibsc *IBindStatusCallback, pihlbc *IHlinkBrowseContext) HRESULT

/*
PFN_HlinkOnNavigate maps to HlinkOnNavigate in hlink.dll.
*/
type PFN_HlinkOnNavigate func(pihlframe *IHlinkFrame, pihlbc *IHlinkBrowseContext, grfHLNF uint32, pimkTarget *IMoniker, pwzLocation *PWSTRElement, pwzFriendlyName *PWSTRElement, puHLID *uint32) HRESULT

/*
PFN_HlinkUpdateStackItem maps to HlinkUpdateStackItem in hlink.dll.
*/
type PFN_HlinkUpdateStackItem func(pihlframe *IHlinkFrame, pihlbc *IHlinkBrowseContext, uHLID uint32, pimkTrgt *IMoniker, pwzLocation *PWSTRElement, pwzFriendlyName *PWSTRElement) HRESULT

/*
PFN_HlinkOnRenameDocument maps to HlinkOnRenameDocument in hlink.dll.
*/
type PFN_HlinkOnRenameDocument func(dwReserved uint32, pihlbc *IHlinkBrowseContext, pimkOld *IMoniker, pimkNew *IMoniker) HRESULT

/*
PFN_HlinkResolveMonikerForData maps to HlinkResolveMonikerForData in hlink.dll.
*/
type PFN_HlinkResolveMonikerForData func(pimkReference *IMoniker, reserved uint32, pibc *IBindCtx, cFmtetc uint32, rgFmtetc *FORMATETC, pibsc *IBindStatusCallback, pimkBase *IMoniker) HRESULT

/*
PFN_HlinkResolveStringForData maps to HlinkResolveStringForData in hlink.dll.
*/
type PFN_HlinkResolveStringForData func(pwzReference *PWSTRElement, reserved uint32, pibc *IBindCtx, cFmtetc uint32, rgFmtetc *FORMATETC, pibsc *IBindStatusCallback, pimkBase *IMoniker) HRESULT

/*
PFN_HlinkParseDisplayName maps to HlinkParseDisplayName in hlink.dll.
*/
type PFN_HlinkParseDisplayName func(pibc *IBindCtx, pwzDisplayName *PWSTRElement, fNoForceAbs BOOL, pcchEaten *uint32, ppimk **IMoniker) HRESULT

/*
PFN_HlinkCreateExtensionServices maps to HlinkCreateExtensionServices in hlink.dll.
*/
type PFN_HlinkCreateExtensionServices func(pwzAdditionalHeaders *PWSTRElement, phwnd HWND, pszUsername *PWSTRElement, pszPassword *PWSTRElement, piunkOuter *IUnknown, riid *Guid, ppvObj *uintptr) HRESULT

/*
PFN_HlinkPreprocessMoniker maps to HlinkPreprocessMoniker in hlink.dll.
*/
type PFN_HlinkPreprocessMoniker func(pibc *IBindCtx, pimkIn *IMoniker, ppimkOut **IMoniker) HRESULT

/*
PFN_OleSaveToStreamEx maps to OleSaveToStreamEx in hlink.dll.
*/
type PFN_OleSaveToStreamEx func(piunk *IUnknown, pistm *IStream, fClearDirty BOOL) HRESULT

/*
PFN_HlinkSetSpecialReference maps to HlinkSetSpecialReference in hlink.dll.
*/
type PFN_HlinkSetSpecialReference func(uReference uint32, pwzReference *PWSTRElement) HRESULT

/*
PFN_HlinkGetSpecialReference maps to HlinkGetSpecialReference in hlink.dll.
*/
type PFN_HlinkGetSpecialReference func(uReference uint32, ppwzReference **PWSTRElement) HRESULT

/*
PFN_HlinkCreateShortcut maps to HlinkCreateShortcut in hlink.dll.
*/
type PFN_HlinkCreateShortcut func(grfHLSHORTCUTF uint32, pihl *IHlink, pwzDir *PWSTRElement, pwzFileName *PWSTRElement, ppwzShortcutFile **PWSTRElement, dwReserved uint32) HRESULT

/*
PFN_HlinkCreateShortcutFromMoniker maps to HlinkCreateShortcutFromMoniker in hlink.dll.
*/
type PFN_HlinkCreateShortcutFromMoniker func(grfHLSHORTCUTF uint32, pimkTarget *IMoniker, pwzLocation *PWSTRElement, pwzDir *PWSTRElement, pwzFileName *PWSTRElement, ppwzShortcutFile **PWSTRElement, dwReserved uint32) HRESULT

/*
PFN_HlinkCreateShortcutFromString maps to HlinkCreateShortcutFromString in hlink.dll.
*/
type PFN_HlinkCreateShortcutFromString func(grfHLSHORTCUTF uint32, pwzTarget *PWSTRElement, pwzLocation *PWSTRElement, pwzDir *PWSTRElement, pwzFileName *PWSTRElement, ppwzShortcutFile **PWSTRElement, dwReserved uint32) HRESULT

/*
PFN_HlinkResolveShortcut maps to HlinkResolveShortcut in hlink.dll.
*/
type PFN_HlinkResolveShortcut func(pwzShortcutFileName *PWSTRElement, pihlsite *IHlinkSite, dwSiteData uint32, piunkOuter *IUnknown, riid *Guid, ppvObj *uintptr) HRESULT

/*
PFN_HlinkResolveShortcutToMoniker maps to HlinkResolveShortcutToMoniker in hlink.dll.
*/
type PFN_HlinkResolveShortcutToMoniker func(pwzShortcutFileName *PWSTRElement, ppimkTarget **IMoniker, ppwzLocation **PWSTRElement) HRESULT

/*
PFN_HlinkResolveShortcutToString maps to HlinkResolveShortcutToString in hlink.dll.
*/
type PFN_HlinkResolveShortcutToString func(pwzShortcutFileName *PWSTRElement, ppwzTarget **PWSTRElement, ppwzLocation **PWSTRElement) HRESULT

/*
PFN_HlinkIsShortcut maps to HlinkIsShortcut in hlink.dll.
*/
type PFN_HlinkIsShortcut func(pwzFileName *PWSTRElement) HRESULT

/*
PFN_HlinkGetValueFromParams maps to HlinkGetValueFromParams in hlink.dll.
*/
type PFN_HlinkGetValueFromParams func(pwzParams *PWSTRElement, pwzName *PWSTRElement, ppwzValue **PWSTRElement) HRESULT

/*
PFN_HlinkTranslateURL maps to HlinkTranslateURL in hlink.dll.
*/
type PFN_HlinkTranslateURL func(pwzURL *PWSTRElement, grfFlags uint32, ppwzTranslatedURL **PWSTRElement) HRESULT
