//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_PeerFreeData maps to PeerFreeData in p2p.dll.
*/
type PFN_PeerFreeData func(pvData uintptr)

/*
PFN_PeerGetItemCount maps to PeerGetItemCount in p2p.dll.
*/
type PFN_PeerGetItemCount func(hPeerEnum uintptr, pCount *uint32) HRESULT

/*
PFN_PeerGetNextItem maps to PeerGetNextItem in p2p.dll.
*/
type PFN_PeerGetNextItem func(hPeerEnum uintptr, pCount *uint32, pppvItems **uintptr) HRESULT

/*
PFN_PeerEndEnumeration maps to PeerEndEnumeration in p2p.dll.
*/
type PFN_PeerEndEnumeration func(hPeerEnum uintptr) HRESULT

/*
PFN_PeerGroupStartup maps to PeerGroupStartup in p2p.dll.
*/
type PFN_PeerGroupStartup func(wVersionRequested uint16, pVersionData *PEER_VERSION_DATA) HRESULT

/*
PFN_PeerGroupShutdown maps to PeerGroupShutdown in p2p.dll.
*/
type PFN_PeerGroupShutdown func() HRESULT

/*
PFN_PeerGroupCreate maps to PeerGroupCreate in p2p.dll.
*/
type PFN_PeerGroupCreate func(pProperties *PEER_GROUP_PROPERTIES, phGroup *uintptr) HRESULT

/*
PFN_PeerGroupOpen maps to PeerGroupOpen in p2p.dll.
*/
type PFN_PeerGroupOpen func(pwzIdentity *PWSTRElement, pwzGroupPeerName *PWSTRElement, pwzCloud *PWSTRElement, phGroup *uintptr) HRESULT

/*
PFN_PeerGroupJoin maps to PeerGroupJoin in p2p.dll.
*/
type PFN_PeerGroupJoin func(pwzIdentity *PWSTRElement, pwzInvitation *PWSTRElement, pwzCloud *PWSTRElement, phGroup *uintptr) HRESULT

/*
PFN_PeerGroupPasswordJoin maps to PeerGroupPasswordJoin in p2p.dll.
*/
type PFN_PeerGroupPasswordJoin func(pwzIdentity *PWSTRElement, pwzInvitation *PWSTRElement, pwzPassword *PWSTRElement, pwzCloud *PWSTRElement, phGroup *uintptr) HRESULT

/*
PFN_PeerGroupConnect maps to PeerGroupConnect in p2p.dll.
*/
type PFN_PeerGroupConnect func(hGroup uintptr) HRESULT

/*
PFN_PeerGroupConnectByAddress maps to PeerGroupConnectByAddress in p2p.dll.
*/
type PFN_PeerGroupConnectByAddress func(hGroup uintptr, cAddresses uint32, pAddresses *PEER_ADDRESS) HRESULT

/*
PFN_PeerGroupClose maps to PeerGroupClose in p2p.dll.
*/
type PFN_PeerGroupClose func(hGroup uintptr) HRESULT

/*
PFN_PeerGroupDelete maps to PeerGroupDelete in p2p.dll.
*/
type PFN_PeerGroupDelete func(pwzIdentity *PWSTRElement, pwzGroupPeerName *PWSTRElement) HRESULT

/*
PFN_PeerGroupCreateInvitation maps to PeerGroupCreateInvitation in p2p.dll.
*/
type PFN_PeerGroupCreateInvitation func(hGroup uintptr, pwzIdentityInfo *PWSTRElement, pftExpiration *FILETIME, cRoles uint32, pRoles *Guid, ppwzInvitation **PWSTRElement) HRESULT

/*
PFN_PeerGroupCreatePasswordInvitation maps to PeerGroupCreatePasswordInvitation in p2p.dll.
*/
type PFN_PeerGroupCreatePasswordInvitation func(hGroup uintptr, ppwzInvitation **PWSTRElement) HRESULT

/*
PFN_PeerGroupParseInvitation maps to PeerGroupParseInvitation in p2p.dll.
*/
type PFN_PeerGroupParseInvitation func(pwzInvitation *PWSTRElement, ppInvitationInfo **PEER_INVITATION_INFO) HRESULT

/*
PFN_PeerGroupGetStatus maps to PeerGroupGetStatus in p2p.dll.
*/
type PFN_PeerGroupGetStatus func(hGroup uintptr, pdwStatus *uint32) HRESULT

/*
PFN_PeerGroupGetProperties maps to PeerGroupGetProperties in p2p.dll.
*/
type PFN_PeerGroupGetProperties func(hGroup uintptr, ppProperties **PEER_GROUP_PROPERTIES) HRESULT

/*
PFN_PeerGroupSetProperties maps to PeerGroupSetProperties in p2p.dll.
*/
type PFN_PeerGroupSetProperties func(hGroup uintptr, pProperties *PEER_GROUP_PROPERTIES) HRESULT

/*
PFN_PeerGroupEnumMembers maps to PeerGroupEnumMembers in p2p.dll.
*/
type PFN_PeerGroupEnumMembers func(hGroup uintptr, dwFlags uint32, pwzIdentity *PWSTRElement, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerGroupOpenDirectConnection maps to PeerGroupOpenDirectConnection in p2p.dll.
*/
type PFN_PeerGroupOpenDirectConnection func(hGroup uintptr, pwzIdentity *PWSTRElement, pAddress *PEER_ADDRESS, pullConnectionId *uint64) HRESULT

/*
PFN_PeerGroupCloseDirectConnection maps to PeerGroupCloseDirectConnection in p2p.dll.
*/
type PFN_PeerGroupCloseDirectConnection func(hGroup uintptr, ullConnectionId uint64) HRESULT

/*
PFN_PeerGroupEnumConnections maps to PeerGroupEnumConnections in p2p.dll.
*/
type PFN_PeerGroupEnumConnections func(hGroup uintptr, dwFlags uint32, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerGroupSendData maps to PeerGroupSendData in p2p.dll.
*/
type PFN_PeerGroupSendData func(hGroup uintptr, ullConnectionId uint64, pType *Guid, cbData uint32, pvData uintptr) HRESULT

/*
PFN_PeerGroupRegisterEvent maps to PeerGroupRegisterEvent in p2p.dll.
*/
type PFN_PeerGroupRegisterEvent func(hGroup uintptr, hEvent HANDLE, cEventRegistration uint32, pEventRegistrations *PEER_GROUP_EVENT_REGISTRATION, phPeerEvent *uintptr) HRESULT

/*
PFN_PeerGroupUnregisterEvent maps to PeerGroupUnregisterEvent in p2p.dll.
*/
type PFN_PeerGroupUnregisterEvent func(hPeerEvent uintptr) HRESULT

/*
PFN_PeerGroupGetEventData maps to PeerGroupGetEventData in p2p.dll.
*/
type PFN_PeerGroupGetEventData func(hPeerEvent uintptr, ppEventData **PEER_GROUP_EVENT_DATA) HRESULT

/*
PFN_PeerGroupGetRecord maps to PeerGroupGetRecord in p2p.dll.
*/
type PFN_PeerGroupGetRecord func(hGroup uintptr, pRecordId *Guid, ppRecord **PEER_RECORD) HRESULT

/*
PFN_PeerGroupAddRecord maps to PeerGroupAddRecord in p2p.dll.
*/
type PFN_PeerGroupAddRecord func(hGroup uintptr, pRecord *PEER_RECORD, pRecordId *Guid) HRESULT

/*
PFN_PeerGroupUpdateRecord maps to PeerGroupUpdateRecord in p2p.dll.
*/
type PFN_PeerGroupUpdateRecord func(hGroup uintptr, pRecord *PEER_RECORD) HRESULT

/*
PFN_PeerGroupDeleteRecord maps to PeerGroupDeleteRecord in p2p.dll.
*/
type PFN_PeerGroupDeleteRecord func(hGroup uintptr, pRecordId *Guid) HRESULT

/*
PFN_PeerGroupEnumRecords maps to PeerGroupEnumRecords in p2p.dll.
*/
type PFN_PeerGroupEnumRecords func(hGroup uintptr, pRecordType *Guid, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerGroupSearchRecords maps to PeerGroupSearchRecords in p2p.dll.
*/
type PFN_PeerGroupSearchRecords func(hGroup uintptr, pwzCriteria *PWSTRElement, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerGroupExportDatabase maps to PeerGroupExportDatabase in p2p.dll.
*/
type PFN_PeerGroupExportDatabase func(hGroup uintptr, pwzFilePath *PWSTRElement) HRESULT

/*
PFN_PeerGroupImportDatabase maps to PeerGroupImportDatabase in p2p.dll.
*/
type PFN_PeerGroupImportDatabase func(hGroup uintptr, pwzFilePath *PWSTRElement) HRESULT

/*
PFN_PeerGroupIssueCredentials maps to PeerGroupIssueCredentials in p2p.dll.
*/
type PFN_PeerGroupIssueCredentials func(hGroup uintptr, pwzSubjectIdentity *PWSTRElement, pCredentialInfo *PEER_CREDENTIAL_INFO, dwFlags uint32, ppwzInvitation **PWSTRElement) HRESULT

/*
PFN_PeerGroupExportConfig maps to PeerGroupExportConfig in p2p.dll.
*/
type PFN_PeerGroupExportConfig func(hGroup uintptr, pwzPassword *PWSTRElement, ppwzXML **PWSTRElement) HRESULT

/*
PFN_PeerGroupImportConfig maps to PeerGroupImportConfig in p2p.dll.
*/
type PFN_PeerGroupImportConfig func(pwzXML *PWSTRElement, pwzPassword *PWSTRElement, fOverwrite BOOL, ppwzIdentity **PWSTRElement, ppwzGroup **PWSTRElement) HRESULT

/*
PFN_PeerGroupPeerTimeToUniversalTime maps to PeerGroupPeerTimeToUniversalTime in p2p.dll.
*/
type PFN_PeerGroupPeerTimeToUniversalTime func(hGroup uintptr, pftPeerTime *FILETIME, pftUniversalTime *FILETIME) HRESULT

/*
PFN_PeerGroupUniversalTimeToPeerTime maps to PeerGroupUniversalTimeToPeerTime in p2p.dll.
*/
type PFN_PeerGroupUniversalTimeToPeerTime func(hGroup uintptr, pftUniversalTime *FILETIME, pftPeerTime *FILETIME) HRESULT

/*
PFN_PeerGroupResumePasswordAuthentication maps to PeerGroupResumePasswordAuthentication in p2p.dll.
*/
type PFN_PeerGroupResumePasswordAuthentication func(hGroup uintptr, hPeerEventHandle uintptr) HRESULT

/*
PFN_PeerIdentityCreate maps to PeerIdentityCreate in p2p.dll.
*/
type PFN_PeerIdentityCreate func(pwzClassifier *PWSTRElement, pwzFriendlyName *PWSTRElement, hCryptProv uintptr, ppwzIdentity **PWSTRElement) HRESULT

/*
PFN_PeerIdentityGetFriendlyName maps to PeerIdentityGetFriendlyName in p2p.dll.
*/
type PFN_PeerIdentityGetFriendlyName func(pwzIdentity *PWSTRElement, ppwzFriendlyName **PWSTRElement) HRESULT

/*
PFN_PeerIdentitySetFriendlyName maps to PeerIdentitySetFriendlyName in p2p.dll.
*/
type PFN_PeerIdentitySetFriendlyName func(pwzIdentity *PWSTRElement, pwzFriendlyName *PWSTRElement) HRESULT

/*
PFN_PeerIdentityGetCryptKey maps to PeerIdentityGetCryptKey in p2p.dll.
*/
type PFN_PeerIdentityGetCryptKey func(pwzIdentity *PWSTRElement, phCryptProv *uintptr) HRESULT

/*
PFN_PeerIdentityDelete maps to PeerIdentityDelete in p2p.dll.
*/
type PFN_PeerIdentityDelete func(pwzIdentity *PWSTRElement) HRESULT

/*
PFN_PeerEnumIdentities maps to PeerEnumIdentities in p2p.dll.
*/
type PFN_PeerEnumIdentities func(phPeerEnum *uintptr) HRESULT

/*
PFN_PeerEnumGroups maps to PeerEnumGroups in p2p.dll.
*/
type PFN_PeerEnumGroups func(pwzIdentity *PWSTRElement, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCreatePeerName maps to PeerCreatePeerName in p2p.dll.
*/
type PFN_PeerCreatePeerName func(pwzIdentity *PWSTRElement, pwzClassifier *PWSTRElement, ppwzPeerName **PWSTRElement) HRESULT

/*
PFN_PeerIdentityGetXML maps to PeerIdentityGetXML in p2p.dll.
*/
type PFN_PeerIdentityGetXML func(pwzIdentity *PWSTRElement, ppwzIdentityXML **PWSTRElement) HRESULT

/*
PFN_PeerIdentityExport maps to PeerIdentityExport in p2p.dll.
*/
type PFN_PeerIdentityExport func(pwzIdentity *PWSTRElement, pwzPassword *PWSTRElement, ppwzExportXML **PWSTRElement) HRESULT

/*
PFN_PeerIdentityImport maps to PeerIdentityImport in p2p.dll.
*/
type PFN_PeerIdentityImport func(pwzImportXML *PWSTRElement, pwzPassword *PWSTRElement, ppwzIdentity **PWSTRElement) HRESULT

/*
PFN_PeerIdentityGetDefault maps to PeerIdentityGetDefault in p2p.dll.
*/
type PFN_PeerIdentityGetDefault func(ppwzPeerName **PWSTRElement) HRESULT

/*
PFN_PeerCollabStartup maps to PeerCollabStartup in p2p.dll.
*/
type PFN_PeerCollabStartup func(wVersionRequested uint16) HRESULT

/*
PFN_PeerCollabShutdown maps to PeerCollabShutdown in p2p.dll.
*/
type PFN_PeerCollabShutdown func() HRESULT

/*
PFN_PeerCollabSignin maps to PeerCollabSignin in p2p.dll.
*/
type PFN_PeerCollabSignin func(hwndParent HWND, dwSigninOptions uint32) HRESULT

/*
PFN_PeerCollabSignout maps to PeerCollabSignout in p2p.dll.
*/
type PFN_PeerCollabSignout func(dwSigninOptions uint32) HRESULT

/*
PFN_PeerCollabGetSigninOptions maps to PeerCollabGetSigninOptions in p2p.dll.
*/
type PFN_PeerCollabGetSigninOptions func(pdwSigninOptions *uint32) HRESULT

/*
PFN_PeerCollabAsyncInviteContact maps to PeerCollabAsyncInviteContact in p2p.dll.
*/
type PFN_PeerCollabAsyncInviteContact func(pcContact *PEER_CONTACT, pcEndpoint *PEER_ENDPOINT, pcInvitation *PEER_INVITATION, hEvent HANDLE, phInvitation *HANDLE) HRESULT

/*
PFN_PeerCollabGetInvitationResponse maps to PeerCollabGetInvitationResponse in p2p.dll.
*/
type PFN_PeerCollabGetInvitationResponse func(hInvitation HANDLE, ppInvitationResponse **PEER_INVITATION_RESPONSE) HRESULT

/*
PFN_PeerCollabCancelInvitation maps to PeerCollabCancelInvitation in p2p.dll.
*/
type PFN_PeerCollabCancelInvitation func(hInvitation HANDLE) HRESULT

/*
PFN_PeerCollabCloseHandle maps to PeerCollabCloseHandle in p2p.dll.
*/
type PFN_PeerCollabCloseHandle func(hInvitation HANDLE) HRESULT

/*
PFN_PeerCollabInviteContact maps to PeerCollabInviteContact in p2p.dll.
*/
type PFN_PeerCollabInviteContact func(pcContact *PEER_CONTACT, pcEndpoint *PEER_ENDPOINT, pcInvitation *PEER_INVITATION, ppResponse **PEER_INVITATION_RESPONSE) HRESULT

/*
PFN_PeerCollabAsyncInviteEndpoint maps to PeerCollabAsyncInviteEndpoint in p2p.dll.
*/
type PFN_PeerCollabAsyncInviteEndpoint func(pcEndpoint *PEER_ENDPOINT, pcInvitation *PEER_INVITATION, hEvent HANDLE, phInvitation *HANDLE) HRESULT

/*
PFN_PeerCollabInviteEndpoint maps to PeerCollabInviteEndpoint in p2p.dll.
*/
type PFN_PeerCollabInviteEndpoint func(pcEndpoint *PEER_ENDPOINT, pcInvitation *PEER_INVITATION, ppResponse **PEER_INVITATION_RESPONSE) HRESULT

/*
PFN_PeerCollabGetAppLaunchInfo maps to PeerCollabGetAppLaunchInfo in p2p.dll.
*/
type PFN_PeerCollabGetAppLaunchInfo func(ppLaunchInfo **PEER_APP_LAUNCH_INFO) HRESULT

/*
PFN_PeerCollabRegisterApplication maps to PeerCollabRegisterApplication in p2p.dll.
*/
type PFN_PeerCollabRegisterApplication func(pcApplication *PEER_APPLICATION_REGISTRATION_INFO, registrationType PEER_APPLICATION_REGISTRATION_TYPE) HRESULT

/*
PFN_PeerCollabUnregisterApplication maps to PeerCollabUnregisterApplication in p2p.dll.
*/
type PFN_PeerCollabUnregisterApplication func(pApplicationId *Guid, registrationType PEER_APPLICATION_REGISTRATION_TYPE) HRESULT

/*
PFN_PeerCollabGetApplicationRegistrationInfo maps to PeerCollabGetApplicationRegistrationInfo in p2p.dll.
*/
type PFN_PeerCollabGetApplicationRegistrationInfo func(pApplicationId *Guid, registrationType PEER_APPLICATION_REGISTRATION_TYPE, ppApplication **PEER_APPLICATION_REGISTRATION_INFO) HRESULT

/*
PFN_PeerCollabEnumApplicationRegistrationInfo maps to PeerCollabEnumApplicationRegistrationInfo in p2p.dll.
*/
type PFN_PeerCollabEnumApplicationRegistrationInfo func(registrationType PEER_APPLICATION_REGISTRATION_TYPE, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCollabGetPresenceInfo maps to PeerCollabGetPresenceInfo in p2p.dll.
*/
type PFN_PeerCollabGetPresenceInfo func(pcEndpoint *PEER_ENDPOINT, ppPresenceInfo **PEER_PRESENCE_INFO) HRESULT

/*
PFN_PeerCollabEnumApplications maps to PeerCollabEnumApplications in p2p.dll.
*/
type PFN_PeerCollabEnumApplications func(pcEndpoint *PEER_ENDPOINT, pApplicationId *Guid, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCollabEnumObjects maps to PeerCollabEnumObjects in p2p.dll.
*/
type PFN_PeerCollabEnumObjects func(pcEndpoint *PEER_ENDPOINT, pObjectId *Guid, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCollabEnumEndpoints maps to PeerCollabEnumEndpoints in p2p.dll.
*/
type PFN_PeerCollabEnumEndpoints func(pcContact *PEER_CONTACT, phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCollabRefreshEndpointData maps to PeerCollabRefreshEndpointData in p2p.dll.
*/
type PFN_PeerCollabRefreshEndpointData func(pcEndpoint *PEER_ENDPOINT) HRESULT

/*
PFN_PeerCollabDeleteEndpointData maps to PeerCollabDeleteEndpointData in p2p.dll.
*/
type PFN_PeerCollabDeleteEndpointData func(pcEndpoint *PEER_ENDPOINT) HRESULT

/*
PFN_PeerCollabQueryContactData maps to PeerCollabQueryContactData in p2p.dll.
*/
type PFN_PeerCollabQueryContactData func(pcEndpoint *PEER_ENDPOINT, ppwzContactData **PWSTRElement) HRESULT

/*
PFN_PeerCollabSubscribeEndpointData maps to PeerCollabSubscribeEndpointData in p2p.dll.
*/
type PFN_PeerCollabSubscribeEndpointData func(pcEndpoint *PEER_ENDPOINT) HRESULT

/*
PFN_PeerCollabUnsubscribeEndpointData maps to PeerCollabUnsubscribeEndpointData in p2p.dll.
*/
type PFN_PeerCollabUnsubscribeEndpointData func(pcEndpoint *PEER_ENDPOINT) HRESULT

/*
PFN_PeerCollabSetPresenceInfo maps to PeerCollabSetPresenceInfo in p2p.dll.
*/
type PFN_PeerCollabSetPresenceInfo func(pcPresenceInfo *PEER_PRESENCE_INFO) HRESULT

/*
PFN_PeerCollabGetEndpointName maps to PeerCollabGetEndpointName in p2p.dll.
*/
type PFN_PeerCollabGetEndpointName func(ppwzEndpointName **PWSTRElement) HRESULT

/*
PFN_PeerCollabSetEndpointName maps to PeerCollabSetEndpointName in p2p.dll.
*/
type PFN_PeerCollabSetEndpointName func(pwzEndpointName *PWSTRElement) HRESULT

/*
PFN_PeerCollabSetObject maps to PeerCollabSetObject in p2p.dll.
*/
type PFN_PeerCollabSetObject func(pcObject *PEER_OBJECT) HRESULT

/*
PFN_PeerCollabDeleteObject maps to PeerCollabDeleteObject in p2p.dll.
*/
type PFN_PeerCollabDeleteObject func(pObjectId *Guid) HRESULT

/*
PFN_PeerCollabRegisterEvent maps to PeerCollabRegisterEvent in p2p.dll.
*/
type PFN_PeerCollabRegisterEvent func(hEvent HANDLE, cEventRegistration uint32, pEventRegistrations *PEER_COLLAB_EVENT_REGISTRATION, phPeerEvent *uintptr) HRESULT

/*
PFN_PeerCollabGetEventData maps to PeerCollabGetEventData in p2p.dll.
*/
type PFN_PeerCollabGetEventData func(hPeerEvent uintptr, ppEventData **PEER_COLLAB_EVENT_DATA) HRESULT

/*
PFN_PeerCollabUnregisterEvent maps to PeerCollabUnregisterEvent in p2p.dll.
*/
type PFN_PeerCollabUnregisterEvent func(hPeerEvent uintptr) HRESULT

/*
PFN_PeerCollabEnumPeopleNearMe maps to PeerCollabEnumPeopleNearMe in p2p.dll.
*/
type PFN_PeerCollabEnumPeopleNearMe func(phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCollabAddContact maps to PeerCollabAddContact in p2p.dll.
*/
type PFN_PeerCollabAddContact func(pwzContactData *PWSTRElement, ppContact **PEER_CONTACT) HRESULT

/*
PFN_PeerCollabDeleteContact maps to PeerCollabDeleteContact in p2p.dll.
*/
type PFN_PeerCollabDeleteContact func(pwzPeerName *PWSTRElement) HRESULT

/*
PFN_PeerCollabGetContact maps to PeerCollabGetContact in p2p.dll.
*/
type PFN_PeerCollabGetContact func(pwzPeerName *PWSTRElement, ppContact **PEER_CONTACT) HRESULT

/*
PFN_PeerCollabUpdateContact maps to PeerCollabUpdateContact in p2p.dll.
*/
type PFN_PeerCollabUpdateContact func(pContact *PEER_CONTACT) HRESULT

/*
PFN_PeerCollabEnumContacts maps to PeerCollabEnumContacts in p2p.dll.
*/
type PFN_PeerCollabEnumContacts func(phPeerEnum *uintptr) HRESULT

/*
PFN_PeerCollabExportContact maps to PeerCollabExportContact in p2p.dll.
*/
type PFN_PeerCollabExportContact func(pwzPeerName *PWSTRElement, ppwzContactData **PWSTRElement) HRESULT

/*
PFN_PeerCollabParseContact maps to PeerCollabParseContact in p2p.dll.
*/
type PFN_PeerCollabParseContact func(pwzContactData *PWSTRElement, ppContact **PEER_CONTACT) HRESULT

/*
PFN_PeerNameToPeerHostName maps to PeerNameToPeerHostName in p2p.dll.
*/
type PFN_PeerNameToPeerHostName func(pwzPeerName *PWSTRElement, ppwzHostName **PWSTRElement) HRESULT

/*
PFN_PeerHostNameToPeerName maps to PeerHostNameToPeerName in p2p.dll.
*/
type PFN_PeerHostNameToPeerName func(pwzHostName *PWSTRElement, ppwzPeerName **PWSTRElement) HRESULT

/*
PFN_PeerPnrpStartup maps to PeerPnrpStartup in p2p.dll.
*/
type PFN_PeerPnrpStartup func(wVersionRequested uint16) HRESULT

/*
PFN_PeerPnrpShutdown maps to PeerPnrpShutdown in p2p.dll.
*/
type PFN_PeerPnrpShutdown func() HRESULT

/*
PFN_PeerPnrpRegister maps to PeerPnrpRegister in p2p.dll.
*/
type PFN_PeerPnrpRegister func(pcwzPeerName *PWSTRElement, pRegistrationInfo *PEER_PNRP_REGISTRATION_INFO, phRegistration *uintptr) HRESULT

/*
PFN_PeerPnrpUpdateRegistration maps to PeerPnrpUpdateRegistration in p2p.dll.
*/
type PFN_PeerPnrpUpdateRegistration func(hRegistration uintptr, pRegistrationInfo *PEER_PNRP_REGISTRATION_INFO) HRESULT

/*
PFN_PeerPnrpUnregister maps to PeerPnrpUnregister in p2p.dll.
*/
type PFN_PeerPnrpUnregister func(hRegistration uintptr) HRESULT

/*
PFN_PeerPnrpResolve maps to PeerPnrpResolve in p2p.dll.
*/
type PFN_PeerPnrpResolve func(pcwzPeerName *PWSTRElement, pcwzCloudName *PWSTRElement, pcEndpoints *uint32, ppEndpoints **PEER_PNRP_ENDPOINT_INFO) HRESULT

/*
PFN_PeerPnrpStartResolve maps to PeerPnrpStartResolve in p2p.dll.
*/
type PFN_PeerPnrpStartResolve func(pcwzPeerName *PWSTRElement, pcwzCloudName *PWSTRElement, cMaxEndpoints uint32, hEvent HANDLE, phResolve *uintptr) HRESULT

/*
PFN_PeerPnrpGetCloudInfo maps to PeerPnrpGetCloudInfo in p2p.dll.
*/
type PFN_PeerPnrpGetCloudInfo func(pcNumClouds *uint32, ppCloudInfo **PEER_PNRP_CLOUD_INFO) HRESULT

/*
PFN_PeerPnrpGetEndpoint maps to PeerPnrpGetEndpoint in p2p.dll.
*/
type PFN_PeerPnrpGetEndpoint func(hResolve uintptr, ppEndpoint **PEER_PNRP_ENDPOINT_INFO) HRESULT

/*
PFN_PeerPnrpEndResolve maps to PeerPnrpEndResolve in p2p.dll.
*/
type PFN_PeerPnrpEndResolve func(hResolve uintptr) HRESULT
