//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:43 CEST

package bindings

/*
FDICREATE_CPU_TYPE is generated from Windows.Win32 metadata.
*/
type FDICREATE_CPU_TYPE int32

const (
	/*
		CpuUNKNOWN from Windows.Win32 metadata.
	*/
	CpuUNKNOWN FDICREATE_CPU_TYPE = -1

	/*
		Cpu80286 from Windows.Win32 metadata.
	*/
	Cpu80286 FDICREATE_CPU_TYPE = 0x0

	/*
		Cpu80386 from Windows.Win32 metadata.
	*/
	Cpu80386 FDICREATE_CPU_TYPE = 0x1
)

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	INCLUDED_FCI             uint32
	_A_NAME_IS_UTF           uint32
	_A_EXEC                  uint32
	StatusFile               uint32
	StatusFolder             uint32
	StatusCabinet            uint32
	INCLUDED_TYPES_FCI_FDI   uint32
	CB_MAX_DISK              int32
	CB_MAX_FILENAME          uint32
	CB_MAX_CABINET_NAME      uint32
	CB_MAX_CAB_PATH          uint32
	CB_MAX_DISK_NAME         uint32
	TcompMASK_TYPE           uint32
	TcompTYPE_NONE           uint32
	TcompTYPE_MSZIP          uint32
	TcompTYPE_QUANTUM        uint32
	TcompTYPE_LZX            uint32
	TcompBAD                 uint32
	TcompMASK_LZX_WINDOW     uint32
	TcompLZX_WINDOW_LO       uint32
	TcompLZX_WINDOW_HI       uint32
	TcompSHIFT_LZX_WINDOW    uint32
	TcompMASK_QUANTUM_LEVEL  uint32
	TcompQUANTUM_LEVEL_LO    uint32
	TcompQUANTUM_LEVEL_HI    uint32
	TcompSHIFT_QUANTUM_LEVEL uint32
	TcompMASK_QUANTUM_MEM    uint32
	TcompQUANTUM_MEM_LO      uint32
	TcompQUANTUM_MEM_HI      uint32
	TcompSHIFT_QUANTUM_MEM   uint32
	TcompMASK_RESERVED       uint32
	INCLUDED_FDI             uint32
}

/*
FDISPILLFILE is generated from Windows.Win32 metadata.
*/
type FDISPILLFILE struct {
	Ach    [2]CHAR
	CbFile int32
}

/*
ERF is generated from Windows.Win32 metadata.
*/
type ERF struct {
	ErfOper int32
	ErfType int32
	FError  BOOL
}

/*
FCIERROR is generated from Windows.Win32 metadata.
*/
type FCIERROR int32

const (
	/*
		FCIERR_NONE from Windows.Win32 metadata.
	*/
	FCIERR_NONE FCIERROR = 0x0

	/*
		FCIERR_OPEN_SRC from Windows.Win32 metadata.
	*/
	FCIERR_OPEN_SRC FCIERROR = 0x1

	/*
		FCIERR_READ_SRC from Windows.Win32 metadata.
	*/
	FCIERR_READ_SRC FCIERROR = 0x2

	/*
		FCIERR_ALLOC_FAIL from Windows.Win32 metadata.
	*/
	FCIERR_ALLOC_FAIL FCIERROR = 0x3

	/*
		FCIERR_TEMP_FILE from Windows.Win32 metadata.
	*/
	FCIERR_TEMP_FILE FCIERROR = 0x4

	/*
		FCIERR_BAD_COMPR_TYPE from Windows.Win32 metadata.
	*/
	FCIERR_BAD_COMPR_TYPE FCIERROR = 0x5

	/*
		FCIERR_CAB_FILE from Windows.Win32 metadata.
	*/
	FCIERR_CAB_FILE FCIERROR = 0x6

	/*
		FCIERR_USER_ABORT from Windows.Win32 metadata.
	*/
	FCIERR_USER_ABORT FCIERROR = 0x7

	/*
		FCIERR_MCI_FAIL from Windows.Win32 metadata.
	*/
	FCIERR_MCI_FAIL FCIERROR = 0x8

	/*
		FCIERR_CAB_FORMAT_LIMIT from Windows.Win32 metadata.
	*/
	FCIERR_CAB_FORMAT_LIMIT FCIERROR = 0x9
)

/*
CCAB is generated from Windows.Win32 metadata.
*/
type CCAB struct {
	Cb                    uint32
	CbFolderThresh        uint32
	CbReserveCFHeader     uint32
	CbReserveCFFolder     uint32
	CbReserveCFData       uint32
	ICab                  int32
	IDisk                 int32
	FFailOnIncompressible int32
	SetID                 uint16
	SzDisk                [256]CHAR
	SzCab                 [256]CHAR
	SzCabPath             [256]CHAR
}

/*
PFNFCIALLOC is generated from Windows.Win32 metadata.
*/
type PFNFCIALLOC uintptr

/*
PFNFCIFREE is generated from Windows.Win32 metadata.
*/
type PFNFCIFREE uintptr

/*
PFNFCIOPEN is generated from Windows.Win32 metadata.
*/
type PFNFCIOPEN uintptr

/*
PFNFCIREAD is generated from Windows.Win32 metadata.
*/
type PFNFCIREAD uintptr

/*
PFNFCIWRITE is generated from Windows.Win32 metadata.
*/
type PFNFCIWRITE uintptr

/*
PFNFCICLOSE is generated from Windows.Win32 metadata.
*/
type PFNFCICLOSE uintptr

/*
PFNFCISEEK is generated from Windows.Win32 metadata.
*/
type PFNFCISEEK uintptr

/*
PFNFCIDELETE is generated from Windows.Win32 metadata.
*/
type PFNFCIDELETE uintptr

/*
PFNFCIGETNEXTCABINET is generated from Windows.Win32 metadata.
*/
type PFNFCIGETNEXTCABINET uintptr

/*
PFNFCIFILEPLACED is generated from Windows.Win32 metadata.
*/
type PFNFCIFILEPLACED uintptr

/*
PFNFCIGETOPENINFO is generated from Windows.Win32 metadata.
*/
type PFNFCIGETOPENINFO uintptr

/*
PFNFCISTATUS is generated from Windows.Win32 metadata.
*/
type PFNFCISTATUS uintptr

/*
PFNFCIGETTEMPFILE is generated from Windows.Win32 metadata.
*/
type PFNFCIGETTEMPFILE uintptr

/*
FDIERROR is generated from Windows.Win32 metadata.
*/
type FDIERROR int32

const (
	/*
		FDIERROR_NONE from Windows.Win32 metadata.
	*/
	FDIERROR_NONE FDIERROR = 0x0

	/*
		FDIERROR_CABINET_NOT_FOUND from Windows.Win32 metadata.
	*/
	FDIERROR_CABINET_NOT_FOUND FDIERROR = 0x1

	/*
		FDIERROR_NOT_A_CABINET from Windows.Win32 metadata.
	*/
	FDIERROR_NOT_A_CABINET FDIERROR = 0x2

	/*
		FDIERROR_UNKNOWN_CABINET_VERSION from Windows.Win32 metadata.
	*/
	FDIERROR_UNKNOWN_CABINET_VERSION FDIERROR = 0x3

	/*
		FDIERROR_CORRUPT_CABINET from Windows.Win32 metadata.
	*/
	FDIERROR_CORRUPT_CABINET FDIERROR = 0x4

	/*
		FDIERROR_ALLOC_FAIL from Windows.Win32 metadata.
	*/
	FDIERROR_ALLOC_FAIL FDIERROR = 0x5

	/*
		FDIERROR_BAD_COMPR_TYPE from Windows.Win32 metadata.
	*/
	FDIERROR_BAD_COMPR_TYPE FDIERROR = 0x6

	/*
		FDIERROR_MDI_FAIL from Windows.Win32 metadata.
	*/
	FDIERROR_MDI_FAIL FDIERROR = 0x7

	/*
		FDIERROR_TARGET_FILE from Windows.Win32 metadata.
	*/
	FDIERROR_TARGET_FILE FDIERROR = 0x8

	/*
		FDIERROR_RESERVE_MISMATCH from Windows.Win32 metadata.
	*/
	FDIERROR_RESERVE_MISMATCH FDIERROR = 0x9

	/*
		FDIERROR_WRONG_CABINET from Windows.Win32 metadata.
	*/
	FDIERROR_WRONG_CABINET FDIERROR = 0xa

	/*
		FDIERROR_USER_ABORT from Windows.Win32 metadata.
	*/
	FDIERROR_USER_ABORT FDIERROR = 0xb

	/*
		FDIERROR_EOF from Windows.Win32 metadata.
	*/
	FDIERROR_EOF FDIERROR = 0xc
)

/*
FDICABINETINFO is generated from Windows.Win32 metadata.
*/
type FDICABINETINFO struct {
	CbCabinet int32
	CFolders  uint16
	CFiles    uint16
	SetID     uint16
	ICabinet  uint16
	FReserve  BOOL
	Hasprev   BOOL
	Hasnext   BOOL
}

/*
FDIDECRYPTTYPE is generated from Windows.Win32 metadata.
*/
type FDIDECRYPTTYPE int32

const (
	/*
		FdidtNEW_CABINET from Windows.Win32 metadata.
	*/
	FdidtNEW_CABINET FDIDECRYPTTYPE = 0x0

	/*
		FdidtNEW_FOLDER from Windows.Win32 metadata.
	*/
	FdidtNEW_FOLDER FDIDECRYPTTYPE = 0x1

	/*
		FdidtDECRYPT from Windows.Win32 metadata.
	*/
	FdidtDECRYPT FDIDECRYPTTYPE = 0x2
)

/*
FDIDECRYPT is generated from Windows.Win32 metadata.
*/
type FDIDECRYPT struct {
	Fdidt           FDIDECRYPTTYPE
	PvUser          uintptr
	PHeaderReserve  uintptr
	CbHeaderReserve uint16
	SetID           uint16
	ICabinet        int32
}

/*
PFNALLOC is generated from Windows.Win32 metadata.
*/
type PFNALLOC uintptr

/*
PFNFREE is generated from Windows.Win32 metadata.
*/
type PFNFREE uintptr

/*
PFNOPEN is generated from Windows.Win32 metadata.
*/
type PFNOPEN uintptr

/*
PFNREAD is generated from Windows.Win32 metadata.
*/
type PFNREAD uintptr

/*
PFNWRITE is generated from Windows.Win32 metadata.
*/
type PFNWRITE uintptr

/*
PFNCLOSE is generated from Windows.Win32 metadata.
*/
type PFNCLOSE uintptr

/*
PFNSEEK is generated from Windows.Win32 metadata.
*/
type PFNSEEK uintptr

/*
PFNFDIDECRYPT is generated from Windows.Win32 metadata.
*/
type PFNFDIDECRYPT uintptr

/*
FDINOTIFICATION is generated from Windows.Win32 metadata.
*/
type FDINOTIFICATION struct {
	Cb       int32
	Psz1     *PSTRElement
	Psz2     *PSTRElement
	Psz3     *PSTRElement
	Pv       uintptr
	Hf       uintptr
	Date     uint16
	Time     uint16
	Attribs  uint16
	SetID    uint16
	ICabinet uint16
	IFolder  uint16
	Fdie     FDIERROR
}

/*
FDINOTIFICATIONTYPE is generated from Windows.Win32 metadata.
*/
type FDINOTIFICATIONTYPE int32

const (
	/*
		FdintCABINET_INFO from Windows.Win32 metadata.
	*/
	FdintCABINET_INFO FDINOTIFICATIONTYPE = 0x0

	/*
		FdintPARTIAL_FILE from Windows.Win32 metadata.
	*/
	FdintPARTIAL_FILE FDINOTIFICATIONTYPE = 0x1

	/*
		FdintCOPY_FILE from Windows.Win32 metadata.
	*/
	FdintCOPY_FILE FDINOTIFICATIONTYPE = 0x2

	/*
		FdintCLOSE_FILE_INFO from Windows.Win32 metadata.
	*/
	FdintCLOSE_FILE_INFO FDINOTIFICATIONTYPE = 0x3

	/*
		FdintNEXT_CABINET from Windows.Win32 metadata.
	*/
	FdintNEXT_CABINET FDINOTIFICATIONTYPE = 0x4

	/*
		FdintENUMERATE from Windows.Win32 metadata.
	*/
	FdintENUMERATE FDINOTIFICATIONTYPE = 0x5
)

/*
PFNFDINOTIFY is generated from Windows.Win32 metadata.
*/
type PFNFDINOTIFY uintptr

/*
FDISPILLFILE is generated from Windows.Win32 metadata.
*/
type FDISPILLFILE struct {
	Ach    [2]CHAR
	CbFile int32
}
