//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_CapCreateCaptureWindowA maps to CapCreateCaptureWindowA in avicap32.dll.
*/
type PFN_CapCreateCaptureWindowA func(lpszWindowName *PSTRElement, dwStyle uint32, x int32, y int32, nWidth int32, nHeight int32, hwndParent HWND, nID int32) HWND

/*
PFN_CapGetDriverDescriptionA maps to CapGetDriverDescriptionA in avicap32.dll.
*/
type PFN_CapGetDriverDescriptionA func(wDriverIndex uint32, lpszName *PSTRElement, cbName int32, lpszVer *PSTRElement, cbVer int32) BOOL

/*
PFN_CapCreateCaptureWindowW maps to CapCreateCaptureWindowW in avicap32.dll.
*/
type PFN_CapCreateCaptureWindowW func(lpszWindowName *PWSTRElement, dwStyle uint32, x int32, y int32, nWidth int32, nHeight int32, hwndParent HWND, nID int32) HWND

/*
PFN_CapGetDriverDescriptionW maps to CapGetDriverDescriptionW in avicap32.dll.
*/
type PFN_CapGetDriverDescriptionW func(wDriverIndex uint32, lpszName *PWSTRElement, cbName int32, lpszVer *PWSTRElement, cbVer int32) BOOL
