//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_TraceRegisterExA maps to TraceRegisterExA in rtutils.dll.
*/
type PFN_TraceRegisterExA func(lpszCallerName *PSTRElement, dwFlags uint32) uint32

/*
PFN_TraceDeregisterA maps to TraceDeregisterA in rtutils.dll.
*/
type PFN_TraceDeregisterA func(dwTraceID uint32) uint32

/*
PFN_TraceDeregisterExA maps to TraceDeregisterExA in rtutils.dll.
*/
type PFN_TraceDeregisterExA func(dwTraceID uint32, dwFlags uint32) uint32

/*
PFN_TraceGetConsoleA maps to TraceGetConsoleA in rtutils.dll.
*/
type PFN_TraceGetConsoleA func(dwTraceID uint32, lphConsole *HANDLE) uint32

/*
PFN_TracePrintfA maps to TracePrintfA in rtutils.dll.
*/
type PFN_TracePrintfA func(dwTraceID uint32, lpszFormat *PSTRElement) uint32

/*
PFN_TracePrintfExA maps to TracePrintfExA in rtutils.dll.
*/
type PFN_TracePrintfExA func(dwTraceID uint32, dwFlags uint32, lpszFormat *PSTRElement) uint32

/*
PFN_TraceVprintfExA maps to TraceVprintfExA in rtutils.dll.
*/
type PFN_TraceVprintfExA func(dwTraceID uint32, dwFlags uint32, lpszFormat *PSTRElement, arglist *int8) uint32

/*
PFN_TracePutsExA maps to TracePutsExA in rtutils.dll.
*/
type PFN_TracePutsExA func(dwTraceID uint32, dwFlags uint32, lpszString *PSTRElement) uint32

/*
PFN_TraceDumpExA maps to TraceDumpExA in rtutils.dll.
*/
type PFN_TraceDumpExA func(dwTraceID uint32, dwFlags uint32, lpbBytes *uint8, dwByteCount uint32, dwGroupSize uint32, bAddressPrefix BOOL, lpszPrefix *PSTRElement) uint32

/*
PFN_TraceRegisterExW maps to TraceRegisterExW in rtutils.dll.
*/
type PFN_TraceRegisterExW func(lpszCallerName *PWSTRElement, dwFlags uint32) uint32

/*
PFN_TraceDeregisterW maps to TraceDeregisterW in rtutils.dll.
*/
type PFN_TraceDeregisterW func(dwTraceID uint32) uint32

/*
PFN_TraceDeregisterExW maps to TraceDeregisterExW in rtutils.dll.
*/
type PFN_TraceDeregisterExW func(dwTraceID uint32, dwFlags uint32) uint32

/*
PFN_TraceGetConsoleW maps to TraceGetConsoleW in rtutils.dll.
*/
type PFN_TraceGetConsoleW func(dwTraceID uint32, lphConsole *HANDLE) uint32

/*
PFN_TracePrintfW maps to TracePrintfW in rtutils.dll.
*/
type PFN_TracePrintfW func(dwTraceID uint32, lpszFormat *PWSTRElement) uint32

/*
PFN_TracePrintfExW maps to TracePrintfExW in rtutils.dll.
*/
type PFN_TracePrintfExW func(dwTraceID uint32, dwFlags uint32, lpszFormat *PWSTRElement) uint32

/*
PFN_TraceVprintfExW maps to TraceVprintfExW in rtutils.dll.
*/
type PFN_TraceVprintfExW func(dwTraceID uint32, dwFlags uint32, lpszFormat *PWSTRElement, arglist *int8) uint32

/*
PFN_TracePutsExW maps to TracePutsExW in rtutils.dll.
*/
type PFN_TracePutsExW func(dwTraceID uint32, dwFlags uint32, lpszString *PWSTRElement) uint32

/*
PFN_TraceDumpExW maps to TraceDumpExW in rtutils.dll.
*/
type PFN_TraceDumpExW func(dwTraceID uint32, dwFlags uint32, lpbBytes *uint8, dwByteCount uint32, dwGroupSize uint32, bAddressPrefix BOOL, lpszPrefix *PWSTRElement) uint32

/*
PFN_LogErrorA maps to LogErrorA in rtutils.dll.
*/
type PFN_LogErrorA func(dwMessageId uint32, cNumberOfSubStrings uint32, plpwsSubStrings **PSTRElement, dwErrorCode uint32)

/*
PFN_LogEventA maps to LogEventA in rtutils.dll.
*/
type PFN_LogEventA func(wEventType uint32, dwMessageId uint32, cNumberOfSubStrings uint32, plpwsSubStrings **PSTRElement)

/*
PFN_LogErrorW maps to LogErrorW in rtutils.dll.
*/
type PFN_LogErrorW func(dwMessageId uint32, cNumberOfSubStrings uint32, plpwsSubStrings **PWSTRElement, dwErrorCode uint32)

/*
PFN_LogEventW maps to LogEventW in rtutils.dll.
*/
type PFN_LogEventW func(wEventType uint32, dwMessageId uint32, cNumberOfSubStrings uint32, plpwsSubStrings **PWSTRElement)

/*
PFN_RouterLogRegisterA maps to RouterLogRegisterA in rtutils.dll.
*/
type PFN_RouterLogRegisterA func(lpszSource *PSTRElement) HANDLE

/*
PFN_RouterLogDeregisterA maps to RouterLogDeregisterA in rtutils.dll.
*/
type PFN_RouterLogDeregisterA func(hLogHandle HANDLE)

/*
PFN_RouterLogEventA maps to RouterLogEventA in rtutils.dll.
*/
type PFN_RouterLogEventA func(hLogHandle HANDLE, dwEventType uint32, dwMessageId uint32, dwSubStringCount uint32, plpszSubStringArray **PSTRElement, dwErrorCode uint32)

/*
PFN_RouterLogEventDataA maps to RouterLogEventDataA in rtutils.dll.
*/
type PFN_RouterLogEventDataA func(hLogHandle HANDLE, dwEventType uint32, dwMessageId uint32, dwSubStringCount uint32, plpszSubStringArray **PSTRElement, dwDataBytes uint32, lpDataBytes *uint8)

/*
PFN_RouterLogEventStringA maps to RouterLogEventStringA in rtutils.dll.
*/
type PFN_RouterLogEventStringA func(hLogHandle HANDLE, dwEventType uint32, dwMessageId uint32, dwSubStringCount uint32, plpszSubStringArray **PSTRElement, dwErrorCode uint32, dwErrorIndex uint32)

/*
PFN_RouterLogEventExA maps to RouterLogEventExA in rtutils.dll.
*/
type PFN_RouterLogEventExA func(hLogHandle HANDLE, dwEventType uint32, dwErrorCode uint32, dwMessageId uint32, ptszFormat *PSTRElement)

/*
PFN_RouterLogEventValistExA maps to RouterLogEventValistExA in rtutils.dll.
*/
type PFN_RouterLogEventValistExA func(hLogHandle HANDLE, dwEventType uint32, dwErrorCode uint32, dwMessageId uint32, ptszFormat *PSTRElement, arglist *int8)

/*
PFN_RouterGetErrorStringA maps to RouterGetErrorStringA in rtutils.dll.
*/
type PFN_RouterGetErrorStringA func(dwErrorCode uint32, lplpszErrorString **PSTRElement) uint32

/*
PFN_RouterLogRegisterW maps to RouterLogRegisterW in rtutils.dll.
*/
type PFN_RouterLogRegisterW func(lpszSource *PWSTRElement) HANDLE

/*
PFN_RouterLogDeregisterW maps to RouterLogDeregisterW in rtutils.dll.
*/
type PFN_RouterLogDeregisterW func(hLogHandle HANDLE)

/*
PFN_RouterLogEventW maps to RouterLogEventW in rtutils.dll.
*/
type PFN_RouterLogEventW func(hLogHandle HANDLE, dwEventType uint32, dwMessageId uint32, dwSubStringCount uint32, plpszSubStringArray **PWSTRElement, dwErrorCode uint32)

/*
PFN_RouterLogEventDataW maps to RouterLogEventDataW in rtutils.dll.
*/
type PFN_RouterLogEventDataW func(hLogHandle HANDLE, dwEventType uint32, dwMessageId uint32, dwSubStringCount uint32, plpszSubStringArray **PWSTRElement, dwDataBytes uint32, lpDataBytes *uint8)

/*
PFN_RouterLogEventStringW maps to RouterLogEventStringW in rtutils.dll.
*/
type PFN_RouterLogEventStringW func(hLogHandle HANDLE, dwEventType uint32, dwMessageId uint32, dwSubStringCount uint32, plpszSubStringArray **PWSTRElement, dwErrorCode uint32, dwErrorIndex uint32)

/*
PFN_RouterLogEventExW maps to RouterLogEventExW in rtutils.dll.
*/
type PFN_RouterLogEventExW func(hLogHandle HANDLE, dwEventType uint32, dwErrorCode uint32, dwMessageId uint32, ptszFormat *PWSTRElement)

/*
PFN_RouterLogEventValistExW maps to RouterLogEventValistExW in rtutils.dll.
*/
type PFN_RouterLogEventValistExW func(hLogHandle HANDLE, dwEventType uint32, dwErrorCode uint32, dwMessageId uint32, ptszFormat *PWSTRElement, arglist *int8)

/*
PFN_RouterGetErrorStringW maps to RouterGetErrorStringW in rtutils.dll.
*/
type PFN_RouterGetErrorStringW func(dwErrorCode uint32, lplpwszErrorString **PWSTRElement) uint32

/*
PFN_RouterAssert maps to RouterAssert in rtutils.dll.
*/
type PFN_RouterAssert func(pszFailedAssertion *PSTRElement, pszFileName *PSTRElement, dwLineNumber uint32, pszMessage *PSTRElement)

/*
PFN_MprSetupProtocolEnum maps to MprSetupProtocolEnum in rtutils.dll.
*/
type PFN_MprSetupProtocolEnum func(dwTransportId uint32, lplpBuffer **uint8, lpdwEntriesRead *uint32) uint32

/*
PFN_MprSetupProtocolFree maps to MprSetupProtocolFree in rtutils.dll.
*/
type PFN_MprSetupProtocolFree func(lpBuffer uintptr) uint32
