//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
IHolographicCameraInterop is generated from Windows.Win32 metadata.
*/
type IHolographicCameraInterop uintptr

/*
IHolographicCameraRenderingParametersInterop is generated from Windows.Win32 metadata.
*/
type IHolographicCameraRenderingParametersInterop uintptr

/*
IHolographicQuadLayerInterop is generated from Windows.Win32 metadata.
*/
type IHolographicQuadLayerInterop uintptr

/*
IHolographicQuadLayerUpdateParametersInterop is generated from Windows.Win32 metadata.
*/
type IHolographicQuadLayerUpdateParametersInterop uintptr

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
}
