//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_KsResolveRequiredAttributes maps to KsResolveRequiredAttributes in ksproxy.ax.
*/
type PFN_KsResolveRequiredAttributes func(DataRange *KSDATAFORMAT, Attributes *KSMULTIPLE_ITEM) HRESULT

/*
PFN_KsOpenDefaultDevice maps to KsOpenDefaultDevice in ksproxy.ax.
*/
type PFN_KsOpenDefaultDevice func(Category *Guid, Access uint32, DeviceHandle *HANDLE) HRESULT

/*
PFN_KsSynchronousDeviceControl maps to KsSynchronousDeviceControl in ksproxy.ax.
*/
type PFN_KsSynchronousDeviceControl func(Handle HANDLE, IoControl uint32, InBuffer uintptr, InLength uint32, OutBuffer uintptr, OutLength uint32, BytesReturned *uint32) HRESULT

/*
PFN_KsGetMultiplePinFactoryItems maps to KsGetMultiplePinFactoryItems in ksproxy.ax.
*/
type PFN_KsGetMultiplePinFactoryItems func(FilterHandle HANDLE, PinFactoryId uint32, PropertyId uint32, Items *uintptr) HRESULT

/*
PFN_KsGetMediaTypeCount maps to KsGetMediaTypeCount in ksproxy.ax.
*/
type PFN_KsGetMediaTypeCount func(FilterHandle HANDLE, PinFactoryId uint32, MediaTypeCount *uint32) HRESULT

/*
PFN_KsGetMediaType maps to KsGetMediaType in ksproxy.ax.
*/
type PFN_KsGetMediaType func(Position int32, AmMediaType *AM_MEDIA_TYPE, FilterHandle HANDLE, PinFactoryId uint32) HRESULT
