//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:54 CEST

package bindings

/*
GPO_OPEN_FLAGS is generated from Windows.Win32 metadata.
*/
type GPO_OPEN_FLAGS uint32

const (
	/*
		GPO_OPEN_LOAD_REGISTRY from Windows.Win32 metadata.
	*/
	GPO_OPEN_LOAD_REGISTRY GPO_OPEN_FLAGS = 0x1

	/*
		GPO_OPEN_READ_ONLY from Windows.Win32 metadata.
	*/
	GPO_OPEN_READ_ONLY GPO_OPEN_FLAGS = 0x2
)

/*
GPO_OPTIONS is generated from Windows.Win32 metadata.
*/
type GPO_OPTIONS uint32

const (
	/*
		GPO_OPTION_DISABLE_USER from Windows.Win32 metadata.
	*/
	GPO_OPTION_DISABLE_USER GPO_OPTIONS = 0x1

	/*
		GPO_OPTION_DISABLE_MACHINE from Windows.Win32 metadata.
	*/
	GPO_OPTION_DISABLE_MACHINE GPO_OPTIONS = 0x2
)

/*
GPO_SECTION is generated from Windows.Win32 metadata.
*/
type GPO_SECTION uint32

const (
	/*
		GPO_SECTION_ROOT from Windows.Win32 metadata.
	*/
	GPO_SECTION_ROOT GPO_SECTION = 0x0

	/*
		GPO_SECTION_USER from Windows.Win32 metadata.
	*/
	GPO_SECTION_USER GPO_SECTION = 0x1

	/*
		GPO_SECTION_MACHINE from Windows.Win32 metadata.
	*/
	GPO_SECTION_MACHINE GPO_SECTION = 0x2
)

/*
Apis is generated from Windows.Win32 metadata.
*/
type Apis struct {
	GPM_USE_PDC                              uint32
	GPM_USE_ANYDC                            uint32
	GPM_DONOTUSE_W2KDC                       uint32
	GPM_DONOT_VALIDATEDC                     uint32
	GPM_MIGRATIONTABLE_ONLY                  uint32
	GPM_PROCESS_SECURITY                     uint32
	RSOP_NO_COMPUTER                         uint32
	RSOP_NO_USER                             uint32
	RSOP_PLANNING_ASSUME_SLOW_LINK           uint32
	RSOP_PLANNING_ASSUME_LOOPBACK_MERGE      uint32
	RSOP_PLANNING_ASSUME_LOOPBACK_REPLACE    uint32
	RSOP_PLANNING_ASSUME_USER_WQLFILTER_TRUE uint32
	RSOP_PLANNING_ASSUME_COMP_WQLFILTER_TRUE uint32
	PI_NOUI                                  uint32
	PI_APPLYPOLICY                           uint32
	PT_TEMPORARY                             uint32
	PT_ROAMING                               uint32
	PT_MANDATORY                             uint32
	PT_ROAMING_PREEXISTING                   uint32
	RP_FORCE                                 uint32
	RP_SYNC                                  uint32
	GPC_BLOCK_POLICY                         uint32
	GPO_FLAG_DISABLE                         uint32
	GPO_FLAG_FORCE                           uint32
	GPO_LIST_FLAG_MACHINE                    uint32
	GPO_LIST_FLAG_SITEONLY                   uint32
	GPO_LIST_FLAG_NO_WMIFILTERS              uint32
	GPO_LIST_FLAG_NO_SECURITYFILTERS         uint32
	GP_DLLNAME                               uintptr
	GP_ENABLEASYNCHRONOUSPROCESSING          uintptr
	GP_MAXNOGPOLISTCHANGESINTERVAL           uintptr
	GP_NOBACKGROUNDPOLICY                    uintptr
	GP_NOGPOLISTCHANGES                      uintptr
	GP_NOMACHINEPOLICY                       uintptr
	GP_NOSLOWLINK                            uintptr
	GP_NOTIFYLINKTRANSITION                  uintptr
	GP_NOUSERPOLICY                          uintptr
	GP_PERUSERLOCALSETTINGS                  uintptr
	GP_PROCESSGROUPPOLICY                    uintptr
	GP_REQUIRESSUCCESSFULREGISTRY            uintptr
	GPO_INFO_FLAG_MACHINE                    uint32
	GPO_INFO_FLAG_BACKGROUND                 uint32
	GPO_INFO_FLAG_SLOWLINK                   uint32
	GPO_INFO_FLAG_VERBOSE                    uint32
	GPO_INFO_FLAG_NOCHANGES                  uint32
	GPO_INFO_FLAG_LINKTRANSITION             uint32
	GPO_INFO_FLAG_LOGRSOP_TRANSITION         uint32
	GPO_INFO_FLAG_FORCED_REFRESH             uint32
	GPO_INFO_FLAG_SAFEMODE_BOOT              uint32
	GPO_INFO_FLAG_ASYNC_FOREGROUND           uint32
	REGISTRY_EXTENSION_GUID                  Guid
	GROUP_POLICY_TRIGGER_EVENT_PROVIDER_GUID Guid
	MACHINE_POLICY_PRESENT_TRIGGER_GUID      Guid
	USER_POLICY_PRESENT_TRIGGER_GUID         Guid
	FLAG_NO_GPO_FILTER                       uint32
	FLAG_NO_CSE_INVOKE                       uint32
	FLAG_ASSUME_SLOW_LINK                    uint32
	FLAG_LOOPBACK_MERGE                      uint32
	FLAG_LOOPBACK_REPLACE                    uint32
	FLAG_ASSUME_USER_WQLFILTER_TRUE          uint32
	FLAG_ASSUME_COMP_WQLFILTER_TRUE          uint32
	FLAG_PLANNING_MODE                       uint32
	FLAG_NO_USER                             uint32
	FLAG_NO_COMPUTER                         uint32
	FLAG_FORCE_CREATENAMESPACE               uint32
	RSOP_USER_ACCESS_DENIED                  uint32
	RSOP_COMPUTER_ACCESS_DENIED              uint32
	RSOP_TEMPNAMESPACE_EXISTS                uint32
	LOCALSTATE_ASSIGNED                      uint32
	LOCALSTATE_PUBLISHED                     uint32
	LOCALSTATE_UNINSTALL_UNMANAGED           uint32
	LOCALSTATE_POLICYREMOVE_ORPHAN           uint32
	LOCALSTATE_POLICYREMOVE_UNINSTALL        uint32
	LOCALSTATE_ORPHANED                      uint32
	LOCALSTATE_UNINSTALLED                   uint32
	MANAGED_APPS_USERAPPLICATIONS            uint32
	MANAGED_APPS_FROMCATEGORY                uint32
	MANAGED_APPS_INFOLEVEL_DEFAULT           uint32
	MANAGED_APPTYPE_WINDOWSINSTALLER         uint32
	MANAGED_APPTYPE_SETUPEXE                 uint32
	MANAGED_APPTYPE_UNSUPPORTED              uint32
	CLSID_GPESnapIn                          Guid
	NODEID_Machine                           Guid
	NODEID_MachineSWSettings                 Guid
	NODEID_User                              Guid
	NODEID_UserSWSettings                    Guid
	CLSID_GroupPolicyObject                  Guid
	ADMXCOMMENTS_EXTENSION_GUID              Guid
	CLSID_RSOPSnapIn                         Guid
	NODEID_RSOPMachine                       Guid
	NODEID_RSOPMachineSWSettings             Guid
	NODEID_RSOPUser                          Guid
	NODEID_RSOPUserSWSettings                Guid
	RSOP_INFO_FLAG_DIAGNOSTIC_MODE           uint32
	GPO_BROWSE_DISABLENEW                    uint32
	GPO_BROWSE_NOCOMPUTERS                   uint32
	GPO_BROWSE_NODSGPOS                      uint32
	GPO_BROWSE_OPENBUTTON                    uint32
	GPO_BROWSE_INITTOALL                     uint32
	GPO_BROWSE_NOUSERGPOS                    uint32
	GPO_BROWSE_SENDAPPLYONEDIT               uint32
}

/*
GPMRSOPMode is generated from Windows.Win32 metadata.
*/
type GPMRSOPMode int32

const (
	/*
		RsopUnknown from Windows.Win32 metadata.
	*/
	RsopUnknown GPMRSOPMode = 0x0

	/*
		RsopPlanning from Windows.Win32 metadata.
	*/
	RsopPlanning GPMRSOPMode = 0x1

	/*
		RsopLogging from Windows.Win32 metadata.
	*/
	RsopLogging GPMRSOPMode = 0x2
)

/*
GPMPermissionType is generated from Windows.Win32 metadata.
*/
type GPMPermissionType int32

const (
	/*
		PermGPOApply from Windows.Win32 metadata.
	*/
	PermGPOApply GPMPermissionType = 0x10000

	/*
		PermGPORead from Windows.Win32 metadata.
	*/
	PermGPORead GPMPermissionType = 0x10100

	/*
		PermGPOEdit from Windows.Win32 metadata.
	*/
	PermGPOEdit GPMPermissionType = 0x10101

	/*
		PermGPOEditSecurityAndDelete from Windows.Win32 metadata.
	*/
	PermGPOEditSecurityAndDelete GPMPermissionType = 0x10102

	/*
		PermGPOCustom from Windows.Win32 metadata.
	*/
	PermGPOCustom GPMPermissionType = 0x10103

	/*
		PermWMIFilterEdit from Windows.Win32 metadata.
	*/
	PermWMIFilterEdit GPMPermissionType = 0x20000

	/*
		PermWMIFilterFullControl from Windows.Win32 metadata.
	*/
	PermWMIFilterFullControl GPMPermissionType = 0x20001

	/*
		PermWMIFilterCustom from Windows.Win32 metadata.
	*/
	PermWMIFilterCustom GPMPermissionType = 0x20002

	/*
		PermSOMLink from Windows.Win32 metadata.
	*/
	PermSOMLink GPMPermissionType = 0x1c0000

	/*
		PermSOMLogging from Windows.Win32 metadata.
	*/
	PermSOMLogging GPMPermissionType = 0x180100

	/*
		PermSOMPlanning from Windows.Win32 metadata.
	*/
	PermSOMPlanning GPMPermissionType = 0x180200

	/*
		PermSOMWMICreate from Windows.Win32 metadata.
	*/
	PermSOMWMICreate GPMPermissionType = 0x100300

	/*
		PermSOMWMIFullControl from Windows.Win32 metadata.
	*/
	PermSOMWMIFullControl GPMPermissionType = 0x100301

	/*
		PermSOMGPOCreate from Windows.Win32 metadata.
	*/
	PermSOMGPOCreate GPMPermissionType = 0x100400

	/*
		PermStarterGPORead from Windows.Win32 metadata.
	*/
	PermStarterGPORead GPMPermissionType = 0x30500

	/*
		PermStarterGPOEdit from Windows.Win32 metadata.
	*/
	PermStarterGPOEdit GPMPermissionType = 0x30501

	/*
		PermStarterGPOFullControl from Windows.Win32 metadata.
	*/
	PermStarterGPOFullControl GPMPermissionType = 0x30502

	/*
		PermStarterGPOCustom from Windows.Win32 metadata.
	*/
	PermStarterGPOCustom GPMPermissionType = 0x30503

	/*
		PermSOMStarterGPOCreate from Windows.Win32 metadata.
	*/
	PermSOMStarterGPOCreate GPMPermissionType = 0x100500
)

/*
GPMSearchProperty is generated from Windows.Win32 metadata.
*/
type GPMSearchProperty int32

const (
	/*
		GpoPermissions from Windows.Win32 metadata.
	*/
	GpoPermissions GPMSearchProperty = 0x0

	/*
		GpoEffectivePermissions from Windows.Win32 metadata.
	*/
	GpoEffectivePermissions GPMSearchProperty = 0x1

	/*
		GpoDisplayName from Windows.Win32 metadata.
	*/
	GpoDisplayName GPMSearchProperty = 0x2

	/*
		GpoWMIFilter from Windows.Win32 metadata.
	*/
	GpoWMIFilter GPMSearchProperty = 0x3

	/*
		GpoID from Windows.Win32 metadata.
	*/
	GpoID GPMSearchProperty = 0x4

	/*
		GpoComputerExtensions from Windows.Win32 metadata.
	*/
	GpoComputerExtensions GPMSearchProperty = 0x5

	/*
		GpoUserExtensions from Windows.Win32 metadata.
	*/
	GpoUserExtensions GPMSearchProperty = 0x6

	/*
		SomLinks from Windows.Win32 metadata.
	*/
	SomLinks GPMSearchProperty = 0x7

	/*
		GpoDomain from Windows.Win32 metadata.
	*/
	GpoDomain GPMSearchProperty = 0x8

	/*
		BackupMostRecent from Windows.Win32 metadata.
	*/
	BackupMostRecent GPMSearchProperty = 0x9

	/*
		StarterGPOPermissions from Windows.Win32 metadata.
	*/
	StarterGPOPermissions GPMSearchProperty = 0xa

	/*
		StarterGPOEffectivePermissions from Windows.Win32 metadata.
	*/
	StarterGPOEffectivePermissions GPMSearchProperty = 0xb

	/*
		StarterGPODisplayName from Windows.Win32 metadata.
	*/
	StarterGPODisplayName GPMSearchProperty = 0xc

	/*
		StarterGPOID from Windows.Win32 metadata.
	*/
	StarterGPOID GPMSearchProperty = 0xd

	/*
		StarterGPODomain from Windows.Win32 metadata.
	*/
	StarterGPODomain GPMSearchProperty = 0xe
)

/*
GPMSearchOperation is generated from Windows.Win32 metadata.
*/
type GPMSearchOperation int32

const (
	/*
		OpEquals from Windows.Win32 metadata.
	*/
	OpEquals GPMSearchOperation = 0x0

	/*
		OpContains from Windows.Win32 metadata.
	*/
	OpContains GPMSearchOperation = 0x1

	/*
		OpNotContains from Windows.Win32 metadata.
	*/
	OpNotContains GPMSearchOperation = 0x2

	/*
		OpNotEquals from Windows.Win32 metadata.
	*/
	OpNotEquals GPMSearchOperation = 0x3
)

/*
GPMReportType is generated from Windows.Win32 metadata.
*/
type GPMReportType int32

const (
	/*
		RepXML from Windows.Win32 metadata.
	*/
	RepXML GPMReportType = 0x0

	/*
		RepHTML from Windows.Win32 metadata.
	*/
	RepHTML GPMReportType = 0x1

	/*
		RepInfraXML from Windows.Win32 metadata.
	*/
	RepInfraXML GPMReportType = 0x2

	/*
		RepInfraRefreshXML from Windows.Win32 metadata.
	*/
	RepInfraRefreshXML GPMReportType = 0x3

	/*
		RepClientHealthXML from Windows.Win32 metadata.
	*/
	RepClientHealthXML GPMReportType = 0x4

	/*
		RepClientHealthRefreshXML from Windows.Win32 metadata.
	*/
	RepClientHealthRefreshXML GPMReportType = 0x5
)

/*
GPMEntryType is generated from Windows.Win32 metadata.
*/
type GPMEntryType int32

const (
	/*
		TypeUser from Windows.Win32 metadata.
	*/
	TypeUser GPMEntryType = 0x0

	/*
		TypeComputer from Windows.Win32 metadata.
	*/
	TypeComputer GPMEntryType = 0x1

	/*
		TypeLocalGroup from Windows.Win32 metadata.
	*/
	TypeLocalGroup GPMEntryType = 0x2

	/*
		TypeGlobalGroup from Windows.Win32 metadata.
	*/
	TypeGlobalGroup GPMEntryType = 0x3

	/*
		TypeUniversalGroup from Windows.Win32 metadata.
	*/
	TypeUniversalGroup GPMEntryType = 0x4

	/*
		TypeUNCPath from Windows.Win32 metadata.
	*/
	TypeUNCPath GPMEntryType = 0x5

	/*
		TypeUnknown from Windows.Win32 metadata.
	*/
	TypeUnknown GPMEntryType = 0x6
)

/*
GPMDestinationOption is generated from Windows.Win32 metadata.
*/
type GPMDestinationOption int32

const (
	/*
		OpDestinationSameAsSource from Windows.Win32 metadata.
	*/
	OpDestinationSameAsSource GPMDestinationOption = 0x0

	/*
		OpDestinationNone from Windows.Win32 metadata.
	*/
	OpDestinationNone GPMDestinationOption = 0x1

	/*
		OpDestinationByRelativeName from Windows.Win32 metadata.
	*/
	OpDestinationByRelativeName GPMDestinationOption = 0x2

	/*
		OpDestinationSet from Windows.Win32 metadata.
	*/
	OpDestinationSet GPMDestinationOption = 0x3
)

/*
GPMReportingOptions is generated from Windows.Win32 metadata.
*/
type GPMReportingOptions int32

const (
	/*
		OpReportLegacy from Windows.Win32 metadata.
	*/
	OpReportLegacy GPMReportingOptions = 0x0

	/*
		OpReportComments from Windows.Win32 metadata.
	*/
	OpReportComments GPMReportingOptions = 0x1
)

/*
IGPM is generated from Windows.Win32 metadata.
*/
type IGPM uintptr

/*
IGPMDomain is generated from Windows.Win32 metadata.
*/
type IGPMDomain uintptr

/*
IGPMBackupDir is generated from Windows.Win32 metadata.
*/
type IGPMBackupDir uintptr

/*
IGPMSitesContainer is generated from Windows.Win32 metadata.
*/
type IGPMSitesContainer uintptr

/*
IGPMSearchCriteria is generated from Windows.Win32 metadata.
*/
type IGPMSearchCriteria uintptr

/*
IGPMTrustee is generated from Windows.Win32 metadata.
*/
type IGPMTrustee uintptr

/*
IGPMPermission is generated from Windows.Win32 metadata.
*/
type IGPMPermission uintptr

/*
IGPMSecurityInfo is generated from Windows.Win32 metadata.
*/
type IGPMSecurityInfo uintptr

/*
IGPMBackup is generated from Windows.Win32 metadata.
*/
type IGPMBackup uintptr

/*
IGPMBackupCollection is generated from Windows.Win32 metadata.
*/
type IGPMBackupCollection uintptr

/*
GPMSOMType is generated from Windows.Win32 metadata.
*/
type GPMSOMType int32

const (
	/*
		SomSite from Windows.Win32 metadata.
	*/
	SomSite GPMSOMType = 0x0

	/*
		SomDomain from Windows.Win32 metadata.
	*/
	SomDomain GPMSOMType = 0x1

	/*
		SomOU from Windows.Win32 metadata.
	*/
	SomOU GPMSOMType = 0x2
)

/*
IGPMSOM is generated from Windows.Win32 metadata.
*/
type IGPMSOM uintptr

/*
IGPMSOMCollection is generated from Windows.Win32 metadata.
*/
type IGPMSOMCollection uintptr

/*
IGPMWMIFilter is generated from Windows.Win32 metadata.
*/
type IGPMWMIFilter uintptr

/*
IGPMWMIFilterCollection is generated from Windows.Win32 metadata.
*/
type IGPMWMIFilterCollection uintptr

/*
IGPMRSOP is generated from Windows.Win32 metadata.
*/
type IGPMRSOP uintptr

/*
IGPMGPO is generated from Windows.Win32 metadata.
*/
type IGPMGPO uintptr

/*
IGPMGPOCollection is generated from Windows.Win32 metadata.
*/
type IGPMGPOCollection uintptr

/*
IGPMGPOLink is generated from Windows.Win32 metadata.
*/
type IGPMGPOLink uintptr

/*
IGPMGPOLinksCollection is generated from Windows.Win32 metadata.
*/
type IGPMGPOLinksCollection uintptr

/*
IGPMCSECollection is generated from Windows.Win32 metadata.
*/
type IGPMCSECollection uintptr

/*
IGPMClientSideExtension is generated from Windows.Win32 metadata.
*/
type IGPMClientSideExtension uintptr

/*
IGPMAsyncCancel is generated from Windows.Win32 metadata.
*/
type IGPMAsyncCancel uintptr

/*
IGPMAsyncProgress is generated from Windows.Win32 metadata.
*/
type IGPMAsyncProgress uintptr

/*
IGPMStatusMsgCollection is generated from Windows.Win32 metadata.
*/
type IGPMStatusMsgCollection uintptr

/*
IGPMStatusMessage is generated from Windows.Win32 metadata.
*/
type IGPMStatusMessage uintptr

/*
IGPMConstants is generated from Windows.Win32 metadata.
*/
type IGPMConstants uintptr

/*
IGPMResult is generated from Windows.Win32 metadata.
*/
type IGPMResult uintptr

/*
IGPMMapEntryCollection is generated from Windows.Win32 metadata.
*/
type IGPMMapEntryCollection uintptr

/*
IGPMMapEntry is generated from Windows.Win32 metadata.
*/
type IGPMMapEntry uintptr

/*
IGPMMigrationTable is generated from Windows.Win32 metadata.
*/
type IGPMMigrationTable uintptr

/*
GPMBackupType is generated from Windows.Win32 metadata.
*/
type GPMBackupType int32

const (
	/*
		TypeGPO from Windows.Win32 metadata.
	*/
	TypeGPO GPMBackupType = 0x0

	/*
		TypeStarterGPO from Windows.Win32 metadata.
	*/
	TypeStarterGPO GPMBackupType = 0x1
)

/*
GPMStarterGPOType is generated from Windows.Win32 metadata.
*/
type GPMStarterGPOType int32

const (
	/*
		TypeSystem from Windows.Win32 metadata.
	*/
	TypeSystem GPMStarterGPOType = 0x0

	/*
		TypeCustom from Windows.Win32 metadata.
	*/
	TypeCustom GPMStarterGPOType = 0x1
)

/*
IGPMBackupDirEx is generated from Windows.Win32 metadata.
*/
type IGPMBackupDirEx uintptr

/*
IGPMStarterGPOBackupCollection is generated from Windows.Win32 metadata.
*/
type IGPMStarterGPOBackupCollection uintptr

/*
IGPMStarterGPOBackup is generated from Windows.Win32 metadata.
*/
type IGPMStarterGPOBackup uintptr

/*
IGPM2 is generated from Windows.Win32 metadata.
*/
type IGPM2 uintptr

/*
IGPMStarterGPO is generated from Windows.Win32 metadata.
*/
type IGPMStarterGPO uintptr

/*
IGPMStarterGPOCollection is generated from Windows.Win32 metadata.
*/
type IGPMStarterGPOCollection uintptr

/*
IGPMDomain2 is generated from Windows.Win32 metadata.
*/
type IGPMDomain2 uintptr

/*
IGPMConstants2 is generated from Windows.Win32 metadata.
*/
type IGPMConstants2 uintptr

/*
IGPMGPO2 is generated from Windows.Win32 metadata.
*/
type IGPMGPO2 uintptr

/*
IGPMDomain3 is generated from Windows.Win32 metadata.
*/
type IGPMDomain3 uintptr

/*
IGPMGPO3 is generated from Windows.Win32 metadata.
*/
type IGPMGPO3 uintptr

/*
GPM is generated from Windows.Win32 metadata.
*/
type GPM struct {
}

/*
GPMDomain is generated from Windows.Win32 metadata.
*/
type GPMDomain struct {
}

/*
GPMSitesContainer is generated from Windows.Win32 metadata.
*/
type GPMSitesContainer struct {
}

/*
GPMBackupDir is generated from Windows.Win32 metadata.
*/
type GPMBackupDir struct {
}

/*
GPMSOM is generated from Windows.Win32 metadata.
*/
type GPMSOM struct {
}

/*
GPMSearchCriteria is generated from Windows.Win32 metadata.
*/
type GPMSearchCriteria struct {
}

/*
GPMPermission is generated from Windows.Win32 metadata.
*/
type GPMPermission struct {
}

/*
GPMSecurityInfo is generated from Windows.Win32 metadata.
*/
type GPMSecurityInfo struct {
}

/*
GPMBackup is generated from Windows.Win32 metadata.
*/
type GPMBackup struct {
}

/*
GPMBackupCollection is generated from Windows.Win32 metadata.
*/
type GPMBackupCollection struct {
}

/*
GPMSOMCollection is generated from Windows.Win32 metadata.
*/
type GPMSOMCollection struct {
}

/*
GPMWMIFilter is generated from Windows.Win32 metadata.
*/
type GPMWMIFilter struct {
}

/*
GPMWMIFilterCollection is generated from Windows.Win32 metadata.
*/
type GPMWMIFilterCollection struct {
}

/*
GPMRSOP is generated from Windows.Win32 metadata.
*/
type GPMRSOP struct {
}

/*
GPMGPO is generated from Windows.Win32 metadata.
*/
type GPMGPO struct {
}

/*
GPMGPOCollection is generated from Windows.Win32 metadata.
*/
type GPMGPOCollection struct {
}

/*
GPMGPOLink is generated from Windows.Win32 metadata.
*/
type GPMGPOLink struct {
}

/*
GPMGPOLinksCollection is generated from Windows.Win32 metadata.
*/
type GPMGPOLinksCollection struct {
}

/*
GPMAsyncCancel is generated from Windows.Win32 metadata.
*/
type GPMAsyncCancel struct {
}

/*
GPMStatusMsgCollection is generated from Windows.Win32 metadata.
*/
type GPMStatusMsgCollection struct {
}

/*
GPMStatusMessage is generated from Windows.Win32 metadata.
*/
type GPMStatusMessage struct {
}

/*
GPMTrustee is generated from Windows.Win32 metadata.
*/
type GPMTrustee struct {
}

/*
GPMClientSideExtension is generated from Windows.Win32 metadata.
*/
type GPMClientSideExtension struct {
}

/*
GPMCSECollection is generated from Windows.Win32 metadata.
*/
type GPMCSECollection struct {
}

/*
GPMConstants is generated from Windows.Win32 metadata.
*/
type GPMConstants struct {
}

/*
GPMResult is generated from Windows.Win32 metadata.
*/
type GPMResult struct {
}

/*
GPMMapEntryCollection is generated from Windows.Win32 metadata.
*/
type GPMMapEntryCollection struct {
}

/*
GPMMapEntry is generated from Windows.Win32 metadata.
*/
type GPMMapEntry struct {
}

/*
GPMMigrationTable is generated from Windows.Win32 metadata.
*/
type GPMMigrationTable struct {
}

/*
GPMBackupDirEx is generated from Windows.Win32 metadata.
*/
type GPMBackupDirEx struct {
}

/*
GPMStarterGPOBackupCollection is generated from Windows.Win32 metadata.
*/
type GPMStarterGPOBackupCollection struct {
}

/*
GPMStarterGPOBackup is generated from Windows.Win32 metadata.
*/
type GPMStarterGPOBackup struct {
}

/*
GPMTemplate is generated from Windows.Win32 metadata.
*/
type GPMTemplate struct {
}

/*
GPMStarterGPOCollection is generated from Windows.Win32 metadata.
*/
type GPMStarterGPOCollection struct {
}

/*
GPO_LINK is generated from Windows.Win32 metadata.
*/
type GPO_LINK int32

const (
	/*
		GPLinkUnknown from Windows.Win32 metadata.
	*/
	GPLinkUnknown GPO_LINK = 0x0

	/*
		GPLinkMachine from Windows.Win32 metadata.
	*/
	GPLinkMachine GPO_LINK = 0x1

	/*
		GPLinkSite from Windows.Win32 metadata.
	*/
	GPLinkSite GPO_LINK = 0x2

	/*
		GPLinkDomain from Windows.Win32 metadata.
	*/
	GPLinkDomain GPO_LINK = 0x3

	/*
		GPLinkOrganizationalUnit from Windows.Win32 metadata.
	*/
	GPLinkOrganizationalUnit GPO_LINK = 0x4
)

/*
GROUP_POLICY_OBJECTA is generated from Windows.Win32 metadata.
*/
type GROUP_POLICY_OBJECTA struct {
	DwOptions     uint32
	DwVersion     uint32
	LpDSPath      *PSTRElement
	LpFileSysPath *PSTRElement
	LpDisplayName *PSTRElement
	SzGPOName     [50]CHAR
	GPOLink       GPO_LINK
	LParam        LPARAM
	PNext         *GROUP_POLICY_OBJECTA
	PPrev         *GROUP_POLICY_OBJECTA
	LpExtensions  *PSTRElement
	LParam2       LPARAM
	LpLink        *PSTRElement
}

/*
GROUP_POLICY_OBJECTW is generated from Windows.Win32 metadata.
*/
type GROUP_POLICY_OBJECTW struct {
	DwOptions     uint32
	DwVersion     uint32
	LpDSPath      *PWSTRElement
	LpFileSysPath *PWSTRElement
	LpDisplayName *PWSTRElement
	SzGPOName     [50]uint16
	GPOLink       GPO_LINK
	LParam        LPARAM
	PNext         *GROUP_POLICY_OBJECTW
	PPrev         *GROUP_POLICY_OBJECTW
	LpExtensions  *PWSTRElement
	LParam2       LPARAM
	LpLink        *PWSTRElement
}

/*
PFNSTATUSMESSAGECALLBACK is generated from Windows.Win32 metadata.
*/
type PFNSTATUSMESSAGECALLBACK uintptr

/*
PFNPROCESSGROUPPOLICY is generated from Windows.Win32 metadata.
*/
type PFNPROCESSGROUPPOLICY uintptr

/*
PFNPROCESSGROUPPOLICYEX is generated from Windows.Win32 metadata.
*/
type PFNPROCESSGROUPPOLICYEX uintptr

/*
RSOP_TARGET is generated from Windows.Win32 metadata.
*/
type RSOP_TARGET struct {
	PwszAccountName   *PWSTRElement
	PwszNewSOM        *PWSTRElement
	PsaSecurityGroups *SAFEARRAY
	PRsopToken        uintptr
	PGPOList          *GROUP_POLICY_OBJECTA
	PWbemServices     *IWbemServices
}

/*
PFNGENERATEGROUPPOLICY is generated from Windows.Win32 metadata.
*/
type PFNGENERATEGROUPPOLICY uintptr

/*
SETTINGSTATUS is generated from Windows.Win32 metadata.
*/
type SETTINGSTATUS int32

const (
	/*
		RSOPUnspecified from Windows.Win32 metadata.
	*/
	RSOPUnspecified SETTINGSTATUS = 0x0

	/*
		RSOPApplied from Windows.Win32 metadata.
	*/
	RSOPApplied SETTINGSTATUS = 0x1

	/*
		RSOPIgnored from Windows.Win32 metadata.
	*/
	RSOPIgnored SETTINGSTATUS = 0x2

	/*
		RSOPFailed from Windows.Win32 metadata.
	*/
	RSOPFailed SETTINGSTATUS = 0x3

	/*
		RSOPSubsettingFailed from Windows.Win32 metadata.
	*/
	RSOPSubsettingFailed SETTINGSTATUS = 0x4
)

/*
POLICYSETTINGSTATUSINFO is generated from Windows.Win32 metadata.
*/
type POLICYSETTINGSTATUSINFO struct {
	SzKey          *PWSTRElement
	SzEventSource  *PWSTRElement
	SzEventLogName *PWSTRElement
	DwEventID      uint32
	DwErrorCode    uint32
	Status         SETTINGSTATUS
	TimeLogged     SYSTEMTIME
}

/*
INSTALLSPECTYPE is generated from Windows.Win32 metadata.
*/
type INSTALLSPECTYPE int32

const (
	/*
		APPNAME from Windows.Win32 metadata.
	*/
	APPNAME INSTALLSPECTYPE = 0x1

	/*
		FILEEXT from Windows.Win32 metadata.
	*/
	FILEEXT INSTALLSPECTYPE = 0x2

	/*
		PROGID from Windows.Win32 metadata.
	*/
	PROGID INSTALLSPECTYPE = 0x3

	/*
		COMCLASS from Windows.Win32 metadata.
	*/
	COMCLASS INSTALLSPECTYPE = 0x4
)

/*
INSTALLSPEC is generated from Windows.Win32 metadata.
*/
type INSTALLSPEC struct {
	Name  *PWSTRElement
	GPOId Guid
}

/*
INSTALLDATA is generated from Windows.Win32 metadata.
*/
type INSTALLDATA struct {
	Type INSTALLSPECTYPE
	Spec INSTALLSPEC
}

/*
APPSTATE is generated from Windows.Win32 metadata.
*/
type APPSTATE int32

const (
	/*
		ABSENT from Windows.Win32 metadata.
	*/
	ABSENT APPSTATE = 0x0

	/*
		ASSIGNED from Windows.Win32 metadata.
	*/
	ASSIGNED APPSTATE = 0x1

	/*
		PUBLISHED from Windows.Win32 metadata.
	*/
	PUBLISHED APPSTATE = 0x2
)

/*
LOCALMANAGEDAPPLICATION is generated from Windows.Win32 metadata.
*/
type LOCALMANAGEDAPPLICATION struct {
	PszDeploymentName *PWSTRElement
	PszPolicyName     *PWSTRElement
	PszProductId      *PWSTRElement
	DwState           uint32
}

/*
MANAGEDAPPLICATION is generated from Windows.Win32 metadata.
*/
type MANAGEDAPPLICATION struct {
	PszPackageName *PWSTRElement
	PszPublisher   *PWSTRElement
	DwVersionHi    uint32
	DwVersionLo    uint32
	DwRevision     uint32
	GpoId          Guid
	PszPolicyName  *PWSTRElement
	ProductId      Guid
	Language       uint16
	PszOwner       *PWSTRElement
	PszCompany     *PWSTRElement
	PszComments    *PWSTRElement
	PszContact     *PWSTRElement
	PszSupportUrl  *PWSTRElement
	DwPathType     uint32
	BInstalled     BOOL
}

/*
GROUP_POLICY_OBJECT_TYPE is generated from Windows.Win32 metadata.
*/
type GROUP_POLICY_OBJECT_TYPE int32

const (
	/*
		GPOTypeLocal from Windows.Win32 metadata.
	*/
	GPOTypeLocal GROUP_POLICY_OBJECT_TYPE = 0x0

	/*
		GPOTypeRemote from Windows.Win32 metadata.
	*/
	GPOTypeRemote GROUP_POLICY_OBJECT_TYPE = 0x1

	/*
		GPOTypeDS from Windows.Win32 metadata.
	*/
	GPOTypeDS GROUP_POLICY_OBJECT_TYPE = 0x2

	/*
		GPOTypeLocalUser from Windows.Win32 metadata.
	*/
	GPOTypeLocalUser GROUP_POLICY_OBJECT_TYPE = 0x3

	/*
		GPOTypeLocalGroup from Windows.Win32 metadata.
	*/
	GPOTypeLocalGroup GROUP_POLICY_OBJECT_TYPE = 0x4
)

/*
GROUP_POLICY_HINT_TYPE is generated from Windows.Win32 metadata.
*/
type GROUP_POLICY_HINT_TYPE int32

const (
	/*
		GPHintUnknown from Windows.Win32 metadata.
	*/
	GPHintUnknown GROUP_POLICY_HINT_TYPE = 0x0

	/*
		GPHintMachine from Windows.Win32 metadata.
	*/
	GPHintMachine GROUP_POLICY_HINT_TYPE = 0x1

	/*
		GPHintSite from Windows.Win32 metadata.
	*/
	GPHintSite GROUP_POLICY_HINT_TYPE = 0x2

	/*
		GPHintDomain from Windows.Win32 metadata.
	*/
	GPHintDomain GROUP_POLICY_HINT_TYPE = 0x3

	/*
		GPHintOrganizationalUnit from Windows.Win32 metadata.
	*/
	GPHintOrganizationalUnit GROUP_POLICY_HINT_TYPE = 0x4
)

/*
IGPEInformation is generated from Windows.Win32 metadata.
*/
type IGPEInformation uintptr

/*
IGroupPolicyObject is generated from Windows.Win32 metadata.
*/
type IGroupPolicyObject uintptr

/*
IRSOPInformation is generated from Windows.Win32 metadata.
*/
type IRSOPInformation uintptr

/*
GPOBROWSEINFO is generated from Windows.Win32 metadata.
*/
type GPOBROWSEINFO struct {
	DwSize       uint32
	DwFlags      uint32
	HwndOwner    HWND
	LpTitle      *PWSTRElement
	LpInitialOU  *PWSTRElement
	LpDSPath     *PWSTRElement
	DwDSPathSize uint32
	LpName       *PWSTRElement
	DwNameSize   uint32
	GpoType      GROUP_POLICY_OBJECT_TYPE
	GpoHint      GROUP_POLICY_HINT_TYPE
}
