//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:34:45 CEST

package bindings

/*
PFN_MI_Application_InitializeV1 maps to MI_Application_InitializeV1 in mi.dll.
*/
type PFN_MI_Application_InitializeV1 func(flags uint32, applicationID *uint16, extendedError **MI_Instance, application *MI_Application) MI_Result
