//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 03:52:55 CEST

package bindings

/*
PFN_IcmpCreateFile maps to IcmpCreateFile in iphlpapi.dll.
*/
type PFN_IcmpCreateFile func() HANDLE

/*
PFN_Icmp6CreateFile maps to Icmp6CreateFile in iphlpapi.dll.
*/
type PFN_Icmp6CreateFile func() HANDLE

/*
PFN_IcmpCloseHandle maps to IcmpCloseHandle in iphlpapi.dll.
*/
type PFN_IcmpCloseHandle func(IcmpHandle HANDLE) BOOL

/*
PFN_IcmpSendEcho maps to IcmpSendEcho in iphlpapi.dll.
*/
type PFN_IcmpSendEcho func(IcmpHandle HANDLE, DestinationAddress uint32, RequestData uintptr, RequestSize uint16, RequestOptions *IP_OPTION_INFORMATION, ReplyBuffer uintptr, ReplySize uint32, Timeout uint32) uint32

/*
PFN_IcmpSendEcho2 maps to IcmpSendEcho2 in iphlpapi.dll.
*/
type PFN_IcmpSendEcho2 func(IcmpHandle HANDLE, Event HANDLE, ApcRoutine PIO_APC_ROUTINE, ApcContext uintptr, DestinationAddress uint32, RequestData uintptr, RequestSize uint16, RequestOptions *IP_OPTION_INFORMATION, ReplyBuffer uintptr, ReplySize uint32, Timeout uint32) uint32

/*
PFN_IcmpSendEcho2Ex maps to IcmpSendEcho2Ex in iphlpapi.dll.
*/
type PFN_IcmpSendEcho2Ex func(IcmpHandle HANDLE, Event HANDLE, ApcRoutine PIO_APC_ROUTINE, ApcContext uintptr, SourceAddress uint32, DestinationAddress uint32, RequestData uintptr, RequestSize uint16, RequestOptions *IP_OPTION_INFORMATION, ReplyBuffer uintptr, ReplySize uint32, Timeout uint32) uint32

/*
PFN_Icmp6SendEcho2 maps to Icmp6SendEcho2 in iphlpapi.dll.
*/
type PFN_Icmp6SendEcho2 func(IcmpHandle HANDLE, Event HANDLE, ApcRoutine PIO_APC_ROUTINE, ApcContext uintptr, SourceAddress *SOCKADDR_IN6, DestinationAddress *SOCKADDR_IN6, RequestData uintptr, RequestSize uint16, RequestOptions *IP_OPTION_INFORMATION, ReplyBuffer uintptr, ReplySize uint32, Timeout uint32) uint32

/*
PFN_IcmpParseReplies maps to IcmpParseReplies in iphlpapi.dll.
*/
type PFN_IcmpParseReplies func(ReplyBuffer uintptr, ReplySize uint32) uint32

/*
PFN_Icmp6ParseReplies maps to Icmp6ParseReplies in iphlpapi.dll.
*/
type PFN_Icmp6ParseReplies func(ReplyBuffer uintptr, ReplySize uint32) uint32

/*
PFN_GetNumberOfInterfaces maps to GetNumberOfInterfaces in iphlpapi.dll.
*/
type PFN_GetNumberOfInterfaces func(pdwNumIf *uint32) uint32

/*
PFN_GetIfEntry maps to GetIfEntry in iphlpapi.dll.
*/
type PFN_GetIfEntry func(pIfRow *MIB_IFROW) uint32

/*
PFN_GetIfTable maps to GetIfTable in iphlpapi.dll.
*/
type PFN_GetIfTable func(pIfTable *MIB_IFTABLE, pdwSize *uint32, bOrder BOOL) uint32

/*
PFN_GetIpAddrTable maps to GetIpAddrTable in iphlpapi.dll.
*/
type PFN_GetIpAddrTable func(pIpAddrTable *MIB_IPADDRTABLE, pdwSize *uint32, bOrder BOOL) uint32

/*
PFN_GetIpNetTable maps to GetIpNetTable in iphlpapi.dll.
*/
type PFN_GetIpNetTable func(IpNetTable *MIB_IPNETTABLE, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetIpForwardTable maps to GetIpForwardTable in iphlpapi.dll.
*/
type PFN_GetIpForwardTable func(pIpForwardTable *MIB_IPFORWARDTABLE, pdwSize *uint32, bOrder BOOL) uint32

/*
PFN_GetTcpTable maps to GetTcpTable in iphlpapi.dll.
*/
type PFN_GetTcpTable func(TcpTable *MIB_TCPTABLE, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetExtendedTcpTable maps to GetExtendedTcpTable in iphlpapi.dll.
*/
type PFN_GetExtendedTcpTable func(pTcpTable uintptr, pdwSize *uint32, bOrder BOOL, ulAf uint32, TableClass TCP_TABLE_CLASS, Reserved uint32) uint32

/*
PFN_GetOwnerModuleFromTcpEntry maps to GetOwnerModuleFromTcpEntry in iphlpapi.dll.
*/
type PFN_GetOwnerModuleFromTcpEntry func(pTcpEntry *MIB_TCPROW_OWNER_MODULE, Class TCPIP_OWNER_MODULE_INFO_CLASS, pBuffer uintptr, pdwSize *uint32) uint32

/*
PFN_GetUdpTable maps to GetUdpTable in iphlpapi.dll.
*/
type PFN_GetUdpTable func(UdpTable *MIB_UDPTABLE, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetExtendedUdpTable maps to GetExtendedUdpTable in iphlpapi.dll.
*/
type PFN_GetExtendedUdpTable func(pUdpTable uintptr, pdwSize *uint32, bOrder BOOL, ulAf uint32, TableClass UDP_TABLE_CLASS, Reserved uint32) uint32

/*
PFN_GetOwnerModuleFromUdpEntry maps to GetOwnerModuleFromUdpEntry in iphlpapi.dll.
*/
type PFN_GetOwnerModuleFromUdpEntry func(pUdpEntry *MIB_UDPROW_OWNER_MODULE, Class TCPIP_OWNER_MODULE_INFO_CLASS, pBuffer uintptr, pdwSize *uint32) uint32

/*
PFN_GetTcpTable2 maps to GetTcpTable2 in iphlpapi.dll.
*/
type PFN_GetTcpTable2 func(TcpTable *MIB_TCPTABLE2, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetTcp6Table maps to GetTcp6Table in iphlpapi.dll.
*/
type PFN_GetTcp6Table func(TcpTable *MIB_TCP6TABLE, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetTcp6Table2 maps to GetTcp6Table2 in iphlpapi.dll.
*/
type PFN_GetTcp6Table2 func(TcpTable *MIB_TCP6TABLE2, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetPerTcpConnectionEStats maps to GetPerTcpConnectionEStats in iphlpapi.dll.
*/
type PFN_GetPerTcpConnectionEStats func(Row *MIB_TCPROW_LH, EstatsType TCP_ESTATS_TYPE, Rw *uint8, RwVersion uint32, RwSize uint32, Ros *uint8, RosVersion uint32, RosSize uint32, Rod *uint8, RodVersion uint32, RodSize uint32) uint32

/*
PFN_SetPerTcpConnectionEStats maps to SetPerTcpConnectionEStats in iphlpapi.dll.
*/
type PFN_SetPerTcpConnectionEStats func(Row *MIB_TCPROW_LH, EstatsType TCP_ESTATS_TYPE, Rw *uint8, RwVersion uint32, RwSize uint32, Offset uint32) uint32

/*
PFN_GetPerTcp6ConnectionEStats maps to GetPerTcp6ConnectionEStats in iphlpapi.dll.
*/
type PFN_GetPerTcp6ConnectionEStats func(Row *MIB_TCP6ROW, EstatsType TCP_ESTATS_TYPE, Rw *uint8, RwVersion uint32, RwSize uint32, Ros *uint8, RosVersion uint32, RosSize uint32, Rod *uint8, RodVersion uint32, RodSize uint32) uint32

/*
PFN_SetPerTcp6ConnectionEStats maps to SetPerTcp6ConnectionEStats in iphlpapi.dll.
*/
type PFN_SetPerTcp6ConnectionEStats func(Row *MIB_TCP6ROW, EstatsType TCP_ESTATS_TYPE, Rw *uint8, RwVersion uint32, RwSize uint32, Offset uint32) uint32

/*
PFN_GetOwnerModuleFromTcp6Entry maps to GetOwnerModuleFromTcp6Entry in iphlpapi.dll.
*/
type PFN_GetOwnerModuleFromTcp6Entry func(pTcpEntry *MIB_TCP6ROW_OWNER_MODULE, Class TCPIP_OWNER_MODULE_INFO_CLASS, pBuffer uintptr, pdwSize *uint32) uint32

/*
PFN_GetUdp6Table maps to GetUdp6Table in iphlpapi.dll.
*/
type PFN_GetUdp6Table func(Udp6Table *MIB_UDP6TABLE, SizePointer *uint32, Order BOOL) uint32

/*
PFN_GetOwnerModuleFromUdp6Entry maps to GetOwnerModuleFromUdp6Entry in iphlpapi.dll.
*/
type PFN_GetOwnerModuleFromUdp6Entry func(pUdpEntry *MIB_UDP6ROW_OWNER_MODULE, Class TCPIP_OWNER_MODULE_INFO_CLASS, pBuffer uintptr, pdwSize *uint32) uint32

/*
PFN_GetOwnerModuleFromPidAndInfo maps to GetOwnerModuleFromPidAndInfo in iphlpapi.dll.
*/
type PFN_GetOwnerModuleFromPidAndInfo func(ulPid uint32, pInfo *uint64, Class TCPIP_OWNER_MODULE_INFO_CLASS, pBuffer uintptr, pdwSize *uint32) uint32

/*
PFN_GetIpStatistics maps to GetIpStatistics in iphlpapi.dll.
*/
type PFN_GetIpStatistics func(Statistics *MIB_IPSTATS_LH) uint32

/*
PFN_GetIcmpStatistics maps to GetIcmpStatistics in iphlpapi.dll.
*/
type PFN_GetIcmpStatistics func(Statistics *MIB_ICMP) uint32

/*
PFN_GetTcpStatistics maps to GetTcpStatistics in iphlpapi.dll.
*/
type PFN_GetTcpStatistics func(Statistics *MIB_TCPSTATS_LH) uint32

/*
PFN_GetUdpStatistics maps to GetUdpStatistics in iphlpapi.dll.
*/
type PFN_GetUdpStatistics func(Stats *MIB_UDPSTATS) uint32

/*
PFN_SetIpStatisticsEx maps to SetIpStatisticsEx in iphlpapi.dll.
*/
type PFN_SetIpStatisticsEx func(Statistics *MIB_IPSTATS_LH, Family uint32) uint32

/*
PFN_GetIpStatisticsEx maps to GetIpStatisticsEx in iphlpapi.dll.
*/
type PFN_GetIpStatisticsEx func(Statistics *MIB_IPSTATS_LH, Family uint32) uint32

/*
PFN_GetIcmpStatisticsEx maps to GetIcmpStatisticsEx in iphlpapi.dll.
*/
type PFN_GetIcmpStatisticsEx func(Statistics *MIB_ICMP_EX_XPSP1, Family uint32) uint32

/*
PFN_GetTcpStatisticsEx maps to GetTcpStatisticsEx in iphlpapi.dll.
*/
type PFN_GetTcpStatisticsEx func(Statistics *MIB_TCPSTATS_LH, Family uint32) uint32

/*
PFN_GetUdpStatisticsEx maps to GetUdpStatisticsEx in iphlpapi.dll.
*/
type PFN_GetUdpStatisticsEx func(Statistics *MIB_UDPSTATS, Family uint32) uint32

/*
PFN_GetTcpStatisticsEx2 maps to GetTcpStatisticsEx2 in iphlpapi.dll.
*/
type PFN_GetTcpStatisticsEx2 func(Statistics *MIB_TCPSTATS2, Family uint32) uint32

/*
PFN_GetUdpStatisticsEx2 maps to GetUdpStatisticsEx2 in iphlpapi.dll.
*/
type PFN_GetUdpStatisticsEx2 func(Statistics *MIB_UDPSTATS2, Family uint32) uint32

/*
PFN_SetIfEntry maps to SetIfEntry in iphlpapi.dll.
*/
type PFN_SetIfEntry func(pIfRow *MIB_IFROW) uint32

/*
PFN_CreateIpForwardEntry maps to CreateIpForwardEntry in iphlpapi.dll.
*/
type PFN_CreateIpForwardEntry func(pRoute *MIB_IPFORWARDROW) uint32

/*
PFN_SetIpForwardEntry maps to SetIpForwardEntry in iphlpapi.dll.
*/
type PFN_SetIpForwardEntry func(pRoute *MIB_IPFORWARDROW) uint32

/*
PFN_DeleteIpForwardEntry maps to DeleteIpForwardEntry in iphlpapi.dll.
*/
type PFN_DeleteIpForwardEntry func(pRoute *MIB_IPFORWARDROW) uint32

/*
PFN_SetIpStatistics maps to SetIpStatistics in iphlpapi.dll.
*/
type PFN_SetIpStatistics func(pIpStats *MIB_IPSTATS_LH) uint32

/*
PFN_SetIpTTL maps to SetIpTTL in iphlpapi.dll.
*/
type PFN_SetIpTTL func(nTTL uint32) uint32

/*
PFN_CreateIpNetEntry maps to CreateIpNetEntry in iphlpapi.dll.
*/
type PFN_CreateIpNetEntry func(pArpEntry *MIB_IPNETROW_LH) uint32

/*
PFN_SetIpNetEntry maps to SetIpNetEntry in iphlpapi.dll.
*/
type PFN_SetIpNetEntry func(pArpEntry *MIB_IPNETROW_LH) uint32

/*
PFN_DeleteIpNetEntry maps to DeleteIpNetEntry in iphlpapi.dll.
*/
type PFN_DeleteIpNetEntry func(pArpEntry *MIB_IPNETROW_LH) uint32

/*
PFN_FlushIpNetTable maps to FlushIpNetTable in iphlpapi.dll.
*/
type PFN_FlushIpNetTable func(dwIfIndex uint32) uint32

/*
PFN_CreateProxyArpEntry maps to CreateProxyArpEntry in iphlpapi.dll.
*/
type PFN_CreateProxyArpEntry func(dwAddress uint32, dwMask uint32, dwIfIndex uint32) uint32

/*
PFN_DeleteProxyArpEntry maps to DeleteProxyArpEntry in iphlpapi.dll.
*/
type PFN_DeleteProxyArpEntry func(dwAddress uint32, dwMask uint32, dwIfIndex uint32) uint32

/*
PFN_SetTcpEntry maps to SetTcpEntry in iphlpapi.dll.
*/
type PFN_SetTcpEntry func(pTcpRow *MIB_TCPROW_LH) uint32

/*
PFN_GetInterfaceInfo maps to GetInterfaceInfo in iphlpapi.dll.
*/
type PFN_GetInterfaceInfo func(pIfTable *IP_INTERFACE_INFO, dwOutBufLen *uint32) uint32

/*
PFN_GetUniDirectionalAdapterInfo maps to GetUniDirectionalAdapterInfo in iphlpapi.dll.
*/
type PFN_GetUniDirectionalAdapterInfo func(pIPIfInfo *IP_UNIDIRECTIONAL_ADAPTER_ADDRESS, dwOutBufLen *uint32) uint32

/*
PFN_NhpAllocateAndGetInterfaceInfoFromStack maps to NhpAllocateAndGetInterfaceInfoFromStack in iphlpapi.dll.
*/
type PFN_NhpAllocateAndGetInterfaceInfoFromStack func(ppTable **IP_INTERFACE_NAME_INFO_W2KSP1, pdwCount *uint32, bOrder BOOL, hHeap HANDLE, dwFlags uint32) uint32

/*
PFN_GetBestInterface maps to GetBestInterface in iphlpapi.dll.
*/
type PFN_GetBestInterface func(dwDestAddr uint32, pdwBestIfIndex *uint32) uint32

/*
PFN_GetBestInterfaceEx maps to GetBestInterfaceEx in iphlpapi.dll.
*/
type PFN_GetBestInterfaceEx func(pDestAddr *SOCKADDR, pdwBestIfIndex *uint32) uint32

/*
PFN_GetBestRoute maps to GetBestRoute in iphlpapi.dll.
*/
type PFN_GetBestRoute func(dwDestAddr uint32, dwSourceAddr uint32, pBestRoute *MIB_IPFORWARDROW) uint32

/*
PFN_NotifyAddrChange maps to NotifyAddrChange in iphlpapi.dll.
*/
type PFN_NotifyAddrChange func(Handle *HANDLE, overlapped *OVERLAPPED) uint32

/*
PFN_NotifyRouteChange maps to NotifyRouteChange in iphlpapi.dll.
*/
type PFN_NotifyRouteChange func(Handle *HANDLE, overlapped *OVERLAPPED) uint32

/*
PFN_CancelIPChangeNotify maps to CancelIPChangeNotify in iphlpapi.dll.
*/
type PFN_CancelIPChangeNotify func(notifyOverlapped *OVERLAPPED) BOOL

/*
PFN_GetAdapterIndex maps to GetAdapterIndex in iphlpapi.dll.
*/
type PFN_GetAdapterIndex func(AdapterName *PWSTRElement, IfIndex *uint32) uint32

/*
PFN_AddIPAddress maps to AddIPAddress in iphlpapi.dll.
*/
type PFN_AddIPAddress func(Address uint32, IpMask uint32, IfIndex uint32, NTEContext *uint32, NTEInstance *uint32) uint32

/*
PFN_DeleteIPAddress maps to DeleteIPAddress in iphlpapi.dll.
*/
type PFN_DeleteIPAddress func(NTEContext uint32) uint32

/*
PFN_GetNetworkParams maps to GetNetworkParams in iphlpapi.dll.
*/
type PFN_GetNetworkParams func(pFixedInfo *FIXED_INFO_W2KSP1, pOutBufLen *uint32) WIN32_ERROR

/*
PFN_GetAdaptersInfo maps to GetAdaptersInfo in iphlpapi.dll.
*/
type PFN_GetAdaptersInfo func(AdapterInfo *IP_ADAPTER_INFO, SizePointer *uint32) uint32

/*
PFN_GetAdapterOrderMap maps to GetAdapterOrderMap in iphlpapi.dll.
*/
type PFN_GetAdapterOrderMap func() *IP_ADAPTER_ORDER_MAP

/*
PFN_GetAdaptersAddresses maps to GetAdaptersAddresses in iphlpapi.dll.
*/
type PFN_GetAdaptersAddresses func(Family uint32, Flags GET_ADAPTERS_ADDRESSES_FLAGS, Reserved uintptr, AdapterAddresses *IP_ADAPTER_ADDRESSES_LH, SizePointer *uint32) uint32

/*
PFN_GetPerAdapterInfo maps to GetPerAdapterInfo in iphlpapi.dll.
*/
type PFN_GetPerAdapterInfo func(IfIndex uint32, pPerAdapterInfo *IP_PER_ADAPTER_INFO_W2KSP1, pOutBufLen *uint32) uint32

/*
PFN_GetInterfaceActiveTimestampCapabilities maps to GetInterfaceActiveTimestampCapabilities in iphlpapi.dll.
*/
type PFN_GetInterfaceActiveTimestampCapabilities func(InterfaceLuid *NET_LUID_LH, TimestampCapabilites *INTERFACE_TIMESTAMP_CAPABILITIES) uint32

/*
PFN_GetInterfaceSupportedTimestampCapabilities maps to GetInterfaceSupportedTimestampCapabilities in iphlpapi.dll.
*/
type PFN_GetInterfaceSupportedTimestampCapabilities func(InterfaceLuid *NET_LUID_LH, TimestampCapabilites *INTERFACE_TIMESTAMP_CAPABILITIES) uint32

/*
PFN_CaptureInterfaceHardwareCrossTimestamp maps to CaptureInterfaceHardwareCrossTimestamp in iphlpapi.dll.
*/
type PFN_CaptureInterfaceHardwareCrossTimestamp func(InterfaceLuid *NET_LUID_LH, CrossTimestamp *INTERFACE_HARDWARE_CROSSTIMESTAMP) uint32

/*
PFN_RegisterInterfaceTimestampConfigChange maps to RegisterInterfaceTimestampConfigChange in iphlpapi.dll.
*/
type PFN_RegisterInterfaceTimestampConfigChange func(Callback PINTERFACE_TIMESTAMP_CONFIG_CHANGE_CALLBACK, CallerContext uintptr, NotificationHandle *HIFTIMESTAMPCHANGE) uint32

/*
PFN_UnregisterInterfaceTimestampConfigChange maps to UnregisterInterfaceTimestampConfigChange in iphlpapi.dll.
*/
type PFN_UnregisterInterfaceTimestampConfigChange func(NotificationHandle HIFTIMESTAMPCHANGE)

/*
PFN_GetInterfaceCurrentTimestampCapabilities maps to GetInterfaceCurrentTimestampCapabilities in iphlpapi.dll.
*/
type PFN_GetInterfaceCurrentTimestampCapabilities func(InterfaceLuid *NET_LUID_LH, TimestampCapabilites *INTERFACE_TIMESTAMP_CAPABILITIES) uint32

/*
PFN_GetInterfaceHardwareTimestampCapabilities maps to GetInterfaceHardwareTimestampCapabilities in iphlpapi.dll.
*/
type PFN_GetInterfaceHardwareTimestampCapabilities func(InterfaceLuid *NET_LUID_LH, TimestampCapabilites *INTERFACE_TIMESTAMP_CAPABILITIES) uint32

/*
PFN_NotifyIfTimestampConfigChange maps to NotifyIfTimestampConfigChange in iphlpapi.dll.
*/
type PFN_NotifyIfTimestampConfigChange func(CallerContext uintptr, Callback PINTERFACE_TIMESTAMP_CONFIG_CHANGE_CALLBACK, NotificationHandle *HIFTIMESTAMPCHANGE) uint32

/*
PFN_CancelIfTimestampConfigChange maps to CancelIfTimestampConfigChange in iphlpapi.dll.
*/
type PFN_CancelIfTimestampConfigChange func(NotificationHandle HIFTIMESTAMPCHANGE)

/*
PFN_IpReleaseAddress maps to IpReleaseAddress in iphlpapi.dll.
*/
type PFN_IpReleaseAddress func(AdapterInfo *IP_ADAPTER_INDEX_MAP) uint32

/*
PFN_IpRenewAddress maps to IpRenewAddress in iphlpapi.dll.
*/
type PFN_IpRenewAddress func(AdapterInfo *IP_ADAPTER_INDEX_MAP) uint32

/*
PFN_SendARP maps to SendARP in iphlpapi.dll.
*/
type PFN_SendARP func(DestIP uint32, SrcIP uint32, pMacAddr uintptr, PhyAddrLen *uint32) uint32

/*
PFN_GetRTTAndHopCount maps to GetRTTAndHopCount in iphlpapi.dll.
*/
type PFN_GetRTTAndHopCount func(DestIpAddress uint32, HopCount *uint32, MaxHops uint32, RTT *uint32) BOOL

/*
PFN_GetFriendlyIfIndex maps to GetFriendlyIfIndex in iphlpapi.dll.
*/
type PFN_GetFriendlyIfIndex func(IfIndex uint32) uint32

/*
PFN_EnableRouter maps to EnableRouter in iphlpapi.dll.
*/
type PFN_EnableRouter func(pHandle *HANDLE, pOverlapped *OVERLAPPED) uint32

/*
PFN_UnenableRouter maps to UnenableRouter in iphlpapi.dll.
*/
type PFN_UnenableRouter func(pOverlapped *OVERLAPPED, lpdwEnableCount *uint32) uint32

/*
PFN_DisableMediaSense maps to DisableMediaSense in iphlpapi.dll.
*/
type PFN_DisableMediaSense func(pHandle *HANDLE, pOverLapped *OVERLAPPED) uint32

/*
PFN_RestoreMediaSense maps to RestoreMediaSense in iphlpapi.dll.
*/
type PFN_RestoreMediaSense func(pOverlapped *OVERLAPPED, lpdwEnableCount *uint32) uint32

/*
PFN_GetIpErrorString maps to GetIpErrorString in iphlpapi.dll.
*/
type PFN_GetIpErrorString func(ErrorCode uint32, Buffer *PWSTRElement, Size *uint32) uint32

/*
PFN_ResolveNeighbor maps to ResolveNeighbor in iphlpapi.dll.
*/
type PFN_ResolveNeighbor func(NetworkAddress *SOCKADDR, PhysicalAddress uintptr, PhysicalAddressLength *uint32) uint32

/*
PFN_CreatePersistentTcpPortReservation maps to CreatePersistentTcpPortReservation in iphlpapi.dll.
*/
type PFN_CreatePersistentTcpPortReservation func(StartPort uint16, NumberOfPorts uint16, Token *uint64) uint32

/*
PFN_CreatePersistentUdpPortReservation maps to CreatePersistentUdpPortReservation in iphlpapi.dll.
*/
type PFN_CreatePersistentUdpPortReservation func(StartPort uint16, NumberOfPorts uint16, Token *uint64) uint32

/*
PFN_DeletePersistentTcpPortReservation maps to DeletePersistentTcpPortReservation in iphlpapi.dll.
*/
type PFN_DeletePersistentTcpPortReservation func(StartPort uint16, NumberOfPorts uint16) uint32

/*
PFN_DeletePersistentUdpPortReservation maps to DeletePersistentUdpPortReservation in iphlpapi.dll.
*/
type PFN_DeletePersistentUdpPortReservation func(StartPort uint16, NumberOfPorts uint16) uint32

/*
PFN_LookupPersistentTcpPortReservation maps to LookupPersistentTcpPortReservation in iphlpapi.dll.
*/
type PFN_LookupPersistentTcpPortReservation func(StartPort uint16, NumberOfPorts uint16, Token *uint64) uint32

/*
PFN_LookupPersistentUdpPortReservation maps to LookupPersistentUdpPortReservation in iphlpapi.dll.
*/
type PFN_LookupPersistentUdpPortReservation func(StartPort uint16, NumberOfPorts uint16, Token *uint64) uint32

/*
PFN_ParseNetworkString maps to ParseNetworkString in iphlpapi.dll.
*/
type PFN_ParseNetworkString func(NetworkString *PWSTRElement, Types uint32, AddressInfo *NET_ADDRESS_INFO, PortNumber *uint16, PrefixLength *uint8) uint32

/*
PFN_GetIfEntry2 maps to GetIfEntry2 in iphlpapi.dll.
*/
type PFN_GetIfEntry2 func(Row *MIB_IF_ROW2) WIN32_ERROR

/*
PFN_GetIfEntry2Ex maps to GetIfEntry2Ex in iphlpapi.dll.
*/
type PFN_GetIfEntry2Ex func(Level MIB_IF_ENTRY_LEVEL, Row *MIB_IF_ROW2) WIN32_ERROR

/*
PFN_GetIfTable2 maps to GetIfTable2 in iphlpapi.dll.
*/
type PFN_GetIfTable2 func(Table **MIB_IF_TABLE2) WIN32_ERROR

/*
PFN_GetIfTable2Ex maps to GetIfTable2Ex in iphlpapi.dll.
*/
type PFN_GetIfTable2Ex func(Level MIB_IF_TABLE_LEVEL, Table **MIB_IF_TABLE2) WIN32_ERROR

/*
PFN_GetIfStackTable maps to GetIfStackTable in iphlpapi.dll.
*/
type PFN_GetIfStackTable func(Table **MIB_IFSTACK_TABLE) WIN32_ERROR

/*
PFN_GetInvertedIfStackTable maps to GetInvertedIfStackTable in iphlpapi.dll.
*/
type PFN_GetInvertedIfStackTable func(Table **MIB_INVERTEDIFSTACK_TABLE) WIN32_ERROR

/*
PFN_GetIpInterfaceEntry maps to GetIpInterfaceEntry in iphlpapi.dll.
*/
type PFN_GetIpInterfaceEntry func(Row *MIB_IPINTERFACE_ROW) WIN32_ERROR

/*
PFN_GetIpInterfaceTable maps to GetIpInterfaceTable in iphlpapi.dll.
*/
type PFN_GetIpInterfaceTable func(Family ADDRESS_FAMILY, Table **MIB_IPINTERFACE_TABLE) WIN32_ERROR

/*
PFN_InitializeIpInterfaceEntry maps to InitializeIpInterfaceEntry in iphlpapi.dll.
*/
type PFN_InitializeIpInterfaceEntry func(Row *MIB_IPINTERFACE_ROW)

/*
PFN_NotifyIpInterfaceChange maps to NotifyIpInterfaceChange in iphlpapi.dll.
*/
type PFN_NotifyIpInterfaceChange func(Family ADDRESS_FAMILY, Callback PIPINTERFACE_CHANGE_CALLBACK, CallerContext uintptr, InitialNotification BOOLEAN, NotificationHandle *HANDLE) WIN32_ERROR

/*
PFN_SetIpInterfaceEntry maps to SetIpInterfaceEntry in iphlpapi.dll.
*/
type PFN_SetIpInterfaceEntry func(Row *MIB_IPINTERFACE_ROW) WIN32_ERROR

/*
PFN_GetIpNetworkConnectionBandwidthEstimates maps to GetIpNetworkConnectionBandwidthEstimates in iphlpapi.dll.
*/
type PFN_GetIpNetworkConnectionBandwidthEstimates func(InterfaceIndex uint32, AddressFamily ADDRESS_FAMILY, BandwidthEstimates *MIB_IP_NETWORK_CONNECTION_BANDWIDTH_ESTIMATES) WIN32_ERROR

/*
PFN_CreateUnicastIpAddressEntry maps to CreateUnicastIpAddressEntry in iphlpapi.dll.
*/
type PFN_CreateUnicastIpAddressEntry func(Row *MIB_UNICASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_DeleteUnicastIpAddressEntry maps to DeleteUnicastIpAddressEntry in iphlpapi.dll.
*/
type PFN_DeleteUnicastIpAddressEntry func(Row *MIB_UNICASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_GetUnicastIpAddressEntry maps to GetUnicastIpAddressEntry in iphlpapi.dll.
*/
type PFN_GetUnicastIpAddressEntry func(Row *MIB_UNICASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_GetUnicastIpAddressTable maps to GetUnicastIpAddressTable in iphlpapi.dll.
*/
type PFN_GetUnicastIpAddressTable func(Family ADDRESS_FAMILY, Table **MIB_UNICASTIPADDRESS_TABLE) WIN32_ERROR

/*
PFN_InitializeUnicastIpAddressEntry maps to InitializeUnicastIpAddressEntry in iphlpapi.dll.
*/
type PFN_InitializeUnicastIpAddressEntry func(Row *MIB_UNICASTIPADDRESS_ROW)

/*
PFN_NotifyUnicastIpAddressChange maps to NotifyUnicastIpAddressChange in iphlpapi.dll.
*/
type PFN_NotifyUnicastIpAddressChange func(Family ADDRESS_FAMILY, Callback PUNICAST_IPADDRESS_CHANGE_CALLBACK, CallerContext uintptr, InitialNotification BOOLEAN, NotificationHandle *HANDLE) WIN32_ERROR

/*
PFN_NotifyStableUnicastIpAddressTable maps to NotifyStableUnicastIpAddressTable in iphlpapi.dll.
*/
type PFN_NotifyStableUnicastIpAddressTable func(Family ADDRESS_FAMILY, Table **MIB_UNICASTIPADDRESS_TABLE, CallerCallback PSTABLE_UNICAST_IPADDRESS_TABLE_CALLBACK, CallerContext uintptr, NotificationHandle *HANDLE) WIN32_ERROR

/*
PFN_SetUnicastIpAddressEntry maps to SetUnicastIpAddressEntry in iphlpapi.dll.
*/
type PFN_SetUnicastIpAddressEntry func(Row *MIB_UNICASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_CreateAnycastIpAddressEntry maps to CreateAnycastIpAddressEntry in iphlpapi.dll.
*/
type PFN_CreateAnycastIpAddressEntry func(Row *MIB_ANYCASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_DeleteAnycastIpAddressEntry maps to DeleteAnycastIpAddressEntry in iphlpapi.dll.
*/
type PFN_DeleteAnycastIpAddressEntry func(Row *MIB_ANYCASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_GetAnycastIpAddressEntry maps to GetAnycastIpAddressEntry in iphlpapi.dll.
*/
type PFN_GetAnycastIpAddressEntry func(Row *MIB_ANYCASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_GetAnycastIpAddressTable maps to GetAnycastIpAddressTable in iphlpapi.dll.
*/
type PFN_GetAnycastIpAddressTable func(Family ADDRESS_FAMILY, Table **MIB_ANYCASTIPADDRESS_TABLE) WIN32_ERROR

/*
PFN_GetMulticastIpAddressEntry maps to GetMulticastIpAddressEntry in iphlpapi.dll.
*/
type PFN_GetMulticastIpAddressEntry func(Row *MIB_MULTICASTIPADDRESS_ROW) WIN32_ERROR

/*
PFN_GetMulticastIpAddressTable maps to GetMulticastIpAddressTable in iphlpapi.dll.
*/
type PFN_GetMulticastIpAddressTable func(Family ADDRESS_FAMILY, Table **MIB_MULTICASTIPADDRESS_TABLE) WIN32_ERROR

/*
PFN_CreateIpForwardEntry2 maps to CreateIpForwardEntry2 in iphlpapi.dll.
*/
type PFN_CreateIpForwardEntry2 func(Row *MIB_IPFORWARD_ROW2) WIN32_ERROR

/*
PFN_DeleteIpForwardEntry2 maps to DeleteIpForwardEntry2 in iphlpapi.dll.
*/
type PFN_DeleteIpForwardEntry2 func(Row *MIB_IPFORWARD_ROW2) WIN32_ERROR

/*
PFN_GetBestRoute2 maps to GetBestRoute2 in iphlpapi.dll.
*/
type PFN_GetBestRoute2 func(InterfaceLuid *NET_LUID_LH, InterfaceIndex uint32, SourceAddress *SOCKADDR_INET, DestinationAddress *SOCKADDR_INET, AddressSortOptions uint32, BestRoute *MIB_IPFORWARD_ROW2, BestSourceAddress *SOCKADDR_INET) WIN32_ERROR

/*
PFN_GetIpForwardEntry2 maps to GetIpForwardEntry2 in iphlpapi.dll.
*/
type PFN_GetIpForwardEntry2 func(Row *MIB_IPFORWARD_ROW2) WIN32_ERROR

/*
PFN_GetIpForwardTable2 maps to GetIpForwardTable2 in iphlpapi.dll.
*/
type PFN_GetIpForwardTable2 func(Family ADDRESS_FAMILY, Table **MIB_IPFORWARD_TABLE2) WIN32_ERROR

/*
PFN_InitializeIpForwardEntry maps to InitializeIpForwardEntry in iphlpapi.dll.
*/
type PFN_InitializeIpForwardEntry func(Row *MIB_IPFORWARD_ROW2)

/*
PFN_NotifyRouteChange2 maps to NotifyRouteChange2 in iphlpapi.dll.
*/
type PFN_NotifyRouteChange2 func(AddressFamily ADDRESS_FAMILY, Callback PIPFORWARD_CHANGE_CALLBACK, CallerContext uintptr, InitialNotification BOOLEAN, NotificationHandle *HANDLE) WIN32_ERROR

/*
PFN_SetIpForwardEntry2 maps to SetIpForwardEntry2 in iphlpapi.dll.
*/
type PFN_SetIpForwardEntry2 func(Route *MIB_IPFORWARD_ROW2) WIN32_ERROR

/*
PFN_FlushIpPathTable maps to FlushIpPathTable in iphlpapi.dll.
*/
type PFN_FlushIpPathTable func(Family ADDRESS_FAMILY) WIN32_ERROR

/*
PFN_GetIpPathEntry maps to GetIpPathEntry in iphlpapi.dll.
*/
type PFN_GetIpPathEntry func(Row *MIB_IPPATH_ROW) WIN32_ERROR

/*
PFN_GetIpPathTable maps to GetIpPathTable in iphlpapi.dll.
*/
type PFN_GetIpPathTable func(Family ADDRESS_FAMILY, Table **MIB_IPPATH_TABLE) WIN32_ERROR

/*
PFN_CreateIpNetEntry2 maps to CreateIpNetEntry2 in iphlpapi.dll.
*/
type PFN_CreateIpNetEntry2 func(Row *MIB_IPNET_ROW2) WIN32_ERROR

/*
PFN_DeleteIpNetEntry2 maps to DeleteIpNetEntry2 in iphlpapi.dll.
*/
type PFN_DeleteIpNetEntry2 func(Row *MIB_IPNET_ROW2) WIN32_ERROR

/*
PFN_FlushIpNetTable2 maps to FlushIpNetTable2 in iphlpapi.dll.
*/
type PFN_FlushIpNetTable2 func(Family ADDRESS_FAMILY, InterfaceIndex uint32) WIN32_ERROR

/*
PFN_GetIpNetEntry2 maps to GetIpNetEntry2 in iphlpapi.dll.
*/
type PFN_GetIpNetEntry2 func(Row *MIB_IPNET_ROW2) WIN32_ERROR

/*
PFN_GetIpNetTable2 maps to GetIpNetTable2 in iphlpapi.dll.
*/
type PFN_GetIpNetTable2 func(Family ADDRESS_FAMILY, Table **MIB_IPNET_TABLE2) WIN32_ERROR

/*
PFN_ResolveIpNetEntry2 maps to ResolveIpNetEntry2 in iphlpapi.dll.
*/
type PFN_ResolveIpNetEntry2 func(Row *MIB_IPNET_ROW2, SourceAddress *SOCKADDR_INET) WIN32_ERROR

/*
PFN_SetIpNetEntry2 maps to SetIpNetEntry2 in iphlpapi.dll.
*/
type PFN_SetIpNetEntry2 func(Row *MIB_IPNET_ROW2) WIN32_ERROR

/*
PFN_NotifyTeredoPortChange maps to NotifyTeredoPortChange in iphlpapi.dll.
*/
type PFN_NotifyTeredoPortChange func(Callback PTEREDO_PORT_CHANGE_CALLBACK, CallerContext uintptr, InitialNotification BOOLEAN, NotificationHandle *HANDLE) WIN32_ERROR

/*
PFN_GetTeredoPort maps to GetTeredoPort in iphlpapi.dll.
*/
type PFN_GetTeredoPort func(Port *uint16) WIN32_ERROR

/*
PFN_CancelMibChangeNotify2 maps to CancelMibChangeNotify2 in iphlpapi.dll.
*/
type PFN_CancelMibChangeNotify2 func(NotificationHandle HANDLE) WIN32_ERROR

/*
PFN_FreeMibTable maps to FreeMibTable in iphlpapi.dll.
*/
type PFN_FreeMibTable func(Memory uintptr)

/*
PFN_CreateSortedAddressPairs maps to CreateSortedAddressPairs in iphlpapi.dll.
*/
type PFN_CreateSortedAddressPairs func(SourceAddressList *SOCKADDR_IN6, SourceAddressCount uint32, DestinationAddressList *SOCKADDR_IN6, DestinationAddressCount uint32, AddressSortOptions uint32, SortedAddressPairList **SOCKADDR_IN6_PAIR, SortedAddressPairCount *uint32) WIN32_ERROR

/*
PFN_ConvertCompartmentGuidToId maps to ConvertCompartmentGuidToId in iphlpapi.dll.
*/
type PFN_ConvertCompartmentGuidToId func(CompartmentGuid *Guid, CompartmentId *uint32) WIN32_ERROR

/*
PFN_ConvertCompartmentIdToGuid maps to ConvertCompartmentIdToGuid in iphlpapi.dll.
*/
type PFN_ConvertCompartmentIdToGuid func(CompartmentId uint32, CompartmentGuid *Guid) WIN32_ERROR

/*
PFN_ConvertInterfaceNameToLuidA maps to ConvertInterfaceNameToLuidA in iphlpapi.dll.
*/
type PFN_ConvertInterfaceNameToLuidA func(InterfaceName *PSTRElement, InterfaceLuid *NET_LUID_LH) WIN32_ERROR

/*
PFN_ConvertInterfaceNameToLuidW maps to ConvertInterfaceNameToLuidW in iphlpapi.dll.
*/
type PFN_ConvertInterfaceNameToLuidW func(InterfaceName *PWSTRElement, InterfaceLuid *NET_LUID_LH) WIN32_ERROR

/*
PFN_ConvertInterfaceLuidToNameA maps to ConvertInterfaceLuidToNameA in iphlpapi.dll.
*/
type PFN_ConvertInterfaceLuidToNameA func(InterfaceLuid *NET_LUID_LH, InterfaceName *PSTRElement, Length uintptr) WIN32_ERROR

/*
PFN_ConvertInterfaceLuidToNameW maps to ConvertInterfaceLuidToNameW in iphlpapi.dll.
*/
type PFN_ConvertInterfaceLuidToNameW func(InterfaceLuid *NET_LUID_LH, InterfaceName *PWSTRElement, Length uintptr) WIN32_ERROR

/*
PFN_ConvertInterfaceLuidToIndex maps to ConvertInterfaceLuidToIndex in iphlpapi.dll.
*/
type PFN_ConvertInterfaceLuidToIndex func(InterfaceLuid *NET_LUID_LH, InterfaceIndex *uint32) WIN32_ERROR

/*
PFN_ConvertInterfaceIndexToLuid maps to ConvertInterfaceIndexToLuid in iphlpapi.dll.
*/
type PFN_ConvertInterfaceIndexToLuid func(InterfaceIndex uint32, InterfaceLuid *NET_LUID_LH) WIN32_ERROR

/*
PFN_ConvertInterfaceLuidToAlias maps to ConvertInterfaceLuidToAlias in iphlpapi.dll.
*/
type PFN_ConvertInterfaceLuidToAlias func(InterfaceLuid *NET_LUID_LH, InterfaceAlias *PWSTRElement, Length uintptr) WIN32_ERROR

/*
PFN_ConvertInterfaceAliasToLuid maps to ConvertInterfaceAliasToLuid in iphlpapi.dll.
*/
type PFN_ConvertInterfaceAliasToLuid func(InterfaceAlias *PWSTRElement, InterfaceLuid *NET_LUID_LH) WIN32_ERROR

/*
PFN_ConvertInterfaceLuidToGuid maps to ConvertInterfaceLuidToGuid in iphlpapi.dll.
*/
type PFN_ConvertInterfaceLuidToGuid func(InterfaceLuid *NET_LUID_LH, InterfaceGuid *Guid) WIN32_ERROR

/*
PFN_ConvertInterfaceGuidToLuid maps to ConvertInterfaceGuidToLuid in iphlpapi.dll.
*/
type PFN_ConvertInterfaceGuidToLuid func(InterfaceGuid *Guid, InterfaceLuid *NET_LUID_LH) WIN32_ERROR

/*
PFN_If_nametoindex maps to If_nametoindex in iphlpapi.dll.
*/
type PFN_If_nametoindex func(InterfaceName *PSTRElement) uint32

/*
PFN_If_indextoname maps to If_indextoname in iphlpapi.dll.
*/
type PFN_If_indextoname func(InterfaceIndex uint32, InterfaceName *PSTRElement) *PSTRElement

/*
PFN_GetCurrentThreadCompartmentId maps to GetCurrentThreadCompartmentId in iphlpapi.dll.
*/
type PFN_GetCurrentThreadCompartmentId func() WIN32_ERROR

/*
PFN_SetCurrentThreadCompartmentId maps to SetCurrentThreadCompartmentId in iphlpapi.dll.
*/
type PFN_SetCurrentThreadCompartmentId func(CompartmentId uint32) WIN32_ERROR

/*
PFN_GetCurrentThreadCompartmentScope maps to GetCurrentThreadCompartmentScope in iphlpapi.dll.
*/
type PFN_GetCurrentThreadCompartmentScope func(CompartmentScope *uint32, CompartmentId *uint32)

/*
PFN_SetCurrentThreadCompartmentScope maps to SetCurrentThreadCompartmentScope in iphlpapi.dll.
*/
type PFN_SetCurrentThreadCompartmentScope func(CompartmentScope uint32) WIN32_ERROR

/*
PFN_GetJobCompartmentId maps to GetJobCompartmentId in iphlpapi.dll.
*/
type PFN_GetJobCompartmentId func(JobHandle HANDLE) uint32

/*
PFN_SetJobCompartmentId maps to SetJobCompartmentId in iphlpapi.dll.
*/
type PFN_SetJobCompartmentId func(JobHandle HANDLE, CompartmentId uint32) WIN32_ERROR

/*
PFN_GetSessionCompartmentId maps to GetSessionCompartmentId in iphlpapi.dll.
*/
type PFN_GetSessionCompartmentId func(SessionId uint32) WIN32_ERROR

/*
PFN_SetSessionCompartmentId maps to SetSessionCompartmentId in iphlpapi.dll.
*/
type PFN_SetSessionCompartmentId func(SessionId uint32, CompartmentId uint32) WIN32_ERROR

/*
PFN_GetDefaultCompartmentId maps to GetDefaultCompartmentId in iphlpapi.dll.
*/
type PFN_GetDefaultCompartmentId func() WIN32_ERROR

/*
PFN_GetNetworkInformation maps to GetNetworkInformation in iphlpapi.dll.
*/
type PFN_GetNetworkInformation func(NetworkGuid *Guid, CompartmentId *uint32, SiteId *uint32, NetworkName *PWSTRElement, Length uint32) WIN32_ERROR

/*
PFN_SetNetworkInformation maps to SetNetworkInformation in iphlpapi.dll.
*/
type PFN_SetNetworkInformation func(NetworkGuid *Guid, CompartmentId uint32, NetworkName *PWSTRElement) WIN32_ERROR

/*
PFN_ConvertLengthToIpv4Mask maps to ConvertLengthToIpv4Mask in iphlpapi.dll.
*/
type PFN_ConvertLengthToIpv4Mask func(MaskLength uint32, Mask *uint32) WIN32_ERROR

/*
PFN_ConvertIpv4MaskToLength maps to ConvertIpv4MaskToLength in iphlpapi.dll.
*/
type PFN_ConvertIpv4MaskToLength func(Mask uint32, MaskLength *uint8) WIN32_ERROR

/*
PFN_GetDnsSettings maps to GetDnsSettings in iphlpapi.dll.
*/
type PFN_GetDnsSettings func(Settings *DNS_SETTINGS) WIN32_ERROR

/*
PFN_FreeDnsSettings maps to FreeDnsSettings in iphlpapi.dll.
*/
type PFN_FreeDnsSettings func(Settings *DNS_SETTINGS)

/*
PFN_SetDnsSettings maps to SetDnsSettings in iphlpapi.dll.
*/
type PFN_SetDnsSettings func(Settings *DNS_SETTINGS) WIN32_ERROR

/*
PFN_GetInterfaceDnsSettings maps to GetInterfaceDnsSettings in iphlpapi.dll.
*/
type PFN_GetInterfaceDnsSettings func(Interface Guid, Settings *DNS_INTERFACE_SETTINGS) WIN32_ERROR

/*
PFN_FreeInterfaceDnsSettings maps to FreeInterfaceDnsSettings in iphlpapi.dll.
*/
type PFN_FreeInterfaceDnsSettings func(Settings *DNS_INTERFACE_SETTINGS)

/*
PFN_SetInterfaceDnsSettings maps to SetInterfaceDnsSettings in iphlpapi.dll.
*/
type PFN_SetInterfaceDnsSettings func(Interface Guid, Settings *DNS_INTERFACE_SETTINGS) WIN32_ERROR

/*
PFN_GetNetworkConnectivityHint maps to GetNetworkConnectivityHint in iphlpapi.dll.
*/
type PFN_GetNetworkConnectivityHint func(ConnectivityHint *NL_NETWORK_CONNECTIVITY_HINT) WIN32_ERROR

/*
PFN_GetNetworkConnectivityHintForInterface maps to GetNetworkConnectivityHintForInterface in iphlpapi.dll.
*/
type PFN_GetNetworkConnectivityHintForInterface func(InterfaceIndex uint32, ConnectivityHint *NL_NETWORK_CONNECTIVITY_HINT) WIN32_ERROR

/*
PFN_NotifyNetworkConnectivityHintChange maps to NotifyNetworkConnectivityHintChange in iphlpapi.dll.
*/
type PFN_NotifyNetworkConnectivityHintChange func(Callback PNETWORK_CONNECTIVITY_HINT_CHANGE_CALLBACK, CallerContext uintptr, InitialNotification BOOLEAN, NotificationHandle *HANDLE) WIN32_ERROR

/*
PFN_PfCreateInterface maps to PfCreateInterface in iphlpapi.dll.
*/
type PFN_PfCreateInterface func(dwName uint32, inAction PFFORWARD_ACTION, outAction PFFORWARD_ACTION, bUseLog BOOL, bMustBeUnique BOOL, ppInterface *uintptr) uint32

/*
PFN_PfDeleteInterface maps to PfDeleteInterface in iphlpapi.dll.
*/
type PFN_PfDeleteInterface func(pInterface uintptr) uint32

/*
PFN_PfAddFiltersToInterface maps to PfAddFiltersToInterface in iphlpapi.dll.
*/
type PFN_PfAddFiltersToInterface func(ih uintptr, cInFilters uint32, pfiltIn *PF_FILTER_DESCRIPTOR, cOutFilters uint32, pfiltOut *PF_FILTER_DESCRIPTOR, pfHandle *uintptr) uint32

/*
PFN_PfRemoveFiltersFromInterface maps to PfRemoveFiltersFromInterface in iphlpapi.dll.
*/
type PFN_PfRemoveFiltersFromInterface func(ih uintptr, cInFilters uint32, pfiltIn *PF_FILTER_DESCRIPTOR, cOutFilters uint32, pfiltOut *PF_FILTER_DESCRIPTOR) uint32

/*
PFN_PfRemoveFilterHandles maps to PfRemoveFilterHandles in iphlpapi.dll.
*/
type PFN_PfRemoveFilterHandles func(pInterface uintptr, cFilters uint32, pvHandles *uintptr) uint32

/*
PFN_PfUnBindInterface maps to PfUnBindInterface in iphlpapi.dll.
*/
type PFN_PfUnBindInterface func(pInterface uintptr) uint32

/*
PFN_PfBindInterfaceToIndex maps to PfBindInterfaceToIndex in iphlpapi.dll.
*/
type PFN_PfBindInterfaceToIndex func(pInterface uintptr, dwIndex uint32, pfatLinkType PFADDRESSTYPE, LinkIPAddress *uint8) uint32

/*
PFN_PfBindInterfaceToIPAddress maps to PfBindInterfaceToIPAddress in iphlpapi.dll.
*/
type PFN_PfBindInterfaceToIPAddress func(pInterface uintptr, pfatType PFADDRESSTYPE, IPAddress *uint8) uint32

/*
PFN_PfRebindFilters maps to PfRebindFilters in iphlpapi.dll.
*/
type PFN_PfRebindFilters func(pInterface uintptr, pLateBindInfo *PF_LATEBIND_INFO) uint32

/*
PFN_PfAddGlobalFilterToInterface maps to PfAddGlobalFilterToInterface in iphlpapi.dll.
*/
type PFN_PfAddGlobalFilterToInterface func(pInterface uintptr, gfFilter GLOBAL_FILTER) uint32

/*
PFN_PfRemoveGlobalFilterFromInterface maps to PfRemoveGlobalFilterFromInterface in iphlpapi.dll.
*/
type PFN_PfRemoveGlobalFilterFromInterface func(pInterface uintptr, gfFilter GLOBAL_FILTER) uint32

/*
PFN_PfMakeLog maps to PfMakeLog in iphlpapi.dll.
*/
type PFN_PfMakeLog func(hEvent HANDLE) uint32

/*
PFN_PfSetLogBuffer maps to PfSetLogBuffer in iphlpapi.dll.
*/
type PFN_PfSetLogBuffer func(pbBuffer *uint8, dwSize uint32, dwThreshold uint32, dwEntries uint32, pdwLoggedEntries *uint32, pdwLostEntries *uint32, pdwSizeUsed *uint32) uint32

/*
PFN_PfDeleteLog maps to PfDeleteLog in iphlpapi.dll.
*/
type PFN_PfDeleteLog func() uint32

/*
PFN_PfGetInterfaceStatistics maps to PfGetInterfaceStatistics in iphlpapi.dll.
*/
type PFN_PfGetInterfaceStatistics func(pInterface uintptr, ppfStats *PF_INTERFACE_STATS, pdwBufferSize *uint32, fResetCounters BOOL) uint32

/*
PFN_PfTestPacket maps to PfTestPacket in iphlpapi.dll.
*/
type PFN_PfTestPacket func(pInInterface uintptr, pOutInterface uintptr, cBytes uint32, pbPacket *uint8, ppAction *PFFORWARD_ACTION) uint32
