//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-26 04:19:44 CEST

package bindings

/*
PFN_CreateInteractionContext maps to CreateInteractionContext in ninput.dll.
*/
type PFN_CreateInteractionContext func(interactionContext *HINTERACTIONCONTEXT) HRESULT

/*
PFN_DestroyInteractionContext maps to DestroyInteractionContext in ninput.dll.
*/
type PFN_DestroyInteractionContext func(interactionContext HINTERACTIONCONTEXT) HRESULT

/*
PFN_RegisterOutputCallbackInteractionContext maps to RegisterOutputCallbackInteractionContext in ninput.dll.
*/
type PFN_RegisterOutputCallbackInteractionContext func(interactionContext HINTERACTIONCONTEXT, outputCallback INTERACTION_CONTEXT_OUTPUT_CALLBACK, clientData uintptr) HRESULT

/*
PFN_RegisterOutputCallbackInteractionContext2 maps to RegisterOutputCallbackInteractionContext2 in ninput.dll.
*/
type PFN_RegisterOutputCallbackInteractionContext2 func(interactionContext HINTERACTIONCONTEXT, outputCallback INTERACTION_CONTEXT_OUTPUT_CALLBACK2, clientData uintptr) HRESULT

/*
PFN_SetInteractionConfigurationInteractionContext maps to SetInteractionConfigurationInteractionContext in ninput.dll.
*/
type PFN_SetInteractionConfigurationInteractionContext func(interactionContext HINTERACTIONCONTEXT, configurationCount uint32, configuration *INTERACTION_CONTEXT_CONFIGURATION) HRESULT

/*
PFN_GetInteractionConfigurationInteractionContext maps to GetInteractionConfigurationInteractionContext in ninput.dll.
*/
type PFN_GetInteractionConfigurationInteractionContext func(interactionContext HINTERACTIONCONTEXT, configurationCount uint32, configuration *INTERACTION_CONTEXT_CONFIGURATION) HRESULT

/*
PFN_SetPropertyInteractionContext maps to SetPropertyInteractionContext in ninput.dll.
*/
type PFN_SetPropertyInteractionContext func(interactionContext HINTERACTIONCONTEXT, contextProperty INTERACTION_CONTEXT_PROPERTY, value uint32) HRESULT

/*
PFN_GetPropertyInteractionContext maps to GetPropertyInteractionContext in ninput.dll.
*/
type PFN_GetPropertyInteractionContext func(interactionContext HINTERACTIONCONTEXT, contextProperty INTERACTION_CONTEXT_PROPERTY, value *uint32) HRESULT

/*
PFN_SetInertiaParameterInteractionContext maps to SetInertiaParameterInteractionContext in ninput.dll.
*/
type PFN_SetInertiaParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, inertiaParameter INERTIA_PARAMETER, value float32) HRESULT

/*
PFN_GetInertiaParameterInteractionContext maps to GetInertiaParameterInteractionContext in ninput.dll.
*/
type PFN_GetInertiaParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, inertiaParameter INERTIA_PARAMETER, value *float32) HRESULT

/*
PFN_SetCrossSlideParametersInteractionContext maps to SetCrossSlideParametersInteractionContext in ninput.dll.
*/
type PFN_SetCrossSlideParametersInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameterCount uint32, crossSlideParameters *CROSS_SLIDE_PARAMETER) HRESULT

/*
PFN_GetCrossSlideParameterInteractionContext maps to GetCrossSlideParameterInteractionContext in ninput.dll.
*/
type PFN_GetCrossSlideParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, threshold CROSS_SLIDE_THRESHOLD, distance *float32) HRESULT

/*
PFN_SetTapParameterInteractionContext maps to SetTapParameterInteractionContext in ninput.dll.
*/
type PFN_SetTapParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter TAP_PARAMETER, value float32) HRESULT

/*
PFN_GetTapParameterInteractionContext maps to GetTapParameterInteractionContext in ninput.dll.
*/
type PFN_GetTapParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter TAP_PARAMETER, value *float32) HRESULT

/*
PFN_SetHoldParameterInteractionContext maps to SetHoldParameterInteractionContext in ninput.dll.
*/
type PFN_SetHoldParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter HOLD_PARAMETER, value float32) HRESULT

/*
PFN_GetHoldParameterInteractionContext maps to GetHoldParameterInteractionContext in ninput.dll.
*/
type PFN_GetHoldParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter HOLD_PARAMETER, value *float32) HRESULT

/*
PFN_SetTranslationParameterInteractionContext maps to SetTranslationParameterInteractionContext in ninput.dll.
*/
type PFN_SetTranslationParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter TRANSLATION_PARAMETER, value float32) HRESULT

/*
PFN_GetTranslationParameterInteractionContext maps to GetTranslationParameterInteractionContext in ninput.dll.
*/
type PFN_GetTranslationParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter TRANSLATION_PARAMETER, value *float32) HRESULT

/*
PFN_SetMouseWheelParameterInteractionContext maps to SetMouseWheelParameterInteractionContext in ninput.dll.
*/
type PFN_SetMouseWheelParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter MOUSE_WHEEL_PARAMETER, value float32) HRESULT

/*
PFN_GetMouseWheelParameterInteractionContext maps to GetMouseWheelParameterInteractionContext in ninput.dll.
*/
type PFN_GetMouseWheelParameterInteractionContext func(interactionContext HINTERACTIONCONTEXT, parameter MOUSE_WHEEL_PARAMETER, value *float32) HRESULT

/*
PFN_ResetInteractionContext maps to ResetInteractionContext in ninput.dll.
*/
type PFN_ResetInteractionContext func(interactionContext HINTERACTIONCONTEXT) HRESULT

/*
PFN_GetStateInteractionContext maps to GetStateInteractionContext in ninput.dll.
*/
type PFN_GetStateInteractionContext func(interactionContext HINTERACTIONCONTEXT, pointerInfo *POINTER_INFO, state *INTERACTION_STATE) HRESULT

/*
PFN_AddPointerInteractionContext maps to AddPointerInteractionContext in ninput.dll.
*/
type PFN_AddPointerInteractionContext func(interactionContext HINTERACTIONCONTEXT, pointerId uint32) HRESULT

/*
PFN_RemovePointerInteractionContext maps to RemovePointerInteractionContext in ninput.dll.
*/
type PFN_RemovePointerInteractionContext func(interactionContext HINTERACTIONCONTEXT, pointerId uint32) HRESULT

/*
PFN_ProcessPointerFramesInteractionContext maps to ProcessPointerFramesInteractionContext in ninput.dll.
*/
type PFN_ProcessPointerFramesInteractionContext func(interactionContext HINTERACTIONCONTEXT, entriesCount uint32, pointerCount uint32, pointerInfo *POINTER_INFO) HRESULT

/*
PFN_BufferPointerPacketsInteractionContext maps to BufferPointerPacketsInteractionContext in ninput.dll.
*/
type PFN_BufferPointerPacketsInteractionContext func(interactionContext HINTERACTIONCONTEXT, entriesCount uint32, pointerInfo *POINTER_INFO) HRESULT

/*
PFN_ProcessBufferedPacketsInteractionContext maps to ProcessBufferedPacketsInteractionContext in ninput.dll.
*/
type PFN_ProcessBufferedPacketsInteractionContext func(interactionContext HINTERACTIONCONTEXT) HRESULT

/*
PFN_ProcessInertiaInteractionContext maps to ProcessInertiaInteractionContext in ninput.dll.
*/
type PFN_ProcessInertiaInteractionContext func(interactionContext HINTERACTIONCONTEXT) HRESULT

/*
PFN_StopInteractionContext maps to StopInteractionContext in ninput.dll.
*/
type PFN_StopInteractionContext func(interactionContext HINTERACTIONCONTEXT) HRESULT

/*
PFN_SetPivotInteractionContext maps to SetPivotInteractionContext in ninput.dll.
*/
type PFN_SetPivotInteractionContext func(interactionContext HINTERACTIONCONTEXT, x float32, y float32, radius float32) HRESULT
