//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-27 08:35:22 CEST

package windows_win32_system_power

/*
EXECUTION_STATE is generated from Windows.Win32 metadata.
*/
type EXECUTION_STATE uint32

const (
	/*
		ES_AWAYMODE_REQUIRED from Windows.Win32 metadata.
	*/
	ES_AWAYMODE_REQUIRED EXECUTION_STATE = 0x40

	/*
		ES_CONTINUOUS from Windows.Win32 metadata.
	*/
	ES_CONTINUOUS EXECUTION_STATE = 0x80000000

	/*
		ES_DISPLAY_REQUIRED from Windows.Win32 metadata.
	*/
	ES_DISPLAY_REQUIRED EXECUTION_STATE = 0x2

	/*
		ES_SYSTEM_REQUIRED from Windows.Win32 metadata.
	*/
	ES_SYSTEM_REQUIRED EXECUTION_STATE = 0x1

	/*
		ES_USER_PRESENT from Windows.Win32 metadata.
	*/
	ES_USER_PRESENT EXECUTION_STATE = 0x4
)

/*
HPOWERNOTIFY is generated from Windows.Win32 metadata.
*/
type HPOWERNOTIFY uintptr

/*
LATENCY_TIME is generated from Windows.Win32 metadata.
*/
type LATENCY_TIME int32

const (
	/*
		LT_DONT_CARE from Windows.Win32 metadata.
	*/
	LT_DONT_CARE LATENCY_TIME = 0x0

	/*
		LT_LOWEST_LATENCY from Windows.Win32 metadata.
	*/
	LT_LOWEST_LATENCY LATENCY_TIME = 0x1
)

/*
POWER_REQUEST_TYPE is generated from Windows.Win32 metadata.
*/
type POWER_REQUEST_TYPE int32

const (
	/*
		PowerRequestDisplayRequired from Windows.Win32 metadata.
	*/
	PowerRequestDisplayRequired POWER_REQUEST_TYPE = 0x0

	/*
		PowerRequestSystemRequired from Windows.Win32 metadata.
	*/
	PowerRequestSystemRequired POWER_REQUEST_TYPE = 0x1

	/*
		PowerRequestAwayModeRequired from Windows.Win32 metadata.
	*/
	PowerRequestAwayModeRequired POWER_REQUEST_TYPE = 0x2

	/*
		PowerRequestExecutionRequired from Windows.Win32 metadata.
	*/
	PowerRequestExecutionRequired POWER_REQUEST_TYPE = 0x3
)

/*
SYSTEM_POWER_STATUS is generated from Windows.Win32 metadata.
*/
type SYSTEM_POWER_STATUS struct {
	ACLineStatus        uint8
	BatteryFlag         uint8
	BatteryLifePercent  uint8
	SystemStatusFlag    uint8
	BatteryLifeTime     uint32
	BatteryFullLifeTime uint32
}
