//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-27 08:35:22 CEST

package windows_win32_system_applicationinstallationandservicing

const (
	/*
		APPLY_OPTION_FAIL_IF_CLOSE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	APPLY_OPTION_FAIL_IF_CLOSE = 0x2

	/*
		APPLY_OPTION_FAIL_IF_EXACT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	APPLY_OPTION_FAIL_IF_EXACT = 0x1

	/*
		APPLY_OPTION_TEST_ONLY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	APPLY_OPTION_TEST_ONLY = 0x4

	/*
		APPLY_OPTION_VALID_FLAGS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	APPLY_OPTION_VALID_FLAGS = 0x7

	/*
		ASSEMBLYINFO_FLAG_INSTALLED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ASSEMBLYINFO_FLAG_INSTALLED = 0x1

	/*
		ASSEMBLYINFO_FLAG_PAYLOADRESIDENT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ASSEMBLYINFO_FLAG_PAYLOADRESIDENT = 0x2

	/*
		CchMaxInteger from Windows.Win32 metadata (originally typed int32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	CchMaxInteger = 0xc

	/*
		DEFAULT_DISK_ID from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	DEFAULT_DISK_ID = 0x2

	/*
		DEFAULT_FILE_SEQUENCE_START from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	DEFAULT_FILE_SEQUENCE_START = 0x2

	/*
		DEFAULT_MINIMUM_REQUIRED_MSI_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	DEFAULT_MINIMUM_REQUIRED_MSI_VERSION = 0x64

	/*
		DELTA_MAX_HASH_SIZE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	DELTA_MAX_HASH_SIZE = 0x20

	/*
		ERROR_PATCH_BIGGER_THAN_COMPRESSED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_BIGGER_THAN_COMPRESSED = 0xc00e3105

	/*
		ERROR_PATCH_CORRUPT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_CORRUPT = 0xc00e4102

	/*
		ERROR_PATCH_DECODE_FAILURE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_DECODE_FAILURE = 0xc00e4101

	/*
		ERROR_PATCH_ENCODE_FAILURE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_ENCODE_FAILURE = 0xc00e3101

	/*
		ERROR_PATCH_IMAGEHLP_FAILURE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_IMAGEHLP_FAILURE = 0xc00e3106

	/*
		ERROR_PATCH_INVALID_OPTIONS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_INVALID_OPTIONS = 0xc00e3102

	/*
		ERROR_PATCH_NEWER_FORMAT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_NEWER_FORMAT = 0xc00e4103

	/*
		ERROR_PATCH_NOT_AVAILABLE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_NOT_AVAILABLE = 0xc00e4106

	/*
		ERROR_PATCH_NOT_NECESSARY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_NOT_NECESSARY = 0xc00e4105

	/*
		ERROR_PATCH_RETAIN_RANGES_DIFFER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_RETAIN_RANGES_DIFFER = 0xc00e3104

	/*
		ERROR_PATCH_SAME_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_SAME_FILE = 0xc00e3103

	/*
		ERROR_PATCH_WRONG_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PATCH_WRONG_FILE = 0xc00e4104

	/*
		ERROR_PCW_BAD_API_PATCHING_SYMBOL_FLAGS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_API_PATCHING_SYMBOL_FLAGS = 0xc00e510d

	/*
		ERROR_PCW_BAD_FAMILY_RANGE_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_FAMILY_RANGE_NAME = 0xc00e5159

	/*
		ERROR_PCW_BAD_FILE_SEQUENCE_START from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_FILE_SEQUENCE_START = 0xc00e513a

	/*
		ERROR_PCW_BAD_GUIDS_TO_REPLACE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_GUIDS_TO_REPLACE = 0xc00e5109

	/*
		ERROR_PCW_BAD_IMAGE_FAMILY_DISKID from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_IMAGE_FAMILY_DISKID = 0xc00e513d

	/*
		ERROR_PCW_BAD_IMAGE_FAMILY_FILESEQSTART from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_IMAGE_FAMILY_FILESEQSTART = 0xc00e513e

	/*
		ERROR_PCW_BAD_IMAGE_FAMILY_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_IMAGE_FAMILY_NAME = 0xc00e5124

	/*
		ERROR_PCW_BAD_IMAGE_FAMILY_SRC_PROP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_IMAGE_FAMILY_SRC_PROP = 0xc00e5126

	/*
		ERROR_PCW_BAD_MAJOR_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_MAJOR_VERSION = 0xc00e518d

	/*
		ERROR_PCW_BAD_PATCH_GUID from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_PATCH_GUID = 0xc00e5108

	/*
		ERROR_PCW_BAD_PRODUCTVERSION_VALIDATION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_PRODUCTVERSION_VALIDATION = 0xc00e5184

	/*
		ERROR_PCW_BAD_SEQUENCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_SEQUENCE = 0xc00e5188

	/*
		ERROR_PCW_BAD_SUPERCEDENCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_SUPERCEDENCE = 0xc00e5187

	/*
		ERROR_PCW_BAD_TARGET from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET = 0xc00e5189

	/*
		ERROR_PCW_BAD_TARGET_IMAGE_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET_IMAGE_NAME = 0xc00e5118

	/*
		ERROR_PCW_BAD_TARGET_IMAGE_PRODUCT_CODE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET_IMAGE_PRODUCT_CODE = 0xc00e517a

	/*
		ERROR_PCW_BAD_TARGET_IMAGE_PRODUCT_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET_IMAGE_PRODUCT_VERSION = 0xc00e517b

	/*
		ERROR_PCW_BAD_TARGET_IMAGE_UPGRADED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET_IMAGE_UPGRADED = 0xc00e5140

	/*
		ERROR_PCW_BAD_TARGET_IMAGE_UPGRADE_CODE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET_IMAGE_UPGRADE_CODE = 0xc00e517c

	/*
		ERROR_PCW_BAD_TARGET_PRODUCT_CODE_LIST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TARGET_PRODUCT_CODE_LIST = 0xc00e510a

	/*
		ERROR_PCW_BAD_TGT_UPD_IMAGES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TGT_UPD_IMAGES = 0xc00e5186

	/*
		ERROR_PCW_BAD_TRANSFORMSET from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_TRANSFORMSET = 0xc00e5185

	/*
		ERROR_PCW_BAD_UPGRADED_IMAGE_FAMILY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_UPGRADED_IMAGE_FAMILY = 0xc00e513f

	/*
		ERROR_PCW_BAD_UPGRADED_IMAGE_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_UPGRADED_IMAGE_NAME = 0xc00e5110

	/*
		ERROR_PCW_BAD_UPGRADED_IMAGE_PRODUCT_CODE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_UPGRADED_IMAGE_PRODUCT_CODE = 0xc00e5177

	/*
		ERROR_PCW_BAD_UPGRADED_IMAGE_PRODUCT_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_UPGRADED_IMAGE_PRODUCT_VERSION = 0xc00e5178

	/*
		ERROR_PCW_BAD_UPGRADED_IMAGE_UPGRADE_CODE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_UPGRADED_IMAGE_UPGRADE_CODE = 0xc00e5179

	/*
		ERROR_PCW_BAD_VERSION_STRING from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BAD_VERSION_STRING = 0xc00e518c

	/*
		ERROR_PCW_BASE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_BASE = 0xc00e5101

	/*
		ERROR_PCW_CANNOT_CREATE_TABLE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANNOT_CREATE_TABLE = 0xc00e5181

	/*
		ERROR_PCW_CANNOT_RUN_MAKECAB from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANNOT_RUN_MAKECAB = 0xc00e5146

	/*
		ERROR_PCW_CANNOT_WRITE_DDF from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANNOT_WRITE_DDF = 0xc00e5145

	/*
		ERROR_PCW_CANT_COPY_FILE_TO_TEMP_FOLDER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_COPY_FILE_TO_TEMP_FOLDER = 0xc00e513b

	/*
		ERROR_PCW_CANT_CREATE_ONE_PATCH_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_CREATE_ONE_PATCH_FILE = 0xc00e513c

	/*
		ERROR_PCW_CANT_CREATE_PATCH_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_CREATE_PATCH_FILE = 0xc00e5106

	/*
		ERROR_PCW_CANT_CREATE_SUMMARY_INFO from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_CREATE_SUMMARY_INFO = 0xc00e5174

	/*
		ERROR_PCW_CANT_CREATE_SUMMARY_INFO_POUND from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_CREATE_SUMMARY_INFO_POUND = 0xc00e5176

	/*
		ERROR_PCW_CANT_CREATE_TEMP_FOLDER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_CREATE_TEMP_FOLDER = 0xc00e5103

	/*
		ERROR_PCW_CANT_DELETE_TEMP_FOLDER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_DELETE_TEMP_FOLDER = 0xc00e5206

	/*
		ERROR_PCW_CANT_GENERATE_SEQUENCEINFO_MAJORUPGD from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_GENERATE_SEQUENCEINFO_MAJORUPGD = 0xc00e5182

	/*
		ERROR_PCW_CANT_GENERATE_TRANSFORM from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_GENERATE_TRANSFORM = 0xc00e5173

	/*
		ERROR_PCW_CANT_GENERATE_TRANSFORM_POUND from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_GENERATE_TRANSFORM_POUND = 0xc00e5175

	/*
		ERROR_PCW_CANT_OVERWRITE_PATCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_OVERWRITE_PATCH = 0xc00e5105

	/*
		ERROR_PCW_CANT_READ_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CANT_READ_FILE = 0xc00e520a

	/*
		ERROR_PCW_CREATEFILE_LOG_FAILED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_CREATEFILE_LOG_FAILED = 0xc00e5195

	/*
		ERROR_PCW_DUPLICATE_SEQUENCE_RECORD from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_DUPLICATE_SEQUENCE_RECORD = 0xc00e5192

	/*
		ERROR_PCW_DUP_IMAGE_FAMILY_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_DUP_IMAGE_FAMILY_NAME = 0xc00e5125

	/*
		ERROR_PCW_DUP_TARGET_IMAGE_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_DUP_TARGET_IMAGE_NAME = 0xc00e5119

	/*
		ERROR_PCW_DUP_TARGET_IMAGE_PACKCODE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_DUP_TARGET_IMAGE_PACKCODE = 0xc00e5141

	/*
		ERROR_PCW_DUP_UPGRADED_IMAGE_NAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_DUP_UPGRADED_IMAGE_NAME = 0xc00e5111

	/*
		ERROR_PCW_DUP_UPGRADED_IMAGE_PACKCODE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_DUP_UPGRADED_IMAGE_PACKCODE = 0xc00e5153

	/*
		ERROR_PCW_ERROR_WRITING_TO_LOG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_ERROR_WRITING_TO_LOG = 0xc00e5198

	/*
		ERROR_PCW_EXECUTE_VIEW from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXECUTE_VIEW = 0xc00e519e

	/*
		ERROR_PCW_EXTFILE_BAD_FAMILY_FIELD from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_BAD_FAMILY_FIELD = 0xc00e512c

	/*
		ERROR_PCW_EXTFILE_BAD_IGNORE_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_BAD_IGNORE_LENGTHS = 0xc00e5166

	/*
		ERROR_PCW_EXTFILE_BAD_IGNORE_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_BAD_IGNORE_OFFSETS = 0xc00e5164

	/*
		ERROR_PCW_EXTFILE_BAD_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_BAD_RETAIN_OFFSETS = 0xc00e5169

	/*
		ERROR_PCW_EXTFILE_BLANK_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_BLANK_FILE_TABLE_KEY = 0xc00e512b

	/*
		ERROR_PCW_EXTFILE_BLANK_PATH_TO_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_BLANK_PATH_TO_FILE = 0xc00e512e

	/*
		ERROR_PCW_EXTFILE_IGNORE_COUNT_MISMATCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_IGNORE_COUNT_MISMATCH = 0xc00e5167

	/*
		ERROR_PCW_EXTFILE_LONG_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_LONG_FILE_TABLE_KEY = 0xc00e512a

	/*
		ERROR_PCW_EXTFILE_LONG_IGNORE_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_LONG_IGNORE_LENGTHS = 0xc00e5165

	/*
		ERROR_PCW_EXTFILE_LONG_IGNORE_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_LONG_IGNORE_OFFSETS = 0xc00e5163

	/*
		ERROR_PCW_EXTFILE_LONG_PATH_TO_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_LONG_PATH_TO_FILE = 0xc00e512d

	/*
		ERROR_PCW_EXTFILE_LONG_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_LONG_RETAIN_OFFSETS = 0xc00e5168

	/*
		ERROR_PCW_EXTFILE_MISSING_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_EXTFILE_MISSING_FILE = 0xc00e512f

	/*
		ERROR_PCW_FAILED_CREATE_TRANSFORM from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAILED_CREATE_TRANSFORM = 0xc00e5205

	/*
		ERROR_PCW_FAILED_EXPAND_PATH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAILED_EXPAND_PATH = 0xc00e51a0

	/*
		ERROR_PCW_FAMILY_RANGE_BAD_RETAIN_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_BAD_RETAIN_LENGTHS = 0xc00e5161

	/*
		ERROR_PCW_FAMILY_RANGE_BAD_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_BAD_RETAIN_OFFSETS = 0xc00e515e

	/*
		ERROR_PCW_FAMILY_RANGE_BLANK_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_BLANK_FILE_TABLE_KEY = 0xc00e515b

	/*
		ERROR_PCW_FAMILY_RANGE_BLANK_RETAIN_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_BLANK_RETAIN_LENGTHS = 0xc00e5160

	/*
		ERROR_PCW_FAMILY_RANGE_BLANK_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_BLANK_RETAIN_OFFSETS = 0xc00e515d

	/*
		ERROR_PCW_FAMILY_RANGE_COUNT_MISMATCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_COUNT_MISMATCH = 0xc00e5162

	/*
		ERROR_PCW_FAMILY_RANGE_LONG_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_LONG_FILE_TABLE_KEY = 0xc00e515a

	/*
		ERROR_PCW_FAMILY_RANGE_LONG_RETAIN_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_LONG_RETAIN_LENGTHS = 0xc00e515f

	/*
		ERROR_PCW_FAMILY_RANGE_LONG_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_LONG_RETAIN_OFFSETS = 0xc00e515c

	/*
		ERROR_PCW_FAMILY_RANGE_NAME_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_FAMILY_RANGE_NAME_TOO_LONG = 0xc00e5158

	/*
		ERROR_PCW_IMAGE_FAMILY_NAME_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_IMAGE_FAMILY_NAME_TOO_LONG = 0xc00e5123

	/*
		ERROR_PCW_IMAGE_PATH_NOT_EXIST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_IMAGE_PATH_NOT_EXIST = 0xc00e5214

	/*
		ERROR_PCW_INTERNAL_ERROR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INTERNAL_ERROR = 0xc00e5201

	/*
		ERROR_PCW_INVALID_LOG_LEVEL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_LOG_LEVEL = 0xc00e5196

	/*
		ERROR_PCW_INVALID_MAJOR_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_MAJOR_VERSION = 0xc00e5216

	/*
		ERROR_PCW_INVALID_PARAMETER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PARAMETER = 0xc00e5194

	/*
		ERROR_PCW_INVALID_PATCHMETADATA_PROP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PATCHMETADATA_PROP = 0xc00e5190

	/*
		ERROR_PCW_INVALID_PATCH_TYPE_SEQUENCING from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PATCH_TYPE_SEQUENCING = 0xc00e5209

	/*
		ERROR_PCW_INVALID_PCP_EXTERNALFILES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_EXTERNALFILES = 0xc00e520e

	/*
		ERROR_PCW_INVALID_PCP_FAMILYFILERANGES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_FAMILYFILERANGES = 0xc00e5218

	/*
		ERROR_PCW_INVALID_PCP_IMAGEFAMILIES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_IMAGEFAMILIES = 0xc00e520f

	/*
		ERROR_PCW_INVALID_PCP_PATCHSEQUENCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_PATCHSEQUENCE = 0xc00e5210

	/*
		ERROR_PCW_INVALID_PCP_PROPERTIES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_PROPERTIES = 0xc00e5217

	/*
		ERROR_PCW_INVALID_PCP_PROPERTY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_PROPERTY = 0xc00e5202

	/*
		ERROR_PCW_INVALID_PCP_TARGETFILES_OPTIONALDATA from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_TARGETFILES_OPTIONALDATA = 0xc00e5211

	/*
		ERROR_PCW_INVALID_PCP_TARGETIMAGES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_TARGETIMAGES = 0xc00e5203

	/*
		ERROR_PCW_INVALID_PCP_UPGRADEDFILESTOIGNORE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_UPGRADEDFILESTOIGNORE = 0xc00e520c

	/*
		ERROR_PCW_INVALID_PCP_UPGRADEDFILES_OPTIONALDATA from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_UPGRADEDFILES_OPTIONALDATA = 0xc00e5212

	/*
		ERROR_PCW_INVALID_PCP_UPGRADEDIMAGES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_PCP_UPGRADEDIMAGES = 0xc00e520d

	/*
		ERROR_PCW_INVALID_RANGE_ELEMENT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_RANGE_ELEMENT = 0xc00e5215

	/*
		ERROR_PCW_INVALID_SUPERCEDENCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_SUPERCEDENCE = 0xc00e5191

	/*
		ERROR_PCW_INVALID_SUPERSEDENCE_VALUE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_SUPERSEDENCE_VALUE = 0xc00e5208

	/*
		ERROR_PCW_INVALID_UI_LEVEL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_INVALID_UI_LEVEL = 0xc00e5197

	/*
		ERROR_PCW_LAX_VALIDATION_FLAGS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_LAX_VALIDATION_FLAGS = 0xc00e5204

	/*
		ERROR_PCW_MAJOR_UPGD_WITHOUT_SEQUENCING from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MAJOR_UPGD_WITHOUT_SEQUENCING = 0xc00e5183

	/*
		ERROR_PCW_MATCHED_PRODUCT_VERSIONS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MATCHED_PRODUCT_VERSIONS = 0xc00e517d

	/*
		ERROR_PCW_MISMATCHED_PRODUCT_CODES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MISMATCHED_PRODUCT_CODES = 0xc00e5143

	/*
		ERROR_PCW_MISMATCHED_PRODUCT_VERSIONS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MISMATCHED_PRODUCT_VERSIONS = 0xc00e5144

	/*
		ERROR_PCW_MISSING_DIRECTORY_TABLE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MISSING_DIRECTORY_TABLE = 0xc00e5207

	/*
		ERROR_PCW_MISSING_PATCHMETADATA from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MISSING_PATCHMETADATA = 0xc00e5213

	/*
		ERROR_PCW_MISSING_PATCH_GUID from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MISSING_PATCH_GUID = 0xc00e5107

	/*
		ERROR_PCW_MISSING_PATCH_PATH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_MISSING_PATCH_PATH = 0xc00e5104

	/*
		ERROR_PCW_NO_UPGRADED_IMAGES_TO_PATCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_NO_UPGRADED_IMAGES_TO_PATCH = 0xc00e510b

	/*
		ERROR_PCW_NULL_PATCHFAMILY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_NULL_PATCHFAMILY = 0xc00e518a

	/*
		ERROR_PCW_NULL_SEQUENCE_NUMBER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_NULL_SEQUENCE_NUMBER = 0xc00e518b

	/*
		ERROR_PCW_OBSOLETION_WITH_MSI30 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_OBSOLETION_WITH_MSI30 = 0xc00e517f

	/*
		ERROR_PCW_OBSOLETION_WITH_PATCHSEQUENCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_OBSOLETION_WITH_PATCHSEQUENCE = 0xc00e5180

	/*
		ERROR_PCW_OBSOLETION_WITH_SEQUENCE_DATA from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_OBSOLETION_WITH_SEQUENCE_DATA = 0xc00e517e

	/*
		ERROR_PCW_OODS_COPYING_MSI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_OODS_COPYING_MSI = 0xc00e510e

	/*
		ERROR_PCW_OPEN_VIEW from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_OPEN_VIEW = 0xc00e519d

	/*
		ERROR_PCW_OUT_OF_MEMORY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_OUT_OF_MEMORY = 0xc00e5199

	/*
		ERROR_PCW_PATCHMETADATA_PROP_NOT_SET from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_PATCHMETADATA_PROP_NOT_SET = 0xc00e518f

	/*
		ERROR_PCW_PCP_BAD_FORMAT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_PCP_BAD_FORMAT = 0xc00e5102

	/*
		ERROR_PCW_PCP_DOESNT_EXIST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_PCP_DOESNT_EXIST = 0xc00e5101

	/*
		ERROR_PCW_SEQUENCING_BAD_TARGET from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_SEQUENCING_BAD_TARGET = 0xc00e518e

	/*
		ERROR_PCW_TARGET_BAD_PROD_CODE_VAL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_BAD_PROD_CODE_VAL = 0xc00e5120

	/*
		ERROR_PCW_TARGET_BAD_PROD_VALIDATE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_BAD_PROD_VALIDATE = 0xc00e511f

	/*
		ERROR_PCW_TARGET_IMAGE_COMPRESSED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_IMAGE_COMPRESSED = 0xc00e511e

	/*
		ERROR_PCW_TARGET_IMAGE_NAME_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_IMAGE_NAME_TOO_LONG = 0xc00e5117

	/*
		ERROR_PCW_TARGET_IMAGE_PATH_EMPTY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_IMAGE_PATH_EMPTY = 0xc00e511b

	/*
		ERROR_PCW_TARGET_IMAGE_PATH_NOT_EXIST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_IMAGE_PATH_NOT_EXIST = 0xc00e511c

	/*
		ERROR_PCW_TARGET_IMAGE_PATH_NOT_MSI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_IMAGE_PATH_NOT_MSI = 0xc00e511d

	/*
		ERROR_PCW_TARGET_IMAGE_PATH_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_IMAGE_PATH_TOO_LONG = 0xc00e511a

	/*
		ERROR_PCW_TARGET_MISSING_SRC_FILES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_MISSING_SRC_FILES = 0xc00e5122

	/*
		ERROR_PCW_TARGET_WRONG_PRODUCT_VERSION_COMP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TARGET_WRONG_PRODUCT_VERSION_COMP = 0xc00e520b

	/*
		ERROR_PCW_TFILEDATA_BAD_IGNORE_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_BAD_IGNORE_LENGTHS = 0xc00e516e

	/*
		ERROR_PCW_TFILEDATA_BAD_IGNORE_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_BAD_IGNORE_OFFSETS = 0xc00e516c

	/*
		ERROR_PCW_TFILEDATA_BAD_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_BAD_RETAIN_OFFSETS = 0xc00e5171

	/*
		ERROR_PCW_TFILEDATA_BAD_TARGET_FIELD from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_BAD_TARGET_FIELD = 0xc00e514f

	/*
		ERROR_PCW_TFILEDATA_BLANK_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_BLANK_FILE_TABLE_KEY = 0xc00e514d

	/*
		ERROR_PCW_TFILEDATA_IGNORE_COUNT_MISMATCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_IGNORE_COUNT_MISMATCH = 0xc00e516f

	/*
		ERROR_PCW_TFILEDATA_LONG_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_LONG_FILE_TABLE_KEY = 0xc00e514c

	/*
		ERROR_PCW_TFILEDATA_LONG_IGNORE_LENGTHS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_LONG_IGNORE_LENGTHS = 0xc00e516d

	/*
		ERROR_PCW_TFILEDATA_LONG_IGNORE_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_LONG_IGNORE_OFFSETS = 0xc00e516b

	/*
		ERROR_PCW_TFILEDATA_LONG_RETAIN_OFFSETS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_LONG_RETAIN_OFFSETS = 0xc00e5170

	/*
		ERROR_PCW_TFILEDATA_MISSING_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_TFILEDATA_MISSING_FILE_TABLE_KEY = 0xc00e514e

	/*
		ERROR_PCW_UFILEDATA_BAD_UPGRADED_FIELD from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEDATA_BAD_UPGRADED_FIELD = 0xc00e5142

	/*
		ERROR_PCW_UFILEDATA_BLANK_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEDATA_BLANK_FILE_TABLE_KEY = 0xc00e5128

	/*
		ERROR_PCW_UFILEDATA_LONG_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEDATA_LONG_FILE_TABLE_KEY = 0xc00e5127

	/*
		ERROR_PCW_UFILEDATA_MISSING_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEDATA_MISSING_FILE_TABLE_KEY = 0xc00e5129

	/*
		ERROR_PCW_UFILEIGNORE_BAD_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEIGNORE_BAD_FILE_TABLE_KEY = 0xc00e5157

	/*
		ERROR_PCW_UFILEIGNORE_BAD_UPGRADED_FIELD from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEIGNORE_BAD_UPGRADED_FIELD = 0xc00e5154

	/*
		ERROR_PCW_UFILEIGNORE_BLANK_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEIGNORE_BLANK_FILE_TABLE_KEY = 0xc00e5156

	/*
		ERROR_PCW_UFILEIGNORE_LONG_FILE_TABLE_KEY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UFILEIGNORE_LONG_FILE_TABLE_KEY = 0xc00e5155

	/*
		ERROR_PCW_UNKNOWN_ERROR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UNKNOWN_ERROR = 0xc00e519a

	/*
		ERROR_PCW_UNKNOWN_INFO from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UNKNOWN_INFO = 0xc00e519b

	/*
		ERROR_PCW_UNKNOWN_WARN from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UNKNOWN_WARN = 0xc00e519c

	/*
		ERROR_PCW_UPGRADED_IMAGE_COMPRESSED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_COMPRESSED = 0xc00e5116

	/*
		ERROR_PCW_UPGRADED_IMAGE_NAME_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_NAME_TOO_LONG = 0xc00e510f

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATCH_PATH_NOT_EXIST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATCH_PATH_NOT_EXIST = 0xc00e5151

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATCH_PATH_NOT_MSI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATCH_PATH_NOT_MSI = 0xc00e5152

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATCH_PATH_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATCH_PATH_TOO_LONG = 0xc00e5150

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATH_EMPTY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATH_EMPTY = 0xc00e5113

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATH_NOT_EXIST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATH_NOT_EXIST = 0xc00e5114

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATH_NOT_MSI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATH_NOT_MSI = 0xc00e5115

	/*
		ERROR_PCW_UPGRADED_IMAGE_PATH_TOO_LONG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_IMAGE_PATH_TOO_LONG = 0xc00e5112

	/*
		ERROR_PCW_UPGRADED_MISSING_SRC_FILES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_UPGRADED_MISSING_SRC_FILES = 0xc00e5121

	/*
		ERROR_PCW_VIEW_FETCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_VIEW_FETCH = 0xc00e519f

	/*
		ERROR_PCW_WRITE_SUMMARY_PROPERTIES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_WRITE_SUMMARY_PROPERTIES = 0xc00e514b

	/*
		ERROR_PCW_WRONG_PATCHMETADATA_STRD_PROP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_PCW_WRONG_PATCHMETADATA_STRD_PROP = 0xc00e5193

	/*
		ERROR_ROLLBACK_DISABLED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	ERROR_ROLLBACK_DISABLED = 0x675

	/*
		IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_ALREADY_INSTALLED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_ALREADY_INSTALLED = 0x3

	/*
		IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_INSTALLED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_INSTALLED = 0x1

	/*
		IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_REFRESHED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	IASSEMBLYCACHEITEM_COMMIT_DISPOSITION_REFRESHED = 0x2

	/*
		IASSEMBLYCACHEITEM_COMMIT_FLAG_REFRESH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	IASSEMBLYCACHEITEM_COMMIT_FLAG_REFRESH = 0x1

	/*
		INFO_BASE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_BASE = 0xc00f5101

	/*
		INFO_ENTERING_PHASE_I from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_ENTERING_PHASE_I = 0xc00f5103

	/*
		INFO_ENTERING_PHASE_II from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_ENTERING_PHASE_II = 0xc00f5108

	/*
		INFO_ENTERING_PHASE_III from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_ENTERING_PHASE_III = 0xc00f5109

	/*
		INFO_ENTERING_PHASE_IV from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_ENTERING_PHASE_IV = 0xc00f510a

	/*
		INFO_ENTERING_PHASE_I_VALIDATION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_ENTERING_PHASE_I_VALIDATION = 0xc00f5102

	/*
		INFO_ENTERING_PHASE_V from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_ENTERING_PHASE_V = 0xc00f510b

	/*
		INFO_GENERATING_METADATA from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_GENERATING_METADATA = 0xc00f5111

	/*
		INFO_PASSED_MAIN_CONTROL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_PASSED_MAIN_CONTROL = 0xc00f5101

	/*
		INFO_PATCHCACHE_FILEINFO_FAILURE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_PATCHCACHE_FILEINFO_FAILURE = 0xc00f5113

	/*
		INFO_PATCHCACHE_PCI_READFAILURE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_PATCHCACHE_PCI_READFAILURE = 0xc00f5114

	/*
		INFO_PATCHCACHE_PCI_WRITEFAILURE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_PATCHCACHE_PCI_WRITEFAILURE = 0xc00f5115

	/*
		INFO_PCP_PATH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_PCP_PATH = 0xc00f5104

	/*
		INFO_PROPERTY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_PROPERTY = 0xc00f5107

	/*
		INFO_SET_OPTIONS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_SET_OPTIONS = 0xc00f5106

	/*
		INFO_SUCCESSFUL_PATCH_CREATION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_SUCCESSFUL_PATCH_CREATION = 0xc00f5117

	/*
		INFO_TEMP_DIR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_TEMP_DIR = 0xc00f5105

	/*
		INFO_TEMP_DIR_CLEANUP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_TEMP_DIR_CLEANUP = 0xc00f5112

	/*
		INFO_USING_USER_MSI_FOR_PATCH_TABLES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INFO_USING_USER_MSI_FOR_PATCH_TABLES = 0xc00f5116

	/*
		INSTALLMESSAGE_TYPEMASK from Windows.Win32 metadata (originally typed int32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	INSTALLMESSAGE_TYPEMASK = -16777216

	/*
		LOGALL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGALL = 0xf

	/*
		LOGERR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGERR = 0x4

	/*
		LOGINFO from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGINFO = 0x1

	/*
		LOGNONE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGNONE = 0x0

	/*
		LOGPERFMESSAGES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGPERFMESSAGES = 0x8

	/*
		LOGTOKEN_NO_LOG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGTOKEN_NO_LOG = 0x1

	/*
		LOGTOKEN_SETUPAPI_APPLOG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGTOKEN_SETUPAPI_APPLOG = 0x2

	/*
		LOGTOKEN_SETUPAPI_DEVLOG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGTOKEN_SETUPAPI_DEVLOG = 0x3

	/*
		LOGTOKEN_TYPE_MASK from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGTOKEN_TYPE_MASK = 0x3

	/*
		LOGTOKEN_UNSPECIFIED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGTOKEN_UNSPECIFIED = 0x0

	/*
		LOGWARN from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	LOGWARN = 0x2

	/*
		MAX_FEATURE_CHARS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MAX_FEATURE_CHARS = 0x26

	/*
		MAX_GUID_CHARS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MAX_GUID_CHARS = 0x26

	/*
		MSIDBOPEN_CREATE from Windows.Win32 metadata (originally typed *PWSTRElement). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSIDBOPEN_CREATE = 0x3

	/*
		MSIDBOPEN_CREATEDIRECT from Windows.Win32 metadata (originally typed *PWSTRElement). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSIDBOPEN_CREATEDIRECT = 0x4

	/*
		MSIDBOPEN_DIRECT from Windows.Win32 metadata (originally typed *PWSTRElement). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSIDBOPEN_DIRECT = 0x2

	/*
		MSIDBOPEN_PATCHFILE from Windows.Win32 metadata (originally typed int32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSIDBOPEN_PATCHFILE = 0x10

	/*
		MSIDBOPEN_READONLY from Windows.Win32 metadata (originally typed *PWSTRElement). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSIDBOPEN_READONLY = 0x0

	/*
		MSIDBOPEN_TRANSACT from Windows.Win32 metadata (originally typed *PWSTRElement). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSIDBOPEN_TRANSACT = 0x1

	/*
		MSI_INVALID_HASH_IS_FATAL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSI_INVALID_HASH_IS_FATAL = 0x1

	/*
		MSI_NULL_INTEGER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	MSI_NULL_INTEGER = 0x80000000

	/*
		PATCH_OPTION_FAIL_IF_BIGGER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_FAIL_IF_BIGGER = 0x100000

	/*
		PATCH_OPTION_FAIL_IF_SAME_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_FAIL_IF_SAME_FILE = 0x80000

	/*
		PATCH_OPTION_INTERLEAVE_FILES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_INTERLEAVE_FILES = 0x40000000

	/*
		PATCH_OPTION_NO_BINDFIX from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_NO_BINDFIX = 0x10000

	/*
		PATCH_OPTION_NO_CHECKSUM from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_NO_CHECKSUM = 0x200000

	/*
		PATCH_OPTION_NO_LOCKFIX from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_NO_LOCKFIX = 0x20000

	/*
		PATCH_OPTION_NO_REBASE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_NO_REBASE = 0x40000

	/*
		PATCH_OPTION_NO_RESTIMEFIX from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_NO_RESTIMEFIX = 0x400000

	/*
		PATCH_OPTION_NO_TIMESTAMP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_NO_TIMESTAMP = 0x800000

	/*
		PATCH_OPTION_RESERVED1 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_RESERVED1 = 0x80000000

	/*
		PATCH_OPTION_SIGNATURE_MD5 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_SIGNATURE_MD5 = 0x1000000

	/*
		PATCH_OPTION_USE_BEST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_USE_BEST = 0x0

	/*
		PATCH_OPTION_USE_LZX_A from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_USE_LZX_A = 0x1

	/*
		PATCH_OPTION_USE_LZX_B from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_USE_LZX_B = 0x2

	/*
		PATCH_OPTION_USE_LZX_BEST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_USE_LZX_BEST = 0x3

	/*
		PATCH_OPTION_USE_LZX_LARGE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_USE_LZX_LARGE = 0x4

	/*
		PATCH_OPTION_VALID_FLAGS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_OPTION_VALID_FLAGS = 0xc0ff0007

	/*
		PATCH_SYMBOL_NO_FAILURES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_SYMBOL_NO_FAILURES = 0x2

	/*
		PATCH_SYMBOL_NO_IMAGEHLP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_SYMBOL_NO_IMAGEHLP = 0x1

	/*
		PATCH_SYMBOL_RESERVED1 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_SYMBOL_RESERVED1 = 0x80000000

	/*
		PATCH_SYMBOL_UNDECORATED_TOO from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_SYMBOL_UNDECORATED_TOO = 0x4

	/*
		PATCH_TRANSFORM_PE_IRELOC_2 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_TRANSFORM_PE_IRELOC_2 = 0x200

	/*
		PATCH_TRANSFORM_PE_RESOURCE_2 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PATCH_TRANSFORM_PE_RESOURCE_2 = 0x100

	/*
		PID_APPNAME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_APPNAME = 0x12

	/*
		PID_AUTHOR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_AUTHOR = 0x4

	/*
		PID_CHARCOUNT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_CHARCOUNT = 0x10

	/*
		PID_COMMENTS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_COMMENTS = 0x6

	/*
		PID_CREATE_DTM from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_CREATE_DTM = 0xc

	/*
		PID_EDITTIME from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_EDITTIME = 0xa

	/*
		PID_KEYWORDS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_KEYWORDS = 0x5

	/*
		PID_LASTAUTHOR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_LASTAUTHOR = 0x8

	/*
		PID_LASTPRINTED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_LASTPRINTED = 0xb

	/*
		PID_LASTSAVE_DTM from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_LASTSAVE_DTM = 0xd

	/*
		PID_MSIRESTRICT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_MSIRESTRICT = 0x10

	/*
		PID_MSISOURCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_MSISOURCE = 0xf

	/*
		PID_MSIVERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_MSIVERSION = 0xe

	/*
		PID_PAGECOUNT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_PAGECOUNT = 0xe

	/*
		PID_REVNUMBER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_REVNUMBER = 0x9

	/*
		PID_SUBJECT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_SUBJECT = 0x3

	/*
		PID_TEMPLATE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_TEMPLATE = 0x7

	/*
		PID_THUMBNAIL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_THUMBNAIL = 0x11

	/*
		PID_TITLE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_TITLE = 0x2

	/*
		PID_WORDCOUNT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	PID_WORDCOUNT = 0xf

	/*
		SFC_DISABLE_ASK from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_DISABLE_ASK = 0x1

	/*
		SFC_DISABLE_NOPOPUPS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_DISABLE_NOPOPUPS = 0x4

	/*
		SFC_DISABLE_NORMAL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_DISABLE_NORMAL = 0x0

	/*
		SFC_DISABLE_ONCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_DISABLE_ONCE = 0x2

	/*
		SFC_DISABLE_SETUP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_DISABLE_SETUP = 0x3

	/*
		SFC_QUOTA_DEFAULT from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_QUOTA_DEFAULT = 0x32

	/*
		SFC_SCAN_ALWAYS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_SCAN_ALWAYS = 0x1

	/*
		SFC_SCAN_IMMEDIATE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_SCAN_IMMEDIATE = 0x3

	/*
		SFC_SCAN_NORMAL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_SCAN_NORMAL = 0x0

	/*
		SFC_SCAN_ONCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	SFC_SCAN_ONCE = 0x2

	/*
		STREAM_FORMAT_COMPLIB_MANIFEST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	STREAM_FORMAT_COMPLIB_MANIFEST = 0x1

	/*
		STREAM_FORMAT_COMPLIB_MODULE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	STREAM_FORMAT_COMPLIB_MODULE = 0x0

	/*
		STREAM_FORMAT_WIN32_MANIFEST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	STREAM_FORMAT_WIN32_MANIFEST = 0x4

	/*
		STREAM_FORMAT_WIN32_MODULE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	STREAM_FORMAT_WIN32_MODULE = 0x2

	/*
		TXTLOG_BACKUP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_BACKUP = 0x80

	/*
		TXTLOG_CMI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_CMI = 0x10000000

	/*
		TXTLOG_COPYFILES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_COPYFILES = 0x8

	/*
		TXTLOG_DEPTH_DECR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DEPTH_DECR = 0x40000

	/*
		TXTLOG_DEPTH_INCR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DEPTH_INCR = 0x20000

	/*
		TXTLOG_DETAILS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DETAILS = 0x5

	/*
		TXTLOG_DEVINST from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DEVINST = 0x1

	/*
		TXTLOG_DEVMGR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DEVMGR = 0x20000000

	/*
		TXTLOG_DRIVER_STORE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DRIVER_STORE = 0x4000000

	/*
		TXTLOG_DRVSETUP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_DRVSETUP = 0x400000

	/*
		TXTLOG_ERROR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_ERROR = 0x1

	/*
		TXTLOG_FILEQ from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_FILEQ = 0x4

	/*
		TXTLOG_FLUSH_FILE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_FLUSH_FILE = 0x100000

	/*
		TXTLOG_INF from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_INF = 0x2

	/*
		TXTLOG_INFDB from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_INFDB = 0x400

	/*
		TXTLOG_INSTALLER from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_INSTALLER = 0x40000000

	/*
		TXTLOG_NEWDEV from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_NEWDEV = 0x1000000

	/*
		TXTLOG_POLICY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_POLICY = 0x800000

	/*
		TXTLOG_RESERVED_FLAGS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_RESERVED_FLAGS = 0xfff0

	/*
		TXTLOG_SETUP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SETUP = 0x8000000

	/*
		TXTLOG_SETUPAPI_BITS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SETUPAPI_BITS = 0x3

	/*
		TXTLOG_SETUPAPI_CMDLINE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SETUPAPI_CMDLINE = 0x2

	/*
		TXTLOG_SETUPAPI_DEVLOG from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SETUPAPI_DEVLOG = 0x1

	/*
		TXTLOG_SIGVERIF from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SIGVERIF = 0x20

	/*
		TXTLOG_SUMMARY from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SUMMARY = 0x4

	/*
		TXTLOG_SYSTEM_STATE_CHANGE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_SYSTEM_STATE_CHANGE = 0x3

	/*
		TXTLOG_TAB_1 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_TAB_1 = 0x80000

	/*
		TXTLOG_TIMESTAMP from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_TIMESTAMP = 0x10000

	/*
		TXTLOG_UI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_UI = 0x100

	/*
		TXTLOG_UMPNPMGR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_UMPNPMGR = 0x2000000

	/*
		TXTLOG_UTIL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_UTIL = 0x200

	/*
		TXTLOG_VENDOR from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_VENDOR = 0x80000000

	/*
		TXTLOG_VERBOSE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_VERBOSE = 0x6

	/*
		TXTLOG_VERY_VERBOSE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_VERY_VERBOSE = 0x7

	/*
		TXTLOG_WARNING from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	TXTLOG_WARNING = 0x2

	/*
		UIALL from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	UIALL = 0x8000

	/*
		UILOGBITS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	UILOGBITS = 0xf

	/*
		UINONE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	UINONE = 0x0

	/*
		WARN_BAD_MAJOR_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_BAD_MAJOR_VERSION = 0xc0105108

	/*
		WARN_BASE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_BASE = 0xc0105101

	/*
		WARN_EQUAL_FILE_VERSION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_EQUAL_FILE_VERSION = 0xc010510a

	/*
		WARN_FILE_VERSION_DOWNREV from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_FILE_VERSION_DOWNREV = 0xc0105109

	/*
		WARN_IMPROPER_TRANSFORM_VALIDATION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_IMPROPER_TRANSFORM_VALIDATION = 0xc0105104

	/*
		WARN_INVALID_TRANSFORM_VALIDATION from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_INVALID_TRANSFORM_VALIDATION = 0xc0105107

	/*
		WARN_MAJOR_UPGRADE_PATCH from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_MAJOR_UPGRADE_PATCH = 0xc0105101

	/*
		WARN_OBSOLETION_WITH_MSI30 from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_OBSOLETION_WITH_MSI30 = 0xc0105111

	/*
		WARN_OBSOLETION_WITH_PATCHSEQUENCE from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_OBSOLETION_WITH_PATCHSEQUENCE = 0xc0105113

	/*
		WARN_OBSOLETION_WITH_SEQUENCE_DATA from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_OBSOLETION_WITH_SEQUENCE_DATA = 0xc0105112

	/*
		WARN_PATCHPROPERTYNOTSET from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_PATCHPROPERTYNOTSET = 0xc010510b

	/*
		WARN_PCW_MISMATCHED_PRODUCT_CODES from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_PCW_MISMATCHED_PRODUCT_CODES = 0xc0105105

	/*
		WARN_PCW_MISMATCHED_PRODUCT_VERSIONS from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_PCW_MISMATCHED_PRODUCT_VERSIONS = 0xc0105106

	/*
		WARN_SEQUENCE_DATA_GENERATION_DISABLED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_SEQUENCE_DATA_GENERATION_DISABLED = 0xc0105102

	/*
		WARN_SEQUENCE_DATA_SUPERSEDENCE_IGNORED from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WARN_SEQUENCE_DATA_SUPERSEDENCE_IGNORED = 0xc0105103

	/*
		WIN32_MSI from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WIN32_MSI = 0x1f4

	/*
		WIN32_MSM from Windows.Win32 metadata (originally typed uint32). Emitted untyped so callers convert to the receiving Go type at the use site.
	*/
	WIN32_MSM = 0x64
)
