//go:build windows && amd64

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-27 08:35:22 CEST

package kernel32_dll

import (
	"syscore/window/win32/bindings/types/windows_win32_foundation"
	"syscore/window/win32/bindings/types/windows_win32_system_diagnostics_debug"
	"syscore/window/win32/bindings/types/windows_win32_system_kernel"
)

/*
PFN_EnableProcessOptionalXStateFeatures maps to EnableProcessOptionalXStateFeatures in kernel32.dll.
*/
type PFN_EnableProcessOptionalXStateFeatures func(Features uint64) windows_win32_foundation.BOOL

/*
PFN_GetEnabledXStateFeatures maps to GetEnabledXStateFeatures in kernel32.dll.
*/
type PFN_GetEnabledXStateFeatures func() uint64

/*
PFN_GetThreadEnabledXStateFeatures maps to GetThreadEnabledXStateFeatures in kernel32.dll.
*/
type PFN_GetThreadEnabledXStateFeatures func() uint64

/*
PFN_GetXStateFeaturesMask maps to GetXStateFeaturesMask in kernel32.dll.
*/
type PFN_GetXStateFeaturesMask func(Context *windows_win32_system_diagnostics_debug.CONTEXT, FeatureMask *uint64) windows_win32_foundation.BOOL

/*
PFN_LocateXStateFeature maps to LocateXStateFeature in kernel32.dll.
*/
type PFN_LocateXStateFeature func(Context *windows_win32_system_diagnostics_debug.CONTEXT, FeatureId uint32, Length *uint32) uintptr

/*
PFN_RtlAddFunctionTable maps to RtlAddFunctionTable in kernel32.dll.
*/
type PFN_RtlAddFunctionTable func(FunctionTable *windows_win32_system_diagnostics_debug.IMAGE_RUNTIME_FUNCTION_ENTRY, EntryCount uint32, BaseAddress uint64) windows_win32_foundation.BOOLEAN

/*
PFN_RtlCaptureContext2 maps to RtlCaptureContext2 in kernel32.dll.
*/
type PFN_RtlCaptureContext2 func(ContextRecord *windows_win32_system_diagnostics_debug.CONTEXT)

/*
PFN_RtlDeleteFunctionTable maps to RtlDeleteFunctionTable in kernel32.dll.
*/
type PFN_RtlDeleteFunctionTable func(FunctionTable *windows_win32_system_diagnostics_debug.IMAGE_RUNTIME_FUNCTION_ENTRY) windows_win32_foundation.BOOLEAN

/*
PFN_RtlInstallFunctionTableCallback maps to RtlInstallFunctionTableCallback in kernel32.dll.
*/
type PFN_RtlInstallFunctionTableCallback func(TableIdentifier uint64, BaseAddress uint64, Length uint32, Callback windows_win32_system_diagnostics_debug.PGET_RUNTIME_FUNCTION_CALLBACK, Context uintptr, OutOfProcessCallbackDll *windows_win32_foundation.PWSTRElement) windows_win32_foundation.BOOLEAN

/*
PFN_RtlLookupFunctionEntry maps to RtlLookupFunctionEntry in kernel32.dll.
*/
type PFN_RtlLookupFunctionEntry func(ControlPc uint64, ImageBase *uint64, HistoryTable *windows_win32_system_diagnostics_debug.UNWIND_HISTORY_TABLE) *windows_win32_system_diagnostics_debug.IMAGE_RUNTIME_FUNCTION_ENTRY

/*
PFN_RtlUnwindEx maps to RtlUnwindEx in kernel32.dll.
*/
type PFN_RtlUnwindEx func(TargetFrame uintptr, TargetIp uintptr, ExceptionRecord *windows_win32_system_diagnostics_debug.EXCEPTION_RECORD, ReturnValue uintptr, ContextRecord *windows_win32_system_diagnostics_debug.CONTEXT, HistoryTable *windows_win32_system_diagnostics_debug.UNWIND_HISTORY_TABLE)

/*
PFN_RtlVirtualUnwind maps to RtlVirtualUnwind in kernel32.dll.
*/
type PFN_RtlVirtualUnwind func(HandlerType windows_win32_system_diagnostics_debug.RTL_VIRTUAL_UNWIND_HANDLER_TYPE, ImageBase uint64, ControlPc uint64, FunctionEntry *windows_win32_system_diagnostics_debug.IMAGE_RUNTIME_FUNCTION_ENTRY, ContextRecord *windows_win32_system_diagnostics_debug.CONTEXT, HandlerData *uintptr, EstablisherFrame *uint64, ContextPointers *windows_win32_system_diagnostics_debug.KNONVOLATILE_CONTEXT_POINTERS) windows_win32_system_kernel.EXCEPTION_ROUTINE

/*
PFN_SetXStateFeaturesMask maps to SetXStateFeaturesMask in kernel32.dll.
*/
type PFN_SetXStateFeaturesMask func(Context *windows_win32_system_diagnostics_debug.CONTEXT, FeatureMask uint64) windows_win32_foundation.BOOL

/*
PFN_Uaw_lstrcmpW maps to Uaw_lstrcmpW in kernel32.dll.
*/
type PFN_Uaw_lstrcmpW func(String1 *uint16, String2 *uint16) int32

/*
PFN_Uaw_lstrcmpiW maps to Uaw_lstrcmpiW in kernel32.dll.
*/
type PFN_Uaw_lstrcmpiW func(String1 *uint16, String2 *uint16) int32

/*
PFN_Uaw_lstrlenW maps to Uaw_lstrlenW in kernel32.dll.
*/
type PFN_Uaw_lstrlenW func(String *uint16) int32

/*
PFN_Uaw_wcschr maps to Uaw_wcschr in kernel32.dll.
*/
type PFN_Uaw_wcschr func(String *uint16, Character uint16) *uint16

/*
PFN_Uaw_wcscpy maps to Uaw_wcscpy in kernel32.dll.
*/
type PFN_Uaw_wcscpy func(Destination *uint16, Source *uint16) *uint16

/*
PFN_Uaw_wcsicmp maps to Uaw_wcsicmp in kernel32.dll.
*/
type PFN_Uaw_wcsicmp func(String1 *uint16, String2 *uint16) int32

/*
PFN_Uaw_wcslen maps to Uaw_wcslen in kernel32.dll.
*/
type PFN_Uaw_wcslen func(String *uint16) uintptr

/*
PFN_Uaw_wcsrchr maps to Uaw_wcsrchr in kernel32.dll.
*/
type PFN_Uaw_wcsrchr func(String *uint16, Character uint16) *uint16
