//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-27 08:35:22 CEST

package windows_win32_system_memory

import (
	"syscore/window/win32/bindings/types/windows_win32_foundation"
)

/*
FILE_MAP is generated from Windows.Win32 metadata.
*/
type FILE_MAP uint32

const (
	/*
		FILE_MAP_WRITE from Windows.Win32 metadata.
	*/
	FILE_MAP_WRITE FILE_MAP = 0x2

	/*
		FILE_MAP_READ from Windows.Win32 metadata.
	*/
	FILE_MAP_READ FILE_MAP = 0x4

	/*
		FILE_MAP_ALL_ACCESS from Windows.Win32 metadata.
	*/
	FILE_MAP_ALL_ACCESS FILE_MAP = 0xf001f

	/*
		FILE_MAP_EXECUTE from Windows.Win32 metadata.
	*/
	FILE_MAP_EXECUTE FILE_MAP = 0x20

	/*
		FILE_MAP_COPY from Windows.Win32 metadata.
	*/
	FILE_MAP_COPY FILE_MAP = 0x1

	/*
		FILE_MAP_RESERVE from Windows.Win32 metadata.
	*/
	FILE_MAP_RESERVE FILE_MAP = 0x80000000

	/*
		FILE_MAP_TARGETS_INVALID from Windows.Win32 metadata.
	*/
	FILE_MAP_TARGETS_INVALID FILE_MAP = 0x40000000

	/*
		FILE_MAP_LARGE_PAGES from Windows.Win32 metadata.
	*/
	FILE_MAP_LARGE_PAGES FILE_MAP = 0x20000000
)

/*
GLOBAL_ALLOC_FLAGS is generated from Windows.Win32 metadata.
*/
type GLOBAL_ALLOC_FLAGS uint32

const (
	/*
		GHND from Windows.Win32 metadata.
	*/
	GHND GLOBAL_ALLOC_FLAGS = 0x42

	/*
		GMEM_FIXED from Windows.Win32 metadata.
	*/
	GMEM_FIXED GLOBAL_ALLOC_FLAGS = 0x0

	/*
		GMEM_MOVEABLE from Windows.Win32 metadata.
	*/
	GMEM_MOVEABLE GLOBAL_ALLOC_FLAGS = 0x2

	/*
		GMEM_ZEROINIT from Windows.Win32 metadata.
	*/
	GMEM_ZEROINIT GLOBAL_ALLOC_FLAGS = 0x40

	/*
		GPTR from Windows.Win32 metadata.
	*/
	GPTR GLOBAL_ALLOC_FLAGS = 0x40
)

/*
HEAP_FLAGS is generated from Windows.Win32 metadata.
*/
type HEAP_FLAGS uint32

const (
	/*
		HEAP_NONE from Windows.Win32 metadata.
	*/
	HEAP_NONE HEAP_FLAGS = 0x0

	/*
		HEAP_NO_SERIALIZE from Windows.Win32 metadata.
	*/
	HEAP_NO_SERIALIZE HEAP_FLAGS = 0x1

	/*
		HEAP_GROWABLE from Windows.Win32 metadata.
	*/
	HEAP_GROWABLE HEAP_FLAGS = 0x2

	/*
		HEAP_GENERATE_EXCEPTIONS from Windows.Win32 metadata.
	*/
	HEAP_GENERATE_EXCEPTIONS HEAP_FLAGS = 0x4

	/*
		HEAP_ZERO_MEMORY from Windows.Win32 metadata.
	*/
	HEAP_ZERO_MEMORY HEAP_FLAGS = 0x8

	/*
		HEAP_REALLOC_IN_PLACE_ONLY from Windows.Win32 metadata.
	*/
	HEAP_REALLOC_IN_PLACE_ONLY HEAP_FLAGS = 0x10

	/*
		HEAP_TAIL_CHECKING_ENABLED from Windows.Win32 metadata.
	*/
	HEAP_TAIL_CHECKING_ENABLED HEAP_FLAGS = 0x20

	/*
		HEAP_FREE_CHECKING_ENABLED from Windows.Win32 metadata.
	*/
	HEAP_FREE_CHECKING_ENABLED HEAP_FLAGS = 0x40

	/*
		HEAP_DISABLE_COALESCE_ON_FREE from Windows.Win32 metadata.
	*/
	HEAP_DISABLE_COALESCE_ON_FREE HEAP_FLAGS = 0x80

	/*
		HEAP_CREATE_ALIGN_16 from Windows.Win32 metadata.
	*/
	HEAP_CREATE_ALIGN_16 HEAP_FLAGS = 0x10000

	/*
		HEAP_CREATE_ENABLE_TRACING from Windows.Win32 metadata.
	*/
	HEAP_CREATE_ENABLE_TRACING HEAP_FLAGS = 0x20000

	/*
		HEAP_CREATE_ENABLE_EXECUTE from Windows.Win32 metadata.
	*/
	HEAP_CREATE_ENABLE_EXECUTE HEAP_FLAGS = 0x40000

	/*
		HEAP_MAXIMUM_TAG from Windows.Win32 metadata.
	*/
	HEAP_MAXIMUM_TAG HEAP_FLAGS = 0xfff

	/*
		HEAP_PSEUDO_TAG_FLAG from Windows.Win32 metadata.
	*/
	HEAP_PSEUDO_TAG_FLAG HEAP_FLAGS = 0x8000

	/*
		HEAP_TAG_SHIFT from Windows.Win32 metadata.
	*/
	HEAP_TAG_SHIFT HEAP_FLAGS = 0x12

	/*
		HEAP_CREATE_SEGMENT_HEAP from Windows.Win32 metadata.
	*/
	HEAP_CREATE_SEGMENT_HEAP HEAP_FLAGS = 0x100

	/*
		HEAP_CREATE_HARDENED from Windows.Win32 metadata.
	*/
	HEAP_CREATE_HARDENED HEAP_FLAGS = 0x200
)

/*
HEAP_INFORMATION_CLASS is generated from Windows.Win32 metadata.
*/
type HEAP_INFORMATION_CLASS int32

const (
	/*
		HeapCompatibilityInformation from Windows.Win32 metadata.
	*/
	HeapCompatibilityInformation HEAP_INFORMATION_CLASS = 0x0

	/*
		HeapEnableTerminationOnCorruption from Windows.Win32 metadata.
	*/
	HeapEnableTerminationOnCorruption HEAP_INFORMATION_CLASS = 0x1

	/*
		HeapOptimizeResources from Windows.Win32 metadata.
	*/
	HeapOptimizeResources HEAP_INFORMATION_CLASS = 0x3

	/*
		HeapTag from Windows.Win32 metadata.
	*/
	HeapTag HEAP_INFORMATION_CLASS = 0x7
)

/*
HEAP_SUMMARY is generated from Windows.Win32 metadata.
*/
type HEAP_SUMMARY struct {
	Cb           uint32
	CbAllocated  uintptr
	CbCommitted  uintptr
	CbReserved   uintptr
	CbMaxReserve uintptr
}

/*
LOCAL_ALLOC_FLAGS is generated from Windows.Win32 metadata.
*/
type LOCAL_ALLOC_FLAGS uint32

const (
	/*
		LHND from Windows.Win32 metadata.
	*/
	LHND LOCAL_ALLOC_FLAGS = 0x42

	/*
		LMEM_FIXED from Windows.Win32 metadata.
	*/
	LMEM_FIXED LOCAL_ALLOC_FLAGS = 0x0

	/*
		LMEM_MOVEABLE from Windows.Win32 metadata.
	*/
	LMEM_MOVEABLE LOCAL_ALLOC_FLAGS = 0x2

	/*
		LMEM_ZEROINIT from Windows.Win32 metadata.
	*/
	LMEM_ZEROINIT LOCAL_ALLOC_FLAGS = 0x40

	/*
		LPTR from Windows.Win32 metadata.
	*/
	LPTR LOCAL_ALLOC_FLAGS = 0x40

	/*
		NONZEROLHND from Windows.Win32 metadata.
	*/
	NONZEROLHND LOCAL_ALLOC_FLAGS = 0x2

	/*
		NONZEROLPTR from Windows.Win32 metadata.
	*/
	NONZEROLPTR LOCAL_ALLOC_FLAGS = 0x0
)

/*
MEMORY_BASIC_INFORMATION is generated from Windows.Win32 metadata.
*/
type MEMORY_BASIC_INFORMATION struct {
	BaseAddress       uintptr
	AllocationBase    uintptr
	AllocationProtect PAGE_PROTECTION_FLAGS
	PartitionId       uint16
	RegionSize        uintptr
	State             VIRTUAL_ALLOCATION_TYPE
	Protect           PAGE_PROTECTION_FLAGS
	Type              PAGE_TYPE
}

/*
MEMORY_BASIC_INFORMATION_1 is generated from Windows.Win32 metadata.
*/
type MEMORY_BASIC_INFORMATION_1 struct {
	BaseAddress       uintptr
	AllocationBase    uintptr
	AllocationProtect PAGE_PROTECTION_FLAGS
	RegionSize        uintptr
	State             VIRTUAL_ALLOCATION_TYPE
	Protect           PAGE_PROTECTION_FLAGS
	Type              PAGE_TYPE
}

/*
MEMORY_MAPPED_VIEW_ADDRESS is generated from Windows.Win32 metadata.
*/
type MEMORY_MAPPED_VIEW_ADDRESS struct {
	Value uintptr
}

/*
MEMORY_RESOURCE_NOTIFICATION_TYPE is generated from Windows.Win32 metadata.
*/
type MEMORY_RESOURCE_NOTIFICATION_TYPE int32

const (
	/*
		LowMemoryResourceNotification from Windows.Win32 metadata.
	*/
	LowMemoryResourceNotification MEMORY_RESOURCE_NOTIFICATION_TYPE = 0x0

	/*
		HighMemoryResourceNotification from Windows.Win32 metadata.
	*/
	HighMemoryResourceNotification MEMORY_RESOURCE_NOTIFICATION_TYPE = 0x1
)

/*
OFFER_PRIORITY is generated from Windows.Win32 metadata.
*/
type OFFER_PRIORITY int32

const (
	/*
		VmOfferPriorityVeryLow from Windows.Win32 metadata.
	*/
	VmOfferPriorityVeryLow OFFER_PRIORITY = 0x1

	/*
		VmOfferPriorityLow from Windows.Win32 metadata.
	*/
	VmOfferPriorityLow OFFER_PRIORITY = 0x2

	/*
		VmOfferPriorityBelowNormal from Windows.Win32 metadata.
	*/
	VmOfferPriorityBelowNormal OFFER_PRIORITY = 0x3

	/*
		VmOfferPriorityNormal from Windows.Win32 metadata.
	*/
	VmOfferPriorityNormal OFFER_PRIORITY = 0x4
)

/*
PAGE_PROTECTION_FLAGS is generated from Windows.Win32 metadata.
*/
type PAGE_PROTECTION_FLAGS uint32

const (
	/*
		PAGE_NOACCESS from Windows.Win32 metadata.
	*/
	PAGE_NOACCESS PAGE_PROTECTION_FLAGS = 0x1

	/*
		PAGE_READONLY from Windows.Win32 metadata.
	*/
	PAGE_READONLY PAGE_PROTECTION_FLAGS = 0x2

	/*
		PAGE_READWRITE from Windows.Win32 metadata.
	*/
	PAGE_READWRITE PAGE_PROTECTION_FLAGS = 0x4

	/*
		PAGE_WRITECOPY from Windows.Win32 metadata.
	*/
	PAGE_WRITECOPY PAGE_PROTECTION_FLAGS = 0x8

	/*
		PAGE_EXECUTE from Windows.Win32 metadata.
	*/
	PAGE_EXECUTE PAGE_PROTECTION_FLAGS = 0x10

	/*
		PAGE_EXECUTE_READ from Windows.Win32 metadata.
	*/
	PAGE_EXECUTE_READ PAGE_PROTECTION_FLAGS = 0x20

	/*
		PAGE_EXECUTE_READWRITE from Windows.Win32 metadata.
	*/
	PAGE_EXECUTE_READWRITE PAGE_PROTECTION_FLAGS = 0x40

	/*
		PAGE_EXECUTE_WRITECOPY from Windows.Win32 metadata.
	*/
	PAGE_EXECUTE_WRITECOPY PAGE_PROTECTION_FLAGS = 0x80

	/*
		PAGE_GUARD from Windows.Win32 metadata.
	*/
	PAGE_GUARD PAGE_PROTECTION_FLAGS = 0x100

	/*
		PAGE_NOCACHE from Windows.Win32 metadata.
	*/
	PAGE_NOCACHE PAGE_PROTECTION_FLAGS = 0x200

	/*
		PAGE_WRITECOMBINE from Windows.Win32 metadata.
	*/
	PAGE_WRITECOMBINE PAGE_PROTECTION_FLAGS = 0x400

	/*
		PAGE_GRAPHICS_NOACCESS from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_NOACCESS PAGE_PROTECTION_FLAGS = 0x800

	/*
		PAGE_GRAPHICS_READONLY from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_READONLY PAGE_PROTECTION_FLAGS = 0x1000

	/*
		PAGE_GRAPHICS_READWRITE from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_READWRITE PAGE_PROTECTION_FLAGS = 0x2000

	/*
		PAGE_GRAPHICS_EXECUTE from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_EXECUTE PAGE_PROTECTION_FLAGS = 0x4000

	/*
		PAGE_GRAPHICS_EXECUTE_READ from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_EXECUTE_READ PAGE_PROTECTION_FLAGS = 0x8000

	/*
		PAGE_GRAPHICS_EXECUTE_READWRITE from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_EXECUTE_READWRITE PAGE_PROTECTION_FLAGS = 0x10000

	/*
		PAGE_GRAPHICS_COHERENT from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_COHERENT PAGE_PROTECTION_FLAGS = 0x20000

	/*
		PAGE_GRAPHICS_NOCACHE from Windows.Win32 metadata.
	*/
	PAGE_GRAPHICS_NOCACHE PAGE_PROTECTION_FLAGS = 0x40000

	/*
		PAGE_ENCLAVE_THREAD_CONTROL from Windows.Win32 metadata.
	*/
	PAGE_ENCLAVE_THREAD_CONTROL PAGE_PROTECTION_FLAGS = 0x80000000

	/*
		PAGE_REVERT_TO_FILE_MAP from Windows.Win32 metadata.
	*/
	PAGE_REVERT_TO_FILE_MAP PAGE_PROTECTION_FLAGS = 0x80000000

	/*
		PAGE_TARGETS_NO_UPDATE from Windows.Win32 metadata.
	*/
	PAGE_TARGETS_NO_UPDATE PAGE_PROTECTION_FLAGS = 0x40000000

	/*
		PAGE_TARGETS_INVALID from Windows.Win32 metadata.
	*/
	PAGE_TARGETS_INVALID PAGE_PROTECTION_FLAGS = 0x40000000

	/*
		PAGE_ENCLAVE_UNVALIDATED from Windows.Win32 metadata.
	*/
	PAGE_ENCLAVE_UNVALIDATED PAGE_PROTECTION_FLAGS = 0x20000000

	/*
		PAGE_ENCLAVE_MASK from Windows.Win32 metadata.
	*/
	PAGE_ENCLAVE_MASK PAGE_PROTECTION_FLAGS = 0x10000000

	/*
		PAGE_ENCLAVE_DECOMMIT from Windows.Win32 metadata.
	*/
	PAGE_ENCLAVE_DECOMMIT PAGE_PROTECTION_FLAGS = 0x10000000

	/*
		PAGE_ENCLAVE_SS_FIRST from Windows.Win32 metadata.
	*/
	PAGE_ENCLAVE_SS_FIRST PAGE_PROTECTION_FLAGS = 0x10000001

	/*
		PAGE_ENCLAVE_SS_REST from Windows.Win32 metadata.
	*/
	PAGE_ENCLAVE_SS_REST PAGE_PROTECTION_FLAGS = 0x10000002

	/*
		SEC_PARTITION_OWNER_HANDLE from Windows.Win32 metadata.
	*/
	SEC_PARTITION_OWNER_HANDLE PAGE_PROTECTION_FLAGS = 0x40000

	/*
		SEC_64K_PAGES from Windows.Win32 metadata.
	*/
	SEC_64K_PAGES PAGE_PROTECTION_FLAGS = 0x80000

	/*
		SEC_FILE from Windows.Win32 metadata.
	*/
	SEC_FILE PAGE_PROTECTION_FLAGS = 0x800000

	/*
		SEC_IMAGE from Windows.Win32 metadata.
	*/
	SEC_IMAGE PAGE_PROTECTION_FLAGS = 0x1000000

	/*
		SEC_PROTECTED_IMAGE from Windows.Win32 metadata.
	*/
	SEC_PROTECTED_IMAGE PAGE_PROTECTION_FLAGS = 0x2000000

	/*
		SEC_RESERVE from Windows.Win32 metadata.
	*/
	SEC_RESERVE PAGE_PROTECTION_FLAGS = 0x4000000

	/*
		SEC_COMMIT from Windows.Win32 metadata.
	*/
	SEC_COMMIT PAGE_PROTECTION_FLAGS = 0x8000000

	/*
		SEC_NOCACHE from Windows.Win32 metadata.
	*/
	SEC_NOCACHE PAGE_PROTECTION_FLAGS = 0x10000000

	/*
		SEC_WRITECOMBINE from Windows.Win32 metadata.
	*/
	SEC_WRITECOMBINE PAGE_PROTECTION_FLAGS = 0x40000000

	/*
		SEC_LARGE_PAGES from Windows.Win32 metadata.
	*/
	SEC_LARGE_PAGES PAGE_PROTECTION_FLAGS = 0x80000000

	/*
		SEC_IMAGE_NO_EXECUTE from Windows.Win32 metadata.
	*/
	SEC_IMAGE_NO_EXECUTE PAGE_PROTECTION_FLAGS = 0x11000000
)

/*
PAGE_TYPE is generated from Windows.Win32 metadata.
*/
type PAGE_TYPE uint32

const (
	/*
		MEM_PRIVATE from Windows.Win32 metadata.
	*/
	MEM_PRIVATE PAGE_TYPE = 0x20000

	/*
		MEM_MAPPED from Windows.Win32 metadata.
	*/
	MEM_MAPPED PAGE_TYPE = 0x40000

	/*
		MEM_IMAGE from Windows.Win32 metadata.
	*/
	MEM_IMAGE PAGE_TYPE = 0x1000000
)

/*
PBAD_MEMORY_CALLBACK_ROUTINE is generated from Windows.Win32 metadata.
*/
type PBAD_MEMORY_CALLBACK_ROUTINE uintptr

/*
PROCESS_HEAP_ENTRY is generated from Windows.Win32 metadata.
*/
type PROCESS_HEAP_ENTRY struct {
	LpData       uintptr
	CbData       uint32
	CbOverhead   uint8
	IRegionIndex uint8
	WFlags       uint16
	HMem         windows_win32_foundation.HANDLE
	DwReserved   [3]uint32
}

/*
PSECURE_MEMORY_CACHE_CALLBACK is generated from Windows.Win32 metadata.
*/
type PSECURE_MEMORY_CACHE_CALLBACK uintptr

/*
SETPROCESSWORKINGSETSIZEEX_FLAGS is generated from Windows.Win32 metadata.
*/
type SETPROCESSWORKINGSETSIZEEX_FLAGS uint32

const (
	/*
		QUOTA_LIMITS_HARDWS_MIN_ENABLE from Windows.Win32 metadata.
	*/
	QUOTA_LIMITS_HARDWS_MIN_ENABLE SETPROCESSWORKINGSETSIZEEX_FLAGS = 0x1

	/*
		QUOTA_LIMITS_HARDWS_MIN_DISABLE from Windows.Win32 metadata.
	*/
	QUOTA_LIMITS_HARDWS_MIN_DISABLE SETPROCESSWORKINGSETSIZEEX_FLAGS = 0x2

	/*
		QUOTA_LIMITS_HARDWS_MAX_ENABLE from Windows.Win32 metadata.
	*/
	QUOTA_LIMITS_HARDWS_MAX_ENABLE SETPROCESSWORKINGSETSIZEEX_FLAGS = 0x4

	/*
		QUOTA_LIMITS_HARDWS_MAX_DISABLE from Windows.Win32 metadata.
	*/
	QUOTA_LIMITS_HARDWS_MAX_DISABLE SETPROCESSWORKINGSETSIZEEX_FLAGS = 0x8
)

/*
UNMAP_VIEW_OF_FILE_FLAGS is generated from Windows.Win32 metadata.
*/
type UNMAP_VIEW_OF_FILE_FLAGS uint32

const (
	/*
		MEM_UNMAP_NONE from Windows.Win32 metadata.
	*/
	MEM_UNMAP_NONE UNMAP_VIEW_OF_FILE_FLAGS = 0x0

	/*
		MEM_UNMAP_WITH_TRANSIENT_BOOST from Windows.Win32 metadata.
	*/
	MEM_UNMAP_WITH_TRANSIENT_BOOST UNMAP_VIEW_OF_FILE_FLAGS = 0x1

	/*
		MEM_PRESERVE_PLACEHOLDER from Windows.Win32 metadata.
	*/
	MEM_PRESERVE_PLACEHOLDER UNMAP_VIEW_OF_FILE_FLAGS = 0x2
)

/*
VIRTUAL_ALLOCATION_TYPE is generated from Windows.Win32 metadata.
*/
type VIRTUAL_ALLOCATION_TYPE uint32

const (
	/*
		MEM_COMMIT from Windows.Win32 metadata.
	*/
	MEM_COMMIT VIRTUAL_ALLOCATION_TYPE = 0x1000

	/*
		MEM_RESERVE from Windows.Win32 metadata.
	*/
	MEM_RESERVE VIRTUAL_ALLOCATION_TYPE = 0x2000

	/*
		MEM_RESET from Windows.Win32 metadata.
	*/
	MEM_RESET VIRTUAL_ALLOCATION_TYPE = 0x80000

	/*
		MEM_RESET_UNDO from Windows.Win32 metadata.
	*/
	MEM_RESET_UNDO VIRTUAL_ALLOCATION_TYPE = 0x1000000

	/*
		MEM_REPLACE_PLACEHOLDER from Windows.Win32 metadata.
	*/
	MEM_REPLACE_PLACEHOLDER VIRTUAL_ALLOCATION_TYPE = 0x4000

	/*
		MEM_LARGE_PAGES from Windows.Win32 metadata.
	*/
	MEM_LARGE_PAGES VIRTUAL_ALLOCATION_TYPE = 0x20000000

	/*
		MEM_RESERVE_PLACEHOLDER from Windows.Win32 metadata.
	*/
	MEM_RESERVE_PLACEHOLDER VIRTUAL_ALLOCATION_TYPE = 0x40000

	/*
		MEM_FREE from Windows.Win32 metadata.
	*/
	MEM_FREE VIRTUAL_ALLOCATION_TYPE = 0x10000
)

/*
VIRTUAL_FREE_TYPE is generated from Windows.Win32 metadata.
*/
type VIRTUAL_FREE_TYPE uint32

const (
	/*
		MEM_DECOMMIT from Windows.Win32 metadata.
	*/
	MEM_DECOMMIT VIRTUAL_FREE_TYPE = 0x4000

	/*
		MEM_RELEASE from Windows.Win32 metadata.
	*/
	MEM_RELEASE VIRTUAL_FREE_TYPE = 0x8000
)

/*
WIN32_MEMORY_RANGE_ENTRY is generated from Windows.Win32 metadata.
*/
type WIN32_MEMORY_RANGE_ENTRY struct {
	VirtualAddress uintptr
	NumberOfBytes  uintptr
}
