//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-06-02 14:49:52 CEST

package windows_win32_system_diagnostics_toolhelp

import (
	"syscore/window/win32/bindings/types/windows_win32_foundation"
)

/*
CREATE_TOOLHELP_SNAPSHOT_FLAGS is generated from Windows.Win32 metadata.
*/
type CREATE_TOOLHELP_SNAPSHOT_FLAGS uint32

const (
	/*
		TH32CS_INHERIT from Windows.Win32 metadata.
	*/
	TH32CS_INHERIT CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0x80000000

	/*
		TH32CS_SNAPALL from Windows.Win32 metadata.
	*/
	TH32CS_SNAPALL CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0xf

	/*
		TH32CS_SNAPHEAPLIST from Windows.Win32 metadata.
	*/
	TH32CS_SNAPHEAPLIST CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0x1

	/*
		TH32CS_SNAPMODULE from Windows.Win32 metadata.
	*/
	TH32CS_SNAPMODULE CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0x8

	/*
		TH32CS_SNAPMODULE32 from Windows.Win32 metadata.
	*/
	TH32CS_SNAPMODULE32 CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0x10

	/*
		TH32CS_SNAPPROCESS from Windows.Win32 metadata.
	*/
	TH32CS_SNAPPROCESS CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0x2

	/*
		TH32CS_SNAPTHREAD from Windows.Win32 metadata.
	*/
	TH32CS_SNAPTHREAD CREATE_TOOLHELP_SNAPSHOT_FLAGS = 0x4
)

/*
HEAPENTRY32 is generated from Windows.Win32 metadata.
*/
type HEAPENTRY32 struct {
	DwSize        uintptr
	HHandle       windows_win32_foundation.HANDLE
	DwAddress     uintptr
	DwBlockSize   uintptr
	DwFlags       HEAPENTRY32_FLAGS
	DwLockCount   uint32
	DwResvd       uint32
	Th32ProcessID uint32
	Th32HeapID    uintptr
}

/*
HEAPENTRY32_FLAGS is generated from Windows.Win32 metadata.
*/
type HEAPENTRY32_FLAGS uint32

const (
	/*
		LF32_FIXED from Windows.Win32 metadata.
	*/
	LF32_FIXED HEAPENTRY32_FLAGS = 0x1

	/*
		LF32_FREE from Windows.Win32 metadata.
	*/
	LF32_FREE HEAPENTRY32_FLAGS = 0x2

	/*
		LF32_MOVEABLE from Windows.Win32 metadata.
	*/
	LF32_MOVEABLE HEAPENTRY32_FLAGS = 0x4
)

/*
HEAPLIST32 is generated from Windows.Win32 metadata.
*/
type HEAPLIST32 struct {
	DwSize        uintptr
	Th32ProcessID uint32
	Th32HeapID    uintptr
	DwFlags       uint32
}

/*
MODULEENTRY32 is generated from Windows.Win32 metadata.
*/
type MODULEENTRY32 struct {
	DwSize        uint32
	Th32ModuleID  uint32
	Th32ProcessID uint32
	GlblcntUsage  uint32
	ProccntUsage  uint32
	ModBaseAddr   *uint8
	ModBaseSize   uint32
	HModule       windows_win32_foundation.HMODULE
	SzModule      [256]windows_win32_foundation.CHAR
	SzExePath     [260]windows_win32_foundation.CHAR
}

/*
MODULEENTRY32W is generated from Windows.Win32 metadata.
*/
type MODULEENTRY32W struct {
	DwSize        uint32
	Th32ModuleID  uint32
	Th32ProcessID uint32
	GlblcntUsage  uint32
	ProccntUsage  uint32
	ModBaseAddr   *uint8
	ModBaseSize   uint32
	HModule       windows_win32_foundation.HMODULE
	SzModule      [256]uint16
	SzExePath     [260]uint16
}

/*
PROCESSENTRY32 is generated from Windows.Win32 metadata.
*/
type PROCESSENTRY32 struct {
	DwSize              uint32
	CntUsage            uint32
	Th32ProcessID       uint32
	Th32DefaultHeapID   uintptr
	Th32ModuleID        uint32
	CntThreads          uint32
	Th32ParentProcessID uint32
	PcPriClassBase      int32
	DwFlags             uint32
	SzExeFile           [260]windows_win32_foundation.CHAR
}

/*
PROCESSENTRY32W is generated from Windows.Win32 metadata.
*/
type PROCESSENTRY32W struct {
	DwSize              uint32
	CntUsage            uint32
	Th32ProcessID       uint32
	Th32DefaultHeapID   uintptr
	Th32ModuleID        uint32
	CntThreads          uint32
	Th32ParentProcessID uint32
	PcPriClassBase      int32
	DwFlags             uint32
	SzExeFile           [260]uint16
}

/*
THREADENTRY32 is generated from Windows.Win32 metadata.
*/
type THREADENTRY32 struct {
	DwSize             uint32
	CntUsage           uint32
	Th32ThreadID       uint32
	Th32OwnerProcessID uint32
	TpBasePri          int32
	TpDeltaPri         int32
	DwFlags            uint32
}
