//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-05-27 08:35:22 CEST

package windows_win32_system_performance_hardwarecounterprofiling

/*
HARDWARE_COUNTER_DATA is generated from Windows.Win32 metadata.
*/
type HARDWARE_COUNTER_DATA struct {
	Type     HARDWARE_COUNTER_TYPE
	Reserved uint32
	Value    uint64
}

/*
HARDWARE_COUNTER_TYPE is generated from Windows.Win32 metadata.
*/
type HARDWARE_COUNTER_TYPE int32

const (
	/*
		PMCCounter from Windows.Win32 metadata.
	*/
	PMCCounter HARDWARE_COUNTER_TYPE = 0x0

	/*
		MaxHardwareCounterType from Windows.Win32 metadata.
	*/
	MaxHardwareCounterType HARDWARE_COUNTER_TYPE = 0x1
)

/*
PERFORMANCE_DATA is generated from Windows.Win32 metadata.
*/
type PERFORMANCE_DATA struct {
	Size               uint16
	Version            uint8
	HwCountersCount    uint8
	ContextSwitchCount uint32
	WaitReasonBitMap   uint64
	CycleTime          uint64
	RetryCount         uint32
	Reserved           uint32
	HwCounters         [16]HARDWARE_COUNTER_DATA
}
