//go:build windows

// This file was auto-generated by 'syscore window bindings generator' at 2026-06-02 14:49:52 CEST

package windows_win32_system_recovery

/*
REGISTER_APPLICATION_RESTART_FLAGS is generated from Windows.Win32 metadata.
*/
type REGISTER_APPLICATION_RESTART_FLAGS uint32

const (
	/*
		RESTART_NO_CRASH from Windows.Win32 metadata.
	*/
	RESTART_NO_CRASH REGISTER_APPLICATION_RESTART_FLAGS = 0x1

	/*
		RESTART_NO_HANG from Windows.Win32 metadata.
	*/
	RESTART_NO_HANG REGISTER_APPLICATION_RESTART_FLAGS = 0x2

	/*
		RESTART_NO_PATCH from Windows.Win32 metadata.
	*/
	RESTART_NO_PATCH REGISTER_APPLICATION_RESTART_FLAGS = 0x4

	/*
		RESTART_NO_REBOOT from Windows.Win32 metadata.
	*/
	RESTART_NO_REBOOT REGISTER_APPLICATION_RESTART_FLAGS = 0x8
)
